### DISCUSSION TITLE
How to remove an entry matching a `name` key?

### DISCUSSION THREAD

**Discussion by mfn** [mikefarah/yq#1025] [Q&A] [answered]
Hello 👋🏼 ,

I'm trying to process a k8s `kustomization.yaml` and remove a matching entry completely. I could not find a native way using the `kustomize` tools so I figured I give `yq` a spin.

The part I'm interesting looks like this:
```yaml
resources:
 - resource1

images:
  - name: a
    newName: repo
    newTag: tag1
  - name: b
    newName: repo
    newTag: tag2
```
What I would like to do is remove entry in `iamges` matching `name: b`, including it's `newName` and `newTag` so that the document afterwards looks like this:
```yaml
resources:
 - resource1

images:
  - name: a
    newName: repo
    newTag: tag1
```

I thought I figure out how to only match one entry and then expand the expression to call `del()` on it, but I fail already the part here.

Some things I tried:
- `yq eval 'select(.images.[])' example.yaml` => full document returned
- `yq eval 'select(.images.[].name == "c")' example.yaml` => no output!
  So I thought I'm on the right track…
- `yq eval 'select(.images.[].name == "b")' example.yaml` => unfortunately same full document again 😞 

I'm somewhat lost here, I tried to make sense of https://mikefarah.gitbook.io/yq/operators/select and scouted the docs already, but it just won't click for me.

Thank you 🙏🏼
