### DISCUSSION TITLE
How to convert empty yml element to empty properties key?

### DISCUSSION THREAD

**Discussion by igorjarm** [mikefarah/yq#1028] [Q&A] [answered]
Is it possible to transform yml file to properties with empty arrays and complex objects?

Actual yml file in question is pretty complex, referencing elements defined in other parts of the same file.
Use case for this is to provide optional values or overrides to the element. The existence of the element is critical, but the contents are optional (see arrayOfSimpleReferences and complexEmptyReferences below).

Thank you in advance.

Description of the problem:

test.yml
```yaml
a:
  simpleValue: 1
  arrayOfReferences: [ONE, TWO]
  complexReferences: {first: THREE, second: FOUR}
  simpleEmptyValue:
  arrayOfSimpleReferences: []
  complexEmptyReferences: {}
```

How I use yq:
```
yq eval-all -o=p test.yml
version 4.14.2
```

For simple values it actually works ok, see a.simpleEmptyValue below
```
a.simpleValue = 1
a.arrayOfReferences.0 = ONE
a.arrayOfReferences.1 = TWO
a.complexReferences.first = THREE
a.complexReferences.second = FOUR
a.simpleEmptyValue = 
```

I would expect the following. Is this possible to achieve, or is this a bug / feature request or even intended feature?
```
a.simpleValue = 1
a.arrayOfReferences.0 = ONE
a.arrayOfReferences.1 = TWO
a.complexReferences.first = THREE
a.complexReferences.second = FOUR
a.simpleEmptyValue = 
a.arrayOfSimpleReferences = 
a.complexEmptyReferences = 
```
