### DISCUSSION TITLE
JSON to YAML docker compose labels with quotes

### DISCUSSION THREAD

**Discussion by ToshY** [mikefarah/yq#1050] [Q&A] [answered]
**Problem**

I'm trying to create a docker compose override yaml file from JSON, which include N amount of labels. I currently have the following setup:

```json
{
  "version": "3.7",
  "traefik": {
    "labels": [
      "traefik.http.routers.traefik-secure.tls.domains[0].main=domain1.local",
      "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.domain1.local",
      "traefik.http.routers.traefik-secure.tls.domains[1].main=domain2.local",
      "traefik.http.routers.traefik-secure.tls.domains[1].sans=*.domain2.local",
      "traefik.http.routers.traefik-secure.tls.domains[N].main=domainN.local",
      "traefik.http.routers.traefik-secure.tls.domains[N].sans=*.domainN.local"
    ]
  }
}
```

with currently the following command:

```shell
yq e -P docker-compose.override.json
```

Which results in:

```yaml
version: "3.7"
traefik:
  labels:
    - traefik.http.routers.traefik-secure.tls.domains[0].main=domain1.local
    - traefik.http.routers.traefik-secure.tls.domains[0].sans=*.domain1.local
    - traefik.http.routers.traefik-secure.tls.domains[1].main=domain2.local
    - traefik.http.routers.traefik-secure.tls.domains[1].sans=*.domain2.local
    - traefik.http.routers.traefik-secure.tls.domains[N].main=domainN.local
    - traefik.http.routers.traefik-secure.tls.domains[N].sans=*.domainN.local
```

**Desired result**

I want to have quotes around the traefik labels like so:

```yaml
version: "3.7"
traefik:
  labels:
    - "traefik.http.routers.traefik-secure.tls.domains[0].main=domain1.local"
    - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.domain1.local"
    - "traefik.http.routers.traefik-secure.tls.domains[1].main=domain2.local"
    - "traefik.http.routers.traefik-secure.tls.domains[1].sans=*.domain2.local"
    - "traefik.http.routers.traefik-secure.tls.domains[N].main=domainN.local"
    - "traefik.http.routers.traefik-secure.tls.domains[N].sans=*.domainN.local"
```
