### DISCUSSION TITLE
Question: How to use environment variables in square brackets

### DISCUSSION THREAD

**Discussion by niharbabu99** [mikefarah/yq#1064] [Q&A] [answered]
YQ version: version 4.16.1
Platform: ubuntu 18.04

My YML looks like Below:
customers :
  - name: cust1
    phoneNumber: 123
    files: ["/home/storage/cust1-profile.jpg","/home/storage/cust1-signature.jpg"]

I am trying to add a new customer at the runtime using a environment variable. I use the below command

 mycust="cust2" yq eval '.jobs += {"name":  env(mycust), "files": "[\"/home/folder + env(mycust) + -profile.jpg + \", \"/home/folder + env(mycust) + -signature.jpg +  \"]", "number": 1234567}' -i sample.yml

But the result is not what I expected, it looks something like below

customers :
  - name: cust1
    phoneNumber: 123
    files: ["/home/storage/cust1-profile.jpg","/home/storage/cust1-signature.jpg"]
  - name: cust2
    files: '["/home/folder + env(mycust) + -profile.jpg + ", "/home/folder + env(mycust) + -signature.jpg +  "]'
    number: 1234567

can someone help me to solve this problem.

Thanks in advance.

**Comment by mikefarah** [comment, marked as answer]
That's because the `files` value is all wrapped in a string, try this instead:
```
mycust="cust2" yq eval '.jobs += {
   "name": env(mycust), 
    "files": [  
                  "/home/folder" + env(mycust) + "-profile.jpg", 
                  "/home/folder" + env(mycust) + "-signature.jpg"  
               ], 
    "number": 1234567
}' -i sample.yaml
```

**Reply by niharbabu99** [reply]
Thanks for the reply, but that gives me the output as below
  - name: cust2
    files:
      - /home/foldercust2-profile.jpg
      - /home/foldercust2-signature.jpg
    number: 1234567

which is not as I am expecting. 
Basically, I am trying to add a new node to a git workflow yml file at runtime. If the node "files" come in the above way My action fails with an error "A sequence was not expected". Contents should be "array string of paths".

My output should be similar to below
- name: cust2
  files: '["/home/folder + env(mycust) + -profile.jpg + ", "/home/folder + env(mycust) + -signature.jpg + "]'
  number: 1234567

**Reply by mikefarah** [reply]
I'm sorry I don't know what you mean? isn't the output in 'similar to below' what you already had?

Are you aware that in yaml:
```
files: ["/home/storage/cust1-profile.jpg","/home/storage/cust1-signature.jpg"]
```

and
```
files: 
   - "/home/storage/cust1-profile.jpg"
   - "/home/storage/cust1-signature.jpg"
```

are the same?

**Reply by niharbabu99** [reply]
Yes I am aware But it is failing when my github action trying to parse the file.

My GitHub action file looks like below
```
name: Validate Changes for pipeline

on:
  push:
    branches:
      - master
    paths:
      - ci/**
  pull_request:
    branches:
      - master
    paths:
      - ci/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    name: validate
    steps:
      - uses: actions/checkout@v2
        with:
          path: ea-uaa-deployment
      - uses: actions/checkout@v2
        with:
          repository: smarsh/delivery-common-tasks
          token: ${{ secrets.ACCESS_TOKEN }}
          path: delivery-common-tasks
      - uses: actions/checkout@v2
        with:
          repository: smarsh/ea-e2e-smoke
          token: ${{ secrets.ACCESS_TOKEN }}
          path: smoke-tests
      - name: Validate bny_ap_southeast_prod
        uses: smarsh/validate-concourse-pipeline-action@development
        env:
          PIPELINE_CONFIG: ci/deploy_uaa.yml
          HANDLEBARS: true
          ENVIRONMENT_NAME: bny_ap_southeast_prod
          VAR_FILES: '["ci/vars/bny_ap_southeast_prod.yml", "ci/vars/bny_ap_southeast_prod_template_vars.yml"]'
          MULTI_REPO: true
          PIPELINE_REPOSITORY: ea-uaa-deployment
```

When I am adding the new entry as per below

```
      - name: Validate test1
        uses: smarsh/validate-concourse-pipeline-action@development
        env:
          PIPELINE_CONFIG: ci/deploy_uaa.yml
          HANDLEBARS: true
          ENVIRONMENT_NAME: bny_ap_southeast_prod
          VAR_FILES: '["ci/vars/file1.yml", "ci/vars/file2.yml"]'
          MULTI_REPO: true
          PIPELINE_REPOSITORY: ea-uaa-deployment
```

if I am adding as per below, git action is failing with the error "A sequence was not expected"

```
      - name: Validate test1
        uses: smarsh/validate-concourse-pipeline-action@development
        env:
          PIPELINE_CONFIG: ci/deploy_uaa.yml
          HANDLEBARS: true
          ENVIRONMENT_NAME: bny_ap_southeast_prod
          VAR_FILES: 
             - "ci/vars/file1.yml"
             - "ci/vars/file2.yml"
          MULTI_REPO: true
          PIPELINE_REPOSITORY: ea-uaa-deployment
```

**Reply by mikefarah** [reply]
Oh II see - `VAR_FILES` is wrapped in single quotes, it's an encoded array! okay try this:


```
mycust="cust2" yq eval '.jobs += {
   "name": env(mycust), 
    "files": ([  
                  "/home/folder" + env(mycust) + "-profile.jpg", 
                  "/home/folder" + env(mycust) + "-signature.jpg"  
               ] | @json), 
    "number": 1234567
}' -i sample.yaml
```

(note that I'm piping the array through `@json` to encode it as a string:

```
jobs:
  - name: cust2
    files: '["/home/foldercust2-profile.jpg","/home/foldercust2-signature.jpg"]'
    number: 1234567
```
