### DISCUSSION TITLE
How to merge arrays

### DISCUSSION THREAD

**Discussion by mjallday** [mikefarah/yq#1074] [Q&A] [answered]
**Input Yaml**

data1.yml:
```yaml
spec:
  versions:
  - schema:
      firstProperty: bar
```

data2.yml:
```yaml
spec:
  versions:
    - schema:
        secondProperty: foo
```

**Command**
The command you ran:
```
yq ea '. as $item ireduce ({}; . * $item )'  data1.yml data2.yml
```

or [docs](https://mikefarah.gitbook.io/yq/operators/multiply-merge)

```
yq eval-all 'select(fileIndex == 0) * select(fileIndex == 1)' data1.yml data2.yml
```

**Actual behavior**

```yaml
spec:
  versions:
    - schema:
        secondProperty: foo
```

**Expected behavior**

```yaml
spec:
  versions:
    - schema:
        firstProperty: bar
        secondProperty: foo
```

**Additional context**
Curious if there's a way to merge the two array values together.
