### DISCUSSION TITLE
several questions

### DISCUSSION THREAD

**Discussion by blastik** [mikefarah/yq#1080] [Q&A] [answered]
hello

i have a yaml like this

```YAML
ingress:
  # ingress.enabled -- Enable ingress resource.
  enabled: true
  albLogs: true
  # ingress.annotations -- Configures annotations for the ingress.
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/healthcheck-path: /v1/healthcheck
  hosts:
    # ingress.hosts[0].host -- Host name for routing traffic.
    - host: whatever
      http:
        paths:
          - path: "/*"
            backend: 
              serviceName: whatever
              servicePort: http
    - host: whatever
      http:
        paths:
          - path: "/*"
            backend: 
              serviceName: whatever
              servicePort: http
```

and I want to convert it to something like the one below. note the differences after `backend:`

```YAML
ingress:
  # ingress.enabled -- Enable ingress resource.
  enabled: true
  albLogs: true
  # ingress.annotations -- Configures annotations for the ingress.
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/healthcheck-path: /v1/healthcheck
  hosts:
    # ingress.hosts[0].host -- Host name for routing traffic.
    - host: whatever
      http:
        paths:
          - path: "/*"
            backend: 
              service:
                name: whatever
                port: 
                  name: http
    - host: whatever
      http:
        paths:
          - path: "/*"
            backend: 
              service:
                name: whatever
                port: 
                  name: http
```

any hints?
so far i run `yq eval '{"service": .ingress.hosts.[].http.paths.[].backend}' file.yaml` and it does add the parent `service:` but i honestly dont know how to merge it?
