### DISCUSSION TITLE
Control the way lists/arrays are displayed

### DISCUSSION THREAD

**Discussion by felipesere** [mikefarah/yq#1085] [Q&A] [answered]
I have a script to update a YAML config of a program I wrote.

Given the following snippet (the config is slightly larger):
```yaml
pull_requests:
  enabled: true
  auth:
    personal_access_token: XYZ
  select: []
```
When I run the `yq` like so:
```sh
yq -i e '.pull_requests.select += {"repo": "felipesere/dotfiles",}' config.yml
yq -i e '.pull_requests.select += {"repo": "felipesere/journal",}' config.yml
```

Then the output I get is:
```yaml
pull_requests:
  enabled: true
  auth:
    personal_access_token: XYZ
  select: [{repo: felipesere/dotfiles}, {repo: felipesere/journal}]
```

This is fine and my program handles it perfectly well.
But given that I also manually edit the file every now and then, I'd rather `yq` output the "bullet-style" (?) list like so:

```yaml
pull_requests:
  enabled: true
  auth:
    personal_access_token: XYZ
  select: 
    - repo: felipesere/dotfiles
    - repo: felipesere/journal
```

Is there a flag I can set to get this output?

**Comment by mikefarah** [comment, marked as answer]
Yep - you can use the [style](https://mikefarah.gitbook.io/yq/operators/style#reset-style-or-pretty-print) operator.

```bash
yq e -i 'with(.pull_requests.select; 
  . style= "" |
  . += {"repo": "felipesere/dotfiles"} |
  . += {"repo": "felipesere/journal"}
)' config.yml
```

```yaml
pull_requests:
  enabled: true
  auth:
    personal_access_token: XYZ
  select:
    - repo: felipesere/dotfiles
    - repo: felipesere/journal

```

For what it's worth - `yq` defaults to the current style of the nodes - and for empty arrays/objects this is necessarily the JSON style (as there's no way of specifying an empty list in bullet points). 

I think I will change this in future versions to assume the default `yaml` style for empty arrays and objects.
