### DISCUSSION TITLE
Sort YAML docs in file by key

### DISCUSSION THREAD

**Discussion by mamachanko** [mikefarah/yq#1101] [Q&A] [answered]
I would like to sort the YAML documents in a file by a specified key.

`yq` deterministically sorts a single doc's keys which is nice, but not enough when you have a multi-doc file.

Let's say I have this input:
```
---
spec: { }
metadata:
  name: bob
---
metadata:
  name: alice
spec: { }
```

How could I achieve this desired output:
```
# sorted by .metadata.name and all fields within each doc
---
metadata:
  name: alice
spec: { }
---
metadata:
  name: bob
spec: { }
```

❤️  `yq` ❤️
