### DISCUSSION TITLE
Deleting object incorrectly deleting attribute, how to delete object?

### DISCUSSION THREAD

**Discussion by CraigRubendall** [mikefarah/yq#1160] [Q&A]
I'm using yq 4.20.1.

I'm working with my kubernetes site.yaml file.  What I need to do is to remove any PodDisruptionBudget objects.  

I can find them properly using this command:

yq eval 'select(.kind == "PodDisruptionBudget")' site.yaml

when I try to delete using a similar syntax:

yq eval 'del(.kind == "PodDisruptionBudget")' site.yaml

the result is that the kind attribute is removed from all objects (including non-PodDisruptionBudget ones)!

I've also tried several other variants:

 yq eval 'del(select(.kind == "PodDisruptionBudget"))' site.yaml  # doesn't remove anything

 yq eval 'del(. | select(.kind == "PodDisruptionBudget"))' site.yaml  # doesn't remove anything

I need to end up with a valid site.yaml file so the answer shouldn't flatten or otherwise disrupt the remaining items in the file contents.

What is the proper syntax for doing so?

**Comment by mikefarah** [comment]
Without having a representative sample file it's hard to know what the syntax should be.

Assuming its something like this:

```yaml
- kind: thing
  other: stuff
- kind: PodDisruptionBudget
  interesting: things
- kind: bingo
  meow: cat
```

Then the command to delete the entry with the kind=PodDistruptionBudget is:


```bash
yq 'del(.[] | select(.kind == "PodDisruptionBudget"))' file.yaml
```

which leaves:

```yaml
- kind: thing
  other: stuff
- kind: bingo
  meow: cat
```

What happens under the hood is:
- splat the array into it's individual elements
- pipe through select, to only select the ones with .kind=="PodDisruptionBudget"
- delete those
