### DISCUSSION TITLE
Is it possible to use envsubst without removing missing variables?

### DISCUSSION THREAD

**Discussion by jpmorin** [mikefarah/yq#1164] [Q&A] [answered]
Hi,

I use **envsubst** to replace dozens of variable in a ci yaml file. However, the file also contains variables that i do not wish to replace nor remove as they are used at runtime.

##### sample.yml
```yaml
example: ${foo}
message: |
  Build $BUILD_ID failed
  Link: $URL/$BUILD_NAME/$BUILD_ID
```

##### command
`foo=bar yq '(.. | select(tag == "!!str")) |= envsubst' sample.yml`

##### expected
```yaml
example: bar
message: |
  Build $BUILD_ID failed
  Link: $URL/$BUILD_NAME/$BUILD_ID
```

##### actual
```yaml
example: bar
message: |
  Build  failed
  Link: //
```

Is there a way to use **envsubst** so that it does not remove missing variables?

Thanks.
