### DISCUSSION TITLE
YAML to JSON and back raises errors

### DISCUSSION THREAD

**Discussion by epodegrid** [mikefarah/yq#1179] [Q&A] [answered]
Hi there. I'm using yq to convert a YAML file into JSON for editing with my C program and then convert it back to YAML. Unfortunately, this causes the error: `Error: bad file 'test.json': yaml: line 18: did not find expected <document start>`.

My document is a Kubernetes file as follows:
```
---
# Source: prometheus/charts/kube-state-metrics/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:    
    helm.sh/chart: kube-state-metrics-4.7.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: kube-state-metrics
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "2.4.1"
  name: release-name-kube-state-metrics
  namespace: default
imagePullSecrets:
  []
---
# Source: prometheus/templates/alertmanager/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: "alertmanager"
    app: prometheus
    release: release-name
    chart: prometheus-15.8.1
    heritage: Helm
  name: release-name-prometheus-alertmanager
  namespace: default
  annotations:
    {}
```
I convert it to JSON using the command `yq -o=j -P test.yaml > test.json` and then back to YAML using `yq -P "." test.json`. I have also tried using eval-all option, but that also produces the same error.

How do I fix this? Thanks in advance!
