### DISCUSSION TITLE
Converting JSON to YAML using qa, without brackets in JSON

### DISCUSSION THREAD

**Discussion by epodegrid** [mikefarah/yq#1185] [Q&A] [answered]
I have a YAML file that I converted into JSON using  `yq ea '[.]' -o=json render.yaml >  render.json`. This works fine but the program I use for scanning the JSON file, checkov, does not work if the root is an array i.e. if the file begins with a square bracket. So I use the command `yq ea '.' -o=json render.yaml >  render.json` to get the output as just objects. 

I need to convert this file back to YAML. Currently I use the command `yq eval-all -P '.[] | split_doc' render.json > checks.yaml`.This causes the error `Error: bad file 'test.json': yaml: line 14: did not find expected <document start>`. 

Is it possible to convert the file from YAML to JSON and back, so that the intermediary file in JSON is not an array, and the final YAML file is still a single file with multiple documents?

**Additional Information**
Sample YAML file used:
```
---
# Source: prometheus/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: prometheus
    group: com.stakater.platform
    provider: stakater
    version: "2.2.0-rc.0"
    chart: "prometheus-1.0.32"
    release: "release-name"
    heritage: "Helm"
  name: monitoring-k8s
  namespace: default
---
# Source: prometheus/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
# document continues
```

JSON file that works with checkov:
```
{
  "apiVersion": "v1",
  "kind": "ServiceAccount",
  "metadata": {
    "name": "release-name-nginx-ingress",
    "namespace": "default",
    "labels": {
      "app.kubernetes.io/name": "release-name-nginx-ingress",
      "helm.sh/chart": "nginx-ingress-0.13.0",
      "app.kubernetes.io/managed-by": "Helm",
      "app.kubernetes.io/instance": "release-name"
    }
  }
}
{
  "apiVersion": "v1",
  "kind": "Secret",
  "metadata": {
    "name": "release-name-nginx-ingress-default-server-tls",
    "namespace": "default",
    "labels": {
      "app.kubernetes.io/name": "release-name-nginx-ingress",
      "helm.sh/chart": "nginx-ingress-0.13.0",
      "app.kubernetes.io/managed-by": "Helm",
      "app.kubernetes.io/instance": "release-name"
    }
  }
}
```

JSON file that yq needs to convert it into YAML. YAML output similar to first example.
```
[
  {
    "apiVersion": "v1",
    "kind": "ServiceAccount",
    "metadata": {
      "name": "release-name-nginx-ingress",
      "namespace": "default",
      "labels": {
        "app.kubernetes.io/name": "release-name-nginx-ingress",
        "helm.sh/chart": "nginx-ingress-0.13.0",
        "app.kubernetes.io/managed-by": "Helm",
        "app.kubernetes.io/instance": "release-name"
      }
    }
  },
  {
    "apiVersion": "v1",
    "kind": "Secret",
    "metadata": {
      "name": "release-name-nginx-ingress-default-server-tls",
      "namespace": "default",
      "labels": {
        "app.kubernetes.io/name": "release-name-nginx-ingress",
        "helm.sh/chart": "nginx-ingress-0.13.0",
        "app.kubernetes.io/managed-by": "Helm",
        "app.kubernetes.io/instance": "release-name"
      }
    }
]
```
