### DISCUSSION TITLE
How to validate yaml file in v4 to make sure there are no duplicate keys?

### DISCUSSION THREAD

**Discussion by shreyaspurohit** [mikefarah/yq#1207] [Q&A] [answered]
I have a yaml file like
```
data:
  key1: 
    a: b
  key2:
    a: b
  key1:
    c: d
```

The `key1` is repeated under `data` multiple times which is not allowed in YAML. I tried the `yq --exit-status 'tag == "!!map" or tag== "!!seq"` in the docs, but the exit code is 0. 

Is it possible to use yq to validate and make sure the yaml file doesn't have duplicate map keys?
