### DISCUSSION TITLE
Manipule helm chart yaml file having {{ }} as values

### DISCUSSION THREAD

**Discussion by ziomill** [mikefarah/yq#1254] [Q&A]
Hello,

I should manipulate an helm chart file like this:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
data:
  MY_PROP_1: {{ .Values.configuration.myFirstProp }}
  MY_PROP_2: {{ .Values.configuration.mySecondProp }}
  MY_PROP_3: {{ .Values.configuration.myThirdProp }}
```

I would replace the **MY_PROP_1: {{ .Values.configuration.myFirstProp }}** with **MY_PROP_1: {{ .Values.deploy.myFirstProp }}**. 

Trying with the yq command:
```bash
yq '.data.MY_PROP_1 = "{{ .Values.deploy.myFirstProp }}"' YQ/configmap-env.yaml
```
I have this strange result:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
data:
  MY_PROP_1: '{{ .Values.deploy.myFirstProp }}'
  MY_PROP_2: {? {.Values.configuration.mySecondProp: ''}: ''}
  MY_PROP_3: {? {.Values.configuration.myThirdProp: ''}: ''}
```

**Problem 1:** The MY_PROP_1 value is replaced by adding the single quotes. 
**Problem 2:** Also other props MY_PROP_2 and MY_PROP_3 have been replaced with strange characters --> {? { the_value}: "}

The goal is to replace only the MY_PROP_1 property, avoiding single quotes. How to do that? Please note that normal yaml file with values without bracket works as expected.

Thank you

**Comment by mikefarah** [comment]
The problem is that the file is not valid yaml - it's a template file for _generating_ yaml. When the underlying yaml parser reads it - it produces strange results :(

**Reply by ziomill** [reply]
Hi @mikefarah ,

So, it's impossible to use **yq** to manipulate helm chart "template" files. Is it right? :-(

**Reply by andry81** [reply]
> So, it's impossible to use yq to manipulate helm chart "template" files. Is it right? :-(

You can't use any string as a value, you still must escape several specific characters, even in a double quotes string.
Why not change the template?

```yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
data:
  MY_PROP_1: "{{ .Values.configuration.myFirstProp }}"
  MY_PROP_2: "{{ .Values.configuration.mySecondProp }}"
  MY_PROP_3: "{{ .Values.configuration.myThirdProp }}"
```
