### DISCUSSION TITLE
How to set some default values to each key in base file from other file

### DISCUSSION THREAD

**Discussion by msmolka** [mikefarah/yq#1260] [Q&A] [answered]
I have following `master.yaml` file

```yaml
root:
  - name: First
    some_value: One
  - name: Second
    some_value: Two
```

and `update.yaml` file

```yaml
defaults:
  other_value: true
  one_more: Three
```

The expected result is:

```yaml
root:
  - name: First
    some_value: One
    other_value: true
    one_more: Three
  - name: Second
    some_value: Two
    other_value: true
    one_more: Three

```

I tried following command:

`yq eval-all '(select(fileIndex == 0).root.[] *+ select(fileIndex == 1).defaults)' './master.yaml' './update.yaml'`

but the result is:

```yaml
name: First
some_value: One
other_value: true
one_more: Three
name: Second
some_value: Two
other_value: true
one_more: Three
```
