### DISCUSSION TITLE
How to convert array of objects to csv?

### DISCUSSION THREAD

**Discussion by balki** [mikefarah/yq#1285] [Q&A] [answered]
Consider below input yaml

```
❯ cat map.yaml                                                                                                                                           
foo: bar
items:
  - name: Tom
    species: cat
    color: blue
  - name: Jim
    species: dog
    color: brown
```
I want to convert it to below csv

```
name,species,color
Tom,cat,blue
Jim,dog,brown

```

I tried below and more - didn't work.

```
❯ cat map.yaml | yq '.items | @csv'           
Error: csv encoding only works for arrays of scalars (string/numbers/booleans), child[0] is a !!map
❯ cat map.yaml | yq '.items | values | @csv'
Error: 1:12: invalid input text "values | @csv"

```

I understand for csv to work, it has to be array of arrays like below, 

```
❯ cat arr.yaml                     
foo: bar
items:
  - - Tom
    - cat
    - blue
  - - Jim
    - dog
    - brown
❯ cat arr.yaml | yq '.items | @csv'
Tom,cat,blue
Jim,dog,brown
```
No header but still ok. Is there a way to convert `map.yaml` to `arr.yaml`, so that it can be converted to csv?
