### DISCUSSION TITLE
Extract all entries that contain value in array

### DISCUSSION THREAD

**Discussion by julianbarg** [mikefarah/yq#1288] [Q&A] [answered]
Given an array: 

```
foo: 
  - b
  - c
bar:
  - 2
  - c
non:
  - a
  - b
```

How do I extract all entries that contain "c", i.e. the entries "foo" and "bar".

What if these entries were nested on an arbitrary deeper level, i.e. selecting on "nested2" containing "target" in the following array:

```
foo:
  nested:
    nested1:
      nested2:
        - target
        - foo
        - bar 
non:
  foo: bar
```
