### DISCUSSION TITLE
Overwriting tags when merging documents

### DISCUSSION THREAD

**Discussion by Sleavely** [mikefarah/yq#1298] [Q&A] [answered]
I've got a main configuration file that I want to merge some overrides into, so I followed the example ["Merge / combine all documents into one"](https://mikefarah.gitbook.io/yq/usage/tips-and-tricks#merge-combine-all-documents-into-one) which outlines the following approach:

```sh
yq ea -i '. as $item ireduce ({}; . * $item )' file1.yml file2.yml
```

And it works well as long as _file2.yml_ doesnt attempt to modify any entries that use tags like `!Sub` which is a common shorthand in CloudFormation syntax.

**file1.yml**

```yaml
Globals:
  Function:
    Environment:
      Variables:
        API_BASE_PATH: !Sub ${PROJECT}
```

**file2.yml**

```yaml
Globals:
  Function:
    Environment:
      Variables:
        API_BASE_PATH: !If
          - IsProd
          - ""
          - !Sub ${PROJECT}
```

The result is an interesting hybrid:

```yaml
Globals:
  Function:
    Environment:
      Variables:
        API_BASE_PATH: !Sub
          - IsProd
          - ""
          - !Sub ${PROJECT}
```

The list of arguments for the `!If` is appropriately injected but the tag itself doesnt seem to overwrite `!Sub`. Does anyone have any ideas on whether its possible to treat the tags as scalar values or some similar approach?

**Comment by Sleavely** [comment]
I tried skipping the tag entirely in file2.yml to use the longform Fn::If which should be interpreted as a regular map:

```yaml
Globals:
  Function:
    Environment:
      Variables:
        API_BASE_PATH:
          Fn::If:
          - IsProd
          - ""
          - !Sub ${PROJECT}
```

but the `!Sub` tag remains after `API_BASE_PATH`:

```yaml
Globals:
  Function:
    Environment:
      Variables:
        API_BASE_PATH: !Sub
          Fn::If:
            - IsProd
            - ""
            - !Sub ${PROJECT}
```
