### DISCUSSION TITLE
how to use a string format output

### DISCUSSION THREAD

**Discussion by zhangguanzhang** [mikefarah/yq#1307] [Q&A]
`file.yml`
```yaml
ssh:
  description: 'SSH connection to Actions'
  required: false
  default: 'false'
target:
  description: 'build/${target} to build'
  required: false
  default: 'r2s' #'x86_64'
```
expect:
```
ssh=false
target=r2s
```
I can only do this 😢
```
$ yq 'to_entries|.[]|.key ' file.yml
ssh
target
$ yq 'to_entries|.[]|.value.default ' file.yml
false
r2s

```
