### DISCUSSION TITLE
how to select list to update

### DISCUSSION THREAD

**Discussion by pycgo** [mikefarah/yq#1311] [Q&A] [answered]
yaml 
```
spec:
  groups:
  - name: test
    rules:
    - alert: test1
      labels:
        a: b
        linkflowAlert: warning
    - alert: test2
      labels:
        severity: warning
       ......
```

i want to change rules(list) -->  alert: test2 -->  labels add a new lables like this
```
spec:
  groups:
  - name: test
    rules:
    - alert: test1
      labels:
        a: b
        linkflowAlert: warning
    - alert: test2
      labels:
        severity: warning
        linkflowAlert: warning
     ......
```
do not use 
`yq e '.spec.groups[0].rules[1].labels += {"linkflowAlert": "warning"}'`
how can i select "alert: test2", then to update labels
