### DISCUSSION TITLE
Rename or remove a key ending with a backslash

### DISCUSSION THREAD

**Discussion by buffcode** [mikefarah/yq#1312] [Q&A] [answered]
I have Symfony YAML configuration file:
```yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
```

I would like to refactor the `App\` key to `Foo\App\` and likewise `App\Controller\` to `Foo\App\Controller\`, but none of the following works:
```
yq '.services["App\\"]' test.yaml
yq '.services.["App\\"]' test.yaml
yq '.services["App"]' test.yaml
```

The only selector that worked is using a wildcard, but this could also select `AppBar\`.
```
yq '.services["App*"]' test.yaml
```

yq version 4.27.2
