### DISCUSSION TITLE
Sort array of dependencies in environment.yml

### DISCUSSION THREAD

**Discussion by rcasero** [mikefarah/yq#1332] [Q&A] [answered]
I have an `environment.yml` file for a conda environment:

```yaml
name: foo
channels:
- pytorch
- conda-forge
- bioconda
dependencies:
- pybigwig=0.3.18
- cpuonly=2.0
- mkl_random=1.2.0
- mkl_fft=1.2.0
- ucsc-bigbedtobed=377
- certifi=2021.5.30
- pip=21.2.4
- torchvision=0.11.3
- cudnn=7.6.5.32
- pytorch-cpu=1.1.0
- python=3.6.15
- pip:
  - -r requirements.txt
```

I'd like to sort the `dependencies:` section alphabetically.

I'm running yq version 4.26.1 installed with snap on linux.

The best I've managed is

```bash
cat environment.yml | yq '.dependencies | sort_keys(.)'
```

but this doesn't seem to sort the array

```
- pybigwig=0.3.18
- cpuonly=2.0
- mkl_random=1.2.0
- mkl_fft=1.2.0
- ucsc-bigbedtobed=377
- certifi=2021.5.30
- pip=21.2.4
- torchvision=0.11.3
- cudnn=7.6.5.32
- pytorch-cpu=1.1.0
- python=3.6.15
- pip:
    - -r requirements.txt
```

(In addition, not sure how I'd put the sorted array back into the file).

Any help would be appreciated, thanks!

Kind regards,

Ramon.
