### DISCUSSION TITLE
How to remove an item of an array

### DISCUSSION THREAD

**Discussion by Evantage-WS** [mikefarah/yq#1340] [Q&A] [answered]
Hi,

Just (hopefully a simple) question:

Is yq capable of removing the ".options.k3s.extraArgs" and then the - arg: with the value "-- flannel-backend=none' completely?

```
apiVersion: k3d.io/v1alpha4
kind: Simple
...
...
options:
  k3d:
    wait: true
  k3s:
    extraArgs:
      - arg: --flannel-backend=none
        nodeFilters:
          - server:*
      - arg: --no-deploy=traefik
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
```

Thanks!

**Comment by mikefarah** [comment, marked as answer]
Yep:

```bash
yq 'del(.options.k3s.extraArgs[] | select(.arg == "--flannel-backend=none"))' file.yaml
```

Explanation:
- `.options.k3s.extraArgs[]` will match every item under extraArgs
- `select(.arg == "--flannel-backend=none")` filters the items to only include the ones that have the matching `arg` value
- wrap the whole thing in `del` to delete those matching items

**Reply by mikefarah** [reply]
Forgot to include the output:

```yaml
apiVersion: k3d.io/v1alpha4
kind: Simple
options:
  k3d:
    wait: true
  k3s:
    extraArgs:
      - arg: --no-deploy=traefik
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
```
