### DISCUSSION TITLE
Exclude All Sub-Objects

### DISCUSSION THREAD

**Discussion by glsutter** [mikefarah/yq#1350] [Q&A]
I have a file that contains:

```
MAC:
  location: useast
  loc: usea
  cidr: 10.1.0.0/26
  PROD:
    prefix: PROD
    zone: mac.prod.company.org
  STAGE:
    prefix: STAGE
    zone: mac.stage.company.org
  TEST:
    prefix: TEST
    zone: mac.test.company.org
MAG:
  location: usgovvirginia
  loc: usva
  cidr: 10.2.0.0/26
  PROD:
    prefix: PROD
    zone: mag.prod.company.org
  STAGE:
    prefix: STAGE
    zone: mag.stage.company.org
  TEST:
    prefix: TEST
    zone: mag.test.company.org
```

And I would like to retrieve the top-level MAC or MAG attributes without any of the sub-objects. For example, given input of MAC, I would like to get this output:

```
location: useast
loc: usea
cidr: 10.1.0.0/26
```

Of course, I can get everything under MAC by using
yq '.MAC'
but how do I exclude all of the sub-object data? FYI - I am willing to hard-code the sub-object identifiers PROD, STAGE, and TEST, if that's necessary. 

I've tried it using del, and also del and select with a regex, but I can't seem to get the right syntax. 

What's the best way to output only the top-level MAC or MAG properties without anything at lower levels in the hierarchy?

Thanks
