### DISCUSSION TITLE
Use ```or``` with ```contains```

### DISCUSSION THREAD

**Discussion by julianbarg** [mikefarah/yq#1356] [Q&A]
Say I have a file foo.yaml:

```yaml
- name: foo
  irrelevant:
    - a
    - h
  tags:
    - a
    - b
    - c
- name: bar
  irrelevant:
    - a
    - h
  tags: 
    - b
    - c
    - d
- name: bar2
  irrelevant:
    - a
    - h
  tags:
    - f
    - g
    - h
```

I want to select all entries in the primary array that contain in the tag array either the value "a" or "h" (or both). How do I go about this?
