### DISCUSSION TITLE
YQ's data model?

### DISCUSSION THREAD

**Discussion by philomory** [mikefarah/yq#1370] [Q&A]
I think there's something about the "data model" of `yq` that I'm not understanding, and maybe someone can shed some light on it?

I'm trying to understand why these two pipelines give different results:

```yaml
#example.yaml
- app_version: 0.1.0 
  chart: foo-1.2.3
  name: foo
- app_version: 0.2.0 
  chart: bar-4.5.6
  name: bar
- app_version: 0.3.0 
  chart: baz-7.8.9
  name: baz
```

```
$ yq '.[] | select(.name=="foo").app_version // 0' example.yaml # attempt 1
0.1.0
0
0
$ yq '.[] | select(.name=="foo") | .app_version // 0' example.yaml # attempt 2
0.1.0
```

I expected the same results in both cases, but it seems like select doesn't actually _remove_ the things it's filtering away until it gets to the pipe operator? Like select makes them temporarily `null`, and then the `|` actually removes them from the array entirely? Except that's clearly not right, because an array of literal `null`s survives the pipe operator without issue.

Can someone explain why these work differently?

(Also `.[] | select(.name=="foo").app_version | . // 0`, which gives the same results as attempt 2, begs an explanation)
