### DISCUSSION TITLE
Filter the path based in search

### DISCUSSION THREAD

**Discussion by junaid18183** [mikefarah/yq#1374] [Q&A] [answered]
Not sure whether what I am asking is supported or not but in all my searches to documentation yield nothing, that's why I am not adding feature_requst 

here is my input yaml file
```
profile: default
hub: ghcr.io/junaid18183/istio
tag: 1.11.3
domain: ijuned.com
revision: ""
openshift: false
imagePullSecrets: []
monitoring:
  enabled: false
postInstallHook:
  image: ghcr.io/junaid18183/base:8.4
  name: base
cni:
  image:
    hub: ghcr.io/junaid18183/istio
```

All I want is the find and replace the `ghcr.io/junaid18183/` to `docker.io/junaid18183/` and create the  patch file as ( containing keys containing only the search items

```
hub: docker.io/junaid18183/istio
postInstallHook:
  image: docker.io/junaid18183/base:8.4
cni:
  image:
    hub: docker.io/junaid18183/istio
```

And the structure and key's to find the string is dynamic. 

I tried 

```
yq '... | select( .== "*ghcr.io/junaid18183*") = "docker.io/junaid18183" | .[]' /tmp/1.yaml
yq ' {} as $o | (.. | select(. == "*jun*")) as $t |(($t | path | .[]) as $p ireduce($o; .[$p]))=$t  | $o' /tmp/1.yaml
```

**Comment by mikefarah** [comment, marked as answer]
Had to think about this one - and I realised that to do it - you need a `setpath` operator like `jq` - which `yq` doesn't yet have. I will add it to the next release, then you will be able to:

```bash
yq '(.. | select(tag == "!!str" and test("ghcr.io/junaid18183"))) as $i ireduce({}; setpath($i | path; $i | sub("ghcr.io", "docker.io"))) file.yaml
```

Explanation:
1. Find all the entries you wish to update `(.. | select(tag == "!!str" and test("ghcr.io/junaid18183"))`
2. Use reduce to create a new object, which will only contain these entries 
3. Create entries in the new object, using the paths of the found entries `setpath($i | path ; ...`
4. For the value param of setpath, substitute the old value with the new value

You won't be able to do this until I release a new version (4.28+)

**Reply by junaid18183** [reply]
Thanks for the prompt reply, I had to hack using bash till then, Below is the hack if some on stumbles upon it 

```
INPUT_FILE=/tmp/source.yaml
DEST_FILE=/tmp/dest.yaml

DEST_REGISTRY="docker.io/junaid18183"
SOURCE_REGISTRY="ghcr.io/junaid18183"
#------------------------------------------------------------
yq -o=props '... comments = ""' $INPUT_FILE | grep -E "$SOURCE_REGISTRY" | yq -p=props >$DEST_FILE
images=($(yq -o=props '... comments = ""' $DEST_FILE | grep -E "$SOURCE_REGISTRY" | awk '{print $3}'))
keys=($(yq -o=props '... comments = ""' $DEST_FILE | grep -E "$SOURCE_REGISTRY" | awk '{print $1}'))

count=0
cmd=""
for i in ${keys[@]}; do
    if [ -n "${cmd}" ]; then
        cmd="$cmd | "
    fi
    image=${images[$count]}
    new_image=${image/$SOURCE_REGISTRY/$DEST_REGISTRY}

    cmd=$cmd".$i = \"${new_image}\" " \
        count=$count+1
done

cmd="yq -i '$cmd' $DEST_FILE"
eval $cmd
echo "$DEST_FILE"

````

**Reply by mikefarah** [reply]
FYI 4.28.1 has been released :)

**Reply by junaid18183** [reply]
oh wow, thanks for the swift reply , confirmed its working as expected 

```
❯ yq '(.. | select(tag == "!!str" and test("ghcr.io/junaid18183"))) as $i ireduce({}; setpath($i | path; $i | sub("ghcr.io", "docker.io")))' /tmp/source.yaml
hub: docker.io/junaid18183/istio
postInstallHook:
  image: docker.io/junaid18183/base:8.4
cni:
  image:
    hub: docker.io/junaid18183/istio
```
