### DISCUSSION TITLE
Multiple occurrence's with key, on replace it replace for both places, intention is to replace either of key.

### DISCUSSION THREAD

**Discussion by dnyaneshwarjadhav** [mikefarah/yq#1386] [Ideas]
```
apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: service
  namespace: dashboard-demo
spec:
  selector:
    matchLabels:
      app: service
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: service
    spec:
      containers:
        - name: service
          image: demo/nonprod:registration.2022-10-18-094257 # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster
---

kind: Service
apiVersion: v1
metadata:
  name: service
  labels:
    name: service
spec:
  ports:
    - nodePort: 30163
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: service
  type: NodePort
```

I am trying with below query ```yq e ".spec.template | select(length>0) | .spec.containers[0].image=\"ttttttt\"" deployment.yaml```
This is not working out.
