### DISCUSSION TITLE
How to merge from properties file without losing fields?

### DISCUSSION THREAD

**Discussion by Desolar1um** [mikefarah/yq#1406] [Q&A]
Hi all,

I am very new to YAML and yq, so Id like to ask for your patience with me here.

I have the following file
```yaml
static_resources:
  listeners:
    - address:
        socket_address:
          address: 0.0.0.0
          port_value: 8080
      filter_chains:
        - filters:
            - name: envoy.filter
              typed_config:
                "@type": type....
                server_name: name
                access_log:
                  - name: access_loggers.stdout
                    typed_config:
                      "@type": type
                codec_type: type
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  response_headers_to_add:
                    - header:
                        key: "UPSTREAM_REMOTE_ADDRESS"
                        value: "%UPSTREAM_REMOTE_ADDRESS%"
                      append: true
                  virtual_hosts:
                    - name: local_service
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: cluster
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type
  clusters:
    - name: cluster
```

I wish to use a properties file to change the value of `server_name`.

```properties
static_resources.listeners.0.filter_chains.0.filters.0.typed_config.server_name=NEW_NAME_TEST
```

When I run the following command, server_name is changed as intended, however I lose the rest of the information from the `listeners` block. 
`yq '. *= load_props("new-config.properties")'  config.yaml`

#### Expected result:
```
static_resources:
  listeners:
    - address:
        socket_address:
          address: 0.0.0.0
          port_value: 8080
      filter_chains:
        - filters:
            - name: envoy.filter
              typed_config:
                "@type": type....
                server_name: NEW_NAME_TEST
                access_log:
                  - name: access_loggers.stdout
                    typed_config:
                      "@type": type
                codec_type: type
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  response_headers_to_add:
                    - header:
                        key: "UPSTREAM_REMOTE_ADDRESS"
                        value: "%UPSTREAM_REMOTE_ADDRESS%"
                      append: true
                  virtual_hosts:
                    - name: local_service
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: cluster
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type
  clusters:
    - name: cluster
```

#### Actual Result
```
static_resources:
  listeners:
    - filter_chains:
        - filters:
            - typed_config:
                server_name: TEST_NAME_TEST
  clusters:
    - name: cluster
```

EDIT: I have a lot of fields that need editing in this way, and I think a properties file would make the most sense for my use case.
