### DISCUSSION TITLE
How to extract data with parent key's name included in output

### DISCUSSION THREAD

**Discussion by jimbuitt-trovata** [mikefarah/yq#1414] [Q&A]
I'm attempting to strip out sections of a YAML file to generate a new YAML file from a subset of its keys. To do that, I need to extract keys and their values while keeping the desired key in the output. 

For example, if I have `test.yaml` like the following:
```
rootkey1:
  subkey1:
    a: b
    c: d
rootkey2:
  subkey2:
    e: f
    g: h
rootkey3:
  subkey3:
    i: j
    k: l
```

To extract `rootkey2`, normally I would run:

`yq .rootkey2 test.yaml`

which gives:
```
subkey2:
  e: f
  g: h
```

However, I would like to get the output:
```
rootkey2:
  subkey2:
     e: f
     g: h
```

Is there a query that gets me both the key name and its value?

Thanks!
