### DISCUSSION TITLE
Set style only for specific type

### DISCUSSION THREAD

**Discussion by carlocorradini** [mikefarah/yq#1416] [Q&A] [answered]
Following the [documentation](https://mikefarah.gitbook.io/yq/operators/style) I can set or update style.
However, `yq e '.. style="double"' file.yml` set style "double" to all values (*str*, *bool*, *int*, *float*):
```yml
a: "Hello World"
b: "true"
c: "10"
d: "3.14"
```
How can I set style (in this case `double`) only for a specific type (in this case *str*):
```yml
a: "Hello World"
b: true
c: 10
d: 3.14
```

Thanks 🥳
