### DISCUSSION TITLE
Content in curly braces is formatted

### DISCUSSION THREAD

**Discussion by huangyutongs** [mikefarah/yq#1421] [Q&A]
```
yq -V
yq (https://github.com/mikefarah/yq/) version 4.29.2
```
I have the following value.yaml
```
operations:
  replicaCount: 3
  readySeconds: 3
  revisionHistoryLimit: 10
  image:
    repository: harbor.platform.yhglobal.cn/yhgit/hub.yhwms.operations
    tag: 2e4aec1e
    pullPolicy: IfNotPresent

  extraEnv:
    {
      "ASPNETCORE_ENVIRONMENT": "Beta",
      "TZ": "Asia/Shanghai",
      "Version": "00b40db3",
    }
```

implement    ```yq  .operations.image.tag=v2 values-beta.yaml```
actual effect
```
operations:
  replicaCount: 3
  readySeconds: 3
  revisionHistoryLimit: 10
  image:
    repository: harbor.platform.yhglobal.cn/yhgit/hub.yhwms.operations
    tag: 123
    pullPolicy: IfNotPresent
  extraEnv: {"ASPNETCORE_ENVIRONMENT": "Beta", "TZ": "Asia/Shanghai", "Version": "00b40db3"}
```
The contents of the curly braces are displayed as one line，How to avoid this problem, I just want it to replace my mirror tag
