### DISCUSSION TITLE
Unable to index array

### DISCUSSION THREAD

**Discussion by s-pravin** [mikefarah/yq#1432] [Q&A] [answered]
I have a sample YAML file with following content:
```
status:
  interfaces:
  - deviceID: "A2A0"
    name: CL1
  - deviceID: "A2A0"
    name: CL2
  - deviceID: 123d
    name: CL33
  - deviceID: 123d
    name: CL34
```
Trying to get first occurrence of `name` with a given `deviceID`. Using the following command:
`yq '.status.interfaces[] | select(.deviceID == "123d") | [.name] | .[0]' sample.yaml`
outputs
```
CL33
CL34
```

My expectation is that it shall output array index 0 i.e. `CL33`. Can you please help me understand what am I missing?

Thanks
