### DISCUSSION TITLE
Extracting price for a product

### DISCUSSION THREAD

**Discussion by arthef** [mikefarah/yq#1436] [Q&A] [answered]
I have been trying this for quite some time and I just cannot find a way or any hints how exactly to do it.
So I have the following 'catalog' yaml:
```yaml
catalog:
  plans:
    plan:
      - +@name: personal-monthly
        product: Personal
        finalPhase:
          recurring:
            recurringPrice:
              price:
                value: "12.34"
      - +@name: small-monthly
        product: Small
        finalPhase:
          recurring:
            recurringPrice:
              price:
                value: "34.56"
```
Now, how to extract price's `value` for `product`: "Personal"? Any suggestions would be very appreciated.
