### DISCUSSION TITLE
Merging, overriding, arrays.

### DISCUSSION THREAD

**Discussion by bukowa** [mikefarah/yq#1437] [General]
Hey i am looking for a way to utilize `jq` as a replacement for `helm` and `kustomize`.  While being excited seeing how nice it can work I just got stuck at arrays, given below files and command - output is not like i would imagine - first element in array `containers` is actually overriden ( key `name`) but it's also added as an additional element. I wonder what would be the best way here to provide consistency while being able to delete certain array element by index and also customizable overriding of other values.
````yaml
# override.yaml
labels: &labels
  my.first.label: "true"
  basic.label: null

templates:
  deployment.yaml:
    metadata:
      name: "metadata.name.override"
      labels:
        <<: *labels
    spec:
      template:
        spec:
          containers:
            - name: "busybox-override"
````
````yaml
# ./templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "metadata.name"
  labels:
    basic.label: "false"
spec:
  selector:
    matchLabels:
      override: "spec.selector.matchLabels.override"
  template:
    metadata:
      labels:
        override: "spec.selector.matchLabels.override"
    spec:
      containers:
        - name: busybox
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - |
              sleep infinity
        - name: busybox2
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - |
              sleep infinity
````
````bash
$ yq '. *d+ (load("./override.yaml") | .templates."deployment.yaml") | explode(.) | del(.. | select(. == null))' ./templates/deployment.yaml
````

````yaml
# output
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "metadata.name.override"
  labels:
    my.first.label: "true"
spec:
  selector:
    matchLabels:
      override: "spec.selector.matchLabels.override"
  template:
    metadata:
      labels:
        override: "spec.selector.matchLabels.override"
    spec:
      containers:
        - name: "busybox-override"
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - |
              sleep infinity
        - name: busybox2
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - |-
              sleep infinity
        - name: "busybox-override"
````
