### DISCUSSION TITLE
Need help to quote value in array

### DISCUSSION THREAD

**Discussion by jmcwork** [mikefarah/yq#1450] [Q&A] [answered]
Hello I have a problem to quote with "" one value in array 

**Version YQ** 
last release ubuntu focal :  4.16.2

**Yml file SRC**
```
cat <<EOF > sample.yml
---
all_access:
  reserved: false
  backend_roles:
  - "admin"
EOF
 ```

**Code**

```bash
#!/bin/bash

ADMIN_TEAM=toto

v=${ADMIN_TEAM} yq eval '.all_access.backend_roles += [env(v)] | .all_access.backend_roles style="double"' -i ./sample.yml 
```
**RESULT**
```
cat  sample.yml
---
all_access:
  reserved: false
  backend_roles:
    - "admin"
    - toto
```	
User toto added **but without double quote**  :-(    (	- "toto"   )
	
Help  !!!
