### DISCUSSION TITLE
How to merge and keep original anchors

### DISCUSSION THREAD

**Discussion by rjshrjndrn** [mikefarah/yq#1452] [Q&A] [answered]
First of all, thank you for this wonderful project. It makes yaml operations humanly :)

**Describe the bug**
Yaml merge drop anchors

Version of yq: 4.30.4
Operating system: linux
Installed via: binary-release
**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)

old_vars.yml:
```yaml
clickhouse:
  enabled: true

global:
  name: app1
```

new_vars.yml:
```yaml
clickhouse: &clickhouse
  enabled: false

global:
  name: app1
  clickhouse: *clickhouse
```

**Command**
The command you ran:
```
 yq '. *= load("old_vars.yaml")' new_vars.yaml
```

**Actual behavior**

```yaml
clickhouse:
  enabled: true
global:
  name: app1
  clickhouse: *clickhouse
```

**Expected behavior**

```yaml
clickhouse:  &clickhouse             #Should have anchor here, like &clickhouse
  enabled: true
global:
  name: app1
  clickhouse: *clickhouse     # This is not a valid alias now

```

**Additional context**

I've 2 files, one the customized by me, other one the software updates, usually every release will have small changes in this yaml. I'm using yq to merge these 2 files, but this anchor is becoming a problem.
