### DISCUSSION TITLE
Adding to an array

### DISCUSSION THREAD

**Discussion by tiredofit** [mikefarah/yq#1485] [Q&A]
I would like yaml to look like this:

````yq
a:
  a1: value1
  a2: value2
  a3: false
  aa:
    - aa1
    - aa2
    aaa: true
````

I can only get it to to the `aa:` key and not able to input `aaa` as such.

Would someone be able to answer this mostly basic question for me? 

````yq
yq -i '.a += {
            "a1": "value" ,
            "a2": "value2" ,
            "a3": false ,
            "aa": [
                "aa1",
                "aa2"
            ]
            } '           
````

**Comment by tiredofit** [comment]
````
yq -n '
        .a.a1 = "value" |
        .a.a2 = "value2" |
        .a.a3 = false |
        .a.aa = [
                {"aaa" : 
                        ["aaa1","aaa2"],
                        "ab" : true}]
        '
````

````
a:
  a1: value
  a2: value2
  a3: false
  aa:
    - aaa:
        - aaa1
        - aaa2
      ab: true
````
