### DISCUSSION TITLE
Extracting certain fields to manipulate them individually and combine into line by line output

### DISCUSSION THREAD

**Discussion by manuelgrabowski** [mikefarah/yq#1488] [Q&A] [answered]
Given the following YAML:

```
- name: Bob Blob
  start_date: 2022-11-05
  slack:
    id: 0123
    username: BOB
  hobbies: []
- name: Jane Doe
  start_date: 2022-12-12
  slack:
    id: 1234
    username: Jane
```

My desired output is:

```
Bob Blob | `@bob`
Jane Doe | `@jane`
```

But I'm unable to figure out how to achieve this, even after going through the docs many times and reading plenty of other examples in here. I'm guessing my approach must be rather fundamentally wrong? Please let me know if I missed this in the docs, it feels like such a basic thing to do.

This is what I tried:

```
cat test.yml | yq '.[] | (.name + " | `@" + .slack.username | downcase + "`")'
```

Which results in this:

```
bob blob | `@bob`
jane doe | `@jane`
```

So `downcase` is applied to the entire line rather than just the `.slack.username` field.
