### DISCUSSION TITLE
how to remove `-` before values

### DISCUSSION THREAD

**Discussion by weironz** [mikefarah/yq#1510] [General]
```
status:
  interfaces:
  - deviceID: 159b
    driver: ice
    linkType: ETH
    mac: b4:96:91:dc:6e:38
    mtu: 1500
    name: ens3f0
    pciAddress: "0000:19:00.0"
    totalvfs: 128
    vendor: "8086"
  - deviceID: 159b
    driver: ice
    linkType: ETH
    mac: b4:96:91:dc:6e:39
    mtu: 1500
    name: ens3f1
    pciAddress: "0000:19:00.1"
    totalvfs: 128
    vendor: "8086"
  - deviceID: 159b
    driver: ice
    linkType: ETH
    mac: b4:96:91:dc:5c:5c
    mtu: 1500
    name: ens1f0
    pciAddress: 0000:5e:00.0
    totalvfs: 128
    vendor: "8086"
  - deviceID: 159b
    driver: ice
    linkType: ETH
    mac: b4:96:91:dc:5c:5d
    mtu: 1500
    name: ens1f1
    pciAddress: 0000:5e:00.1
    totalvfs: 128
    vendor: "8086"
  syncStatus: Succeeded
```
i don't want `-` before "0000:19:00.0"
```
root@ubuntu:~# cat sriovnetworknodestates.yaml | yq  '.status.interfaces | map(select(.name == "ens3f0") | .pciAddress)'
- "0000:19:00.0"
```
because i want put "0000:19:00.0"to a env
```
pc_address=$(cat sriovnetworknodestates.yaml | yq  '.status.interfaces | map(select(.name == "ens3f0") | .pciAddress)')
```
