### DISCUSSION TITLE
Filter an array and iterate on selected entries in shell script

### DISCUSSION THREAD

**Discussion by balki** [mikefarah/yq#1511] [Q&A] [answered]
Example yaml (ex.yaml):

```yaml
items:
  - name: foo
    place: nyc
  - name: bar
    place: sea
  - name: blah
    place: nyc
  - name: xyz
    place: san
  - name: abc
    place: san
```
script:

```bash
#!/usr/bin/bash

# limit and filter variable comes from user input (e.g. commandline)
limit=2
filter='.place != "nyc"'

for index in $(yq ".items | .[] | select($filter) | path | .[-1]" ./ex.yaml | head -n $limit)
do # Do something with the selected entries
                name=$(yq ".items.$index | .name" ex.yaml)
                place=$(yq ".items.$index | .place" ex.yaml)
                echo "Hello $name, You live in $place."
done
```
Is there a better concise way to do the above? In particular, is it possible to replace `| head -n $limit`, inside yq expression and still have the original index values for the loop?

Output:
```
Hello bar, You live in sea.
Hello xyz, You live in san.
```
