### DISCUSSION TITLE
Adding alias and anchor in yml file

### DISCUSSION THREAD

**Discussion by kelly-scalapay** [mikefarah/yq#1518] [Q&A] [answered]
Im unable to have the & and * characters appear as not in quote, is there a way I can do the below without it wrapping the values for the anchor and alias in quotes for a bitbucket-pipelines.yml file.

```
    yq e '.definitions.steps = [{
        "step":"&Check-dev", 
            "name":"Check dev", 
            "script":["script.sh"]
        }] + .definitions.steps' bitbucket-pipelines.yml
```

and then the below:

`yq '.pipelines.branches.develop = [{"step":"*Check-dev"}] + .pipelines.branches.develop ' bitbucket-pipelines.yml`

Id like it to look like the below:

```
definitions:
  caches:
    npm: $HOME/.npm
  steps:
    - step: &Check-dev
        name: Check dev
        script:
          - script.sh

pipelines:
  branches:
    develop:
      - step: *Check-dev
```
but i get the below:

```
definitions:
  caches:
    npm: $HOME/.npm
  steps:
    - step: '&Check-dev'
        name: Check dev
        script:
          - script.sh

pipelines:
  branches:
    develop:
    - step: '*Check-dev'
```

**Comment by mikefarah** [comment, marked as answer]
Yep - you need to use the anchor and alias operators, documented here: https://mikefarah.gitbook.io/yq/operators/anchor-and-alias-operators

**Reply by kelly-scalapay** [reply]
Ive gone through the documentation and having trouble implementing it how i need.

Im trying to get this new step to be the first in the array of steps, while still keeping the existing steps already there, using the below 

```yq '.pipelines.branches.develop[].step alias = "Check-dev"' bitbucket-pipelines.yml```

results in:
```
pipelines:
  branches:
    develop:
      - step: *Check-dev
      - step: *Check-dev
```

Where when I attempt to get the first element , 

`yq '.pipelines.branches.develop[].step alias = "Check-dev"' bitbucket-pipelines.yml`

it will replace the first value.

**Reply by mikefarah** [reply]
I'm getting confused as to what you are trying to do. The command you have there with `.develop[]` will match every item in the array.

**Reply by kelly-scalapay** [reply]
Im trying to insert a new step under the develop section, ideally if my yml looks like the below:

```
pipelines:
  branches:
    develop:
      - step: *Check-test
      - step: *Check-prod
```


Id like it to add the Check-dev step at the beginning

```
pipelines:
  branches:
    develop:
      - step: *Check-dev
      - step: *Check-test
      - step: *Check-prod
```
