### DISCUSSION TITLE
Replace the value of a specific key in a "collection"

### DISCUSSION THREAD

**Discussion by aldobazzi** [mikefarah/yq#1523] [Q&A]
Hi all

The topic seemed simple but I still did not find a suitable solution also after extensively checking the documentation and existing discussions. 

I have a YAML containing the following "collection"

```
collection:
  - cat: "cat value"
  - goat: "goat value"
  - dog: "dog value"
```

How could one search for a specific key and replace its value in this collection, given the position/index of the element is not known?
For example replacing `goat` with a new value `goat value new` ?

Many thanks, regards
Aldo
