### DISCUSSION TITLE
yq has introduced '!!merge' inside yml file and not sure why

### DISCUSSION THREAD

**Discussion by kelly-scalapay** [mikefarah/yq#1527] [Q&A]
Ive used yq to modify and add extra steps to a bitbucket pipelines yml file and noticed that its changed the below:

```
    Pipeline-Deploy-Foo:
      - step:
          <<: *Deploy-Foo-Auto
          trigger: automatic
```

To the below:

```
    Pipeline-Deploy-Foo:
      - step:
          !!merge <<: *Deploy-Foo-Auto
          trigger: automatic
```

This area of the yml file wasn't modified or inserted as part of the yq command so i'm not sure why its made this change in the file. Is there a way I can have it not introduce the !!merge word infront of the <<?

thanks
