### DISCUSSION TITLE
how to use yq as a yaml viewer?

### DISCUSSION THREAD

**Discussion by leleliu008** [mikefarah/yq#1558] [Q&A]
given a yaml file named ncurses.yml and it's content as follows:
```yaml
summary: Text-based UI library
web-url: https://www.gnu.org/software/ncurses
src-url: https://ftp.gnu.org/gnu/ncurses/ncurses-6.3.tar.gz
src-sha: 97fc51ac2b085d4cde31ef4d2c3122c21abc217e9090a43a30fc5ec21684e059
git-url: https://github.com/mirror/ncurses
license: MIT

binbstd: yes
install: |
    run install -d "$PACKAGE_INSTALL_DIR/lib/pkgconfig" || return 1

    configure \
        --with-pkg-config-libdir="$PACKAGE_INSTALL_DIR/lib/pkgconfig" \
        --with-shared \
        --without-ada \
        --without-tests \
        --without-debug \
        --without-valgrind \
        --enable-const \
        --enable-widec \
        --enable-termcap \
        --enable-warnings \
        --enable-pc-files \
        --enable-ext-mouse \
        --enable-ext-colors \
        --disable-stripping \
        --disable-assertions \
        --disable-gnat-projects \
        --disable-echo && 
        {
            cd "$PACKAGE_INSTALL_DIR/include" || return 1
            
            for item in curses.h ncurses.h form.h menu.h panel.h term.h termcap.h
            do
                ln -s "ncursesw/$item" "$item" || return 1
            done
            
            cd "$PACKAGE_INSTALL_DIR/lib" || return 1

            for item in libncurses libpanel libmenu libform
            do
                ln -s "${item}w$STATIC_LIBRARY_SUFFIX" "${item}$STATIC_LIBRARY_SUFFIX" || return 1
                ln -s "${item}w$SHARED_LIBRARY_SUFFIX" "${item}$SHARED_LIBRARY_SUFFIX" || return 1
            done

            ln -s libncurses++w.a libncurses++.a || return 1

            cd "$PACKAGE_INSTALL_DIR/lib/pkgconfig" &&
            ln -s ncursesw.pc ncurses.pc
        }
```

I use `yq -P ncurses.yml` command to see the file content, I expected to see raw file with addtion of color highlighting, but actually it output a processed content as follows:

```yaml
summary: Text-based UI library
web-url: https://www.gnu.org/software/ncurses
src-url: https://ftp.gnu.org/gnu/ncurses/ncurses-6.3.tar.gz
src-sha: 97fc51ac2b085d4cde31ef4d2c3122c21abc217e9090a43a30fc5ec21684e059
git-url: https://github.com/mirror/ncurses
license: MIT
binbstd: yes
install: "run install -d \"$PACKAGE_INSTALL_DIR/lib/pkgconfig\" || return 1\n\nconfigure \\\n    --with-pkg-config-libdir=\"$PACKAGE_INSTALL_DIR/lib/pkgconfig\" \\\n    --with-shared \\\n    --without-ada \\\n    --without-tests \\\n    --without-debug \\\n    --without-valgrind \\\n    --enable-const \\\n    --enable-widec \\\n    --enable-termcap \\\n    --enable-warnings \\\n    --enable-pc-files \\\n    --enable-ext-mouse \\\n    --enable-ext-colors \\\n    --disable-stripping \\\n    --disable-assertions \\\n    --disable-gnat-projects \\\n    --disable-echo && \n    {\n        cd \"$PACKAGE_INSTALL_DIR/include\" || return 1\n        \n        for item in curses.h ncurses.h form.h menu.h panel.h term.h termcap.h\n        do\n            ln -s \"ncursesw/$item\" \"$item\" || return 1\n        done\n        \n        cd \"$PACKAGE_INSTALL_DIR/lib\" || return 1\n\n        for item in libncurses libpanel libmenu libform\n        do\n            ln -s \"${item}w$STATIC_LIBRARY_SUFFIX\" \"${item}$STATIC_LIBRARY_SUFFIX\" || return 1\n            ln -s \"${item}w$SHARED_LIBRARY_SUFFIX\" \"${item}$SHARED_LIBRARY_SUFFIX\" || return 1\n        done\n\n        ln -s libncurses++w.a libncurses++.a || return 1\n\n        cd \"$PACKAGE_INSTALL_DIR/lib/pkgconfig\" &&\n        ln -s ncursesw.pc ncurses.pc\n    }\n"
```

how should I do?
