### DISCUSSION TITLE
How to merge two .yaml files such that shared keys between the files uses only one of their values?

### DISCUSSION THREAD

**Discussion by williamj20** [mikefarah/yq#1561] [Q&A] [answered]
Hi, I am attempting to merge two yaml files and would like any shared keys under a specific key to use values from one of the yaml files, and not merge both. This problem may be better described using an example. GIven file1.yaml and file2.yaml, I am trying to achieve the following:

file1.yaml
```
name: 'file1'
paths:
  path1: 
    content: "t"
  path2:
    content: "b"
```

file2.yaml
```
name: 'file2'
paths:
  path1: 
    value: "t"
```

My ideal result in merging is the following file:

file3.yaml
```
name: 'file2'
paths:
  path1: 
    value: "t"
  path2:
    content: "b"
```

Specifically, I would like to overwrite any key under paths such that if both yaml files have the same key under paths, then only use the value from file2. Is this possible? Apologies in advance for the convoluted description of the problem

**Comment by mikefarah** [comment, marked as answer]
You may need to modify this a little, but hopefully you get the gist:

```bash
yq '. as $d1 | load("file2.yaml") as $d2 | 
   ($d1 | .paths | keys | .[]) as $i ireduce($d2; 
   .paths[$i] = .paths[$i] // $d1.paths[$i])' file1.yaml
```

Explanation:
High level, this works by reducing the path keys from file1 into file2, where each path we either use file2 if present, file1 otherwise.

- `'. as $d1 | load("file2.yaml") as $d2` Load the files into $d1 and $d1
- `($d1 | .paths | keys | .[]) as $i ireduce($d2` Reduce the paths in $d1 into $d2
- `.paths[$i] = .paths[$i] // $d1.paths[$i]` Every path element in $d1, update the path entry in $d2. Using the alternative operator `//` this will use the existing $d2 path if it's there already, otherwise it will use the $d1 path (`$d1.paths[$i]`)

Hope that makes sense!

**Reply by williamj20** [reply]
Thank you for the solution! It is extremely helpful. I have an additional question. Is it possible to modify the command you've provided so that any keys which exist in file1 but don't exist in file2 would also use the file1 keys and values? Currently to my understanding, any keys which exist in file2 but not file1 will be added. I'd like to do the same for any keys which exist in file1 but not in file2 as well. Here's a visualization of the question: 

file1.yaml

```
name: 'file1'
paths:
  path1: 
    content: "t"
  path2:
    content: "b"
 title: "file1yaml"
```

file2.yaml

```
name: 'file2'
paths:
  path1: 
    value: "t"
info: "file2yamlinfo"
```

Result:

file3.yaml

```
name: 'file2'
paths:
  path1: 
    value: "t"
  path2:
    content: "b"
 title: "file1yaml"
 info: "file2yamlinfo"
```
