### DISCUSSION TITLE
unknown anchor error when merging multiple files

### DISCUSSION THREAD

**Discussion by chr1shung** [mikefarah/yq#1564] [Q&A] [answered]
Hi, my use case is merging 2 (or more) docker compose files and retrieve only the services list.  
Consider the following simplified examples:

- basic.yml
```yaml
x-common-env-variables: &common-variables
  BASIC_KEY: value

services:
  consul:
    image: consul:1.13.2
    container_name: consul
    environment:
      <<: *common-variables

```

- advance.yml
```yaml
x-advance-env-variables: &advance-variables
  ADVANCE_KEY: value

services:
  consul:
    environment:
      <<: *advance-variables
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    environment:
      <<: *advance-variables
```

Here's what I've tried:
```shell
$ yq ea '. as $item ireduce ({}; . * $item )' basic.yml advance.yml | yq '.services | keys | ... comments=""'
Error: bad file '-': yaml: unknown anchor 'advance-variables' referenced
```

Any chance I can make this work ?
Thanks for the help
