### DISCUSSION TITLE
How to remove a certian element in an array

### DISCUSSION THREAD

**Discussion by AristoChen** [mikefarah/yq#1606] [Q&A] [answered]
Hi, I am quite new to yq, and I have tried to google and search the discussions here for a while, still not able to get the expected ressult

Here is the `test.yaml` that I have
```yaml
build-packages:
  - bc
  - bison
  - build-essential
  - on amd64:
    - gcc-aarch64-linux-gnu
    - gcc-or1k-elf
```

I would like to remove the `gcc-or1k-elf`, and the expected outcome should be

```yaml
build-packages:
  - bc
  - bison
  - build-essential
  - on amd64:
    - gcc-aarch64-linux-gnu
```

Thanks in advance for any help!
