### DISCUSSION TITLE
yq get values from key list

### DISCUSSION THREAD

**Discussion by weironz** [mikefarah/yq#1633] [General]
sample config.yaml
```
spec:
  hosts:
  - {name: node1, address: 172.16.0.2, internalAddress: 172.16.0.2, port: 8022, user: ubuntu, password: "Qcloud@123"}
  - {name: node2, address: 172.16.0.3, internalAddress: 172.16.0.3, password: "Qcloud@123", labels: {disk: SSD, role: backend}}
  - {name: node3, address: 172.16.0.4, internalAddress: 172.16.0.4, privateKeyPath: "~/.ssh/id_rsa"}
  - {name: node4, address: 172.16.0.5, internalAddress: 172.16.0.5, privateKeyPath: "~/.ssh/id_rsa"}
  roleGroups:
    etcd:
    - node1
    - node2
    - node3
    master:
    - node1
    - node2
    worker:
    - node1
    - node2
```

i want get all etcd group member address or password..
```
$ yq .spec.roleGroups.etcd.[] config.yaml
node1
node2
node3
```
how can i get this output
```
$ yq  xxx  match (node1 node2 node3)   .address
172.16.0.2
172.16.0.3
172.16.0.4
```

any idea ,thanks.
