### DISCUSSION TITLE
access element

### DISCUSSION THREAD

**Discussion by thatsk** [mikefarah/yq#1637] [General]
```
nomad::config_hash:
  client:
    - enabled: true
      host_volume:
        eas:
          - path: /var/Jukebox/eas
            read_only: false
      options:
        - docker.privileged.enabled: true
          docker.volumes.enabled: true
          driver.raw_exec.enable: true
  consul:
    - address: 127.0.0.1:8500
      auto_advertise: true
      client_auto_join: true
      client_service_name: nomad-client-%{hiera('consul.datacenter')}
      server_auto_join: true
      server_service_name: nomad-%{hiera('consul.datacenter')}
      token: '%{alias(''consul.mobi_service_token'')}'
  data_dir: /var/lib/nomad
  datacenter: '%{alias(''consul.datacenter'')}'
  enable_syslog: false
  log_file: /var/log/nomad/nomad.log
  log_level: INFO
  log_rotate_max_files: 3
  telemetry:
    - collection_interval: 1s
      disable_hostname: true
      prometheus_metrics: true
      publish_allocation_metrics: true
      publish_node_metrics: true
```

How to access this?
