### DISCUSSION TITLE
Appending to array not working as expected

### DISCUSSION THREAD

**Discussion by mvaalexp** [mikefarah/yq#1643] [Q&A]
I am trying to append an object created from another array into an array. It is only adding the last element in the array though.
https://mikefarah.gitbook.io/yq/operators/add#concatenate-to-existing-array

sample.yaml
```
a:
  mountedConfigMaps:
    - name: "foo-config-test"
      mountPath: "/etc/foo-test"
    - name: "foo-config-test-2"
      mountPath: "/etc/foo-test-2"
  volumes:
    - name: "foo-config-empty"
      emptyDir: {}
```

`yq ".a.volumes += (.a.mountedConfigMaps.[] | { \"name\": .name, \"configMap\": { \"name\": .name }} | [.])" sample.yml `

Actual:
```
a:
  mountedConfigMaps:
    - name: "foo-config-test"
      mountPath: "/etc/foo-test"
    - name: "foo-config-test-2"
      mountPath: "/etc/foo-test-2"
  volumes:
    - name: "foo-config-empty"
      emptyDir: {}
    - name: "foo-config-test-2"
      configMap:
        name: "foo-config-test-2"

```

Expected:
```
a:
  mountedConfigMaps:
    - name: "foo-config-test"
      mountPath: "/etc/foo-test"
    - name: "foo-config-test-2"
      mountPath: "/etc/foo-test-2"
  volumes:
    - name: "foo-config-empty"
      emptyDir: {}
    - name: "foo-config-test"
      configMap:
        name: "foo-config-test"
    - name: "foo-config-test-2"
      configMap:
        name: "foo-config-test-2"
```

`yq "(.a.mountedConfigMaps.[] | { \"name\": .name, \"configMap\": { \"name\": .name }} | [.])" sample.yml`
Proper array:
```
- name: "foo-config-test"
  configMap:
    name: "foo-config-test"
- name: "foo-config-test-2"
  configMap:
    name: "foo-config-test-2"
```
