### DISCUSSION TITLE
How do I update a value and add a comment at the same time?

### DISCUSSION THREAD

**Discussion by andrewimeson** [mikefarah/yq#1666] [Q&A]
Hello,

I have this (simplified) pre-commit file in a bunch of places with a bunch of variations that I need to update.

```yaml
---
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
  - repo: https://github.com/lyz-code/yamlfix
    rev: 1.9.0
    hooks:
      - id: yamlfix
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.5.1-1
    hooks:
      - id: shfmt
```

I need to set the revision for `yamlfix` to `1.3.1` and also add a comment above mentioning why it's pinned at that version

```yaml
---
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
  - repo: https://github.com/lyz-code/yamlfix
    # blah blah
    rev: 1.3.1
    hooks:
      - id: yamlfix
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.5.1-1
    hooks:
      - id: shfmt
```

The exact placement of the comment isn't critical, I just want it somewhere around the yamlfix dictionary.

I can update the value successfully with

```sh
yq -i '
(.repos.[]
  | select(.repo == "*yamlfix")
  | .rev
) = "1.3.1"
' .pre-commit-config.yaml
```

But I can't seem to find a way to set `head_comment`. One way I attempted to ended up with the `rev` of all items being updated

```sh
yq -i '
(.repos.[]
  | select(.repo == "*yamlfix") head_comment="blah blah"
  | .rev
) = "1.3.1"
' .pre-commit-config.yaml
```

```yaml
---
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 1.3.1
    hooks:
      - id: trailing-whitespace
  # blah blah
  - repo: https://github.com/lyz-code/yamlfix
    # blah blah
    rev: 1.3.1
    hooks:
      - id: yamlfix
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: 1.3.1
    hooks:
      - id: shfmt
```
