### DISCUSSION TITLE
How to add text without ""

### DISCUSSION THREAD

**Discussion by shinrage** [mikefarah/yq#1682] [Q&A]
Hello experts,
Im trying to add text without quotes to a yaml file using this amazing tool yq.

`yq eval -i '.test.hosts.axdestest101.jirakey = text' sample.yaml`
Error: 1:36: invalid input text "text"

`yq eval -i '.test.hosts.axdestest101.jirakey = "text"' sample.yaml`

But with "" is working fine, can you help me to do this ? 

sample.yaml
```
test:
  hosts:
    axdestest102:
      jirakey: ""
    axdestest101:
      jirakey: 0
```
