### DISCUSSION TITLE
Adding a new list

### DISCUSSION THREAD

**Discussion by eveardown** [mikefarah/yq#1688] [Q&A]
Hi,

I have this YAML in `new.yaml`:

```
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: project-request
  creationTimestamp: null
objects:
  - kind: Project
    apiVersion: project.openshift.io/v1
    metadata:
      name: ${PROJECT_NAME}
      creationTimestamp: null
      annotations:
        openshift.io/description: ${PROJECT_DESCRIPTION}
        openshift.io/display-name: ${PROJECT_DISPLAYNAME}
        openshift.io/requester: ${PROJECT_REQUESTING_USER}
    spec: {}
    status: {}
  - kind: RoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: admin
      namespace: ${PROJECT_NAME}
      creationTimestamp: null
    subjects:
      - kind: User
        apiGroup: rbac.authorization.k8s.io
        name: ${PROJECT_ADMIN_USER}
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: admin
parameters:
  - name: PROJECT_NAME
  - name: PROJECT_DISPLAYNAME
  - name: PROJECT_DESCRIPTION
  - name: PROJECT_ADMIN_USER
  - name: PROJECT_REQUESTING_USER
``` 
I'd like to insert this YAML
```
      labels:
        - label: ${PROJECT_NAME}
```
Immediately before the `spec` in the `Project` object.

I can do this with the following yq query:

```
yq --prettyPrint -i '.objects.0.metadata.labels[0] = {"label": "${PROJECT_NAME}"}' new.yaml
```

My question is can I do this, not using an index on `objects`, but the value of the `object.kind` field instead? If so, how?

I'm using `yq (https://github.com/mikefarah/yq/) version v4.34.1` on Red Hat Enterprise Linux version 9.2

Many thanks,
Steve Brown
