### DISCUSSION TITLE
Is possible to select by subproperty?

### DISCUSSION THREAD

**Discussion by shinrage** [mikefarah/yq#1698] [General]
Hello,
I have a very big YAML like this format:
```
app:
  hosts:
    severname:
      team: Windows
      model: X
      ip: X
app2:
  hosts:
    severname2:
      team: Linux
      model: X
      ip: X
```

I want to select by team but maintain the yaml estructure,
I have tried this:
`yq eval 'select(.[].[].[].team == "Windows")' test.yaml`
but it shows all items,
by this way:
`yq eval '.[].[].[] | select(.team == "Windows")' test.yml`
is working, but i lost the yaml estructure of the main file, it only outputs the final properties.
```
team: Windows
model: X
ip: X
```
Is there any way to do this using the same YAML structure as the main file?

Thanks in advance

**Comment by mikefarah** [comment]
Can you please provide an example of the output you want - I'm a little confused

**Reply by shinrage** [reply]
Yes mike, sorry, the desired output i want is like this:

```
app:
  hosts:
    severname:
      team: Windows
      model: X
      ip: X
```

The output have to include all the parents of the yaml for each item matched with the select.

Thank you
