### DISCUSSION TITLE
apply changes to specific document in a multi document yaml

### DISCUSSION THREAD

**Discussion by mauricioscastro** [mikefarah/yq#1705] [Q&A] [answered]
I am still trying, but I just can´t seen to get this done and I know there's probably a straightforward way to do this.

I have a yaml with multiple documents:
```yaml
a: b
n:
  x: z
c:
 eee: M
---
a: b1
n:
  x: y
c1:
 eee1: M
---
a: b3
n:
  x: k
c2:
 eee2: M
```
and I need to select the one with a == b1 and n.x == y ,  update c1.eee1 and with that update the original document, or else, update di=2 with the result, or is there a way to this in one step?
