### DISCUSSION TITLE
How to add an object to a list if it doesn't exist?

### DISCUSSION THREAD

**Discussion by notorand-it** [mikefarah/yq#1716] [General]
I am not sure I can really do this in with a single command.
Of course I know how to do it with 2 (query + conditional add).
This is the file:
```
list:
  - name: one
    value: 1
  - name: two
    value: 2
```
I would like to add/replace `[{"name": "one", "value": "1"}]` only if the object with `name` "one" is not in the `list`, so only a single object is present in the list with the propery `"name": "one"`.
Any hint?
