### DISCUSSION TITLE
[question] how to add a newline in to 3-4th level of yaml

### DISCUSSION THREAD

**Discussion by dinhdobathi1992** [mikefarah/yq#1720] [Q&A]
src : 
```
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: calico-node
  namespace: kube-system
  labels:
    k8s-app: calico-node
spec:
  selector:
    matchLabels:
      k8s-app: calico-node
```

dest: (expected) 
```
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: calico-node
  namespace: kube-system
  labels:
    k8s-app: calico-node
spec:
  selector:
    matchLabels:
      k8s-app: calico-node
      test: true
```
