### DISCUSSION TITLE
Reference parent key name when replacing value of sub-key

### DISCUSSION THREAD

**Discussion by manuelgrabowski** [mikefarah/yq#1736] [Q&A] [answered]
I have the following input:

```yaml
toplevel1:
  replaceme: "test1"
  keepme1: "test2"
  keepme2:
    - "test3"
    - "test4"

toplevel2:
  replaceme: "test5"
  keepme2:
    - "test6"
    - "test7"


toplevel3:
  replaceme:
    - "test8"
    - "test9"
  keepme1: "test0"
```

and want to get to this output:

```yaml
toplevel1:
  replaceme: "foobar in toplevel1"
  keepme1: "test2"
  keepme2:
    - "test3"
    - "test4"

toplevel2:
  replaceme: "foobar in toplevel2"
  keepme2:
    - "test6"
    - "test7"


toplevel3:
  replaceme: "foobar in toplevel3"
  keepme1: "test0"
```

So replace the `replaceme` elements, regardless of them being a string or an array, with a string that contains the parent key name. I got the replacing part: `yq '. | (.[].replaceme |= "foobar in ")'`

But I can't figure out how back-reference to the toplevel key names in the value assignment.

**Comment by mikefarah** [comment, marked as answer]
You can use the `parent` operator to access the parent map, then `key` to get the key value:

`yq '(.. | select(has("replaceme")) | .replaceme) |= ("foobar in " + (parent | key))' file.yaml`

Note that I also have `.. | select(has("replaceme")) | .replaceme`:
- `..` recursively matches all the nodes
- `select(has("replaceme"))` will select all the nodes that have that field defined

Edit: formatting

**Reply by mikefarah** [reply]
```yaml
toplevel1:
  replaceme: "foobar in toplevel1"
  keepme1: "test2"
  keepme2:
    - "test3"
    - "test4"
toplevel2:
  replaceme: "foobar in toplevel2"
  keepme2:
    - "test6"
    - "test7"
toplevel3:
  replaceme: foobar in toplevel3
  keepme1: "test0"
```
