### DISCUSSION TITLE
Avoid operator being parsed as selector

### DISCUSSION THREAD

**Discussion by thardev** [mikefarah/yq#1740] [Q&A] [answered]
Hi 🙂 

So I have the following statement `yq -i '.logging.writers.filename = "/var/log/__APP__/__APP__.log"'` that I'm trying to use to replace the value on that nested key, but I get this error:
`Error: cannot index array with 'filename' (strconv.ParseInt: parsing "filename": invalid syntax)`

So I understood it is because it recognises `.filename` as operator instead as of a key. I tried many solutions but I cannot get it working, any clues?

Thanks!

**Comment by mikefarah** [comment]
Do you have an example of the file you are updating? I actually think the problem is 'writers' is an array of objects, and the expression is trying to index the array with 'filename' instead of a number

**Reply by thardev** [reply, marked as answer]
Hi @mikefarah 

You are actually right, the `writers` entry looks like this:
```
logging:
  min_level: __PRINT_LEVEL__
  writers:
    - type: stdout
      format: pretty-colored
    - type: file
      format: json
      filename: /var/log/__APP__/__APP__.log
      max_size: 100
      max_backups: 10
      compress: true
```

So I already figured out and I solved it using the following expression: `yq -i '.logging.writers[1].filename = "/var/log/__APP__/__APP__.log"'`

Thanks a lot for your answer!
