### DISCUSSION TITLE
Append YAML to YAML as YAML not as multi-line string

### DISCUSSION THREAD

**Discussion by mnmami** [mikefarah/yq#1743] [Q&A]
I have these files:

- base.yaml
```bash
key1:
- key2:  []
```

- file1.yaml
```
key3: value3
key4: value4
```

- file2.yaml
```
key5: value5
key6: value6
```

I want to get this output:

```
key1:
- key2:
  - key3: value3
    key4: value4 
  - key5: value5
    key6: value6
```

What I tried :
```
for file in [file1.yaml, file2.yaml]; do
  content=$(cat $file)
  yq eval '.key1[].key2 += ["$content"]' -i output.yaml
```

What I got (not desired --file1.yaml and file2.yaml are appended as multi-line strings not as YAMLs):
```
key1:
- key2: 
  - |-
    key3: value3
    key4: value4 
  - |-
    key3: value3
    key4: value4
```
