### DISCUSSION TITLE
Uncomment yaml files

### DISCUSSION THREAD

**Discussion by avi-08** [mikefarah/yq#1748] [Q&A]
Is there a way to uncomment yaml files using yq? Sample use-case which I'm looking for is to take below yaml file:

```yaml
metadata:
  name: webserver
  labels:
    app: nginx
#  env: prod
#  size: medium
  annotations:
    description: |
      webservice to host data files
      use channel #app 
```

and generate the following output

```yaml
metadata:
  name: webserver
  labels:
    app: nginx
    env: prod
    size: medium
  annotations:
    description: |
      webservice to host data files
      use channel #app  
```
