### DISCUSSION TITLE
extracting nested objects

### DISCUSSION THREAD

**Discussion by bboles** [mikefarah/yq#1772] [Q&A] [answered]
Given this example YAML:
```
workflow:
  name: Rules Testing

default:
  image: $CI_REGISTRY/clp/default-build-image/ubuntu:master-84443

.shell-cmds:
  script:
    - 'echo "Running job: $CI_JOB_NAME"'
    - 'echo "Branch:      $CI_COMMIT_BRANCH"'

stages:
  - plan
  - apply

dev-esup-api-plan:
  stage: plan
  only:
    changes:
      - vpc-dev/nomad-jobs/esup-api/*
  script:
        - !reference [.shell-cmds, script]

dev-esup-api-apply:
  stage: apply
  dependencies:
    - dev-esup-api-plan
  needs:
    - dev-esup-api-plan
  only:
    refs:
      - master
    changes:
      - vpc-dev/nomad-jobs/esup-api/*
  script:
        - !reference [.shell-cmds, script]

dev-ems-api-plan:
  stage: plan
  only:
    changes:
      - vpc-dev/nomad-jobs/ems-api/*
  script:
        - !reference [.shell-cmds, script]

dev-ems-api-apply:
  stage: apply
  dependencies:
    - dev-ems-api-plan
  needs:
    - dev-ems-api-plan
  only:
    refs:
      - master
    changes:
      - vpc-dev/nomad-jobs/ems-api/*
  script:
        - !reference [.shell-cmds, script]

dev-ems-daemons-plan:
  stage: plan
  only:
    changes:
      - vpc-dev/nomad-jobs/tsup-em/*
  script:
        - !reference [.shell-cmds, script]

dev-ems-daemons-apply:
  stage: apply
  dependencies:
    - dev-ems-daemons-plan
  needs:
    - dev-ems-daemons-plan
  only:
    refs:
      - master
    changes:
      - vpc-dev/nomad-jobs/tsup-em/*
  script:
        - !reference [.shell-cmds, script]

dev-tsup-web:
  stage: apply
  resource_group: esup-dev
  only:
    refs:
      - master
    changes:
      - vpc-dev/nomad-jobs/tsup-web/*
  script:
        - !reference [.shell-cmds, script]

qa-tsup-web:
  stage: apply
  resource_group: esup-qa
  only:
    refs:
      - master
    changes:
      - vpc-qa/nomad-jobs/tsup-web/*
  script:
        - !reference [.shell-cmds, script]

prod-tsup-web:
  stage: apply
  resource_group: esup-prod
  only:
    refs:
      - master
    changes:
      - vpc-prod/nomad-jobs/tsup-web/*
  when: manual
  script:
        - !reference [.shell-cmds, script]
```
I want to be able to find any root dictionary that has an `only:` value.  For any dictionary that we find an `only:`, print out the dictionary key and the `only:` dictionary so that we get output like this:
```
dev-esup-api-plan:
  only:
    changes:
      - vpc-dev/nomad-jobs/esup-api/*

dev-esup-api-apply:
  only:
    refs:
      - master
    changes:
      - vpc-dev/nomad-jobs/esup-api/*

dev-ems-api-plan:
  only:
    changes:
      - vpc-dev/nomad-jobs/ems-api/*

dev-ems-api-apply:
  only:
    refs:
      - master
    changes:
      - vpc-dev/nomad-jobs/ems-api/*

dev-ems-daemons-plan:
  only:
    changes:
      - vpc-dev/nomad-jobs/tsup-em/*

dev-ems-daemons-apply:
  only:
    refs:
      - master
    changes:
      - vpc-dev/nomad-jobs/tsup-em/*

dev-tsup-web:
  only:
    refs:
      - master
    changes:
      - vpc-dev/nomad-jobs/tsup-web/*

qa-tsup-web:
  only:
    refs:
      - master
    changes:
      - vpc-qa/nomad-jobs/tsup-web/*

prod-tsup-web:
  only:
    refs:
      - master
    changes:
      - vpc-prod/nomad-jobs/tsup-web/*
```
I can get part of the way there with this:
```
yq '.[] | select(has("only")) | .only' .gitlab-ci.yml
```

**Comment by bboles** [comment, marked as answer]
After reading the docs more and some hacking around I came up with this:
```
yq 'select(di == 0) * . + select(.) | .[] | select(has("only")) | { (key): (pick(["only"])) }' .gitlab-ci.only.yml
```
Output:
```
dev-esup-api-plan:
  only:
    changes:
      - vpc-dev/nomad-jobs/esup-api/*
dev-esup-api-apply:
  only:
    refs:
      - master
    changes:
      - vpc-dev/nomad-jobs/esup-api/*
dev-ems-api-plan:
  only:
    changes:
      - vpc-dev/nomad-jobs/ems-api/*
dev-ems-api-apply:
  only:
    refs:
      - master
    changes:
      - vpc-dev/nomad-jobs/ems-api/*
dev-ems-daemons-plan:
  only:
    changes:
      - vpc-dev/nomad-jobs/tsup-em/*
...
```
This gets me the data that I want!  One small nit, I would like to figure out how to get `yq` to add a newline between each root-level dictionary, like this:
```
dev-esup-api-plan:
  only:
    changes:
      - vpc-dev/nomad-jobs/esup-api/*

dev-esup-api-apply:
  only:
    refs:
      - master
    changes:
      - vpc-dev/nomad-jobs/esup-api/*

dev-ems-api-plan:
  only:
    changes:
      - vpc-dev/nomad-jobs/ems-api/*

dev-ems-api-apply:
  only:
    refs:
      - master
    changes:
      - vpc-dev/nomad-jobs/ems-api/*

dev-ems-daemons-plan:
  only:
    changes:
      - vpc-dev/nomad-jobs/tsup-em/*
...
```
