### DISCUSSION TITLE
Need help for get array keys to process after inside a bash loop

### DISCUSSION THREAD

**Discussion by cesarjorgemartinez** [mikefarah/yq#1779] [General]
Hi,

I have a yaml as follows:
```
data:
  item1: text1
  item2: text2
...
```

I need to get the key names, then:
```
yq eval '.data | keys' prueba2.yml 
- item1
- item2
```
But I need only the names, not the "- " part. Howto print as simple?:
```
item1
item2
```

I have yq version 4.16.2

Regards
