### DISCUSSION TITLE
split into multiple multidocs files

### DISCUSSION THREAD

**Discussion by benjamin-bergia** [mikefarah/yq#1799] [Q&A]
Hello,

I am trying to split documents coming from stdin into multiple files based on a specific field.
Something like
```bash
doSomething| yq -s '(.test // "default")`
```
and I do get one file for each `test` field value. Unfortunately, I have multiple documents with the same  value and I would like them to endup into the same file.

for example this:
```yaml
---
name: first
test: a
---
name: second
test: b
---
name: third
test: b
```
Should result in two files:
a.yml
```yaml
---
name: first
test: a
```
b.yml
```yaml
---
name: second
test: b
---
name: third
test: b
```

I have spent quite some time on this and I didn't really fine anything that could help. Could somebody give me a hint?

**Comment by mikefarah** [comment]
I can't think of a way to do it in a single `yq` expression - but you could do it like this:

```
cat file.yaml | yq ea '[.] | group_by(.test) | .[] | split_doc' -s '.[0].test // "default"'
```

This will read all the documents from the stream, group it by '.test' and then write out the documents to separate files. Each file is an array of results though, not separate yaml documents. For instance, b.yml:

```yaml
---
- name: second
  test: b
- name: third
  test: b
```

Now you need to iterate over all those files (e.g. bash/find) and run this yq command to update each file from an array to a bunch of documents:

```
yq -i '.[] | split_doc' b.yml
```

b.yml now looks like:

```yaml
name: second
test: b
---
name: third
test: b
```

For example, you can do this using find:

```
find *.yml -exec yq '.[] | split_doc' -i {} \;
```
