### DISCUSSION TITLE
Cannot run `yq` command; `unknown command "my-file.xml" for "yq"`

### DISCUSSION THREAD

**Discussion by ero-qt** [mikefarah/yq#1804] [Q&A] [answered]
I'm running `yq` in a GitHub action to format an XML file.  
I install it like this:
```yml
- name: Install yq
  run: |
    sudo add-apt-repository ppa:rmescandon/yq
    sudo apt update
    sudo apt install yq -y
```
And run it like this:
```yml
- name: Format .xml file with yq
  run: |
    yq -i -I 4 -ox '.' my-file.xml
```
But the GitHub action fails with the error in the title.
