### DISCUSSION TITLE
Unable to format JSON into custom format (with strange errors)

### DISCUSSION THREAD

**Discussion by ero-qt** [mikefarah/yq#1806] [Q&A] [answered]
Hi,

I'm running `yq` in a GitHub action. I have tried the `cmd`s below and received the respective errors.

`Error: bad file '-': yaml: did not find expected ',' or '}'`
```yml
steps:
  - uses: mikefarah/yq@v4.35.2
    with:
      cmd: echo ${{ inputs.releaseNotes }} | yq 'to_entries | map(["## " + .key] + (.value | map("- " + .))) | flatten | join("\n")'
```

---

`Error: bad file '-': invalid character 't'`
```yml
steps:
  - uses: mikefarah/yq@v4.35.2
    with:
      cmd: echo ${{ inputs.releaseNotes }} | yq -pj 'to_entries | map(["## " + .key] + (.value | map("- " + .))) | flatten | join("\n")'
```

---

The input is `{"title":["content1","content2"]}`. The expected result is
```md
## title
- content1
- content2
```
