### DISCUSSION TITLE
Append object to array and quote field value

### DISCUSSION THREAD

**Discussion by boekhold** [mikefarah/yq#1816] [Q&A]
Hi,

I'm trying to 'patch' a large Helm manifest using the Helm postrenderer feature calling out to a shell script that runs YQ on its STDIN. One of the "patches" I need to do is to append an entry to the "env" of a container inside a deployment. The *value* of one of the fields in that object needs to be *quoted*, either single-quoted or double-quoted.

I have figured out how to append the additional entry to the array, but I can't figure out how to do the quoting.

I've reduced the scenario to the following test case:

*helm manifest file 'manifest.yaml':*
```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app1_config
  labels:
    app: app1
data:
    app1.properties: |
        app1.optionA=valueA
        app1.hardcoded.option=hardcodedvalue
        app1.optionB=valueB
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  labels:
    app: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: my-java-app2:1.0.0
        env:
        - name: ENVVAR1
          value: value1
        - name: ENVVAR2
          value: value2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app3_config
  labels:
    app: app3
data:
    app3.properties: |
        app3.optionA=valueA
        app3.hardcoded.option=hardcodedvalue
        app3.optionB=valueB
```

*YQ expressions file 'patch.yq':*
```
select(.kind == "ConfigMap" and .metadata.name == "app1_config")
    .data."app1.properties" |=
    sub("(app1.hardcoded.option)=hardcodedvalue", "$1=myvalue")
|
select(.kind == "Deployment" and .metadata.name == "app2")
    .spec.template.spec.containers[0] |=
    .env += [{"name": "ENVVAR3", "value": "http://myhost/path"}]
|
select(.kind == "ConfigMap" and .metadata.name == "app3_config")
    .data."app3.properties" |=
    sub("(app3.hardcoded.option)=hardcodedvalue", "$1=myvalue")
```
The specific expression that I'm having trouble with is the one in the middle, related to "app2".

Executing this with:

`cat manifest.yaml | yq --from-file patch.yq`

This correctly adds the `ENVVAR3` entry to the Deployment, but the value is unquoted. I've been experimenting with the `style="single"` (and double) expression, but have been unable to figure out how to quote /just this one value/.

Any suggestions on how to implement this requirement?
