### DISCUSSION TITLE
I'd like to output a yaml structure to 1 single line

### DISCUSSION THREAD

**Discussion by maxrem** [mikefarah/yq#1862] [Q&A] [answered]
I'd like to go from 

```yaml
values:
    first:
        title: "Some title"
        order_by: date
    second:
        title: "Another title"
        order_by: rating
```

to

```yaml
values: {first: {title: "Some title", order_by: date}, second: {title: "Another title", order_by: rating}}
```

I've tried `yq -I=0 input.yaml` but that doesn't seem to do anything. Is this possible any other way?
