### DISCUSSION TITLE
How can I modify part of an URI in a YAML file using yq?

### DISCUSSION THREAD

**Discussion by pauloomarcelo** [mikefarah/yq#1870] [Q&A]
I need to update parts of a YAML file, let's say I have this YAML:

  transformations:
                template: "/pix-bacen/api/v2/pix/
              - match_rule: "^/pxxxx/xx/x
                template: "/pix-bacen/api/v2/pix/
              - match_rule: "^/pxxxx/xx/xxxx
                template: "/pix-bacssss/api/v2/pix/
              - match_rule: "^/pxxx/xxx/xx

If I want to change just the "/pix-bacen/" part to "/pix-bacen-NEW/", without changing anything else, how should I act? I've tried to use the "with" operator and the "-i" but I just could not figure it out

**Comment by shakibamoshiri** [comment]
You have to ways 

First using `-i` in-place update flag 

Second by making a tmp file and then overwrite the original one

**You yaml does not seem to well-formatted , please update your sample so can be tested** 

sample input 
```yaml
transformations:
  - template: /pix-bacen/api/v2/pix/
  - template: /pix-bacen/api/v2/pix/
  - template: /pix-bacssss/api/v2/pix/
```

Les update the first index [0]

```bash
yq '.transformations[0].template = "xyz"' file.yaml
```

sample output
```yaml
transformations:
  - template: xyz
  - template: /pix-bacen/api/v2/pix/
  - template: /pix-bacssss/api/v2/pix
 ```

after testing and seeing the output was correct then you can use `-i` flag or make a new file then swap them
