### DISCUSSION TITLE
Convert object array to string array with comments

### DISCUSSION THREAD

**Discussion by alinjie** [mikefarah/yq#1902] [Q&A] [answered]
Hello - yq noob here.

Say I have this input:
```yaml
- id: 123
  name: "abc"
- id: 456
  name: "def"
```
And I want to produce an output array where each line consists of the name as the value and the id as a comment after the value, like so:

```yaml
- abc # 123
- def # 456
```

How would I achieve this with yq?
