### DISCUSSION TITLE
Unexpected content added to yaml file

### DISCUSSION THREAD

**Discussion by dmitchsplunk** [mikefarah/yq#1907] [Q&A] [answered]
I'm trying to update the [opentelemetry-demo.yaml file](https://github.com/open-telemetry/opentelemetry-demo/blob/main/kubernetes/opentelemetry-demo.yaml) with yq, which includes multiple documents.  Specifically, I'd like to add the following environment variable to each container: 

```
- name: NODE_IP
  valueFrom:
    fieldRef:
      fieldPath: status.hostIP
```

I tried using the following command for this: 

```
    yq eval -i '(.spec.template.spec.containers[].env) += {
      "name": "NODE_IP",
      "valueFrom": {
        "fieldRef": {
          "fieldPath": "status.hostIP"
        }
      }
    }
    ' opentelemetry-demo.yaml
```

That works fine for documents in the file that include `.spec.template.spec.containers[].env`.  For example: 

```
spec:
  replicas: 1
  selector:
    matchLabels:
      opentelemetry.io/name: opentelemetry-demo-paymentservice
  template:
    metadata:
      labels:
        opentelemetry.io/name: opentelemetry-demo-paymentservice
        app.kubernetes.io/instance: opentelemetry-demo
        app.kubernetes.io/component: paymentservice
        app.kubernetes.io/name: opentelemetry-demo-paymentservice
    spec:
      serviceAccountName: opentelemetry-demo
      containers:
        - name: paymentservice
          image: 'ghcr.io/open-telemetry/demo:1.6.0-paymentservice'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: service
          env:
            - name: OTEL_SERVICE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels['app.kubernetes.io/component']
            - name: OTEL_COLLECTOR_NAME
              value: 'opentelemetry-demo-otelcol'
            - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
              value: cumulative
            - name: PAYMENT_SERVICE_PORT
              value: "8080"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://$(OTEL_COLLECTOR_NAME):4317
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.name=$(OTEL_SERVICE_NAME),service.namespace=opentelemetry-demo
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
```

But it's also adding `.spec.template.spec.containers[]` to documents that didn't have it before.  For example: 

```
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/version: "10.1.5"
  name: opentelemetry-demo-grafana
  namespace: otel-demo
spec:
  template:
    spec:
      containers: []
```
How do I ensure that the new environment variable is **only** added to documents that already include `.spec.template.spec.containers[].env`?
