### DISCUSSION TITLE
invalid input text "\\\"testing\\\")"

### DISCUSSION THREAD

**Discussion by nkrishnakishor** [mikefarah/yq#1912] [General]
Hi 
I'm trying to fetch keys which match a particular value on Windows PowerShell but seeing `invalid input text` error.

Below is the data
```
List1:
  - List2:
      - team: dba
        CloudProvider: aws
        Comment: testing
      - team: it
        CloudProvider: aws
        Comment: staging
      - team: qa
        CloudProvider: azure
        Comment: testing
      - team: qa
        CloudProvider: azure
        Comment: testing
```
query I tried are `yq ".List1[].List2[] | select(.Comment == \""testing\"")" file.yaml` and `yq '.List1[].List2[] | select(.Comment == \"testing\")' file.yaml` both resulted in same error ` Error: 1:39: invalid input text "\\\"testing\\\")"`.

I'm using
```
yq --version
yq (https://github.com/mikefarah/yq/) version v4.40.5

PowerShell version
PSVersion                      7.4.0
PSEdition                      Core
```
