### DISCUSSION TITLE
Why `eval(pathexp)` prints the input twice?

### DISCUSSION THREAD

**Discussion by lucabalsanelli** [mikefarah/yq#1920] [Q&A]
I was trying to understand [Merge arrays of objects together, matching on a key](https://mikefarah.gitbook.io/yq/operators/multiply-merge#merge-arrays-of-objects-together-matching-on-a-key) from the manual and I noticed something strange to me.

We are given `sample.yml` and `another.yml`:

    myArray:
      - a: apple
        b: appleB
    something: else

    newArray:
      - a: banana
        c: bananaC

If I do

```
originalPath="." \
yq eval-all 'eval(strenv(originalPath))' \
  sample.yml another.yml
```
I get

```
myArray:
  - a: apple
    b: appleB
something: else
---
newArray:
  - a: banana
    c: bananaC
myArray:
  - a: apple
    b: appleB
something: else
---
newArray:
  - a: banana
    c: bananaC
```

that is the output is duplicated. On the other hand, if I do

```
yq eval-all '.' sample.yml another.yml
```
I get

```
myArray:
  - a: apple
    b: appleB
something: else
---
newArray:
  - a: banana
    c: bananaC
```
that is I get just the expected objects. Why is that the case? Am I missing something?

Thanks,
Luca
