### DISCUSSION TITLE
How to add multiple documents into an array

### DISCUSSION THREAD

**Discussion by a1994sc** [mikefarah/yq#1923] [Q&A]
I am trying to identify all the images for a given helm release, and trying to put them into a list format. Like below:

```yaml
- name: cert-controller
  image: "ghcr.io/external-secrets/external-secrets:v0.9.11"
- name: external-secrets
  image: "ghcr.io/external-secrets/external-secrets:v0.9.11"
- name: webhook
  image: "ghcr.io/external-secrets/external-secrets:v0.9.11"
```

However the closest I have gotten with the following command is

```shell
helm template external-secrets external-secrets/external-secrets | yq 'select(.kind=="Deployment") | .spec.template.spec.containers[] | {"name": .name, "image": .image}'
```

```yaml
name: cert-controller
image: "ghcr.io/external-secrets/external-secrets:v0.9.11"
name: external-secrets
image: "ghcr.io/external-secrets/external-secrets:v0.9.11"
name: webhook
image: "ghcr.io/external-secrets/external-secrets:v0.9.11"
```

I think that if I could use add all the docs to an array I can use `map(select( ... ))` to have each of the elements be part of the array.... However if there is a better way to do what I want I would all ears.

### Steps for reproducing
1. Install helm
    * [link](https://helm.sh/docs/intro/install/)
2. 
    ```shell
    helm repo add external-secrets https://charts.external-secrets.io
    ```
3. 
    ```shell
    helm template external-secrets external-secrets/external-secrets | yq 'select(.kind=="Deployment") | .spec.template.spec.containers[] | {"name": .name, "image": .image}'
    ```
