### DISCUSSION TITLE
Avoid getting |- in the output when appending to an existing array.

### DISCUSSION THREAD

**Discussion by larssb** [mikefarah/yq#1928] [Q&A]
I have this YAML Array:

```yaml
vmrules:
  - test-spas-worker-23:
      nets:
        - name: test-spas
          ip: 192.168.88.25
          public: false
      cmds:
        - bash /root/worker.sh --provider azure
        - bash /root/installEtcdctl
      files:
        - path: /root/worker.sh
          currentdir: True
          origin: ~/repo/kubernetes/deploy/bootstrapping/worker.sh
        - path: /var/lib/rancher/audit/audit-policy.yaml
          currentdir: True
          origin: ~/repo/kubernetes/deploy/cluster-configuration/audit-logging/audit-policy.yaml
        - path: /root/installEtcdctl
          currentdir: True
          origin: ~/repo/src/bash/installEtcdctl
        - path: /etc/logrotate.d/rsyslog
          currentdir: True
          origin: ~/repo/kubernetes/deploy/bootstrapping/rsyslog
      tags:
        - ssh-enabled-server
        - test-spas-node
```
I'm trying to add this yaml block scalar to the `vmrules[]` Array.

```yaml
 test-spas-worker-35:
    nets:
      - name: test-spas
        ip: 192.168.88.27
        public: false
    cmds:
      - bash /root/worker.sh --provider azure
      - bash /root/installEtcdctl
    files:
      - path: /root/worker.sh
        currentdir: True
        origin: ~/repo/kubernetes/deploy/bootstrapping/worker.sh
      - path: /var/lib/rancher/audit/audit-policy.yaml
        currentdir: True
        origin: ~/repo/kubernetes/deploy/cluster-configuration/audit-logging/audit-policy.yaml
      - path: /root/installEtcdctl
        currentdir: True
        origin: ~/repo/src/bash/installEtcdctl
      - path: /etc/logrotate.d/rsyslog
        currentdir: True
        origin: ~/repo/kubernetes/deploy/bootstrapping/rsyslog
    tags:
      - ssh-enabled-server
      - test-spas-node
```

However, when I do so with: `yq e --inplace '.vmrules += "'"$testSpasWorker35Yaml"'"' ../test-spas.yml` this is the result:

```yaml
- |- 
  test-spas-worker-35:
      nets:
        - name: test-spas
          ip: 192.168.88.27
          public: false
      cmds:
        - bash /root/worker.sh --provider azure
        - bash /root/installEtcdctl
      files:
        - path: /root/worker.sh
          currentdir: True
          origin: ~/repo/kubernetes/deploy/bootstrapping/worker.sh
        - path: /var/lib/rancher/audit/audit-policy.yaml
          currentdir: True
          origin: ~/repo/kubernetes/deploy/cluster-configuration/audit-logging/audit-policy.yaml
        - path: /root/installEtcdctl
          currentdir: True
          origin: ~/repo/src/bash/installEtcdctl
        - path: /etc/logrotate.d/rsyslog
          currentdir: True
          origin: ~/repo/kubernetes/deploy/bootstrapping/rsyslog
      tags:
        - ssh-enabled-server
        - test-spas-node
```

---

How can I avoid the `|-` in the output. When `|-` is in the output further yq queries no longer act the same, as on entries the `vmrules` array that **DO NOT** have `|-`. E.g. `yq '.vmrules[]."test-test-worker-35"` is not working. I need this and other of yq type queries to work as they do when the block scalar is not in the output.

I've tried using the `... style = ""` option. I've further tried:

* I've been through the different `yq` operators. But, haven't found one of use in this case ( as far as I can see )
* Tried eval()
* Tried enclosing 
* Searched duckduckgo, google and stackoverflow. This GitHub repo/issue and discussions
* Alternatively tried: `yq e --inplace '.vmrules |= . + ["'"$testSpasWorker35Yaml"'"']' ../test-spas.yml`

---

Further, I've read:

- [Append to existing array](https://mikefarah.gitbook.io/yq/operators/add#append-to-existing-array)
- [How to update a YAML file with scalar (|-) YAML embedded ](https://github.com/mikefarah/yq/discussions/1345)
- [block scalar yq GitHub repo search](https://github.com/search?q=repo%3Amikefarah%2Fyq+block+scalar&type=issues)

---

Please help here. Much appreciated.

Thank you very much.
