### DISCUSSION TITLE
Merge only new fields without recursive merge

### DISCUSSION THREAD

**Discussion by danicc097** [mikefarah/yq#1934] [Q&A] [answered]
version v4.34.2

#file1.yaml
```yaml
paths:
  /something:
    bla: 1
components:
  schemas:
    Pet: #file1
      this-should-not-appear: 123123
    NotGenerated: #file1
      type: string

```

#generated.yaml
```yaml
components:
  schemas:
    Pet:  #gen
      only-this-field-should-appear: 1
    SomethingElse: #gen
      x-is-generated: true
      type: object
      properties:
        id:
          type: integer

```
executing either:
```bash
yq eval-all "(
        select(fi == 0).components.schemas
        ) as \$schemas
        | (
          select(fi == 1).components.schemas
        ) as \$generated_schemas
        | select(fi == 0)
        | .components.schemas = \$generated_schemas *n \$schemas
        " file1.yaml generated.yaml
#or
yq eval-all "(
        select(fi == 0).components
        ) as \$components
        | (
          select(fi == 1).components
        ) as \$generated_components
        | select(fi == 0)
        | .components = \$generated_components *n \$components
        " file1.yaml generated.yaml
```

outputs the following:

```yaml
paths:
  /something:
    bla: 1
components:
  schemas:
    Pet: #gen
      only-this-field-should-appear: 1
      this-should-not-appear: 123123
    SomethingElse: #gen
      x-is-generated: true
      type: object
      properties:
        id:
          type: integer
    NotGenerated:
      type: string
```

is there a way to prevent merging recursively? i.e. Pet should only have the field `only-this-field-should-appear: 1`

**Comment by mikefarah** [comment, marked as answer]
You can use "+" as a shallow merge:


```
yq 'load("examples/data1.yaml") + load("examples/data2.yaml")' -n
```

```yaml
paths:
  /something:
    bla: 1
components:
  schemas:
    Pet: #gen
      only-this-field-should-appear: 1
    SomethingElse: #gen
      x-is-generated: true
      type: object
      properties:
        id:
          type: integer
```
