### DISCUSSION TITLE
help retrieving multiple yaml values

### DISCUSSION THREAD

**Discussion by lordigon** [mikefarah/yq#1952] [Q&A]
Hi all,
this is a test yaml I'm using

```yaml
foo:
  imageTag: 1.0.0-20240219020324
bar:
  comp:
    imageTag: 1.0.23
  artifact:
    imageTag: 1.0.23
  test:
    imageTag: 1.0.16
```

and i would like to know how can I retrieve the list of all imageTag values. Something like

```bash
foo.imageTag 1.0.0-20240219020324
bar.comp.imageTag 1.0.23
bar.artifact.imageTag 1.0.23
bar.test.imageTag 1.0.16
```
