### DISCUSSION TITLE
How to update the exiting key value element in the kubernetes yaml file. If key doesn't exist, add the pair to the array.

### DISCUSSION THREAD

**Discussion by its-raj21** [mikefarah/yq#1954] [Q&A]
Hi Team,

Spend lot of time, but could fine a solution yet, so requesting for community help.

Basically I like to create a new k8s job based on a existing job in k8s but like to modify or add new key value element to the environment variables array.

Input environment variables:
country=India
destination=London

Yaml template of the existing job
```
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    cronjob.kubernetes.io/instantiate: manual
  name: testjob
  namespace: test-cronjobs
  ownerReferences:
  - apiVersion: batch/v1
    kind: CronJob
    name: service-a
spec:
  backoffLimit: 10
  template:
      labels:
        app: service-a
        run: service-a
    spec:
      containers:
      - env:
        - name: country
          value: Belgium
        - name: CRON
          value: 30 * * * *
        - name: MY_ENV
          value: dev
        envFrom:
        - secretRef:
            name: service-a-secret
        image: AwesomeImage
        imagePullPolicy: IfNotPresent
        name: service-a
   ```    
After the update using yq, I expect to have the following output, especially the environment variables changed if the key exist, or appended if the key doesn't exist.

```
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    cronjob.kubernetes.io/instantiate: manual
  name: testjob
  namespace: test-cronjobs
  ownerReferences:
  - apiVersion: batch/v1
    kind: CronJob
    name: service-a
spec:
  backoffLimit: 10
  template:
      labels:
        app: service-a
        run: service-a
    spec:
      containers:
      - env:
        - name: country
          value: India  ## env modified
        - name: CRON
          value: 30 * * * *
        - name: MY_ENV
          value: dev
        - name: destination  ## env added
          value: London 
        envFrom:
        - secretRef:
            name: service-a-secret
        image: AwesomeImage
        imagePullPolicy: IfNotPresent
        name: service-a
```        

Is it possible to achieve this using yq. please assist. 

Regards,
Raj
