### DISCUSSION TITLE
Changing value of a json object in a yaml file

### DISCUSSION THREAD

**Discussion by nicodmt** [mikefarah/yq#2002] [Q&A]
Hi,

I have a config.yaml file with a json object within that I need to change a value during YQ task run in pipeline.
I want the key "currentVersion" to get it's value updated but for some reason I just can't access the "config.json" object and the task creates a new field at the end (see config.yaml example below, the last three rows).

In my pipeline.yaml I left some of the expressions I've tried to work with.
ChatGPT was unfortunately not of any help and the documentation on here didn't help.

Here follows some simplified code samples.

config.yaml:

```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: ...
  name: app-config
data:
  config.json: |-
    {
      ... ,
      "currentVersion": "value",
     ...
    }
  config:
    json:
      currentVersion: test15
```

pipeline.yaml:

```
    - name: update-version-tag
      params:
        - name: files
          value:
          - ./kustomize/overlays/$(params.project)/app-config.yaml
        - name: expression
          value: '.data."config.json".currentVersion = \"$(params.tag)"\'
          #value: '.data."config.json" |= . + {"currentVersion": "$(params.tag)"}'
          #value: '.data."config.json" |= (. | split("\n")[:-1] + ["  \"currentVersion\": \"$(params.tag)\",", "  }"] | join("\n"))'
          #value: '.data."config.json" |= (input | .currentVersion = "$(params.tag)"; .)'
          #value: '.data."config.json" |= sub("(.*\"currentVersion\": \")[^\"]+(\".*)"; "\\1$(params.tag)\\2")'
          #value: '.data."config.json" |= sub("(.*\"currentVersion\": \")[^\"]+(\".*)"; "\\1" + "$(params.tag)" + "\\2")'
          #value: 'select(.data == "want-to-update").foo |= ( fromjson | .a = "updated a" | tojson )' sample.yaml 
          #value: 'select (.data."config.json") |= ( fromjson | .currentVersion = $(params.tag) | tojson)'
      taskRef:
        name: yq
        kind: Task
      workspaces:
        - name: ...
```

and finally the YQ task itself:

```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: "yq"
  labels:
    app.kubernetes.io/version: "0.3"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: "Developer Tools"
    tekton.dev/tags: "yq"
    tekton.dev/displayName: "YQ replace"
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    This task can be used to replace fields in YAML files. For example for altering helm charts on GitOps repos.
  workspaces:
    - name: source
      description: A workspace that contains the file which needs to be altered.
  params:
    - name: files
      type: array
      description: A list of files to execute the expression on. Needs to be relative to the source workspace.
    - name: expression
      type: string
      description: The yq expression to apply. Can be used to replace yaml fields.
    - name: image
      type: string
      description: The yq image to use.
      default: docker.io/mikefarah/yq:4.16.2@some_sha_numbers
  steps:
    - name: replace-in-yaml
      image: $(params.image)
      workingDir: $(workspaces.source.path)
      args: ["$(params.files[*])"]
      script: |
        set -e
        for var in "$@"
        do
            /usr/bin/yq eval -i "$(params.expression)" "$var"
        done
        echo "$(params.expression)"
      securityContext:
        runAsUser: 0
```
