### DISCUSSION TITLE
Powershell error: 1:41 invalid input text

### DISCUSSION THREAD

**Discussion by JDubbTX** [mikefarah/yq#2007] [Q&A]
I am using YQ to parse a value out of a YAML file that looks like this:

```YAML
packages:
  - source: https://some.url.org/path/to/package/file/package-v1.1.1.tar.gz
    target: package-client
  - source: https://some.url.org/path/to/other/package/file/other-package-v1.1.1.tar.gz
    target: other-package-client
```

The YAML file contents are stored in a variable named $yamlData in my Powershell script

My powershell command is like this:

>  ``$packageSource = (Write-Output $yamlData | yq ".packages[] | select(.target == `"other-package-client`").source")``

Expected output: "https://some.url.org/path/to/other/package/file/other-package-v1.1.1.tar.gz"

- In my windows dev environment, with yq version v4.33.3 it works as expected
- In my windows WSL / Ubuntu environment, with yq version v4.35.1 it works as expected
- In my windows WSL/Ubuntu environment, with yq version updated to 4.42.1 it works as expected
- In my docker mcr.microsoft.com/powershell:lts-debian-11 based dev environment, with yq version v4.40.7, or with v4.42.1 it returns `Error: 1:41: invalid input text "other-package-client])..."`
- Same error happens in my pipeline docker image redhat ubi9 based environment with yq version v4.43.1, which is where I need it to work.

How can I modify the command to make it work in the debian/redhat environments with later yq versions?

Edit:  Was figuring out how to delimit backticks in the command

**Comment by JDubbTX** [comment]
Simplifying this, with testfile.txt:

```YAML
packages:
  - source: https://some.url.org/path/to/package/file/package-v1.1.1.tar.gz
    target: package-client
  - source: https://some.url.org/path/to/other/package/file/other-package-v1.1.1.tar.gz
    target: other-package-client
```
`yq '.packages[] | select(. == https*)' testfile.txt` gives the same error

![image](https://github.com/mikefarah/yq/assets/56802156/60592171-9a51-4d9d-b6e6-d0dd866f1754)
