### DISCUSSION TITLE
Filter based on multiple conditions on a nested array of objects but extract upper level element for csv output

### DISCUSSION THREAD

**Discussion by mik047** [mikefarah/yq#2013] [General]
I have set of yaml files, each containing a structure and content like following.

(file-1.yaml)
```yaml
cname: file-1
cid: 1
func:
    apis:
    - aid: id1234
      aname: api1234
      required: true
    - aid: id4567
      aname: api4567
      required: false
   ...
```

(file-2.yaml)
```yaml
cname: file-2
cid: 2
func:
    apis:
    - aid: id1234
      aname: api1234
      required: true
    - aid: id4567
      aname: api4567
      required: false
  ...
```

(file-n.yaml)
```yaml
cname: file-n
cid: n
func:
    apis:
    - aid: id1234
      aname: api1234
      required: false
    - aid: id4567
      aname: api4567
      required: true
  ...
```

I wish to crease a csv of entries like this: for a given aid (say `id1234`), filter across files and fetch those which match this `aid` and `required=true`

cid,cname
```csv
1,file-1
2,file-2
```

I tried following, but it gives a wrong result.

```bash
yq e '. | select(.func.apis.[].aid == “id1234" and .func.apis.[].required == "true") | [.cid,.cname] | @csv' *.yaml | grep -v '^$' | grep -v ‘-‘ | sort
```
It gives output like following:

cid,cname
```csv
1,file-1
2,file-2
n,file-n
```
Seems, the filter is trying to do `and` operation _across_ the entries rather than _within_ the entries. 

If I try following, the filtering condition works as expected, but I am unable to fetch `cid` and `cname` with this query.

```bash
yq e ‘.func.apis.[] | select(.aid == “id1234" and .required == "true") | [.aid,.aname] | @csv' *.yaml | grep -v '^$' | grep -v '-' | sort
```

Can someone help?
