### DISCUSSION TITLE
how to disable quote when using --input-format props

### DISCUSSION THREAD

**Discussion by shakibamoshiri** [mikefarah/yq#2023] [Q&A] [answered]
When the input format is **props** e.g.

```bash
echo a.b.c 10 | yq --input-format props
```
the output value is string, while number is expected 

```yaml
a:
  b:
    c: "10"
```

expected outupt

```yaml
a:
  b:
    c: 10
```

Also adding `--unwrapScalar` has no effect 
Any solution ?
