### DISCUSSION TITLE
substitute with select and delete

### DISCUSSION THREAD

**Discussion by giammbo** [mikefarah/yq#2031] [Q&A]
Hello,

im try to modify a yaml with yq, but unfortunately i'm not able to find a solution.
This is the starting yaml:

```
env:
  a:b
steps:
  - group: build
    key: build
    steps:
      - label: docker Build
         key: docker-build
  - group: push
    key: push
    depends_on: build
    steps:
      - label: docker Build
         key: docker-build
```

i need to delete the `group: build` and modify the `depend_on` on the group push.

im trying with this:

```
yq -oy "del(.steps.[] | select(.key == \"build\")),  select(key == \"push\").depends_on == \"test\" " "${temporay_template}"
```
