### DISCUSSION TITLE
New fields added to `.value` in `to_entries[] | (.value changes) | from_entries` are lost if I combine the result with another array

### DISCUSSION THREAD

**Discussion by Frederick888** [mikefarah/yq#2052] [Q&A] [answered]
I'm trying to add matrices into jobs in a GitHub Actions manifest, but only to those which have `actions/setup-go@...` steps. (I'm using `yq` v4.44.1 from Homebrew.)

The input looks like:
```yml
name: CI
on:
  pull_request:
jobs:
  no_setup_go:
    runs-on: [ubuntu-stable]
    steps:
      - run: |
          exit 0
  has_setup_go:
    runs-on: [ubuntu-stable]
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20.1"
      - run: |
          exit 0
  also_has_setup_go:
    runs-on: [ubuntu-stable]
    strategy:
      fail-fast: false
      matrix:
        go_version:
          - "1.19"
          - "1.20"
          - "1.21"
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go_version }}
      - run: |
          exit 0
```

Since
```sh
GO_VERSIONS='["1.20.x", "1.21.x", "1.22.x"]'

yq --exit-status eval '
    .jobs
        | to_entries[]
        | select(.value.steps[] | select(.uses | contains("/setup-go@")) | . += { "with": { "go-version": "${{ matrix.go_version }}" } })
        | .value.strategy.fail-fast = false | .value.strategy.matrix.go_version = '"$GO_VERSIONS"'
    ' .github/workflows/ci.yaml
```
...gave me
```yml
key: has_setup_go
value:
  runs-on: [ubuntu-stable]
  steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go_version }}
    - run: |
        exit 0
  strategy:
    fail-fast: false
    matrix:
      go_version:
        - 1.20.x
        - 1.21.x
        - 1.22.x
key: also_has_setup_go
value:
  runs-on: [ubuntu-stable]
  strategy:
    fail-fast: false
    matrix:
      go_version:
        - 1.20.x
        - 1.21.x
        - 1.22.x
  steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go_version }}
    - run: |
        exit 0
```

I thought it'd be a simple matter of merging back the other jobs:
```sh
GO_VERSIONS='["1.20.x", "1.21.x", "1.22.x"]'

yq --exit-status eval '
    .jobs = (
        [
            .jobs
                | to_entries[]
                | select(.value.steps[] | select(.uses | contains("/setup-go@")) | . += { "with": { "go-version": "${{ matrix.go_version }}" } })
                | .value.strategy.fail-fast = false | .value.strategy.matrix.go_version = '"$GO_VERSIONS"'
        ] + [
            .jobs
                | to_entries[]
                | select([.value.steps[] | select(.uses | contains("/setup-go@"))] | length == 0)
        ]
        | from_entries
    )' .github/workflows/ci.yaml
```
However this actually gave me:
```yml
name: CI
on:
  pull_request:
jobs:
  has_setup_go:
    runs-on: [ubuntu-stable]
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go_version }}
      - run: |
          exit 0
  also_has_setup_go:
    runs-on: [ubuntu-stable]
    strategy:
      fail-fast: false
      matrix:
        go_version:
          - 1.20.x
          - 1.21.x
          - 1.22.x
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go_version }}
      - run: |
          exit 0
  no_setup_go:
    runs-on: [ubuntu-stable]
    steps:
      - run: |
          exit 0
```

The new `strategy` field in `has_setup_go` was somehow gone. In fact, I could replace the second array of jobs with an empty `[]` and the same thing happened.

Any idea what I did wrong? Thank you.
