### DISCUSSION TITLE
Trying to get the value of an object that is up the path from a searched-for array element value

### DISCUSSION THREAD

**Discussion by steve-nay-sage** [mikefarah/yq#2080] [General]
I've tried several variations of commands to do this, but all without success. I tried to get chatGPT to assist me, but it's so bad with yq that it's almost laughable. There is some underlying concept here that eludes me. I've tried using `contains` and `select` and `has` and piping to `path` etc. but I'm just not getting it. Help would really be appreciated!

Here is the top part of the actual file that I'm working with. In the last `pages` array there is an element with a value that contains "general-ledger.statistical-account.yaml" My script gets that value as input (or the equivalent from another element), so that's what I have to search with. What I'd like to be able to find is the value of the `group` object above that array element, which in this example is "General Ledger". I just can't put the yq pieces together in the right way to make that happen.

```
- page: index.mdx

- group: Get Started
  page: developer-portal/getting-started/index.mdx
  expanded: false
  pages:
    - label: Quick Start
      page: developer-portal/getting-started/quick-start.mdx


- group: API References
  page: openapi/index.md
  expanded: true
  pages:

    - group: Company Configuration
      page: openapi/index-company.md
      expanded: false
      selectFirstItemOnExpand: false
      pages:
        - page: openapi/co/company-config-attachment.yaml #uncertified
        - page: openapi/co/company-config-folder.yaml #uncertified
        - group: Dimensions
          expanded: false
          selectFirstItemOnExpand: false
          pages:
            - page: openapi/co/company-config-class.yaml
            - page: openapi/co/company-config-contact.yaml #uncertified
            - page: openapi/co/company-config-department.yaml
            - page: openapi/co/company-config-entity.yaml #uncertified
            - page: openapi/co/company-config-location.yaml
        - page: openapi/co/company-config-document-sequence.yaml
        - page: openapi/co/company-config-email-template.yaml #uncertified

    - group: General Ledger
      page: openapi/index-gl.md
      expanded: false
      selectFirstItemOnExpand: false
      pages:
        - page: openapi/gl/general-ledger.account.yaml
        - page: openapi/gl/general-ledger.statistical-account.yaml
        - page: openapi/gl/general-ledger-account-group.yaml #uncertified
        - page: openapi/gl/general-ledger-account-group-purpose.yaml
```
