### DISCUSSION TITLE
Help combining two maps based on map name

### DISCUSSION THREAD

**Discussion by glitchcrab** [mikefarah/yq#2084] [Q&A] [answered]
I have the following data structure, whereby each entry under `.nodePools` represents a basic VM configuration, and each VM's configuration is extended by referencing a named class under `.nodeClasses`:

```
nodePools:
  - class: default
    replicas: 2
    name: worker
  - class: default
    replicas: 2
    name: anotherworker
nodeClasses:
  default:
    memoryMiB: 16896
    diskGiB: 50
```

I have tried and failed at the following; I would like to write a command to iterate over each nodePool, look up its class and then duplicate the keys from the class into the nodePool. The aim is to end up with the following:

```
nodePools:
  - class: default
    replicas: 2
    name: worker
    memoryMiB: 16896
    diskGiB: 50
  - class: default
    replicas: 2
    name: anotherworker
    memoryMiB: 16896
    diskGiB: 50
nodeClasses:
  default:
    memoryMiB: 16896
    diskGiB: 50
```

Could anyone help me out with this please?
