### DISCUSSION TITLE
Extract nested entries from an array

### DISCUSSION THREAD

**Discussion by cmoulliard** [mikefarah/yq#2088] [Q&A]
The following "job1.yaml" file is a typical example describing for a github workflow the jobs and steps to be executed: https://docs.github.com/en/actions/using-workflows/about-workflows#create-an-example-workflow

In order to get from a yaml flow, the list of the job's names and their step's names, I'm wondering how jq could help me here

Sample:
```
name: Create Release

jobs:
  preparation:
    name: Preparation
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get stack names and USN support
        id: get-stack-names

      - name: Get Repository Name

  poll_images:
    name: Poll Images
    steps:
      - name: Find and Download Previous build image hash code of stack ${{ matrix.stacks.build_image }}
        if: ${{ matrix.stacks.create_build_image == true }}

      - name: Find and Download Previous run image hash code of stack ${{ matrix.stacks.run_image }}
```
What I expect to get (to document a project) is the following result (which could also be enriched with solme additional fields like `if: ` etc:
```
jobs:
  name: preparation
  steps:
      - name: Checkout repo
      - name: Get stack names and USN support
      - name: Get Repository Name
   ...
  name: poll_images
  steps:
      - name: Find and Download Previous build image hash code of stack ${{ matrix.stacks.build_image }}
      - name: Find and Download Previous run image hash code of stack ${{ matrix.stacks.run_image }}
    ...  
```
The following code extracts well the job name but don't include the list of the steps
```
yq '.jobs[] as $job ireduce (""; (. + " ") + $job.name)' $YAML_DIR/flow.yaml
 Preparation Poll Images
```

**Comment by mikefarah** [comment]
You can do it like this:

```
yq '.jobs |= [.[]] | .jobs[].steps[] |= pick(["name"])' data1.yaml

name: Create Release
jobs:
  - name: Preparation
    steps:
      - name: Checkout repo
      - name: Get stack names and USN support
      - name: Get Repository Name
  - name: Poll Images
    steps:
      - name: Find and Download Previous build image hash code of stack ${{ matrix.stacks.build_image }}
      - name: Find and Download Previous run image hash code of stack ${{ matrix.stacks.run_image }}

```

Explanation:
- `.jobs |= [.[]]`; Update the jobs map (w.r.t to itself); setting jobs to be an array of all the map values. This works because `.[]` on a map matches all the map values, wrapping that with`[.[]]` makes it an array of all the values.
- `.jobs[].steps[] |= pick(["name"])`; from each of the step elements, [pick](https://mikefarah.gitbook.io/yq/operators/pick) the name field
