### DISCUSSION TITLE
How to sort/reorder by the value of a map, not the key

### DISCUSSION THREAD

**Discussion by ccoVeille** [mikefarah/yq#2089] [Q&A] [answered]
I would like to order a yaml map by value

Here is the document I want to sort
https://github.com/jargonLint/jargonLint/blob/main/vale/styles/jargonLint/Technology.yml

Right now, it is sorted `sort`, and I had to copy-paste content twice, something I would like to avoid

Here is an example of what I want to sort

```yaml
---
action:
  name: replace
extends: substitution
ignorecase: true
level: warning
message: Use '%s' instead of '%s'
swap:
  (?<!\.)HTML: HTML 
  i18n: i18n
  Homebrew: Homebrew
  (?<!\.)HTMX: HTMX  
  HTTP(?!:): HTTP
```

I would like the order to be this one, so ordered by the value of the map.

```yaml
---
action:
  name: replace
extends: substitution
ignorecase: true
level: warning
message: Use '%s' instead of '%s'
swap:
  Homebrew: Homebrew
  (?<!\.)HTML: HTML  # also a file extension
  (?<!\.)HTMX: HTMX  # also a file extension
  HTTP(?!:): HTTP
  i18n: i18n
```

I tried multiple things, looked at the doc twice, looked at discussion here or stack overflow.

So here I am. Thanks
