### DISCUSSION TITLE
delete entire document from multi-document file/input

### DISCUSSION THREAD

**Discussion by travisghansen** [mikefarah/yq#2102] [Q&A] [answered]
I would like to remove an entire document (preferably by some selector, but by index would be crude enough) from the input.

```
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/component: rabbitmq-operator
    app.kubernetes.io/name: rabbitmq-system
    app.kubernetes.io/part-of: rabbitmq
  name: rabbitmq-system
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.15.0
  name: bindings.rabbitmq.com
spec:
  group: rabbitmq.com
  names:
    categories:
    - rabbitmq
    kind: Binding
    listKind: BindingList
    plural: bindings
    singular: binding
  scope: Namespaced
---
foo: bar
---
bar: baz
```

I would like to remove any document for example which contains `kind: Namespace`, or document at index 0.
