### DISCUSSION TITLE
Extracting Quoted String Values from Kustomize Literals

### DISCUSSION THREAD

**Discussion by excalq** [mikefarah/yq#2104] [Q&A]
Hello, I'm working on a GitHub action which will use `yq` to extract a value from a Kustomize K8s file, which uses key-value literals to build ConfigMaps.

The subject text:
```
...
configMapGenerator:
  - name: client
    behavior: merge
    literals:
      - VITE_ENV=demo
      - VITE_SUPPORTED_APP_IDS="1,10,3323,8888"
```

Attempted `yq`: 
```
yq '.configMapGenerator[] | select(.name == "client") | .literals[] | select(. == "VITE_SUPPORTED_APP_IDS=*") | split("=") | .[1]' k8s/demo/kustomization.yaml
````

Actual Result: `"1,10,3323,8888"`
Desired Result: `1,10,3323,8888`

This can be fixed outside of `yq` with additional piping to `tr -d '"'`, but I was wondering if there's a pattern to do so all within a `yq` command. Thanks!
