### DISCUSSION TITLE
How to reduce similar elements of array

### DISCUSSION THREAD

**Discussion by dparmar** [mikefarah/yq#2105] [Q&A] [answered]
I am struggling to figure out a way to aggregate `sample` values based on `name` key. Appreciate your help!

Input:

```yml
- name: api
  sample:
    count: 20
    rate: 2
- name: api
  sample:
    count: 30
    rate: 3
- name: data
  sample:
    count: 40
    rate: 4
- name: data
  sample:
    count: 50
    rate: 5
- name: users
  sample:
    value: 2
- name: users
  sample:
    value: 3
```

Expected output:
```yml
- name: api
  sample:
    count: 50
    rate: 5
- name: data
  sample:
    count: 90
    rate: 9
- name: users
  sample:
    value: 5
```
