### DISCUSSION TITLE
Extract one value from submapping

### DISCUSSION THREAD

**Discussion by bpj** [mikefarah/yq#2111] [Q&A]
Noob question, most likely a FAQ:

I have input like this:

``` yaml
meta:
  version: 1.234
data:
  foo:
    corporis-aliquam:
      this: similique
      that: Est
    tenetur-rerum:
      this: ipsum
      that: Aut
    repellat-officiis:
      this: sint
      that: Et
```

I want to convert it into this:

``` yaml
corporis-aliquam: similique
tenetur-rerum: ipsum
repellat-officiis: sint
```

i.e. the original keys from the `data.foo` with the values of `this` from their original values.

Seemingly simple but I can’t figure out the right expression.

The actual input obviously has other keys and values and a couple of thousand entries. It would be easy to do with a script, but I really would like to know how to do it with yq! :-)
