### DISCUSSION TITLE
Yaml to csv - how to convert map object

### DISCUSSION THREAD

**Discussion by iGabyTM** [mikefarah/yq#2134] [Q&A]
I have a yaml file that looks like this:
```yaml
- name: Object 1
  map:
    simple: Hello
    deeper:
      value: World
- name: Object 2
  map:
    simple: Hello
    deeper:
      value: World
```
And I wand the csv to look like this:
```csv
name,map.simple,map.deeper.value
Object 1,Hello,World
Object 2,Hello,World
```

Curreny when I use `yq -o=csv test.yaml` it complains about `!!map` not supported. I just want to get the full path of a key as column name and then the value at that path.
The object is quite big and I can't really put all possible keys and their path in the command.
