### DISCUSSION TITLE
how to get all "leaves"?

### DISCUSSION THREAD

**Discussion by minhtrancccp** [mikefarah/yq#2146] [Q&A]
here's my yaml file:
```yaml
a:
 - v
 - [...]
 - b:
  - w
  - [...]
 - c:
  - x
  - [...]
  - d:
   - y
   - [...]
e:
 - z
 - [...]
```

how can i get the leaves, i.e. `vwxyz` and so on?
many thanks.
