### DISCUSSION TITLE
Add a record/array element and then insert yaml file as key  of that `record`

### DISCUSSION THREAD

**Discussion by dkebler** [mikefarah/yq#2161] [Q&A]
I have a yaml array kinda like so

y1.yaml
```yaml
history:
   - id: 20240928082901
     desc: first history
     details:
        date: somedate
        cid: 45321
```

I have another file like so

y2.yaml
```yaml
date: anotherdate
cid: 96566
```

What I need to do is create a new "record" (i.e. array element)  in `y1.yaml` from a bash heredoc (below) and then add `y2.yaml` under  a new `details:` key of that new record/element saving it all back to `y1.yaml`.

```bash
<some command> << EOF 
id: $(date '+%Y%m%d%H%M%S')
desc: $DESC 
EOF
```

so result would look like this.

y1.yaml
```yaml
history:
   -  id: 20240928082901
      desc: first history
      details:
           date: somedate
           cid: 45321
    - id: 20240929112923
      desc: second history
      details:
           date: anotherdate
           cid: 96566
```

I saw a lot of hard coded examples of insert (including docs) but nothing that uses another yaml file or a string of yaml (as a heredoc).  

When using sed  I  single quote out and in anything I want bash to subs/eval in the sed  'command' so maybe something like that except yq expects json there not yaml.  

maybe kinda like this???    `yq e '<prejson>' $(yq -o=json '.' y2.yml)' <closing json> * .'  y1.yml`

https://github.com/mikefarah/yq/discussions/1688
https://stackoverflow.com/questions/61109518/how-to-insert-or-add-a-field-in-a-yaml-after-a-specific-key-in-yq
https://github.com/mikefarah/yq/discussions/821

Little Help/ Suggestions? Thx
