### DISCUSSION TITLE
Split a single file into multiple by map value field

### DISCUSSION THREAD

**Discussion by ei-man** [mikefarah/yq#2174] [Q&A] [answered]
Hello,
Having an input value like the following:
```
FirstValue:
    name: John
    group: FirstGroup
SecondValue:
    name: NotJohn
    group: SecondGroup
ThirdValue:
    name: MaybeJohn
    group: SecondGroup
```

I'd like to split it into multiple files, where the destination file would depend on the value of `<key>.group`.
Expected output:
```
# FirstGroup.yaml
FirstValue:
    name: John
    group: FirstGroup
```

```
# SecondGroup.yaml
SecondValue:
    name: NotJohn
    group: SecondGroup
ThirdValue:
    name: MaybeJohn
    group: SecondGroup
```

I've tried `yq ..\yq-input.yaml -s 'to_entries | .[] | .value.group'`, but it produces only 1 file with all the output.
```
# FirstGroup.yaml
FirstValue:
    name: John
    group: FirstGroup
SecondValue:
    name: NotJohn
    group: SecondGroup
ThirdValue:
    name: MaybeJohn
    group: SecondGroup
```

Thanks!
