### DISCUSSION TITLE
How to use string substitution (hyphen to underscore) for key inside strenv?

### DISCUSSION THREAD

**Discussion by sanzoghenzo** [mikefarah/yq#2193] [Q&A]
Hi there, first of all, many thanks for this wonderful tool!

I'm trying to handle docker swarm secrets and configs updates as [described here](https://blog.viktoradam.net/2018/02/28/swarm-secrets-made-easy/), but using Task and yq.

My docker compose file (I call it `stack.yaml`) is something like this

```yaml
services:
  # various containers
configs:
  first-config:
    file: ./configs/first.yaml
  # other configs here
secrets:
  first-secret:
    file: ./secrets/my-first-secret
  # and so on
```

To sum up: for each entry in the `configs` and `secrets` sections, I need to add the `name` attribute and set it to the `key` + the md5sum of the `.file`.

With the following I can successfully build the envvars with the md5sum of the files

```yaml
tasks:
  deploy-stack:
    desc: Deploy the stack specified in STACK_NAME envvar
    vars:
      STACK_DIR: stacks/{{.STACK_NAME}}
      COMPOSE_FILE: '{{.STACK_DIR}}/stack.yaml'
      HASHES:
        sh: "yq -o=shell '.secrets + .configs | map(key: \"$(md5sum {{.STACK_DIR}}/\" + .file + \" | cut -f 1 -d \\\" \\\")\") | flatten | .[]' {{.COMPOSE_FILE}}"
    cmds:
      - cmd: echo "{{.HASHES}}"
```

```shell
$ STACK_NAME=test task deploy-stack
first_config=<hash of ./configs/first.yaml>
first_secret=<hash of ./secrets/my-first-secret>
```

I'm stuck on the second part, which is to set the `name` attribute; since the variables from the `-o=shell` output have underscores in place of hyphens, I need to replace them in the `key`s in order to match them with `strenv`. I tried with this:

```yaml
      - cmd: "{{.HASHES}} yq 'with(.secrets[]; .name = key + strenv(key | sub(\"-\", \"_\")))' {{.COMPOSE_FILE}} | yq 'with(.configs[]; .name = key + strenv(key | sub(\"-\", \"_\")))'"
```

but I got `Error: bad expression, got close brackets without matching opening bracket`

I bet this is because the pipe operator is not allowed inside parenthesis of other operators (strenv in this case).
Is there a smarter way to solve this?
