### DISCUSSION TITLE
Expand a flat list of yaml keys to a structure

### DISCUSSION THREAD

**Discussion by chlab** [mikefarah/yq#2212] [Ideas]
I would like to be able to expand a flat list of yaml keys to a yaml structure, for example:

Input:
```
foo.bar.baz
foo.bar.boo
bar.foo
```

Output:
```
foo:
  bar:
    baz: null
bar:
  foo: null
```

My use case for this is to extract a list of values from a helm chart and then generate a dummy values file for it, e.g.:

```
grep -o '\.Values\.[^ }]*' my-template.yaml | sort | uniq | sed 's/\.Values\.//' | yq xy
```

Is this maybe even possible already? I didn't see anything that would indicate so in the docs.

**Comment by mikefarah** [comment]
If you convert it to a valid yaml list of path expressions:
```yaml
- .foo.bar.baz
- .foo.bar.boo
- .bar.foo
```

Then you can use ireduce and eval:

```bash
echo "foo.bar.baz
foo.bar.boo
bar.foo" | sed -e 's/^/- \./' | yq '.[] as $i ireduce({}; eval($i) = null)'
```

**Reply by mikefarah** [reply]
```yaml
foo:
  bar:
    baz: null
    boo: null
bar:
  foo: null
```
