### DISCUSSION TITLE
Merge two files with tag replace

### DISCUSSION THREAD

**Discussion by klinux** [mikefarah/yq#2223] [Q&A]
Hello,

I have two files, I have created a merge, but some blocks was duplicated.

**file1.yaml**
```
...
paths:
  /backoffice:
  - methods:
    - GET
    - PUT
    - POST
    apikey:
      propagateApiKey: true
    description: "Description of the ApiKey Gravitee Policy",
    enabled: true
  - methods:
    - GET
    - PUT
    - POST
    rate-limit:
      async: false
      addHeaders: false
      rate:
        periodTime: 1
        periodTimeUnit: SECONDS
        limit: 5
...
```

**file2.yaml**
```
...
paths:
  /backoffice:
  - methods:
    - GET
    - PUT
    - POST
    rate-limit:
      async: false
      addHeaders: false
      rate:
        periodTime: 1
        periodTimeUnit: SECONDS
        limit: 50
...
```
I'm using this command:
`yq eval-all '. as $item ireduce ({}; . *+ $item)' file1.yaml file2.yaml > merged.yaml`

The merge works fine, I want to merge the files, the **file1** is the base, and **file2** is the difference that I want to add.

But in the cases that I have some duplicated, the merge duplicate the result, like:

**merged.yaml**
```
...
paths:
  /backoffice:
  - methods:
    - GET
    - PUT
    - POST
    apikey:
      propagateApiKey: true
    description: "Description of the ApiKey Gravitee Policy",
    enabled: true
  - methods:
    - GET
    - PUT
    - POST
    rate-limit:
      async: false
      addHeaders: false
      rate:
        periodTime: 1
        periodTimeUnit: SECONDS
        limit: 50
  - methods:
    - GET
    - PUT
    - POST
    rate-limit:
      async: false
      addHeaders: false
      rate:
        periodTime: 1
        periodTimeUnit: SECONDS
        limit: 50
...
```
There's any way do replace the values, example, the result that I need is:
```
...
paths:
  /backoffice:
  - methods:
    - GET
    - PUT
    - POST
    apikey:
      propagateApiKey: true
    description: "Description of the ApiKey Gravitee Policy",
    enabled: true
  - methods:
    - GET
    - PUT
    - POST
    rate-limit:
      async: false
      addHeaders: false
      rate:
        periodTime: 1
        periodTimeUnit: SECONDS
        limit: 50
...
```
