### DISCUSSION TITLE
Preserve multiline strings with properties output

### DISCUSSION THREAD

**Discussion by dudicoco** [mikefarah/yq#2236] [Q&A]
I am diffing two yaml files per https://mikefarah.gitbook.io/yq/usage/tips-and-tricks#comparing-yaml-files and I would like to preserve multiline strings in the output.

Input:
```yaml
root:
  foo: bar
  configmap: |
    # comment
    one
    two
    three
```

Output:
```properties
root.foo = bar
root.configmap = # comment\none\ntwo\nthree\n
```

Desired output:
```properties
root.foo = bar
root.configmap = 
    # comment
    one
    two
    three
```
