### DISCUSSION TITLE
conditionally update from values in a second file

### DISCUSSION THREAD

**Discussion by dnlwgnd** [mikefarah/yq#2255] [Q&A] [answered]
I need to update in a yaml file parts of a value from values in a second yaml file. specifically using this representative test case:

test.yaml:
``` 
spec:
  template:
    spec:
      containers:
      - name: some-backend
        image: my.registry.com/some/some-backend@sha256:11aa
      - name: some-backend2
        image: my.registry.com/some/some-backend@sha256:11aa
      - name: some-backend3
        image: my.registry.com/some/some-other@sha256:abcd
```

trigger_payload.yaml:
```
event_type: pushImage
events:
  - full_name: some/some-backend
    image_id: 22aa
  - full_name: some/some-frontend
    image_id: 56ab
```

I need to update each image-id in test.yaml from the image_id given in trigger_payload.yaml if their image names match the full_name and leave them unchanged if they do not match.
the expected result would be
```
spec:
  template:
    spec:
      containers:
      - name: some-backend
        image: my.registry.com/some/some-backend@sha256:22aa
      - name: some-backend2
        image: my.registry.com/some/some-backend@sha256:22aa
      - name: some-backend3
        image: my.registry.com/some/some-other@sha256:abcd
```
I was hoping to find a single yq expression to do this, but alas I can quite wrap my head aroud it. I do have a solution looping over the events in trigger_payload.yaml in a bash loop which I do not like too much. Any hints greately appreciated. Thanks!

**Comment by mikefarah** [comment, marked as answer]
I made a slight change to the trigger_payload, to make it easier to update by looking up the ids given a key:

```yaml
some-backend:
  image_id: 22aa
some-frontend:
  image_id: 56ab
```

Then we can update the original given the trigger by doing:

```bash
# use ea to load up both files into memory
./yq ea '
    # file[1] is the reference/trigger yaml, lets call that $trig
     select(fi==1) as $trig | 
    # we only want to output the contents of the first file, so select that
     select(fi==0) | 
    # now lets update the container entries
     with(.spec.template.spec.containers[];
        # here we find the image id in the trigger
         $trig[.name].image_id as $newImageId | 
        # if the trigger exists, we  update the image using regex
         select($newImageId) | .image |= sub("(.*):.*", "${1}:" + $newImageId) )
' examples/data1.yaml examples/data2.yaml
```

The key bit is here `$ref[.name].image_id as $newImageId ` where it looks up the replacement image id. If you can't simplify the file like I did, then you can just do a select expression to find the right entry.
