### DISCUSSION TITLE
Recursively search for keys and apply custom sort

### DISCUSSION THREAD

**Discussion by jacobbednarz** [mikefarah/yq#2279] [Q&A] [answered]
I have the following working to give me a predefined sort order with the remainder keys at the end.

```
$ yq '.methods |= pick( (["get", "list", "create", "update", "delete"] + keys) | unique)' example_sort_2.yaml
```

Before 

```yaml
methods:
  create: post /foo
  delete: delete /foo/{id}
  foo: get /
  bar: get /foo
  get: get /foo/{id}
  list: get /foo
  update: put /foo/{id}
```

After

```yaml
methods:
  get: get /foo/{id}
  list: get /foo
  create: post /foo
  update: put /foo/{id}
  delete: delete /foo/{id}
  foo: get /
  bar: get /foo
```

However, I need to apply it recursively and I don't always know what level the `.methods` will be at. Any guidance on the best approach to traversing to find `.methods` and modify it regardless of nesting level?

Full example

```yaml
foo:
  subresources:
    bar:
      methods:
        create: post /bar
        bar: get /bar
    baz:
      methods:
        delete: delete /baz
        get: get /baz
        create: post /baz
        update: put /baz
    qux:
      methods:
        list: get /qux
        create:
          endpoint: post /qux
        delete: delete /qux
        get: get /qux
        update: put /qux
quux:
  methods:
    list: get /quux
    create: post /quux
    delete: delete /quux
    get: get /quux
    update: put /quux
```

Expected outcome 

```yaml
foo:
  subresources:
    bar:
      methods:
        create: post /bar
        bar: get /bar
    baz:
      methods:
        get: get /baz
        create: post /baz
        update: put /baz
        delete: delete /baz
    qux:
      methods:
        list: get /qux
        get: get /qux
        create:
          endpoint: post /qux
        update: put /qux
        delete: delete /qux
quux:
  methods:
    get: get /quux
    list: get /quux
    create: post /quux
    update: put /quux
    delete: delete /quux
```

I did try with `.. | select(has("methods"))` however, that is giving some unexpected output (basically each iteration and nesting level) instead of just the thing i'm looking to update adding to the confusion.
