### DISCUSSION TITLE
How to generate an XML element with attributes and an array value from a map

### DISCUSSION THREAD

**Discussion by gorgenarrows** [mikefarah/yq#2293] [Q&A] [answered]
I'm sure this is simple, but I'm just not finding a good answer!

I have two inputs that I'm merging and turning into XML. The "update" input looks like this:
```
001-20241221-2:
  alt: Four rowers in holiday hats on the dock.
  caption: Warming up before the races
002-20241221-8:
  alt: A quad at the dock getting ready to launch.
  caption: Preparing to launch
003-20241221-13:
  alt: A quad at the dock getting ready to launch.
  caption: Ready, set, go!
```
The "figures" input (that will be updated) looks like this:
```
001-20241221-2:
  image: file:////home/gnrc/Documents/Publii/sites/gnrc/input/media/posts/33/gallery/001-20241221-2-web.jpg
  data-size: 1600x2400
  thumbnail: file:////home/gnrc/Documents/Publii/sites/gnrc/input/media/posts/33/gallery/001-20241221-2-web-thumbnail.jpg
  alt: ""
  width: "768"
  height: "1152"
  caption: ""
002-20241221-8:
  image: file:////home/gnrc/Documents/Publii/sites/gnrc/input/media/posts/33/gallery/002-20241221-8-web.jpg
  data-size: 1600x1066
  thumbnail: file:////home/gnrc/Documents/Publii/sites/gnrc/input/media/posts/33/gallery/002-20241221-8-web-thumbnail.jpg
  alt: ""
  width: "768"
  height: "512"
  caption: ""
003-20241221-13:
  image: file:////home/gnrc/Documents/Publii/sites/gnrc/input/media/posts/33/gallery/003-20241221-13-web.jpg
  data-size: 1600x1066
  thumbnail: file:////home/gnrc/Documents/Publii/sites/gnrc/input/media/posts/33/gallery/003-20241221-13-web-thumbnail.jpg
  alt: A quad at the dock getting ready to launch.
  width: "768"
  height: "512"
  caption: Ready, set, go!
```
The final stage in this merges the updates with the figures and generates YAML that converts nicely into the XML that I need. The YAML I currently generate looks like this (I've cut this down to just show the first figure to save space):
```
figure:
  +@class: gallery__item
  a:
    +@href: file:////home/gnrc/Documents/Publii/sites/gnrc/input/media/posts/33/gallery/001-20241221-2-web.jpg
    +@data-size: 1600x2400
    img:
      +@src: file:////home/gnrc/Documents/Publii/sites/gnrc/input/media/posts/33/gallery/001-20241221-2-web-thumbnail.jpg
      +@alt: "Four rowers in holiday hats on the dock."
      +@width: "768"
      +@height: "1152"
  figcaption: "Warming up before the races"
```
And it generates XML like this:
```
<figure class="gallery__item">
  <a href="file:////home/gnrc/Documents/Publii/sites/gnrc/input/media/posts/33/gallery/001-20241221-2-web.jpg" data-size="1600x2400">
    <img src="file:////home/gnrc/Documents/Publii/sites/gnrc/input/media/posts/33/gallery/001-20241221-2-web-thumbnail.jpg" alt="Four rowers in holiday hats on the dock." width="768" height="1152"></img>
  </a>
  <figcaption>Warming up before the races</figcaption>
</figure>
<figure class="gallery__item">
  ...
</figure>
```
The script is:
```
. *? load(strenv(update))
| {
	"figure": map(.caption as $caption
		| {
		"+@class": "gallery__item",
		"a": {
			"+@href": .image,
			"+@data-size": .data-size,
			"img": {
				"+@src": .thumbnail,
				"+@alt": .alt,
				"+@width": .width,
				"+@height": .height
			}
		}
		} | ((select($caption != "") | .figcaption) = $caption)
	).[]
}
```
Now, what's driving me nuts is that I would really like the XML to be wrapped inside a "div" with some attributes. To do that, I'd  need to generate YAML that looks like this:
```
div:
  +@class: gallery
  +@contenteditable: "false"
  +@data-is-empty: "false"
  +@data-translation: Add images
  +@data-columns: "3"
  figure:
    +@class: gallery__item
    a:
      +@href: file:////home/gnrc/Documents/Publii/sites/gnrc/input/media/posts/33/gallery/001-20241221-2-web.jpg
      +@data-size: 1600x2400
      img:
        +@src: file:////home/gnrc/Documents/Publii/sites/gnrc/input/media/posts/33/gallery/001-20241221-2-web-thumbnail.jpg
        +@alt: "Four rowers in holiday hats on the dock."
        +@width: "768"
        +@height: "1152"
    figcaption: "Warming up before the races"
```

And I just can't come up with a reasonable way to do it!

As I said, I'm sure this is easy!
