### DISCUSSION TITLE
Change all keys in yaml file to lowercase

### DISCUSSION THREAD

**Discussion by 0byt3** [mikefarah/yq#2306] [Q&A] [answered]
The syntax on how to recurse and then manipulate the key name is not clicking with me.
The following works for the first keys, so I thought I could use it recursively somehow.
```bash
yq -N -o yml '. | with_entries(.key |= downcase)' test.yml
```

I have got this far:
```bash
yq -N -o yml '(.. | select(type == "!!map")) | with_entries(.key |= downcase)' test.yml
```

However it doesn't produce the correct results.

file:
```yml
key_one: "<password>"

key_two: "<username>"

KEY_three:
  key_a:
    Key_i: "val_three_a_i"
    key_ii: "val_three_a_ii"

  key_B:
    key_i: "val_three_b_i"
    key_I: "val_three_b_ii"

  key_c:
    key_i: "val_three_a_i"
    key_I: "val_three_a_ii"
```

output:
```yml
key_one: "<password>"
key_two: "<username>"
key_three:
  key_a:
    Key_i: "val_three_a_i"
    key_ii: "val_three_a_ii"
  key_B:
    key_i: "val_three_b_i"
    key_I: "val_three_b_ii"
  key_c:
    key_i: "val_three_a_i"
    key_I: "val_three_a_ii"
key_a:
  Key_i: "val_three_a_i"
  key_ii: "val_three_a_ii"
key_b:
  key_i: "val_three_b_i"
  key_I: "val_three_b_ii"
key_c:
  key_i: "val_three_a_i"
  key_I: "val_three_a_ii"
key_i: "val_three_a_i"
key_ii: "val_three_a_ii"
key_i: "val_three_b_i"
key_i: "val_three_b_ii"
key_i: "val_three_a_i"
key_i: "val_three_a_ii"
```
