### DISCUSSION TITLE
How to combine 2 files and merge array while deduplicating on sub-key

### DISCUSSION THREAD

**Discussion by tcreese** [mikefarah/yq#2331] [Q&A]
I'm trying to figure out how to merge two yaml files into one and combine the "rules" array but deduplicate items based on the identifier keeping the value in the host.yaml file.

global.yaml
```
mode: MONITOR
batch_size: 100
rules:
  - rule_type: SIGN
    policy: block
    identifier: itemA
    msg: block itemA
  - rule_type: SIGN
    policy: allow
    identifier: itemB
    msg: allow itemB
```

host.yaml
```
mode: WHITELIST
rules:
  - rule_type: SIGN
    policy: allow
    identifier: itemA
    msg: allow itemA
```

Desired Output
```
mode: WHITELIST
batch_size: 100
rules:
  - rule_type: SIGN
    policy: allow
    identifier: itemB
    msg: allow itemB
  - rule_type: SIGN
    policy: allow
    identifier: itemA
    msg: allow itemA
```

I've tried a couple of things but can't seem to figure out exactly what I'm trying to do.
