### DISCUSSION TITLE
How to remove map entries from selected nested maps properties

### DISCUSSION THREAD

**Discussion by james-lim-ev** [mikefarah/yq#2343] [Q&A] [answered]
Hi yq community, I have a question here.

I have a yaml file looks kind of like this:
```
...
.
.
.
    TypeA:
      type: object
      field:
        - title: Field A
          properties:
            propA:
              ref: 'some/reference'
        - title: Field B
          properties:
            propB:
              ref: 'some/reference'
      properties:
        propA:
          ref: 'some/reference'
        propB:
          ref: 'some/reference'
.
.
.
    TypeB:
      type: object
      field:
        - title: Field C
          properties:
            propA:
              ref: 'some/reference'
        - title: Field D
          properties:
            propB:
              ref: 'some/reference'
      properties:
        propA:
          ref: 'some/reference'
        propB:
          ref: 'some/reference'
        propC:
          ref: 'some/reference'
        propD:
          ref: 'some/reference'
.
.
.
...
```

My objective is to remove the duplicated properties in the top properties section if the field section has already contain the same properties.

My desire output:
```
...
.
.
.
    TypeA:
      type: object
      field:
        - title: Field A
          properties:
            propA:
              ref: 'some/reference'
        - title: Field B
          properties:
            propB:
              ref: 'some/reference'
.
.
.
    TypeB:
      type: object
      field:
        - title: Field C
          properties:
            propA:
              ref: 'some/reference'
        - title: Field D
          properties:
            propB:
              ref: 'some/reference'
      properties:
        propC:
          ref: 'some/reference'
        propD:
          ref: 'some/reference'
.
.
.
...
```

How do I do this with yq? I've tried multiple approaches with `pick` and `omit` but can't get anywhere I want it to go. 

I'd really appreciate it if someone could figure out any working approaches.

**Comment by james-lim-ev** [comment]
so the closest approach I came about is 

```
yq '.. | select(has("field") and has("properties")).properties |= omit(["propA","propB"])' myfile.yaml
```

but I still need to specify the string array. Is there a way that I can plug `field[].properties | keys` as a string array into `omit` ? 

I tried
```
yq '.. | select(has("field") and has("properties")).properties |= omit(select(has("field") and has("properties")).field[].properties | keys)' myfile.yaml
```
but that didn't work for me.

**Comment by mikefarah** [comment, marked as answer]
```
yq 'with(.. | select(kind == "map" and .type == "object"); 
    ([.field[].properties | keys] | flatten ) as $k | .properties |= omit($k) ) ' 
```

- `with(.. | select(kind == "map" and .type == "object"); <<exp>>` will iterate over every `type: object` node
- Then we need to get an array of the keys the we want to omit. `([.field[].properties | keys] | flatten )` and save that as `$k`
- And finally we update the properties map to omit those keys `.properties |= omit($k)`

**Reply by mikefarah** [reply]
```
TypeA:
  type: object
  field:
    - title: Field A
      properties:
        propA:
          ref: 'some/reference'
    - title: Field B
      properties:
        propB:
          ref: 'some/reference'
  properties: {}
TypeB:
  type: object
  field:
    - title: Field C
      properties:
        propA:
          ref: 'some/reference'
    - title: Field D
      properties:
        propB:
          ref: 'some/reference'
  properties:
    propC:
      ref: 'some/reference'
    propD:
      ref: 'some/reference'
```
