### DISCUSSION TITLE
Split result array into files, but keep all parent keys?

### DISCUSSION THREAD

**Discussion by treatmesubj** [mikefarah/yq#2355] [Q&A] [answered]
I've got a yaml like below, with a bunch of templates, which I like to split into separate files, using a command like this: 
```bash
mkdir split &&
    yq '.spec.templates.[]' my-pipeline.yaml -s '"./split/" + .templateName'`
```
`my-pipeline.yaml`:
```yaml
apiVersion: crd.ibm.k8s.io/v1
kind: FactPipeline
metadata:
  name: my-pipeline
spec:
  templates:
    - templateName: temp1
    - templateName: temp2
    - templateName: temp3
```

However, in each of the splits, it would be nice if I could keep all the parent-keys.
So, for example, the first resulting file would be this:
```yaml
apiVersion: crd.ibm.k8s.io/v1
kind: FactPipeline
metadata:
  name: my-pipeline
spec:
  templates:
    - templateName: temp1
```
