### DISCUSSION TITLE
How can I split a nested yaml into multiple files by iterating through multiple keys?

### DISCUSSION THREAD

**Discussion by dmc-94** [mikefarah/yq#2372] [Q&A] [answered]
Hi there,

I want to split a big yaml file into multiple yaml files. I looked into the QA with following example: https://github.com/mikefarah/yq/discussions/1562 but I can not really figure it out, as I don't understand how to double loop through this file.

I have following data

```
regions:
  region1:
    item1:
      settingA: null
      settingB: null
    item2:
      - value1
      - value2
  region2:
    item1:
      settingA: something
      settingB: configured
    item2:
      - value1
      - value2
```

I basically need to split the files by region and item.

So in the end this example should generate 4 yaml files like region1_item1.yaml , region1_item2.yaml, region2_item1.yaml and so on..

And the content should always be a key and the values of the region map:

`region1_item1.yaml`
```
item1:
  settingA: null
  settingB: null
```

Any help is appreciated. Thank you!

**Comment by mikefarah** [comment, marked as answer]
Probably way to late for you now (sorry); but for future readers:

You'll need to use the `-s` command to split each result into their own file.

So the first step is to work out how to split up the doc into the components that you want in each file, then the next step is to work out the right expression to give to '-s' to generate the filenames.

First Option (easier)

```
yq -s '(parent | key) + "_" + (key) ' '.regions[][]' examples/data1.yaml
```

- The main expression splits over each "item" _value_ map
e.g. for the path .regions.region2.item1:
```
settingA: something
settingB: configured
```

Then the `-s` expression is run against that match to generate the filename. We can use 'parent' to go up the node tree to provide more context.
In this case 'parent' is the region2 _map_; and the key of that is "region2". The key of that map is "item2", so this will create a filename "region2_item1.yml"

Second (harder) - to get the item name as a root in each child:
```
./yq  -s '.region + "_" + .item' '.regions[][] | {key: ., "region": parent | key, "item": key}' examples/data1.yaml
```
I'll need to create a _new_ map with that item key in each result. Because it's a new map, that maeans I can't use parent to look up the tree anymore; so we'll bake in the values of region and item name in order to be able to refer to them in the '-s' expression

This will yield a file like;
"region2_item1.yml"
```
item1:
  settingA: something
  settingB: configured
region: region2
item: item1

```
