### DISCUSSION TITLE
adding an alias if it does not exist yet

### DISCUSSION THREAD

**Discussion by tcurdt** [mikefarah/yq#2376] [Q&A]
I have this file

```
keys:
  - &bootstrap_blue age1ckhajem9pxd3k5q0twarlv4uqhzn44n98s93wuzkjml5wnw8qc8q85hj2l
  - &bootstrap_green age1u46k46h9j5qghluuddpl6der33jmtxl87f5sfpzvmlqqksyvgcls8khlhh
creation_rules:
  - path_regex: \.yaml$
    key_groups:
      - age:
          - *bootstrap_green
  - path_regex: \.env$
    key_groups:
      - age:
          - *bootstrap_green
```

I want to update or add a new anchor and I want all those anchors to be reference from the key_groups.
So basically:

```
keys:
  - &bootstrap_blue age1ckhajem9pxd3k5q0twarlv4uqhzn44n98s93wuzkjml5wnw8qc8q85hj2l
  - &bootstrap_green age1u46k46h9j5qghluuddpl6der33jmtxl87f5sfpzvmlqqksyvgcls8khlhh
creation_rules:
  - path_regex: \.yaml$
    key_groups:
      - age:
          - *bootstrap_blue
          - *bootstrap_green
  - path_regex: \.env$
    key_groups:
      - age:
          - *bootstrap_blue
          - *bootstrap_green
```

I tried first upserting the anchor:

```
    yq e '
      select(.keys[] | select(anchor == strenv(ANCHOR)) | . = strenv(AGE_PUBLIC_KEY)) //
      (.keys += [strenv(AGE_PUBLIC_KEY)] | (.keys[-1] anchor = strenv(ANCHOR)))
      ' -i .sops.yaml
```

but adding to the key_groups I struggle.

Either I always add to the list and create duplicates or they do not get added at all.

```
    yq e '
      (select(.keys[] | select(anchor == strenv(ANCHOR)) | . = strenv(AGE_PUBLIC_KEY)) //
      (.keys += [strenv(AGE_PUBLIC_KEY)] | (.keys[-1] anchor = strenv(ANCHOR)))) |
      .creation_rules[] |= (select(.key_groups[].age[] | . == strenv(ANCHOR)) // (.key_groups[].age[-1] alias |= .))
      ' -i .sops.yaml
```

I feel a little lost here. Any advice appreciated.
