### DISCUSSION TITLE
Setting a value while preserving its anchor in v4

### DISCUSSION THREAD

**Discussion by oleobal** [mikefarah/yq#679] [Q&A] [answered]
Hello,

I have a slight issue with v4 which I'd like help with, if possible.

Here's an example to explain my problem. I have a file of the form:

```
registry: &registry ''

front-image:
  name: "frontend"
  registry: *registry
```

I'm looking to update the value of the `.registry` key so as to update the rest of the file accordingly via aliases; I don't want to explode the alias.

In v3, this can be done with a command of the form `yq write my-file 'registry' my.registry.url --anchorName 'registry'`

How would I do this in v4? I understand from the documentation how to set values and anchors, but not both at the same time.

Thanks!
