### DISCUSSION TITLE
v4: Dots in key names

### DISCUSSION THREAD

**Discussion by holmesb** [mikefarah/yq#685] [Q&A] [answered]
Hi,
Given the following test.yaml:
```
items:
- metadata:
    annotations:
      a.b.c/d: string_value
- metadata:
    annotations:
      a.b.c/d: string_value2
- metadata:
```
In yq v3, the following:
``yq r test.yaml items[*].metadata.annotations.["a.b.c/d"]``

successfully returned:
string_value
string_value2

Now, my best guess at the equivalent v4 command:
``yq e ".items[].metadata.annotations.[\"a.b.c/d\"]" test.yaml``

Errors:
"Error: Cannot index array with 'a.b.c/d' (strconv.ParseInt: parsing "a.b.c/d": invalid syntax)".  
Is this a bug, or is there a better way?

BTW, this command works fine when specifying an item:
``yq e ".items[1].metadata.annotations.[\"a.b.c/d\"]" test.yaml``
gives:
string_value2
