### DISCUSSION TITLE
right expression ot merge any number of files [v4]

### DISCUSSION THREAD

**Discussion by rbauduin** [mikefarah/yq#690] [Q&A] [answered]
In [another question](https://github.com/mikefarah/yq/discussions/688#discussion-2044706), this command was mentioned for merging files:
```
yq eval-all 'select(fileIndex == 0) * select(filename == ".yml")' ./configFiles/.yml > ./newConfig/combined.yml
```
but it seems that according to the [source code](https://github.com/mikefarah/yq/blob/f46fe384bddc9aa2b2fe7e1966af87ceb2faf2f3/pkg/yqlib/all_at_once_evaluator.go#L45) the first file would be processed twice.
As shown belown I can't get the expected result either.

I'm testing with files with this content for file number `i`:
```
country:
- cities:
  - Cityi
  name: Ci
```
Merging 3 files manually gives
```
$ yq4 eval-all 'select(fileIndex == 0) *+ select(fileIndex==1) *+ select(fileIndex==2)'  f1 f2 f3
country:
  - cities:
      - City1
    name: C1
  - name: C2
    cities:
      - city2
  - name: C3
    cities:
      - City3
```
But what if you don't know the number of files to work on?
With the command referenced, we don't get the right result (and we also see f1 was combined with itself):
```
yq4 eval-all 'select(fileIndex == 0) *+ select(filename=="f*")'  f1 f2 f3
country:
  - cities:
      - City1
    name: C1
  - cities:
      - City1
    name: C1
country:
  - cities:
      - City1
    name: C1
  - name: C2
    cities:
      - city2
country:
  - cities:
      - City1
    name: C1
  - name: C3
    cities:
      - City3
```

So what's the right expression to put in `yq eval-all ${expression} *.yaml` for merging all files, getting the same result as `fileIndex(0) *+ fileIndex(1) ... + fileIndex(n)` ?
