### DISCUSSION TITLE
Support converting yaml to properties

### DISCUSSION THREAD

**Discussion by eldada** [mikefarah/yq#699] [Q&A] [answered]
**Please describe your feature request.**
I have use cases where I want to flatten a yaml into a properties file format.

**Describe the solution you'd like**
If we have data.yml like:

```yaml
a:
  array:
    - name: "element1"
      value: "value1"
    - name: "element2"
      value: "value2"
      sub-array:
        - sub1: "x"
        - sub2: "y"
        - sub3: "z"
```

And we run a command:

```bash
yq eval --prop data.yml'
```

it could output

```
a.array.0.name=element1
a.array.0.value=value1
a.array.1.name=element2
a.array.1.value=value2
a.array.1.sub-array.0.sub1=x
a.array.1.sub-array.1.sub2=y
a.array.1.sub-array.2.sub3=z

```

**Describe alternatives you've considered**
I wrote a [bash script](https://github.com/eldada/yaml-to-properties) to do this with `yq`, but I think this can. (and should) be a built in feature of `yq`.

**Comment by mikefarah** [comment]
```
yq eval '.. | select((tag == "!!map" or tag == "!!seq") | not) | (path | join(".")) + "=" + .' examples/data1.yaml
```

Synopsis:
- recurse into everything
- filter out maps and arrays
- join the path array with '.' 
- append "=" and the value

**Reply by eldada** [reply]
This is great! Thank you for the solution.
How do I use it to convert only a specific key and not all the file? I tried several options but didn't get the expected result...

**Reply by mikefarah** [reply]
Instead of using '..' to match everything in the file, replace with with an expression to find your key (e.g. `a.b.c`)

**Reply by eldada** [reply]
That's what I tried to begin with, but failed. Consider the example 
```yaml
a:
  key1: "value1"
  key2: 2.6
  ab:
    key1: 6
    key2: "h"
```

I run
```
yq eval 'a.ab | select((tag == "!!map" or tag == "!!seq") | not) | (path | join(".")) + "=" + .' examples/simple.yaml
```
and get
```
Error: Parsing expression: Lexer error: could not match text starting at 1:1 failing at 1:3.
	unmatched text: "a."
```

I also tried with `.a.ab` and got an empty response.
