### DISCUSSION TITLE
Using logical and-operation in evaluation results in new element

### DISCUSSION THREAD

**Discussion by ErikLundJensen** [mikefarah/yq#704] [Q&A] [answered]
First, thanks for the great work and for the new 4.x releases.
Maybe I'm pushing yq too hard as my combination of features is not documented. I'm trying to construct an evaluation with a logical and-operation.

Given the following input in the file values.yaml
```
apps:
- name: myproxy
  feature: abc-123
  image:
    name: nginx
    tag: 1.14.2
- name: other
  image:
    name: nginx
    tag: 2.4.4
```
and the command
```
yq eval '(.apps[] | (select (.name == "myproxy") | select(.feature == "abc-123")).image.tag) = "2.0.0"' values.yaml 
```
results in update of the image.tag for the app with the name "myproxy":
```
apps:
  - name: myproxy
    feature: abc-123
    image:
      name: nginx
      tag: 2.0.0
  - name: other
    image:
      name: nginx
      tag: 2.4.4
```
This really great as that was not possible in yq version 3.x

However, when removing the field "feature" from the input file values.yaml like this:
```
apps:
- name: myproxy
  image:
    name: nginx
    tag: 1.14.2
- name: other
  image:
    name: nginx
    tag: 2.4.4
```
and execute the same command then the result includes a **feature: null** as seen below:
```
apps:
  - name: myproxy
    image:
      name: nginx
      tag: 1.14.2
    feature: null
  - name: other
    image:
      name: nginx
      tag: 2.4.4
```

I wonder how a new element "feature" is added to the output structure as it is only used in the select statement.

Version info:
yq version 4.4.0
