### DISCUSSION TITLE
Insert empty value

### DISCUSSION THREAD

**Discussion by sylvainbx** [mikefarah/yq#740] [Q&A] [answered]
## What I want

Using yq V4, how to insert a key with an empty value in a yaml document?

For example, I have the following document:
```yaml
a:
  b:
    c: "lorem ipsum"
```

I would like to add `a.d` with no value. Here's the expected result:
```yaml
a:
  b:
    c: "lorem ipsum"
  d:
```
### Using yq v3

With V3, I used to accomplish this with:
```bash
yq w -i sample.yml a.d ''
```

### Using yq v4
But, with V4, if I specify an empty string:
```bash
yq -i eval '.a.d = ""' sample.yml
```

I'll get something like this, which is not what I was expecting, because it inserts a string instead of a map:
```yaml
a:
  b:
    c: "lorem ipsum"
  d: ""
```
Is there a special operator to accomplish that? _e.g._
```bash
yq -i eval '.a.d = <empty>' sample.yml
```
