### DISCUSSION TITLE
Rename key

### DISCUSSION THREAD

**Discussion by sylvainbx** [mikefarah/yq#741] [Q&A] [answered]
Using yq V4, how to rename a key in a yaml document?

For example, I have the following document:
```yaml
a:
  b:
    c: "lorem ipsum"
```

I would like to rename `a.b` to `a.foo`. Here's the expected result:
```yaml
a:
  foo:
    c: "lorem ipsum"
```
I've looked around in the docs but I wasn't able to find any operator to accomplish that. Is this feasible?
