### DISCUSSION TITLE
how can i replace part of the value in v4?

### DISCUSSION THREAD

**Discussion by pycgo** [mikefarah/yq#765] [Q&A] [answered]
origin file
```
spring:
  dataSource:
    username: zxx
    password: 123456
    url: jdbc:mysql://test.bd.com:3306
```

i hope  test.bd.com  will replace to other string like   "testNew.bd.cn"
```
spring:
  dataSource:
    username: zxx
    password: 123456
    url: jdbc:mysql://testNew.bd.cn:3306
```
