### DISCUSSION TITLE
if key exist,then replace value ,if not exist ,do not create key

### DISCUSSION THREAD

**Discussion by pycgo** [mikefarah/yq#778] [Q&A] [answered]
```
[root@test ~]# yq e test.yaml 
spring:
  dataSource:
    username: zxx
    password: 123456
    url: jdbc:mysql://test.bd.com:3306
if key exist,then replace value  that is ok 
```
[root@test ~]# yq e '.spring.dataSource.username="aaa"' test.yaml 
spring:
  dataSource:
    username: aaa
    password: 123456
    url: jdbc:mysql://test.bd.com:3306
```
but i want first judge the key "uername111" is exist in orign file ,then repalce it ；if not exist，then do not create new key "username111"
```
[root@test ~]# yq e '.spring.dataSource.username111="aaa"' test.yaml 
spring:
  dataSource:
    username: zxx
    password: 123456
    url: jdbc:mysql://test.bd.com:3306
    username111: aaa
[root@test ~]# 
```
