### DISCUSSION TITLE
Another merge question

### DISCUSSION THREAD

**Discussion by lyandr** [mikefarah/yq#780] [Q&A]
hello @mikefarah,

thanks for your answer about my first question. But i have another question. I want to merge the following files:

file1.yml
```yml
a:
  - b:
    - c:
      - foo: bar
 ````

file2.yml
```yml
a:
  - b:
    - c:
      - bar: foo
```

file3.yml
```yml
a:
  - c:
    - john: doe
````

If i run a merge with `yq ea -M '. as $item ireduce({}; . *d $item)'  file1.yml file2.yml file3.yml` i have the following result:
```yml
a:
  - b:
      - c:
          - foo: bar
            bar: foo
    c:
      - john: doe
```

I know that the result is a valid yaml result, but for some reasons mkdocs rise an error during the mkdocs.yml parsing. So the 
wanted result is the following:
```yml
a:
  - b:
      - c:
          - foo: bar
          - bar: foo
  - c:
      - john: doe
```

Is it possible to obtain a "-" on each entries of an array? Thanks for your help.

Regards
Lyandr

**Comment by mikefarah** [comment]
The issue is that as far as `yq` is concerned, it's just merging arrays of objects.

At the moment, you have the 'deep' merge flag, so objects in the same array index will be merged together (which is what you want for file1 and file2.

With file 3 however, you actually want to _append_ the object it's index 0 to the existing array (and put it in index 1), rather than deep merge into index 0 (which is what deep merge does).

As far as I can tell, there are two ways around this, either:
a) in fileIndex3, put an empty/null object in the first array position, followed by what you want in index 0:

new file3:
```yaml
a:
 - null
  - c:
    - john: doe
```

b) use 'deep' merge to merge file 1 and file 2 using the deep merge flag, then merge the result of that with file 3 using the append flag.
