### DISCUSSION TITLE
Add object containing double quotes to array

### DISCUSSION THREAD

**Discussion by don-attilio** [mikefarah/yq#787] [Q&A] [answered]
Hello,
My starting yaml file is something like:
```
a:
  b:
    - e1: 'variable1 == "string1"'
```
I would like to add another element to b and this is what I came up with:

```
yq e '.a.b + {"e2":"variable2 == '"string2"' | .. style="single"}' myfile.yaml
output:
a:
  b:
    - e1: 'variable1 == "string1"'
    - e2: 'variable2 == string2'
```

Unfortunately string2 is not surrounded by double quotes.
If I remove from the previous command the single quotes surrounding the double quotes I get this error:

```
Error: Parsing expression: Lexer error: could not match text starting at 1:50 failing at 1:51.
	unmatched text: "s"
```

Is there any way to do that?

Thanks,
Attilio
