### DISCUSSION TITLE
Identify map keys, whose value is a map that has direct child `enabled: true`

### DISCUSSION THREAD

**Discussion by ghost** [mikefarah/yq#802] [Q&A] [answered]
Hello, I am new to yq v4. I am running `yq version 4.7.1`. I read through the documentation but I haven't figured out the syntax to solve my need. Could anyone help?

Here is my document:
```yaml
Cruise Control:
  speed: 100
  enabled: true
Headlights:
  broken: false
  enabled: false
Gearbox:
  tractionControl:
    enabled: true
  gear: 3
  neutral: false
Climate Control:
  temperature: 70
  enabled: true
Make: "Toyota"
Passengers: []
```

I do not know all possible top level keys. I am looking for a general solution to identify the set of top level keys that have an `enabled: true` child as their direct descendent, i.e. my desired output is:
```
Cruise Control
Climate Control
```

So far I have tried:
```
yq e '.[] | has("enabled")' demo.yaml
yq e '.[] | (.enabled==true)' demo.yaml
yq e '.[] | select(enabled==true)' demo.yaml
yq e '.[] | select(.enabled==true)' demo.yaml
yq e 'keys' demo.yaml
```

I've noticed that the `Passengers: []` key causes problems. I think my next step is probably to filter out non-map values?
