### DISCUSSION TITLE
Filter out direct child objects whose key doesn't match a specific value

### DISCUSSION THREAD

**Discussion by sguillope** [mikefarah/yq#809] [Q&A] [answered]
Hi all,

I've been trying so many different combinations of `del()`, `select()` and `has()` but I just can't find the right expression :(

I have a yaml source that looks like this:
```yaml
name: some value
# ...other keys
environment:
  prod:
    config:
      # more child keys
  staging:
    config:
      # more child keys
  dev:
    config:
      # more child keys
```

I'm trying to apply a filter it to remove the direct child objects of `environment` whose key doesn't match a specific value. 
For example, if the value is `prod`, I want the result to be:
```yaml
name: some value
# ...other keys preserved
environment:
  prod:
    config:
      # more child keys
```

Any ideas?

Bonus problem: if none of the child objects are matched (e.g. value == `test`) then I'd like `environment` not to be present in the result. :)
