### DISCUSSION TITLE
How to perform an replace-only update of a multidoc file

### DISCUSSION THREAD

**Discussion by BrendanGalloway** [mikefarah/yq#816] [Q&A] [answered]
For example, if I have a file:

```yaml
a:
  b: 1
---
a:
  c: 2
---
a:
  b: 5
```
and want to update all existing instances of `a.b` (and only existing instances) to be 10, how would I do so?
if I use `yq eval '.a.b = 10'` the output is:
```yaml
a:
  b: 10
---
a:
  c: 2
  b: 10
---
a:
  b: 10
```
which adds a new `a.b` entry, which is not desired. If I try use a filter such as `yq eval '.a | select(has("b")) | .b = 10'` then the output contains only the entries that matched the select, not the complete contents.  And then only the child entries at that:
```yaml
b: 10
---
b: 10
```
yq3 has a workaround in the merge command that lets me get the output I would like (even if it's a bit clunky to use):
`yq m --overwrite --autocreate=false test.yml <(printf 'a:\n  b: 10') -d=*`
```yaml
a:
  b: 10
---
a:
  c: 2
---
a:
  b: 10
```
is there an equivalent yq4 eval that gets the same output?

**Comment by mikefarah** [comment, marked as answer]
You just need to filter out the nodes that don't have `.a.b` on the LHS of the update operator:

```
yq e '(select(.a.b) | .a.b) = 10' examples/data1.yaml
```

**Reply by BrendanGalloway** [reply]
@mikefarah thanks, that works perfectly

**Comment by infa-ddeore** [comment]
@mikefarah how to replace all key, values? provided command updates the matching value, what i want is to replace a.b and a.c with provided `a.b` 

input:
```
a:
  b: 1
---
a:
  c: 2
---
a:
  b: 5
  e: 3
```

```
$ cat /tmp/4 | yq4 '(select(.a.b) | .a.b) = 20'
a:
  b: 20
---
a:
  c: 2
---
a:
  b: 20
  e: 3
```

expected output
```
a:
  b: 20
---
a:
  c: 2
---
a:
  b: 20
```

**Reply by mikefarah** [reply]
I'm confused - what are you replacing with what? the expected output, a.c hasn't changed, but the third doc `a` has lost `e` and has had `b` updated... not sure what the intention is here?

**Reply by infa-ddeore** [reply]
@mikefarah, i want to replace all elements, expected output is as below where in last element `a.e` is removed and contains only given value(s)

```
a:
  b: 20
---
a:
  c: 2
---
a: 
  b: 20 
```
