### DISCUSSION TITLE
Merging file without changing array value

### DISCUSSION THREAD

**Discussion by steenstra** [mikefarah/yq#836] [Q&A] [answered]
When given the files `a.yaml` and `b.yaml`:

`a.yaml`
```
filled-in: custom_client_value
something:
 - a
 - b
something2: [a, b,]
```

`b.yaml`
```
filled-in: default_value
something: default_value
something2: 
  - default
  - value
this_is_a_new_value: spiksplinternieuw
```

I want to use `yq` to merge the files into:

`c.yaml`

```
filled-in: custom_client_value
something:
 - a
 - b
someting2: [a, b]
this_is_a_new_value: spiksplinternieuw
```

So line 1 tm 5 should stay like in `a.yaml`, but the new value `spiksplinternieuw` should be added. Basically, I want `yq` to only add the missing values, but not change any existing ones.

However, what happens, is this:

(v3) - `yq merge --comments overwrite a.yaml b.yaml`

results in

```
filled-in: custom_client_value
something: default_value
something2: 
  - default
  - value
this_is_a_new_value: spiksplinternieuw
```

When consulting the (v3) help function, it shows:
```
Flags:
  -a, --arrays string     array merge strategy (update/append/overwrite)
                          update: recursively update arrays by their index
                          append: concatenate arrays together
                          overwrite: replace arrays
```

It seems there's not an easy way for keeping the arrays as they are, like there is with all other values. Or am I missing something?
