### DISCUSSION TITLE
[v4] merge 2 files with diffrent format to correct format

### DISCUSSION THREAD

**Discussion by kholisrag** [mikefarah/yq#858] [Q&A] [answered]
Hi, sorry for this stupid question

we have 2 file :

`users.yaml`
```
data:
  mapUsers: |
    - groups:
      - a-client-group
      userarn: test:user/clients-user-001
```

`additional.yaml`
```
- groups:
  - b-clients-group
  userarn: test:user/clients-user-999
```

what `yq` v4 syntax I need to use to achieve : 

`combine.yaml`
```
data:
  mapUsers: |
    - groups:
      - a-client-group
      userarn: test:user/clients-user-001
    - groups:
      - b-clients-group
      userarn: test:user/clients-user-999
```
note that file `users.yaml` vs `additional.yaml` have different indent for the list / array

any help appreciate, thanks in advance!
