### DISCUSSION TITLE
How to remove an empty map from YAML?

### DISCUSSION THREAD

**Discussion by andremicocci** [mikefarah/yq#882] [Q&A] [answered]
I need to remove an empty map from a YAML.
Sometimes this map may have values, and sometimes this will appears empty.

My YAML code looks like this:
```yml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations: {}
  creationTimestamp: "2021-03-24T13:16:10Z"
```
I need to remove `annotations: {}`

My desired output:
```yml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: "2021-03-24T13:16:10Z"
```
Anybody can helps me?

https://stackoverflow.com/questions/68264327/yq-how-to-remove-an-empty-map-from-yaml
