### DISCUSSION TITLE
Replacing scalar from file

### DISCUSSION THREAD

**Discussion by p3lim** [mikefarah/yq#894] [Q&A] [answered]
Let's say I have this file:
```yaml
data:
  values: |
    foo: bar
```

And another file:
```yaml
john: 42
```

Can I with yq replace the `.data.values` scalar in the first file with the contents of the second file to create this?:
```yaml
data:
  values: |
    john: 42
```

The closest I've gotten is this:
```bash
yq ea 'select(fileIndex==0).data.values = select(fileIndex==1) | select(fileIndex==0)' first.yaml second.yaml
```
Which does not result in scalar data:
```yaml
data:
  values:
    john: 42
```
