### DISCUSSION TITLE
how to rename key in a map (or hash)

### DISCUSSION THREAD

**Discussion by hungpr0** [mikefarah/yq#898] [Q&A] [answered]
Hello,
With yq version 4.11.1, please help to check how to rename a key `users.name` to `users.username`
```
users:
  - name: firstname.lastname1
    firstname: firstname1
    lastname: lastname1
  - name: firstname.lastname2
    firstname: firstname2
    lastname: lastname2
```

Expected result:
```
users:
  - username: firstname.lastname1
    firstname: firstname1
    lastname: lastname1
  - username: firstname.lastname2
    firstname: firstname2
    lastname: lastname2
```
I tried with these as search on https://github.com/mikefarah/yq/discussions/741 but it doesn't work
```
yq e ".users.username = .users.name | del(.users.name)" users.yml
Error: Cannot index array with 'username' (strconv.ParseInt: parsing "username": invalid syntax)
```
Thank you
