### DISCUSSION TITLE
Maps not supported yet. so any idea when it's possible to do so

### DISCUSSION THREAD

**Discussion by Bennet-Sunder** [mikefarah/yq#911] [Q&A] [answered]
Suppose I have a file like so 

```
---
root:
  key:
    first: name
```

And I want to add a key-value pair to this like so 

```
---
root:
  key:
    first: name
    second: last

```

And I try something like this `yq eval '.root.key += {1:2}'  sample.yml -i` I get an error saying that this can't be done as yet. 
Any idea if this is something that will be supported in the future and any possible ETA around that? Thanks!

**Comment by mikefarah** [comment, marked as answer]
You don't need the addition operator for that, you can just

```
yq e '.root.key.second = "last"'
```

**Reply by Bennet-Sunder** [reply]
Thanks so what isn't possible right now is. 

From 
```
---
root:
  key:
    first: name
```

I wouldn't be able to do this. 

```
---
root:
  key:
    first: name
  new:
     another: key  
```
