### DISCUSSION TITLE
Inplace array merge causing duplicates instead of replace

### DISCUSSION THREAD

**Discussion by mssanjay** [mikefarah/yq#953] [Q&A] [answered]
Issue:
I am trying to merge(replace) array elements by key or name. This is causing duplicates instead of replace.
As explained below, my expection is that the YQ inplace merge should overwrite array elements by matching "service.[].name"

Version of yq: 4.13.2

Input Yaml
service1.yml:
```
_format_version: "1.1"
services:
  - name: service1
    url: https://service11.microservice.net
plugins:
  - name: prometheus
```

service2.yml:
```
_format_version: "1.1"
services:
  - name: service2
    url: https://service22.microservice.net
plugins:
  - name: prometheus
```
master.yml:
```
_format_version: "1.1"
services:
  - name: service1
    url: https://service1.microservice.net
  - name: service2
    url: https://service2.microservice.net
  - name: service3
    url: https://service3.microservice.net
  - name: service4
    url: https://service4.microservice.net    
plugins:
  - name: prometheus
```
Command
The command you ran:
```
yq eval-all '. as $item ireduce ({}; . *+ $item)' --inplace master.yml .\service1.yml .\service2.yml
```
Actual behavior
```
_format_version: "1.1"
services:
  - name: service1
    url: https://service1.microservice.net
  - name: service2
    url: https://service2.microservice.net
  - name: service3
    url: https://service3.microservice.net
  - name: service4
    url: https://service4.microservice.net
  - name: service1
    url: https://service11.microservice.net
  - name: service2
    url: https://service22.microservice.net
plugins:
  - name: prometheus
  - name: prometheus
  - name: prometheus
```

Expected behavior
```
_format_version: "1.1"
services:
  - name: service1
    url: https://service11.microservice.net
  - name: service2
    url: https://service22.microservice.net
  - name: service3
    url: https://service3.microservice.net
  - name: service4
    url: https://service4.microservice.net    
plugins:
  - name: prometheus
```
I like to overwrite array elements with service1.yml and service2.yml "services".

Thanks
Sanjay
