### DISCUSSION TITLE
Explain for contains function

### DISCUSSION THREAD

**Discussion by mexoboy** [mikefarah/yq#957] [Q&A] [answered]
Hi. I have yaml config with servers. And I need find servers with specific tag. I use contains for that, but I have some unexpected result:
```yaml
servers:
  - name: server-1
    tags:
      - foo
  - name: server-2
    tags:
      - bar
  - name: server-3
    tags:
      - foo
      - bar
```
I run command for tag "foo" and receive correct values, which I expected:
```bash
# yq e '.servers[] | select(.tags[] | contains("foo")) | .name' test.yaml
server-1
server-3
```
But it didn't work for tag bar:
```bash
# yq e '.servers[] | select(.tags[] | contains("bar")) | .name' test.yaml
server-2
```

Could you please explain how it's work and how I can change my query for take expected result?
