### DISCUSSION TITLE
Dear YQ, Why do you eat my Comments?

### DISCUSSION THREAD

**Discussion by rhatfield-bushel** [mikefarah/yq#965] [Q&A] [answered]
Dear YQ,

I have tried many permutations of your command, and yet; no joy.

I would like to nest an entire YAML file within a single object, and I can't seem to get my point across.

How can I satiate your hunger? Are you not entertained?

I attempt the following

```shell
cat test.yaml <<'EOF'
# Here's the first comment
first: 'first value'
# Here's the second comment
second: 'second value'
# Here's the third comment
third: 'third comment'
EOF
yq e '{"prefix":.}' test.yaml
```

And you still give me

```yaml
prefix:
  first: 'first value'
  # Here's the second comment
  second: 'second value'
  # Here's the third comment
  third: 'third comment'
```

How do I get you to leave my comments alone?

Sincerely Yours, 
A confused developer

**Comment by mikefarah** [comment, marked as answer]
Dear confused developer,

I am greedily eating your first comment because I think it's a document header (its pre-processed as part of a workaround/hack for a go-yaml issue).

My appetite is never sated, however you can force me not to eat you header by:

```
yq e --header-preprocess=false  '{"prefix":.}' test.yaml 
```

Sincere apologies,
yq

**Reply by rhatfield-bushel** [reply]
So this fixed my issue better than expected, kinda.

Using the following `test.yaml` file

```yaml
# yaml-language-server: $schema=./values.schema.yaml

# Here's the first comment
first: "first value"
# Here's the second comment
second: "second value"
# Here's the third comment
third: "third comment"
```

And the command `yq e --header-preprocess=false '{"prefix":.}' test.yaml` still strips off the first line, but retains the important comments in this case

```yaml
prefix:
  # Here's the first comment
  first: "first value"
  # Here's the second comment
  second: "second value"
  # Here's the third comment
  third: "third comment"
```

I'm guessing this has to do with the aforementioned document header preprocessor workaround? 

In any case, that schema would no longer be valid so it works out well, thanks for the help!

**Comment by chr1shung** [comment]
Hi I came across this issue today, my use case is trying to parse a docker-compose.yml and get a list of services name. For example:
```yaml
services:
  # This is a
  A:
    image: repo/A
  # This is b
  B:
    image: repo/B
  # This is c
  C:
    image: repo/C
```
I was running `yq --header-preprocess=false '.services | keys' sample.yml` but it still ate the comment:
```
# This is a
- A
# This is b
- B
# This is c
- C
```

Is there any way to get rid of it ? 
Thanks for the help
