### DISCUSSION TITLE
Merging array elements with two different schemas

### DISCUSSION THREAD

**Discussion by mssanjay** [mikefarah/yq#968] [Q&A] [answered]
Hi,
I have two YAML files with different schemas and I like to merge a specific array elements from second file  into the first file.

file1.yaml
---------------
```
mgwaskong:
  kong:
    dblessConfig:
      config:
        services: []
```

file2.yaml
---------------
```
services:
 - name: service1
    url: url1
 - name: service2
   url: url2

```

How can I merge services from file2.yaml into services from file1.yaml?

Thanks
sanjay
