### DISCUSSION TITLE
How to update/merge object inside an array with specific key: value

### DISCUSSION THREAD

**Discussion by strudelPi** [mikefarah/yq#983] [Q&A] [answered]
Hey folks,

My goal is checking a nested object inside an array of those objects for a specific key: value and if missing, update it.

e.g.
``` yaml
metadata:
  - important:
    name: Jonas
    phone: 123
  - lessImportant:
    age: 12
objects:
  - name: hello
    number: 7
  - name: hello2
    number: 6
  - name: hello
    number: 2
```
for this document, I would like to update an object with `number: 2` with e.g. `new: yes`

Now my problem here is, using `.objects[] | select(.number == 2) | .new = "yes"` but doing this, I am now in the narrow context with just:
``` yaml
name: hello
number: 2
new: yes
```
 but what I need is to rewrite the original file. The `--in-place` won't help me as it will change the file in place but just with this and I would loose the original data. Unfortunately I found no documentation mentioning on how to get back to the context of the whole file in order for `yq` to print out the whole thing.

Another thing I tried was merging the result with the original file, with no success as I would need a deep merge of the object I am merging but I need that for the specific array index where `number: 2` which according to [this](https://github.com/mikefarah/yq/issues/796) is not possible in `yq`.

Any suggestions? I think I'm just missing some very simple workflow with `yq` since this seems like a pretty basic usecase.

Thanks for any answers :-)
