### DISCUSSION TITLE
how to set yq exit status

### DISCUSSION THREAD

**Discussion by moluzhui** [mikefarah/yq#992] [General]
```yaml
apiVersion: apps.kruise.io/v1alpha1
kind: CloneSet
metadata:
  generation: 1
  ...
spec:
  ...
  ...
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: data1
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 60G
  - metadata:
      creationTimestamp: null
      name: data2
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 60G
status:
  availableReplicas: 1
```

I want to modify **volumeTemplate storage** value 
```shell
match="${1-all}"
storage="$2"

if [[ $match == "all" ]]; then
    s="$storage" yq e '.spec.volumeClaimTemplates[].spec.resources.requests.storage = env(s)' cloneset_modifystorage.yml
else
    m="$match" s="$storage" yq e '(.spec.volumeClaimTemplates[] | select(.metadata.name == env(m)).spec.resources.requests.storage) |= env(s)' cloneset_modifystorage.yml
fi
```
The code above could match the storage that deleted a particular list, but I want to **return an error if the match fails**.

In the official documentation, the [-e flag](https://mikefarah.gitbook.io/yq/commands/evaluate-all#flags)  seems to work, but when I use it, $?
Has been 0, and did not achieve the expected match failure return
```shell
m="$match" s="$storage" yq e '(.spec.volumeClaimTemplates[] | select(.metadata.name == env(m)).spec.resources.requests.storage) |= env(s)' cloneset_modifystorage.yml -e 1
echo $?
```

I really appreciate any help with this.
