### ISSUE TITLE
Sort document by key

### ISSUE THREAD

**Issue by wake42** [mikefarah/yq#1024]
**Please describe your feature request.**
I wish I could use yq to sort a multidocument file based on a key. 

**Describe the solution you'd like**
Given a file
```yml
name: Beta
data:
  rank: bla bla
---
name: Alfa
data:
  rank: bla bla
---
name: Gamma
data:
  rank: bla bla
```
I would like to sort the order of the included yaml document given a key, so that the above, sorted by key `.name` would become

```yaml
name: Alfa
data:
  rank: bla bla
---
name: Beta
data:
  rank: bla bla
---
name: Gamma
data:
  rank: bla bla
```

**Comment by mikefarah** [comment]
This can now be done with 4.16.1 with the new `sort_by` operator. This operator sorts arrays, so you first need to put the docs into an array, sort, then split them out again:

```bash
yq ea '[.] | sort_by(.name) | .[] | splitDoc' file.yaml
```

**Comment by Zebradil** [comment]
The suggestion doesn't seem to work:

```
cat << EOF | yq '[.] | sort_by(.name) | .[] | splitDoc'
name: Beta
data:
  rank: bla bla
---
name: Alfa
data:
  rank: bla bla
---
name: Gamma
data:
  rank: bla bla
EOF
name: Beta
data:
  rank: bla bla
name: Alfa
data:
  rank: bla bla
name: Gamma
data:
  rank: bla bla
```

```
yq (https://github.com/mikefarah/yq/) version 4.21.1
```

**Comment by eripa** [comment]
Hello @mikefarah,

sorry for bringing this thread back from the dead. But is it possible to have second (and third etc) key sorting like below. I.e. first sort all documents on X, but for if the value is the same, use the second key Y to sort within those?

i.e. 


```yaml
name: Beta
other: Epsilon
---
name: Alfa
other: Gamma
---
name: Beta
other: Delta
```

result (Beta Delta comes before Beta Epsilon):


```yaml
name: Alfa
other: Gamma
---
name: Beta
other: Delta
---
name: Beta
other: Epsilon
```

Thanks a lot 🙏
