### ISSUE TITLE
[misleading message] Error: yaml: line 3: did not find expected key

### ISSUE THREAD

**Issue by ryenus** [mikefarah/yq#1030]
**Describe the bug**
When an item in an array is indented wrong, the error message reported is unclear,  and it points to the wrong line.

Version of yq: `4.16.1`
Operating system: mac
Installed via: homebrew

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
data1.yml:
```yaml
- item: 1
  attr: 1
- item: 2
  attr: 2
- item: 3
  attr: 3
- item: 4
  attr: 4
```

data2.yml:
```yaml
- item: 1
  attr: 1
- item: 2
  attr: 2
- item: 3
  attr: 3
  - item: 4
  attr: 4
```

**Command**
The command you ran:
```
yq -oj e . data1.yaml data2.yaml
```

**Actual behavior**
```
... // data1.yaml converted to json properly
Error: yaml: line 4: did not find expected key
```

**Expected behavior**

```yaml
Error: data2.yaml: line 7: bad indentation
```

**Additional context**
Here the problem is the bad indentation on line 7 with the 4th item in the array, but the reported error is:
```
Error: yaml: line 4: did not find expected key
````

Where the item `2` with attr `2` looks just fine, it doesn't even point to item `3`, which makes it confusing and not helpful with locating the actual problem.

And the difference between the actual line and the reported line could be quite large when item `3` takes many lines.

Also it should report the file name whenever available, this would be very helpful when processing multiple input files.

Nevertheless, thank you very much for making yq, it's very useful, especially in places where json is too strict and jq refuse to work, that's when yq would come and rescue :-)
