### ISSUE TITLE
Compiling a file with yaml merged content will get wrong results

### ISSUE THREAD

**Issue by zhangguanzhang** [mikefarah/yq#1032]
**Describe the bug**

Note that any how to questions should be posted in the discussion board and not raised as an issue.

Version of yq: yq (https://github.com/mikefarah/yq/) version 4.16.1
Operating system: linux
Installed via: binary release

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
data1.yml:
```yaml
arm64: &arm64
  a: b
aarch64:
  <<: *arm64
```

**Command**
The command you ran:  
```
yq e -i .amd64.storage.version=1 data1.yml
```

**Actual behavior**

```yaml
arm64: &arm64
  a: b
aarch64:
  !!merge <<: *arm64
amd64:
  storage:
    version: 1
```

**Expected behavior**

```yaml
arm64: &arm64
  a: b
aarch64:
  <<: *arm64
amd64:
  storage:
    version: 1
```

**Additional context**
