### ISSUE TITLE
Question: How do i perform a merge typed array

### ISSUE THREAD

**Issue by josephlim75** [mikefarah/yq#1052]
I have 2 yaml files with the following typed array.  How do I achieve the following expected result.  I tried ` yq ea 'select(fileIndex == 0) * select(fileIndex == 1)' filex.yml filex.yml` OR `*+` but i can't seems to merge them with the expected result I want.  The result is always `overwrite` or `append` with duplicate `DBSERVER` and `DBURL`.

file1.yaml
```yaml
external:
  - name: DBSERVER
    value: FILE1VALUE
  - name: DBURL
    value: FILE1VALUE
  - name: FILE1
    value: FILE1VAL
```

file2.yaml
```yaml
external:
  - name: DBSERVER
    value: FILE2VALUE
  - name: DBURL
    value: FILE2VALUE
  - name: FILE2
    value: FILE2VALUE
```

## Expected Results
```yaml
external:
  - name: DBSERVER
    value: FILE2VALUE
  - name: DBURL
    value: FILE2VALUE
  - name: FILE2
    value: FILE2VALUE
  - name: FILE1
    value: FILE1VALUE
```
