### ISSUE TITLE
Question: How can I put the values in square brackets

### ISSUE THREAD

**Issue by viorelfoamete** [mikefarah/yq#1053]
First of all really appreciating the work on this.
Second, newbie here so please be pacient.

Version of yq: 4.16.2
Operating system: mac
Installed via: homebrew

**I want to generate a file containing data like below:**
```yaml
a:
  b:
    c: ['x', 'y', 'z']
```

**Closest I could get using this:**
```
yq e -n '.a.b.c[0] = "x" | .a.b.c[1] = "y" | .a.b.c[2] = "z"'
```

**Which resulted into this:**

```yaml
a:
  b:
    c:
      - x
      - y
      - z
```

**How can I get the values of key c in square brackets instead of one on each line?**
