### ISSUE TITLE
Replacement of value within multiple document YAML file removes first document

### ISSUE THREAD

**Issue by tstmrk** [mikefarah/yq#1056]
**Describe the bug**
When I try to replace a value within the second document of a YAML file containing multiple documents the first documents is removed, where I expect that the files stays intact. Hopefully there is an other way of doing this or a workaround. I saw one related issue, but that one is already closed: https://github.com/mikefarah/yq/issues/351

Version of yq: 4.X.X
yq (https://github.com/mikefarah/yq/) version 4.16.2

OS: Windows WSL

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
data1.yml:
```yaml
foo: hello
---
bar:
  - name: bla
    version: yahoo
```

**Command**
The command you ran:
```
yq eval 'select(documentIndex == 1) | .bar[0].version="33"' test.yaml -i
```
(I got this example from: https://mikefarah.gitbook.io/yq/upgrading-from-v3#multiple-documents)

**Actual behavior**
The new file:
```yaml
bar:
  - name: bla
    version: "33"
```

**Expected behavior**
```yaml
foo: hello
---
bar:
  - name: bla
    version: "33"
```
