### ISSUE TITLE
write/update tree value

### ISSUE THREAD

**Issue by rosskevin** [mikefarah/yq#106]
I'm trying to merge two files, but that may be too opinionated because the top level is an array
Merge attempt:
```sh
yaml m -x ~/.hal/config setup/projects/config 
```

Source `~/.hal/config`:
```yaml
deploymentConfigurations:
- name: default
  deploymentEnvironment:
    size: SMALL
    type: Distributed
    accountName: k8s-account
    consul:
      enabled: false
    vault:
      enabled: false
```

Override `setup/projects/config`:
```yaml
deploymentConfigurations:
- name: default
  deploymentEnvironment:
    customSizing:
      spin-clouddriver:
        limits:
          cpu: 1
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 512Mi
      spin-deck:
        limits:
          cpu: 250m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 128Mi
```

Since I might be expecting too much from merge, I tried just setting the value as a tree from a read command, which did not work.

```sh
yaml w ~/.hal/config  deploymentConfigurations[0].deploymentEnvironment.customSizing \
    `yaml r setup/projects/config deploymentConfigurations[0].deploymentEnvironment.customSizing`
```

1. is a tree value allowed?
1. any recommendations to accomplish this?
