### ISSUE TITLE
Multiplication of two arrays (`!!seq`) or maps (`!!map`) fails if one of them is empty

### ISSUE THREAD

**Issue by lukasbestle** [mikefarah/yq#1060]
**Describe the bug**
I'm using `yq` to import multiple YAML files into one main file. To merge arrays from multiple files into one, I have defined a `!merge` tag that loads the referenced file and merges the loaded YAML data into the parent node.

However the operation fails with `Error: Cannot multiply !!seq with !!seq` if one of the imported arrays is empty.

Version of yq: 4.16.2
Operating system: macOS 10.15.7
Installed via: Homebrew

**Input Yaml**

`main.yml`:
```yaml
list:
  - !merge merged1.yml
  - !merge merged2.yml
```

`merged1.yml`:
```yaml
- this: is a list item
- this: is another one
```

`merged2.yml`:
```yaml
!!seq

# empty list
```

**Command**
The command you ran:
```
yq eval 'with(.. | select(tag == "!merge"); parent = (parent *+ load(.)) | del(.))' main.yml
```

**Actual behavior**

```plain
Error: Cannot multiply !!seq with !!seq
```

**Expected behavior**

```yaml
list:
  - this: is a list item
  - this: is another one
  # empty list
```

**Additional context**

The following `merged2.yml` works fine:

```yaml
!!seq
- not: empty
```

The following `merged2.yml` causes a `Error: Cannot multiply !!seq with !!null` error, which is to be expected as `yq` doesn't know the data type of the empty file:
```yaml
# empty list
```

**Comment by lukasbestle** [comment]
The example above is close to my actual use case. For easier reproduction here's an even more reduced example:

`main.yml`:
```yaml
list1:
  - this: is a list item
  - this: is another one
list2: !!seq
  # empty list
```

Command:
```
yq eval '.list1 * .list2' main.yml
```

Error output:
```
Error: Cannot multiply !!seq with !!seq
```

**Comment by lukasbestle** [comment]
The same also happens with empty maps:

`main.yml`:
```yaml
map1:
  this: is an object
  and: this is another one
map2: !!map
  # empty map
```

Command:

```
yq eval '.map1 *+ .map2' main.yml
```

Error output:

```
Error: Cannot multiply !!map with !!map
```
