### ISSUE TITLE
Multiplication of two maps drops recursive data

### ISSUE THREAD

**Issue by lukasbestle** [mikefarah/yq#1061]
**Describe the bug**
If two maps are multiplied, they are generally merged recursively. But if one child node is an empty `!!map` or a `null` value, this empty value is set as the result and the other multiplication input is discarded.

Version of yq: 4.16.2
Operating system: macOS 10.15.7
Installed via: Homebrew

**Input Yaml**
`main1.yml`:
```yaml
map1:
  this:
    - is a list
  and:
    - this is another one
map2:
  this:
    - is a new item
  and: !!map
    # this is an empty map
```

`main2.yml`:
```yaml
map1:
  this:
    - is a list
  and:
    - this is another one
map2:
  this:
    - is a new item
  and:
    # this is just a comment
```

**Command**
The command you ran:
```
yq eval '.map1 *+ .map2' main{1,2}.yml
```

**Actual behavior**

```yaml
this:
  - is a list
  - is a new item
and: !!map
# this is an empty map

---
this:
  - is a list
  - is a new item
and:
```

**Expected behavior**

```yaml
this:
  - is a list
  - is a new item
and:
  - this is another one
  # this is an empty map

---
this:
  - is a list
  - is a new item
and:
  - this is another one
  # this is just a comment
```

**Additional context**
Possibly related to #1060.
