### ISSUE TITLE
Environment variable with leading "/" (slash) on windows

### ISSUE THREAD

**Issue by UnleashSpirit** [mikefarah/yq#1063]
**Describe the bug**
Environment variable with leading slash nor working

Version of yq: 4.15.1
Operating system: windows
Installed via: chocolatey

**Input Yaml**

data1.yaml:
```yaml
a:
  b: /foo/bar
```

**Command**
The command you ran:
```
foo=$(yq e -MP '.a.b' data1.yaml) yq e -MP '.a.c = env(foo) | .a.d = strenv(foo)' data1.yaml
```

**Actual behavior**

```yaml
a:
  b: /foo/bar
  c: C:/Program Files/Git/foo/bar
  d: C:/Program Files/Git/foo/bar
```

**Expected behavior**

```yaml
a:
  b: /foo/bar
  c: /foo/bar
  d: /foo/bar
```

**Additional context**
Run on windows from git bash terminal

EDIT :
Just tried with docker, it work
