### ISSUE TITLE
Support maps for addition

### ISSUE THREAD

**Issue by brenner-tobias** [mikefarah/yq#1069]
**Please describe your feature request.**
I want to add a map to all existing map entries.

**Describe the solution you'd like**
If we have data1.yml like:
(please keep to around 10 lines )

```yaml
ingress:
   - hostname: "ds.example.com"
      service: "http://192.168.1.2"
    - hostname: "fritz.example.com"
      service: "http://192.168.1.1"
```

And we run a command:

```bash
yq e -i '.ingress[] += {"originRequest": {"noTLSVerify": "true"}}' data1.yml
```

it could update data1.yml with the following information

```yaml
ingress:
   - hostname: "ds.example.com"
      service: "http://192.168.1.2"
      originRequest:
         noTLSVerify: true
    - hostname: "fritz.example.com"
      service: "http://192.168.1.1"
      originRequest:
         noTLSVerify: true
```

**Describe alternatives you've considered**
No idea, any suggestions?

** Anything else**
Please see [this snipped](https://jqplay.org/s/F2P2WnNvIw) for an example with `jq`

**Comment by mikefarah** [comment]
`+` in `jq` is just variant of `*` for maps - whereby it does a shallow merge instead of a deep merge. In this case, you could use `*` and still get what you want - (although I haven't added `*=` yet either, will get to it soon).

Until then - this is still possible in `yq` by doing:

```bash
yq e 'with(.ingress[]; . = . * {"originRequest": {"noTLSVerify": "true"}})' file.yaml
```

```yaml
ingress:
  - hostname: "ds.example.com"
    service: "http://192.168.1.2"
    originRequest:
      noTLSVerify: "true"
  - hostname: "fritz.example.com"
    service: "http://192.168.1.1"
    originRequest:
      noTLSVerify: "true"
```
