### ISSUE TITLE
add multiple same keys to the yaml file

### ISSUE THREAD

**Issue by itnazeer** [mikefarah/yq#1070]
**Describe the bug**
Add multiple same keys to the yaml file

I want to add below content in yaml file using yq, I am having issues adding hypen and adding the same keys multiples times in the same yaml file.

```
subjects:
  - kind: User
    name: test
    apiGroup: rbac.authorization.k8s.io
  - kind: User
    name: test1
    apiGroup: rbac.authorization.k8s.io
  - kind: User
    name: test2
    apiGroup: rbac.authorization.k8s.io
```
