### ISSUE TITLE
Merge sequences with anchor

### ISSUE THREAD

**Issue by wbzhang2594** [mikefarah/yq#1072]
I just started to use the yq. But I met a problem of merging sequences. 

There is a yaml file like this. 
file: 1.yml
```yaml
a: &a
  - name: 1
    value: 1
  - name: 2
    value: 2
b: 
  - *a
  - name: 3
    value: 3
```
After run command
```bash
yq e '. | explode(.)' 1.yml
```
I expected to get the "b" like
```yaml
b:
  - name: 1
    value: 1
  - name: 2
    value: 2
  - name: 3
    value: 3
```
However the result is observed like this ( another more deep "-" sequence)
```yaml
b:
  - - name: 1
      value: 1
    - name: 2
      value: 2
  - name: 3
    value: 3
```

Is there any way to get the expected result?

**Comment by mikefarah** [comment]
I don't think you can do that with the yaml standards. Best I could get was

```yaml
a: 
  - &a
    name: 1
    value: 1
  - name: 2
    value: 2
b: 
  - *a
  - name: 3
    value: 3
```

which yielded:

```yaml
a:
  - name: 1
    value: 1
  - name: 2
    value: 2
b:
  - name: 1
    value: 1
  - name: 3
    value: 3
```

Otherwise, you can use `yq` to do it for you:

```yaml
a: 
  - name: 1
    value: 1
  - name: 2
    value: 2
b: 
  - name: 3
    value: 3
```

```bash
yq e '.b = .a + .b' sample.yaml
```

**Comment by caquino** [comment]
I have a similar issue, I'm trying to use yq to workaround GitHub Actions workflows lack of anchors/aliases and such, which increases duplication a lot, if I attempt to use it I receive a similar result as the first example, where it creates it under a sub-level in the main array. Is there any way to overcome that or to flatten the array after merge?


example:
```
dry_test: &dry_test
  - name: Checkout Code
    uses: actions/checkout@v4
  - name: Install go
    uses: actions/setup-go@v4
    with:
      go-version: "1.20"
  - name: Build
    run: go build ./...

name: Test Source Workflow

on:
  pull_request:

jobs:
  first_job:
    steps:
      - *dry_test
      - name: another item to be merged
        uses: actions/another_action@vx

  another_job:
    steps:
      - *dry_test
      - name: another item to be merged
        uses: actions/another_action@vx
```

result:
```yq 'explode(.)' yq.yml

dry_test:
  - name: Checkout Code
    uses: actions/checkout@v4
  - name: Install go
    uses: actions/setup-go@v4
    with:
      go-version: "1.20"
  - name: Build
    run: go build ./...
name: Test Source Workflow
on:
  pull_request:
jobs:
  first_job:
    steps:
      - - name: Checkout Code
          uses: actions/checkout@v4
        - name: Install go
          uses: actions/setup-go@v4
          with:
            go-version: "1.20"
        - name: Build
          run: go build ./...
      - name: another item to be merged
        uses: actions/another_action@vx
  another_job:
    steps:
      - - name: Checkout Code
          uses: actions/checkout@v4
        - name: Install go
          uses: actions/setup-go@v4
          with:
            go-version: "1.20"
        - name: Build
          run: go build ./...
      - name: another item to be merged
        uses: actions/another_action@vx
```
