### ISSUE TITLE
how to change value for a key in yaml file

### ISSUE THREAD

**Issue by rajeshwer** [mikefarah/yq#1081]
**Describe the bug**
dont see docs on how to change value 

Version of yq: 4.17.2
Operating system: mac
Installed via: homebrew

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
expected
data1.yml:
```yaml
users:
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
        args:
          - "token"
```
generated
data2.yml:
```yaml
users:
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      '- token'
```

**Command**
The command you ran:
```
yq eval '.users.user.exec.args|= "- token"' shell.yaml >> shell1.yaml
```
