### ISSUE TITLE
Document structure not preserved when using merge anchors

### ISSUE THREAD

**Issue by plaflamme** [mikefarah/yq#1083]
**Describe the bug**

`yq` will not preserve the original document when a merge anchor is present.

Version of yq: 4.17.2
Operating system: mac
Installed via: brew

**Input Yaml**

`a.yml`:

```yaml
a: &ab
  b: foo
c:
  <<: *ab
```

**Command**

```
yq e '.' a.yml
```

**Actual behavior**

A `!!merge` node is inserted in the document

```yaml
a: &ab
  b: foo
c:
  !!merge <<: *ab
```

**Expected behavior**

The original document should be untouched:

```yaml
a: &ab
  b: foo
c:
  <<: *ab
```
