### ISSUE TITLE
Environment variable nested items function

### ISSUE THREAD

**Issue by aaron-uk** [mikefarah/yq#1087]
**Please describe your feature request.**

I wish I could use yq to split a variable string into an array to use within my code.

As 'variable=a yq evel '.[env(variable)] = "something"' only works at one level nesting, I would like a new function to work with multiple nested paths e.g. 'nested_variable=a.b.c yq evel '.[arrenv(nested_variable)] = "something"' (I have used 'arr' prefix as an example but it could be anything.)

The main reason for this is to have a reusable task for my continuous integration pipeline where the path to the 'tag' in the example below will be in different nested positions in the .yaml file on different projects.

**Describe the solution you'd like**
If we have values.yaml like:

```yaml
project:
  environment:
    PORT: 389
  image:
    repository: project/image
    pullPolicy: Always
    tag: "1.0.0"
```

And we run a command:

```bash
tag_path=project.image.tag yq eval '.[arrenv(tag_path)] = "1.0.1"' -i values.yaml
```

it could output

```yaml
project:
  environment:
    PORT: 389
  image:
    repository: project/image
    pullPolicy: Always
    tag: "1.0.1"
```

I love using yq and this would make it even better!
cheers Aaron
