### ISSUE TITLE
raw-output support 

### ISSUE THREAD

**Issue by jamesongithub** [mikefarah/yq#1088]
**Please describe your feature request.**
It would be nice if yq could support a raw-output (-r) support like jq https://stedolan.github.io/jq/manual/

![image](https://user-images.githubusercontent.com/4452738/151255292-1a7177cc-2e9d-49aa-90a8-91d22c728da1.png)

Note:
- how to questions should be posted in the discussion board and not raised as an issue.
- V3 will no longer have any enhancements.

**Describe the solution you'd like**

given
```yaml
- CidrBlock: 10.0.0.0/16
  CidrBlockAssociationSet:
    - AssociationId: vpc-cidr-assoc-063cb30fc812850a6
      CidrBlock: 10.0.0.0/16
      CidrBlockState:
        State: associated
  DhcpOptionsId: dopt-06e6dc6e9428a25c0
  InstanceTenancy: default
  IsDefault: false
  OwnerId: '120693342179'
  State: available
  VpcId: vpc-09a0b71553fb5b243
- CidrBlock: 10.0.0.0/16
  CidrBlockAssociationSet:
    - AssociationId: vpc-cidr-assoc-0e7bea93aae9b6e56
      CidrBlock: 10.0.0.0/16
      CidrBlockState:
        State: associated
  DhcpOptionsId: dopt-06e6dc6e9428a25c0
  InstanceTenancy: default
  IsDefault: false
  OwnerId: '120693342179'
  State: available
  VpcId: vpc-0c901d75f55b106e8
```

And we run a command:

```bash
yq e '.[] | map(.VpcId) |  flatten' - -r
```

it could output

```yaml
vpc-09a0b71553fb5b243
vpc-0c901d75f55b106e8
```

instead of 
```yaml
- vpc-09a0b71553fb5b243
- vpc-0c901d75f55b106e8
```

**Describe alternatives you've considered**
Or just allow flatten to flatten to a new line delimited list (vs yaml list)

**Additional context**
Maybe this is possible already?
