### ISSUE TITLE
Keys and lists with empty value are missing when converting yaml to property file format.

### ISSUE THREAD

**Issue by Grace-xiao-A** [mikefarah/yq#1090]
Hello,
**Describe the bug**
When I use --outputformat=props to convert yaml file to property file format, it seems some keys and lists with empty value are missing in property file.

Note that any how to questions should be posted in the discussion board and not raised as an issue.

Version of yq: 4.15.1
Operating system: linux
Installed via: binary release

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
...values.yml:

```
eric-cnom-document-database-mg:
  affinity:
    podAntiAffinity: hard
  annotations: {}
  clusterDomain: cluster.local
  enabled: true
  imageCredentials:
    pullSecret: ""
    registry: {}
    repoPath: proj-pc-released
  initConfigMap: {}
  labels: {}
  mongodbExtraFlags: []

```

**Command**
The command you ran:
```
yq eval 'sortKeys(..)' values.yaml --output-format=props > values-props
```

**Actual behavior**
...values-props
eric-cnom-document-database-mg.affinity.podAntiAffinity = hard
eric-cnom-document-database-mg.clusterDomain = cluster.local
eric-cnom-document-database-mg.enabled = true
eric-cnom-document-database-mg.imageCredentials.pullSecret = 
eric-cnom-document-database-mg.imageCredentials.repoPath = proj-pc-released
```

**Expected behavior**

```values-props
eric-cnom-document-database-mg.affinity.podAntiAffinity = hard
eric-cnom-document-database-mg.annotations = 
eric-cnom-document-database-mg.clusterDomain = cluster.local
eric-cnom-document-database-mg.enabled = true
eric-cnom-document-database-mg.imageCredentials.pullSecret = 
eric-cnom-document-database-mg.imageCredentials.registry = 
eric-cnom-document-database-mg.imageCredentials.repoPath = proj-pc-released
eric-cnom-document-database-mg.initConfigMap = 
eric-cnom-document-database-mg.labels =
eric-cnom-document-database-mg.mongodbExtraFlags =

```

**Additional context**
