### ISSUE TITLE
Selecting elements from map could be simplified 

### ISSUE THREAD

**Issue by inianv** [mikefarah/yq#1102]
From what I have seen so far, selecting elements from map using with_entries/select idiom could be simplified by using styles similar to how jq does

```yaml
country:
  name: Australia
  capital: Canberra
  type: Continent
```

And we run a command:

```bash
yq '.country |= with_entries(select(.key == "name" or .key == "capital"))'  yaml
```
to output

```yaml
country:
  name: Australia
  capital: Canberra
```

If it were a JSON, jq could do

```bash
yq -o=json yaml | jq '.country |= {name, capital}'
{
  "country": {
    "name": "Australia",
    "capital": "Canberra"
  }
}
```

Or even use `map_values`

```bash
yq -o=json yaml | jq 'map_values({name, capital})'
{
  "country": {
    "name": "Australia",
    "capital": "Canberra"
  }
}
```

Would be nice to have something similar for yq as well. Use case example from StackOverflow - [Remove certain fields from a YAML map object using yq](https://stackoverflow.com/questions/71062862/remove-certain-fields-from-a-yaml-map-object-using-yq)
