### ISSUE TITLE
multiple assignment mode like sed -f

### ISSUE THREAD

**Issue by turbomam** [mikefarah/yq#1103]
**Please describe your feature request.**
I would like `yq` to have a mode in which multiple assignments are defined in a single text file, just like `sed -f` can be used with a text file containing several substitution patterns

**Describe the solution you'd like**
If we have presidents.yaml like:

```yaml
george_washington:
  name: George Washington
  birthplace: Virginia
  wife: Martha Washington
abraham_lincoln:
  name: George Washington
  birthplace: Kentucky
  wife: Martha Washington
```

And we have history_lesson.txt like

```
.abraham_lincoln.birthplace |= "Kentucky"
.abraham_lincoln.wife |= "Mary Lincoln"
```

And we run a command:

```bash
yq --expressions-file history_lesson.txt presidents.yaml
```

it could output

```yaml
george_washington:
  name: George Washington
  birthplace: Virginia
  wife: Martha Washington
abraham_lincoln:
  name: George Washington
  birthplace: Kentucky
  wife: Mary Lincoln
```

So I wouldn't have to say

```bash
yq e '.abraham_lincoln.birthplace |= "Kentucky"' presidents.yaml | yq e '.abraham_lincoln.wife |= "Mary Lincoln"' presidents.yaml
```

etc.
