### ISSUE TITLE
Always get lexer error

### ISSUE THREAD

**Issue by ognif** [mikefarah/yq#1104]
**Describe the bug**
Installed yq wit snap on Ubuntu system

Start multiple ways:
````
yq version Chart.yaml
yq 'vrsion' 'Chart.yaml'
yq r Chart.yaml version
yq r 'Chart.yaml' 'version'
````

I also tried with other Helm chart yaml files. I always get the error:

````
Error: Parsing expression: Lexer error: could not match text starting at 1:1 failing at 1:2.
	unmatched text: "v"
````

yq 4.18.1
Ubuntu 20.04.3 LTS
Installed with snap

Sample yaml:
````
apiVersion: v1
description: This chart allows quickly deploying the my software
name: my-umbrella
version: 1.0.0

dependencies:
  - name: couchdb
    version: 3.3.4
    repository: file://charts/couchdb
    condition: couchdb.enabled
  - name: common
    version: 1.11.1
    repository: file://charts/common
    condition: mongodb.enabled
  - name: mongodb
    version: 11.0.2
    repository: file://charts/mongodb
    condition: mongodb.enabled
````
