### ISSUE TITLE
Allow modification of single document in a multi-document file by match

### ISSUE THREAD

**Issue by dennisjac** [mikefarah/yq#1117]
**Please describe your feature request.**
Given the following yaml file:
```yaml
kind: A
metadata:
  name: x
value: 1
---
kind: B
metadata:
  name: y
value: 2
```
It would be nice to be able to express the following: "In the document that matches kind=B and metadata.name=y set value to 3" resulting in the following output:
```yaml
kind: A
metadata:
  name: x
value: 1
---
kind: B
metadata:
  name: y
value: 3
```
It is a common case that Kubernetes project provide their manifests as large multi-document files and sometimes these files need to be patched to make the work in specific environments.

**Describe the solution you'd like**
Right now for a single yaml document this is easily accomplished using something like:
`yq '.value = 3' test.yaml`

What would need to be added is a selector that finds the document to apply this change to based on a match.

**Describe alternatives you've considered**
There exists a "document_index" operator according to the docs that allows selecting a document by index but this doesn't seem to really allow the kind of operation mentioned above.
