### ISSUE TITLE
YQ unable to parse value mixing  {{ yaml_var }}-string

### ISSUE THREAD

**Issue by larkoie** [mikefarah/yq#1126]
**Bad file error  when mixing yaml {{ var }} with string**
When yq is parsing a YAML file containing values likes {{ my_var }}-something it's not able to understand as a value and returns:
Error: bad file 'my.yaml' : yaml: line x: did not find expected key.
(note that line x is not the line that contains {{ my_var }}-something )

Version of yq: 4.20.2
Operating system: Linux
Installed via: binary copy

**Input Yaml**
test.yaml:
```yaml
---
global:
  metadata:
    labels:
      my-first-label: web
      my-second-label: db
      my-third-label: {{ my_var }}-something
local:
  issuer: tester
```

**Command**
The command you ran:
```
yq '.global.metadata.labels.my-first-label' test.yml
```

**Actual behavior**

```yaml
Error: bad file 'test.yaml': line 3: did not find expected key
```

**Expected behavior**

```yaml
web
```

**Additional context**
If i write it like this it will work: 
.```yaml
      my-third-label: " {{my_var }}-something"
```
But normally the syntax without double quotes around it should be accepted as it's an accepted YAML syntax.
