### ISSUE TITLE
decode properties file with version prior to 4.18

### ISSUE THREAD

**Issue by jiezhang0917** [mikefarah/yq#1128]
**Describe the bug**
I'm trying to parse a properties file to yaml. Following this guide https://mikefarah.gitbook.io/yq/usage/properties#decode-properties, I got error `Error: unknown shorthand flag: 'p' in -p=props` when run `yq -p=props e sample.properties`

Version of yq: 4.16.2
Operating system: Alpine Linux v3.14
Installed via: wget

**Input Properties file**
sample.properties:
```
# comments on values appear
person.name = Mike

# comments on array values appear
person.pets.0 = cat
person.food.0 = pizza
```

**Command**
The command I ran:
```
yq -p=props e sample.properties
```

**Actual behavior**
Error: unknown shorthand flag: 'p' in -p=props

**Expected behavior**
Output
```yaml
person:
    name: Mike # comments on values appear
    pets:
        - cat # comments on array values appear
    food:
        - pizza
```

**Additional context**
It's a little bit hard for us to upgrade to newer version of `yq`. So hope you can help me figure out how to make this work with the 4.16 version. Thank you!
