### ISSUE TITLE
yq recursive search skips first configuration

### ISSUE THREAD

**Issue by zfrhv** [mikefarah/yq#1129]
**Describe the bug**
yq skips the first object configuration in recursive search.

Version of yq: 4.19.1
Operating system: rhel 8.4
Installed via: wget from url

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
values.yaml:
```yaml
prometheus:
  prometheusSpec:
    image:
      repository: quay.io/prometheus/prometheus
prometheus:
  monitor:
    enabled: false
```

**Command**
The command you ran:
```
cat list.yaml | yq e '[.. | select(has("repository"))]'
```

**Actual behavior**

```yaml
[]
```

**Expected behavior**

```yaml
- repository: quay.io/prometheus/prometheus
```

**Additional context**
