### ISSUE TITLE
Pretty print just fixes indentation and doesn't convert/update any quoting style or collapse multiline strings

### ISSUE THREAD

**Issue by manuel-koch** [mikefarah/yq#1131]
**Please describe your feature request.**
Limit pretty-print functionality to just fix indentation, i.e. don't convert any quoting style and don't collapse multiline strings.

Current implementation will fix indentations _and_ collapse multiline text.

**Describe the solution you'd like**
If we have `some.yml` like:

```yaml
country: Australia
cities:
      - Sydney
      - Batemans Bay
description: |
    Is a pretty country
    with lots of animals
    of different kinds.
```

And we run a command:

```bash
yq --prettyPrint --prettyJustIndent --inplace some.yml
```

it could output

```yaml
country: Australia
cities:
  - Sydney
  - Batemans Bay
description: |
  Is a pretty country
  with lots of animals
  of different kinds.
```
