### ISSUE TITLE
Update/Rename Key using Environment Variables

### ISSUE THREAD

**Issue by varundmishra** [mikefarah/yq#1134]
**Please describe your feature request.**
A clear and concise description of what the request is and what it would solve. 
yq should be able to update keys using environment variables

**Describe the solution you'd like**
If we have data1.yml like:
```yaml
vpc:
  id: "vpcid"  # (optional, must match VPC ID used for each subnet below)
  subnets:
    # must provide 'private' and/or 'public' subnets by availibility zone as shown
    private:
      regionaza:
        id: "subnetid"

      regionazb:
        id: "subnetid"
```

And we run a command:

```bash
NG_AZ1="us-west-1a" '.vpc.subnets.private.env(NG_AZ1) = .vpc.subnets.private.regionaza | del(.vpc.subnets.private.regionaza)'
or
NG_AZ1="us-west-1a" '.vpc.subnets.private.strenv(NG_AZ1) = .vpc.subnets.private.regionaza | del(.vpc.subnets.private.regionaza)'
```

it could output

```yaml
vpc:
  id: "vpcid"  # (optional, must match VPC ID used for each subnet below)
  subnets:
    # must provide 'private' and/or 'public' subnets by availibility zone as shown
    private:
      us-west-1a:
        id: "subnetid"

      regionazb:
        id: "subnetid"
```
