### ISSUE TITLE
Delete a key in YAML

### ISSUE THREAD

**Issue by Yatharth0045** [mikefarah/yq#1135]
**Please describe your feature request.** 
I wish I could use yq to delete a key  

**Describe the solution you'd like**
If we have data1.yml like:

```yaml
name: Yatharth
country: India
age: 27
```

And we run a command:

```bash
yq delete '.age'
```

it could output

```yaml
name: Yatharth
country: India
```
