### ISSUE TITLE
Add a variable to existing array

### ISSUE THREAD

**Issue by jindov** [mikefarah/yq#1141]
**Please describe your feature request.**
I wish to have an easy way to add a $VAR in to a existing array. For example: I read from a source.yaml and have an output then I can use this output as an element of a yq add command

**Describe the solution you'd like**
If we have source.yml like:
(please keep to around 10 lines )

```yaml
env:
  - name: KEY1
    value: VALUE1
  - name: KEY2
    value: VALUE2
```

and target.yaml
```yaml
spec:
  template:
    spec:
      containers:
      - image: myimage:latest
         ports:
         - containerPort: 8000
```

And we read env in file source.yaml

```bash
yq '.env' source.yaml
```

it could output

```yaml
- name: KEY1
  value: VALUE1
- name: KEY2
  value: VALUE2
```

Then we can use it as an input of another yq command to add it into an existing array in target.yaml

```bash
yq '.spec.template.spec.containers + $(yq ".env" source.yaml)' target.yaml
```

Expected:
```
spec:
  template:
    spec:
      containers:
      - image: myimage:latest
         ports:
         - containerPort: 8000
         env:
         - name: KEY1
            value: VALUE1
         - name: KEY2
            value: VALUE2
```

But got error

```
Error: Parsing expression: Lexer error: could not match text starting at 1:34 failing at 1:36.
	unmatched text: "$("
```
