### ISSUE TITLE
Replace a string with a star 

### ISSUE THREAD

**Issue by MattCGI** [mikefarah/yq#1150]
**Describe the bug**
Hello, I am facing an issue with yq (yq (https://github.com/mikefarah/yq/) version 4.22.1) on Debian 4.19.

I am trying to modify strings in a yaml with * in it.

The aim is to prefix all my paths with /portail.

But, as you can see, I have 2 stars at the end of the string without understanding why...

**Input Yaml**
```
_format_version: "1.1"
services:
- routes:
  - paths:
    - /ws/maroute*
  - paths:
    - /csp/test*
  - paths:
    - /wssoap/route*
  - paths:
    - /wsrest/route*
```

exportWithYQ.yaml:
```
_format_version: "1.1"
services:
  - routes:
      - paths:
          - /portail/ws/maroute**
      - paths:
          - /portail/csp/test**
      - paths:
          - /portail/wssoap/route**
      - paths:
          - /portail/wsrest/route**

```

**Command**
The command I ran:
```
yq e '.services[].routes[].paths[] |= sub(.,"/portail"+.)' export.yaml > exportWithYQ.yaml
```

What am I doing wrong ?

Thanks a lot.

Regards,

Matthieu.
