### ISSUE TITLE
Issue updating a value in a nested list 

### ISSUE THREAD

**Issue by nesth** [mikefarah/yq#1151]
**Describe the bug**
Since version 4.20.2 yq is not updating a values within a nested list. 

Version of yq: >4.20.1
Operating system: mac/linux
Installed via: docker/nixpkgs

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
data1.yml:
```yaml
apiVersion: v2
name: mychart
version: 0.1
dependencies:
  - name: redis
    version: 1.0
```

**Command**
The command you ran:
```
yq eval-all '(.dependencies[] | select(.name == "redis")) as $d | $d.version = "2.0"' data1.yaml
```

**Actual behavior**

```yaml
apiVersion: v2
name: mychart
version: 0.1
dependencies:
  - name: redis
    version: 1.0
```

**Expected behavior**

```yaml
apiVersion: v2
name: mychart
version: 0.1
dependencies:
  - name: redis
    version: 2.0
```

**Additional context**
This was working up until version 4.20.1
