### ISSUE TITLE
merge strips out data silently

### ISSUE THREAD

**Issue by shortjared** [mikefarah/yq#116]
```yaml
AWSTemplateFormatVersion: "2010-09-09"
Description: Example cfn

Parameters:
Resources:
  ExampleTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      TopicName: my-example-topic

Outputs:
  MyTopicArn:
    Description: my topic arn
    Value: !Ref ExampleTopic
``` 

This is seemingly valid yaml, works great with AWS. They are leveraging custom yaml classes to allow this to work, and resolve it on their end (I do know that there is some schema requirements within yaml to make the extensions work with other parsers. ex: [cloudformation-yaml](https://github.com/trek10inc/cloudformation-schema-js-yaml).

If I do a merge... (or even read), those custom classes get stripped out with zero warning.
```yaml
AWSTemplateFormatVersion: 2010-09-09
Description: Example cfn
Parameters: null
Resources:
  ExampleTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: my-example-topic
Outputs:
  MyTopicArn:
    Description: my topic arn
    Value: ExampleTopic
```

Is it possible to allow simply pass-through here?
