### ISSUE TITLE
Apostrophe added in array

### ISSUE THREAD

**Issue by pedrojreis** [mikefarah/yq#1161]
**Describe the bug**
yq adding apostrophe onto array.
I have a GHA variable that contains [a,b,c,d] and want to write it onto .body.1.attributes.options and it's adding apostrophe .
I've tried different styles, but to no avail.

**Version of yq:** 4.21.1
**Operating system:** Linux
**Installed via:** docker
**Testing via:** Act but GHA outputs the same

**Input Yaml**
I Want to replace the entire array, so the += will not work for my usecase.
```yaml
name: "Yaml File"

body:
  - type: markdown
    attributes:
      value: |
        Some Description
  - type: dropdown
    id: files
    attributes:
      label: Select an option
      multiple: true
      options: [a,b]

```

**Command**
The command you ran:
```
yq -i '.body.1.attributes.options = "[a,b,c,d]"' .pathToFile/file.yml
```

**Actual behavior**

```yaml
name: "Yaml File"

body:
  - type: markdown
    attributes:
      value: |
        Some Description
  - type: dropdown
    id: files
    attributes:
      label: Select an option
      multiple: true
      options: '[a,b,c,d]'

```

**Expected behavior**

```yaml
name: "Yaml File"

body:
  - type: markdown
    attributes:
      value: |
        Some Description
  - type: dropdown
    id: files
    attributes:
      label: Select an option
      multiple: true
      options: [a,b,c,d]

```

Is there any command that i'm not aware of?

Thanks in advance
