### ISSUE TITLE
Unable to get map content of specific files: Error: Bad expression, please check expression syntax

### ISSUE THREAD

**Issue by MartinDelille** [mikefarah/yq#1196]
**Describe the bug**

I have the following error when trying to look the content of a YAML file although it works on an almost identical one:
`Error: Bad expression, please check expression syntax`
Version of yq: 4.24.5
Operating system: windows
Installed via: scoop

**Input Yaml**
I have two yaml files:

[recipes/quazip/config.yml](https://github.com/conan-io/conan-center-index/blob/master/recipes/quazip/config.yml):
```yaml
versions:
  "1.3":
    folder: all
  "1.2":
    folder: all
  "1.1":
    folder: all
```

On this first one, the command `yq '.versions["1.3"]' recipes/quazip/config.yml` output the expected result:
```yaml
folder: all
```

Unfortunately, it doesn't work on this one:
[recipes/qt/config.yml](https://github.com/conan-io/conan-center-index/blob/master/recipes/qt/config.yml):
```yaml
versions:
  "5.15.2":
    folder: 5.x.x
  "5.15.3":
    folder: 5.x.x
  "6.0.4":
    folder: 6.x.x
  "6.1.3":
    folder: 6.x.x
  "6.2.4":
    folder: 6.x.x
  "6.3.0":
    folder: 6.x.x
```

**Command**
The command you ran:
```
yq '.versions["6.3.0"]' recipes/qt/config.yml
```

**Actual behavior**

```
Error: Bad expression, please check expression syntax
```

**Expected behavior**

```yaml
folder: 6.x.x
```

Am I doing something wrong ?
