### ISSUE TITLE
inconsistent output for apparently equivalent array-appending code

### ISSUE THREAD

**Issue by jhnc** [mikefarah/yq#1214]
**Describe the bug**

Explicitly constructing an array concatenation gives a different result to use of `+=`.

Version of yq: 4.25.1
Operating system: linux
Installed via: https://github.com/mikefarah/yq/releases/download/v4.25.1/yq_linux_amd64

**Input Yaml**
data.yml:
```yaml
s:
  - x: a
    y: aaa
  - x: b
    y: bbb
  - x: a
    y: ccc
```

**Command**
The command you ran:
```
yq '{ "s" : [ .s[], ( .s[] | select(.x=="a") | .x="A" ) ] }' <data.yml >res1.yml
yq   '.s += [         .s[] | select(.x=="a") | .x="A"   ]'   <data.yml >res2.yml
```

**Actual behavior**

res1.yml
```yaml
s:
  - x: A
    y: aaa
  - x: b
    y: bbb
  - x: A
    y: ccc
  - x: A
    y: aaa
  - x: A
    y: ccc
```

**Expected behavior**

res2.yml
```yaml
s:
  - x: a
    y: aaa
  - x: b
    y: bbb
  - x: a
    y: ccc
  - x: A
    y: aaa
  - x: A
    y: ccc
```

**Additional context**
kislyuk/yq produces `res2.yml` for both code (and a third different result with only 4 elements for the first code if the parentheses are elided, presumably due to higher precedence of comma)
