### ISSUE TITLE
Keep indentation of arrays during update

### ISSUE THREAD

**Issue by felipecrs** [mikefarah/yq#1216]
**Please describe your feature request.**

Sorry, I searched but I did not find any similar issue.

Consider a YAML file like:

```yaml
apiVersion: v2
appVersion: "0.1.0"
description: A Helm chart
name: mychart
version: "0.1.0"
dependencies:
- name: anotherchart
  version: ">0.0.0-0"
```

And what happens is:

```console
$ yq '(.dependencies[] | select(.name == "anotherchart") | .version) |= "1.1.1"' Chart.yaml
apiVersion: v2
appVersion: "0.1.0"
description: A Helm chart
name: mychart
version: "0.1.0"
dependencies:
  - name: anotherchart
    version: "1.1.1"
```

```diff
- - name: anotherchart
-   version: ">0.0.0-0"
+   - name: anotherchart
+     version: "1.1.1"
```

**Describe the solution you'd like**

I want the output to retain the original indentation of the array, i.e.:

```yaml
apiVersion: v2
appVersion: "0.1.0"
description: A Helm chart
name: mychart
version: "0.1.0"
dependencies:
- name: anotherchart
  version: "1.1.1"
```

**Describe alternatives you've considered**
I haven't found any way around it.

**Additional context**
N/A
