### ISSUE TITLE
Adding a child object to a nested object erases the rest of the document

### ISSUE THREAD

**Issue by jxn** [mikefarah/yq#1224]
**Describe the bug**
Apologies if I'm misusing the project, but as I understand it this seems to be a bug....
When doing an in-place edit of a yaml document, I expect be able to add a new object to a node without destroying the resto fo the document
`bash

`

Note that any how to questions should be posted in the discussion board and not raised as an issue.

Version of yq: 4.25.1
Operating system: linux
Installed via: binary download from github

**Input Yaml**
values.yml:
```yaml
controller:
  service:
    annotations:
        service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
        service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
```

**Command**
The command you ran:
```bash
yq e '.controller.service.annotations + {"service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags": "somethingelse"}' values.yaml -i
```

**Actual behavior**

```yaml
service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: somethingelse
```

**Expected behavior**

```yaml
controller:
  service:
    annotations:
        service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
        service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
        service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: somethingelse
```

**Additional context**
Hopefully I'm not just doing the wrong command, but it seems all of the structure of the document disappears when appending this new object to the node.  The new object is added, but the `controller.service.annotations` parent nodes are completely wiped out.  I have alos tested this with larger documents, and it seems the only things that survive are the child objects from the targeted node.
