### ISSUE TITLE
Extracting specific kind object with YQ

### ISSUE THREAD

**Issue by faraktingi** [mikefarah/yq#1225]
hello,

I'm looking how it is possible with yq to extract from a helm template yaml file all entries corresponding to a specific kind.
for example I have in my file:

```
...
---
# Source: tmp/secret1.yaml
apiVersion: v1
kind: Secret
metadata:
  name: secret1
  namespace: ns1
type: Opaque
data:
  d1s1: d1s1
stringData:
  sd1s1: sd1s1
---
# Source: tmp/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap1
  namespace: ns1
data:
  d1cm: d1cm
---
# Source: tmp/secret2.yaml
apiVersion: v1
kind: Secret
metadata:
  name: secret2
  namespace: ns2
type: Opaque
data:
  d1s2: d1s2
stringData:
  sd1s2: sd1s2
---
...
```

So the idea is to extract only all `kind: Secret` name + data + stringdata with its keys/values.

Output could be something like:

```
---
name: secret1
data:
  d1s1: d1s1
stringData:
  sd1s1: sd1s1
---
name: secret2
data:
  d1s2: d1s2
stringData:
  sd1s2: sd1s2
```

Thanks a lot for any help.
