### ISSUE TITLE
Option to remove prefix dash/-/hyphen when using `keys`

### ISSUE THREAD

**Issue by LarsBingBong** [mikefarah/yq#1228]
I'm parsing this YAML construct

```yaml
vmrules:
  #### MASTERS
  - fest-fest-master-0:
      nets:
        - name: spas_network
          dns: 192.168.2.21,192.168.2.22
          gateway: 192.168.220.1
          ip: 192.168.233.71
          mask: 255.255.254.0
          nic: ens192
```
with this `yq` query.

`yq e '.vmrules[] | select(.fest-fest-master-*.nets[].ip == "192.168.233.71") | keys' ./fest-fest.yml`

There are several nodes/vm's in the `.vmrules` section. Therefore the `wildcard` match on the node name after the first pipe. The result is good - the query works.

Result: `- fest-fest-master-0`

**Describe the solution you'd like**

I would like an option to the `keys` `operator`  where one can get rid of the `dash | - | hyphen`. This so that one do not have to remove the dash with some other tool.

**Describe alternatives you've considered**
Just to remove the `-` with some other tool.
