### ISSUE TITLE
comment is visible when some feature like pick or length

### ISSUE THREAD

**Issue by gabs77** [mikefarah/yq#1231]
Comment is visible when some feature like pick or length

Version of yq: 4.25.X
Operating system: linux/windows

**Input Yaml**
data1.yml:
```yaml
# --------------------------------------------------
# It's a test with comment
# --------------------------------------------------
test:
  - name: a
  - name: b
  - name: c
groups:
  - name: a
  - name: b
  - name: c
  - name: c
```
data2.yml:
```yaml
# --------------------------------------------------
# It's a test with comment
# --------------------------------------------------
groups:
  - name: d
```
**Command**
The command you ran:
```
 yq '[ .groups[].name | select(.=="a") ] | length' data1.yml
```

**Actual behavior**

```yaml
# --------------------------------------------------
# It's a test with comment
# --------------------------------------------------
1
```

**Expected behavior**

```yaml
1
```

**Additional context**
Same problem with the pick feature
yq 'pick(["groups"]) | explode(.) as $item ireduce ({}; . *+ $item)' data1.yml data2.yml --no-doc --prettyPrint

**Actual behavior**

```yaml
# --------------------------------------------------
# It's a test with comment
# --------------------------------------------------
groups:
  - name: a
  - name: b
  - name: c
  - name: c
# --------------------------------------------------
# It's a test with comment
# --------------------------------------------------
groups:
  - name: d
```

**Expected behavior**

```yaml
groups:
  - name: a
  - name: b
  - name: c
  - name: c
groups:
  - name: d
```
