### ISSUE TITLE
print from leaf to parent

### ISSUE THREAD

**Issue by 1Mark** [mikefarah/yq#1244]
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```
is there a way to specify 
`name: nginx` and then it returns i.e the node specified and it's parent(s)
```
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```

**Comment by mikefarah** [comment]
Not that I can think of immediately - though I'm not sure how it would know to show 'replicas', "selectors" and other parent siblings...

There could be some clever way of using the "path" operator (which returns an array of the yaml path to get to the target)...

**Comment by mikefarah** [comment]
Ooh got it:

```
yq ' {} as $o | 
  (.. | select(tag == "!!map" and .name == "nginx")) as $t | 
  (($t | path | .[]) as $p ireduce($o; .[$p]))=$t  | 
   $o' 
file.yaml
```

Explanation:
- create a blank map, this will be our output `$o`
- find the target `$t`
- reduce the target path by traversing into the empty map. This will automatically create the object as it traverses
- assign the result (which will be the full target path) to the target value
- pipeout `$o`, the desired output

**Comment by mikefarah** [comment]
Forgot to put the result in:

```yaml
pec:
  template:
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80

```
