### ISSUE TITLE
Removes blank lines, add extra indentation to comments during editing

### ISSUE THREAD

**Issue by notorand-it** [mikefarah/yq#1248]
**Describe the bug**
Removes blank lines, indents comments during editing.

This is the demo file:
```
Something:
# Something comment

  Other:
  # Other comment

    X: Y
```

This is the command:

yq -i '.Something.Other.Z = "W"'  yaml.yaml 

It should add another propery to "Other".

Actual Result:
```
Something:
  # Something comment
  Other:
    # Other comment
    X: Y
    Z: W
```

Expected result:
```
Something:
# Something comment

  Other:
  # Other comment

    X: Y
    Z: W
```

Version of yq: 4.25.2
Operating system: ArchLinux x86_64
Installed via: repository community/go-yq 4.25.2-1
