### ISSUE TITLE
eval-all removes first comment on multiple documents file

### ISSUE THREAD

**Issue by GBwandersoncamargo** [mikefarah/yq#1258]
**Describe the bug**

When I execute `eval-all` with multiple documents, if first file has a comment on the first line (like `helm template` output), the comment disappears.

Version of yq: 4.25.3
Operating system: linux
Installed via: binary release

**Input Yaml**

data.yml:
```yaml
---
# foobar-a
foobar: a
---
# foobar-b
foobar: b
```

**Command**

```
yq eval-all '[.]' data.yaml
```

**Actual behavior**

```yaml
- foobar: a
- # foobar-b
  foobar: b
```

**Expected behavior**

```yaml
- # foobar-a
  foobar: a
- # foobar-b
  foobar: b
```

**Additional context**

Also, I don't know if comments inside elements of arrays are allowed.
