### ISSUE TITLE
How to add empty keys?

### ISSUE THREAD

**Issue by amg-web** [mikefarah/yq#1304]
I need to add several  blockes with empty keys.
```
kurento:
  - ip: 3.3.3.113
    url: ws://127.0.0.1:8888/kurento
    # mediaType: (main|audio|content)
    ipClassMappings:
      local:
      private:
      public:
    options:
      failAfter: 5
      request_timeout: 30000
      response_timeout: 30000
    mediaType: main
  - ip: 3.3.3.113
    url: ws://127.0.0.1:8889/kurento
    mediaType: audio
    ipClassMappings:
      local:
      private:
      public:
    options:
      failAfter: 5
      request_timeout: 30000
      response_timeout: 30000
  - ip: 3.3.3.113
    url: ws://127.0.0.1:8890/kurento
    mediaType: content
    ipClassMappings:
      local:
      private:
      public:
    options:
      failAfter: 5
      request_timeout: 30000
      response_timeout: 30000

```
I used:
```
  for i in `seq 0 2`; do
    yq -i ".kurento[$i].ip = \"$IP\"" $KURENTO_CONFIG
    yq -i ".kurento[$i].url = \"ws://127.0.0.1:$(($i + 8888))/kurento\"" $KURENTO_CONFIG
    yq -i ".kurento[$i].mediaType = \"${MEDIA_TYPE[$i]}\"" $KURENTO_CONFIG
    yq -i ".kurento[$i].ipClassMappings.local = \" \" " $KURENTO_CONFIG
    yq -i ".kurento[$i].ipClassMappings.private = \" \" " $KURENTO_CONFIG
    yq -i ".kurento[$i].ipClassMappings.public = \" \" " $KURENTO_CONFIG
    yq -i ".kurento[$i].options.failAfter = 5" $KURENTO_CONFIG
    yq -i ".kurento[$i].options.request_timeout = 30000" $KURENTO_CONFIG
    yq -i ".kurento[$i].options.response_timeout = 30000" $KURENTO_CONFIG
  done
```
but always get something like:
```
ipClassMappings:
      local: " "
      private: " "
      public: " "
```

if use nothing the file is fully erased.
