### ISSUE TITLE
yq -i Error: open /tmp/temp*: no such file or directory

### ISSUE THREAD

**Issue by austincunningham** [mikefarah/yq#1305]
**Describe the bug**

using the `yq -i` command throws an error.   
```bash
Error: open /tmp/temp*:  no such file or directory
```

reinstalling 4.26.1 fixes the issue

Note that any how to questions should be posted in the discussion board and not raised as an issue.

Version of yq: yq (v4/stable) 4.26.1
Operating system: linux
Installed via: snap

**Input Yaml**

Trying to patch the spec object with the -i flag seems like tmp file is not created/found to allow the edit, system /tmp is only showing 2% usage
catalogSource.yaml:
```yaml
spec:
  sourceType: grpc
  image: quay.io/austincunningham/integreatly-index:1.14.0
```

**Command**
The command you ran:
```
 yq -i '.spec.test="TEST"' catalogSource.yaml
```

**Actual behavior**

```yaml
Error: open /tmp/temp2289380881: no such file or directory
```

**Expected behavior**

```yaml
spec:
  sourceType: grpc
  image: quay.io/austincunningham/integreatly-index:1.14.0
  test: TEST
```

**Additional context**
Reinstall binary seems to fix the issue 
```bash
~ snap remove yq
~ snap install yq --channel=v4/stable
yq (v4/stable) 4.26.1 from Mike Farah (mikefarah) installed

# run the command again
~ yq -i '.spec.test="TEST"' catalogSource.yaml
~ cat catalogSource.yaml 
spec:
  sourceType: grpc
  image: quay.io/austincunningham/integreatly-index:1.14.0
  test: TEST
```
Not sure how to reproduce, you may close if you wish seems to happen after `yq` has been used for a while this is the second time I have seen this issue. Posting so something shows up the next time I go looking for it.
