### ISSUE TITLE
Custom indent for lists

### ISSUE THREAD

**Issue by kaovilai** [mikefarah/yq#1309]
**Please describe your feature request.**
A clear and concise description of what the request is and what it would solve. 
Eg. I wish I could use yq to [...]
have custom indent for list/arrays.

related to #194

Note:
- how to questions should be posted in the discussion board and not raised as an issue.
- V3 will no longer have any enhancements.

**Describe the solution you'd like**
If we have data1.yml like:
(please keep to around 10 lines )

```yaml
country: Australia
  province: space
citizen:
  - 1
  - 2
```

And we run a command:

```bash
yq --no-list-indent '.' data1.yml
```

it could output

```yaml
country: Australia
  province: space
citizen:
- 1
- 2
```

**Describe alternatives you've considered**
```bash
yq --list-indent 0 '.' data1.yml
```
**Additional context**
Would like to avoid indent changes to original file.
https://github.com/openshift/oadp-operator/pull/796
