### ISSUE TITLE
YAML property names get mixed up if one contains `*`

### ISSUE THREAD

**Issue by qqilihq** [mikefarah/yq#1323]
**Describe the bug**

YAML property names get replaced if one of them contains an asterisk `*` when running the “merge YAML” example.

Below, this is the case for `image/*`. Note that for this bug report, I’m “merging” just a single YAML to illustrate the issue.

Version of yq: 4.27.3
Operating system: mac
Installed via: homebrew

**Input Yaml**
data1.yml:
```yaml
example:
  image/webp:
  image/svg+xml:
  image/jpeg:
  image/png:
  image/*:
```

**Command**
The command you ran:
```
yq ea '. as $item ireduce ({}; . * $item )' data1.yml
```

**Actual behavior**

```yaml
example:
  image/*:
  image/*:
  image/*:
  image/*:
```

**Expected behavior**

```yaml
example:
  image/webp:
  image/svg+xml:
  image/jpeg:
  image/png:
  image/*:
```

**Additional context**
