### ISSUE TITLE
sampling using pick from the root object does not work

### ISSUE THREAD

**Issue by levin-kelevra** [mikefarah/yq#1334]
**Describe the bug**
sampling using pick from the root object does not work

Version of yq: 4.27.5
Operating system: linux
Installed via: release

**Input Yaml**
data1.yml:
```yaml
metadata:
  labels:
    app: postgres
    index: "1"
    replicationRole: primary
  name: postgres-1
  namespace: default
spec:
  podManagementPolicy: OrderedReady
  replicas: 0
```

**Command**
```
kubectl get sts postgres-1 -o yaml | yq e '. | pick(["metadata.name", "metadata.namespace", "spec.replicas"])' -
```

**Actual behavior**

```yaml
{}
```

**Expected behavior**

```yaml
metadata:
  name: postgres-1
  namespace: default
spec:
  replicas: 0
```

**Additional context**
