### ISSUE TITLE
Multiple anchor will get a wrong result

### ISSUE THREAD

**Issue by everyx** [mikefarah/yq#1343]
**Describe the bug**
`eval` command with `del` operator is not worked as expected when yaml contain multiple nested anchors.

Version of yq: yq (https://github.com/mikefarah/yq/) version 4.27.5
Operating system: linux
Installed via: pacman package manager (Archlinux)

**Input Yaml**

input.yaml:
```yaml
x-proxy-rules-dns: &proxy-rules-dns
  domain:
    - githubusercontent.com

x-proxy-rules: &proxy-rules
  <<: *proxy-rules-dns
  geoip:
    - telegram

route:
  rules:
    - outbound: proxy
      <<: *proxy-rules
```

**Command**
The command you ran:
```
cat input.yaml | yq -e "del(.x-*)" -o json
```

**Actual behavior**

```json
{
  "route": {
    "rules": [
      {
        "outbound": "proxy",
        "<<": {
          "domain": [
            "githubusercontent.com"
          ]
        },
        "geoip": [
          "telegram"
        ]
      }
    ]
  }
}
```

**Expected behavior**
```json
{
  "route": {
    "rules": [
      {
        "outbound": "proxy",
        "domain": [
          "githubusercontent.com"
        ],
        "geoip": [
          "telegram"
        ]
      }
    ]
  }
}
```

**Additional context**
`cat input.yaml | yq -o json` is ok.
