### ISSUE TITLE
When converting multi document file to list of maps, leading comments are dropped

### ISSUE THREAD

**Issue by zachary-povey** [mikefarah/yq#1358]
**Describe the bug**
When converting a file containing multiple yaml documents into a list of maps, any leading comments on the first document are lost.

Version of yq: 4.27.5
Operating system: mac
Installed via: brew

**test.yml:**
```yaml
---
# leading comment doc 1
a: 1
---
# leading comment doc 2
a: 2
```
**Command**
The command I ran:
```
yq ea '[.]' test.yaml 
```

**Actual behavior**

```yaml
- a: 1
- # leading comment doc 2
  a: 2
```

**Expected behavior**

```yaml
- # leading comment doc 1
  a: 1
- # leading comment doc 2
  a: 2
```

**Additional context**
Possibly Related To: https://github.com/mikefarah/yq/issues/1354

Happens with or without leading `---` on first doc.

**Workaround**
If anyone comes to this and needs a workaround my current total hack is to prepend an empty document into the file contents before, and then remove any empty maps from the list after.
