### ISSUE TITLE
Incorrect line_comment placement for dictionaries.

### ISSUE THREAD

**Issue by landure** [mikefarah/yq#1365]
When adding a line comment to a dictionary entry, the line comment is outputted on the next entry after the dictionary entry. 

Version of yq: 4.27.5
Operating system: Ubuntu 22.04 Jammy Jellyfish
Installed via: binary release

Setting a line comment with this command:

```bash
echo "volumes:
  beehive-conf:
    driver: local
services:
  - beehive" \
  | yq 'eval' ".volumes.beehive-conf line_comment=\"Beehive configuration volume\""
```

the output is:

```yaml
volumes:
  beehive-conf:
    driver: local
services: # Beehive configuration volume
  - beehive
```

the output should be:

```yaml
volumes:
  beehive-conf:  # Beehive configuration volume
    driver: local
services:
  - beehive
```
