### ISSUE TITLE
set multi string is not expected

### ISSUE THREAD

**Issue by cyxinda** [mikefarah/yq#1369]
**Describe the bug**
when I run `printf -v m "cat\ndddd " ; m="$m" yq -n '.a = strenv(m)'`,It will print out `a: "cat\ndddd "`.
It is not expected as follow:
root@yong:/tmp/yaml# printf -v m "cat\ndddd " ; m="$m" yq -n '.a = strenv(m)'
a: "cat\ndddd "
but when I add any string(not blankspace) to the string tail,it would be OK.
root@yong:/tmp/yaml# printf -v m "cat\ndddd dd" ; m="$m" yq -n '.a = strenv(m)'
a: |-
  cat
  dddd dd

root@yong:/tmp/yaml#

the behavior above is strange.
If there are more characters in the string, his behavior is even more unpredictable,as follow:

root@yong:/tmp/yaml#   printf -v m "pull -u __pullUser -p __pullPwk -h __pullHost -s __basePath/resource/__project/kata/files/google/corpus/k9/k865138k17f1958502ek060ecfeeb6 -t /root/service/krimo-nlu-smalltalk/mokel/vocab.txt\npull -u __pullUser -p __pullPwk -h __pullHost -s __basePath/resource/__project/kata/files/google/corpus/06/9b6a451a7941f932e5f234kcaa9e43 -t /root/service/krimo-nlu-smalltalk/mokel/pytorch_mokel.bin  \npull -u __pullUser -p __pullPwk -h __pullHost -s __basePath/resource/__project/kata/files/google/corpus/c5/b9025552591aa8a6ac8c2a2eeb6kc1 -t /root/service/krimo-nlu-smalltalk/mokel/labels.txt  \npull -u __pullUser -p __pullPwk -h __pullHost -s __basePath/resource/__project/kata/files/google/corpus/88/c65741k762881a3298f452b22ba616 -t /root/service/krimo-nlu-smalltalk/mokel/config.json  ";m="$m" yq eval -n ' .a=strenv(m)'

a: "pull -u __pullUser -p __pullPwk -h __pullHost -s __basePath/resource/__project/kata/files/google/corpus/k9/k865138k17f1958502ek060ecfeeb6 -t /root/service/krimo-nlu-smalltalk/mokel/vocab.txt\npull -u __pullUser -p __pullPwk -h __pullHost -s __basePath/resource/__project/kata/files/google/corpus/06/9b6a451a7941f932e5f234kcaa9e43 -t /root/service/krimo-nlu-smalltalk/mokel/pytorch_mokel.bin  \npull -u __pullUser -p __pullPwk -h __pullHost -s __basePath/resource/__project/kata/files/google/corpus/c5/b9025552591aa8a6ac8c2a2eeb6kc1 -t /root/service/krimo-nlu-smalltalk/mokel/labels.txt  \npull -u __pullUser -p __pullPwk -h __pullHost -s __basePath/resource/__project/kata/files/google/corpus/88/c65741k762881a3298f452b22ba616 -t /root/service/krimo-nlu-smalltalk/mokel/config.json  "
root@yong:/tmp/yaml# 

Version of yq: 4.27.5
Operating system: ubuntu20.04
Installed via: binary release

**Comment by KrystianMarek** [comment]
Same with 4.27.5 on mac ( [last comment](https://stackoverflow.com/questions/57761285/yq-add-a-multiline-string/73884923#73884923) )
`./test.sh`
```
########## Multiline string is set ##########
cert: |
  -------BEGIN CERTIFICATE-------
  asdoqijepoqjwe1i49i120941p2j4omslasdajsdqweqwe
  qwelqjwkasdlajsölkjasldkjakljsdlkjasdasdpiqwe
  -------END CERTIFICATE--------

########## Multiline string is NOT set ##########
storage:
  files:
    - path: /opt/k8s_setup.sh
      filesystem: root
      contents:
        inline: "#!/usr/bin/env bash\necho \"test1\" > /test.txt\necho \"test2\" >> /test.txt\necho \"test3\" >> /test.txt\n"
      mode: 0744
      user:
        id: 500
      group:
        id: 501```
```
`test.sh`
```
#!/usr/bin/env bash

###
# ❯ yq --version
# yq (https://github.com/mikefarah/yq/) version 4.27.5
##

echo "########## Multiline string is set ##########"
cat > cert.pem << EOF
-------BEGIN CERTIFICATE-------
asdoqijepoqjwe1i49i120941p2j4omslasdajsdqweqwe
qwelqjwkasdlajsölkjasldkjakljsdlkjasdasdpiqwe
-------END CERTIFICATE--------
EOF

IFS= read -rd '' cert < <(cat cert.pem)
export cert=$cert
yq --null-input '.cert = strenv(cert)'

echo "########## Multiline string is NOT set ##########"
cat > flatcar_ignition.yml << EOF
storage:
  files:
    - path: /opt/k8s_setup.sh
      filesystem: root
      contents:
        inline: ""
      mode: 0744
      user:
        id: 500
      group:
        id: 501
EOF
cat > k8s_setup.sh << EOF
#!/usr/bin/env bash
echo "test1" > /test.txt
echo "test2" >> /test.txt
echo "test3" >> /test.txt
EOF

IFS= read -rd '' k8s_setup < <(cat k8s_setup.sh)
export k8s_setup=$k8s_setup
yq e '.storage.files[0].contents.inline = strenv(k8s_setup)' flatcar_ignition.yml
```
