### ISSUE TITLE
Filter the path based in search

### ISSUE THREAD

**Issue by junaid18183** [mikefarah/yq#1371]
Not sure whether what I am asking is supported or not but in all my searches to documentation yield nothing, that's why I am not adding feature_requst 

here is my input yaml file
```
profile: default
hub: ghcr.io/junaid18183/istio
tag: 1.11.3
domain: ijuned.com
revision: ""
openshift: false
imagePullSecrets: []
monitoring:
  enabled: false
postInstallHook:
  image: ghcr.io/junaid18183/base:8.4
  name: base
hub: ghcr.io/junaid18183/istio
cni:
  image:
    hub: ghcr.io/junaid18183/istio
```

All I want is the find and replace the `ghcr.io/junaid18183/` to `docker.io/junaid18183/` and create the  patch file as ( containing keys containing only the search items

```
hub: docker.io/junaid18183/istio
postInstallHook:
  image: docker.io/junaid18183/base:8.4
hub: docker.io/junaid18183/istio
cni:
  image:
    hub: docker.io/junaid18183/istio
```
