### ISSUE TITLE
[HELP] - Large Files Split & Large Files Stream

### ISSUE THREAD

**Issue by STSMHQ** [mikefarah/yq#1381]
Hi, there,

I'm new using this command line tool. I searched the issues in this repository, the documentation and also the StackOverflow website and I couldn't find a answer to my doubt, that's why I'm opening this issue right now. Hope someone can help me solving this.

I've some large YAML files, like 1GB~2GB each. And I want to do something about them, basically:

- I want to be able to stream the entire file, without the need of loading the entire file into memory - Stream Option.
- I want to be able to split this files into small ones. I searched the documentation and the option I found is to create a new file for each document inside the YAML file separated by `---` and that's not my case. My file is a full root node array with many, many documents. So, basically, I want to split my enormous array YAML file into small ones using documents' indexes. For instance, I want to be able to create new files for each 1000 documents that I've in my large YAML input file.

Example of my files' structure:

```yaml
---
- id: example
  date: example
  meeting_content: 
   - >
     example
   - >
     example
   - >
     (...)
  meeting_creator: example
- id: example1
  date: example1
  meeting_content:
   - >
     example1
   - >
     example1
   - >
     (...)
  meeting_creator: example1
```

I hope someone can help me solve this issues. Thanks in advance for the time spent reading my issue ❤️ 

Regards,
**STSM**
