### ISSUE TITLE
/entrypoint.sh: line 11: can't create : nonexistent directory

### ISSUE THREAD

**Issue by jdsr4c** [mikefarah/yq#1388]
**Describe the bug**
All of our GitHub Actions deployments are suddenly failing at the yq step (no recent changes) with the following error:

Run mikefarah/yq@master
  with:
    cmd: yq .dev.s3Bucket '.github/config.yml'
  env:
    AWS_REGION: us-east-1
    ENVIRONMENT: dev

"yq .dev.s3Bucket '.github/config.yml'"

/entrypoint.sh: line 11: can't create : nonexistent directory

Version of yq: latest
Operating system: linux
Installed via: docker

**Input Yaml**
build-pipeline.yml:
```yaml
- name: Get s3Bucket
    id: getS3Bucket
    uses: mikefarah/yq@master
    with:
        cmd: yq .${{ env.ENVIRONMENT }}.s3Bucket '.github/config.yml'
```

note: ${{ env.ENVIRONMENT }} resolves to 'dev'

.github/config.yml:
```yaml
dev: 
  s3Bucket: lambda-artifacts-px1lncq0gq9ti7k9jcyn
```

**Command**
The command you ran:
```
yq .dev.s3Bucket '.github/config.yml'
```

**Additional context**
This has been working for us all year until now, and we made no changes to our script before this started happening. So it was very sudden and random.
