### ISSUE TITLE
Trouble with long strings

### ISSUE THREAD

**Issue by IdanAdar** [mikefarah/yq#139]
Given a YAML with this:
```
image:
  imagePullPolicy: Always
  repository: someText
  tag: 
```

I want to edit `tag` with a property as part of my pipeline, and I do it like so, e.g.:

```
LatestTag = "201803280824"
../../../yaml w -i myYaml.yaml image.tag $LatestTag
```

What happens is that `201803280824` is stored as something like `11.1234+11` instead.
After some googling it seems that the solution is to add `!!str` before the value so that it will be interpreted as a string instead. Problem is I'm not sure how to property insert `!!str 201803280824` as the value for `tag`.

No matter how I try it it's transforming to either `'!!str 201803280824'` or `'!!str'` or `11.1234+11` but never `!!str 201803280824` (note that there are no quotes surrounding it, which is important for `!!str`).

Also related I guess is that the input for `w -i` doesn't handle spaces in values...

**Comment by mikefarah** [comment]
yep :( this is the same issue as https://github.com/mikefarah/yq/issues/107

**Comment by mikefarah** [comment]
Also - I couldn't replicate w -i not handling spaces
```
yq w -i examples/data3.yaml c.test "cat and"
cat examples/data3.yaml
b:
- 2
- 3
- 4
c:
  test: cat and
  other: true
d: false%
```
