### ISSUE TITLE
Quoted value in select() gets closing quote removed on windows only

### ISSUE THREAD

**Issue by karosas** [mikefarah/yq#1405]
**Describe the bug**
Running a select query comparing yaml to a quoted value (e.g. `...select(.name == "myValue")` on windows fails with debug message showing that quoted value doesn't have closing quote. Running same query on same input works on WSL

Version of yq: 4.28.2 (both windows and WSL)
Operating system: Windows / WSL
Installed via: binary release on both

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
data1.yml:
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://localhost:1234
  name: minikube
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://localhost:4321
  name: docker-desktop
```

**Command**
The command you ran:
```
cat .\sample.yml | yq '.clusters[] | select(.name == "minikube") | .cluster.server'
```

**Actual behavior**

```
Error: 1:31: invalid input text "minikube) | .clu..."
```

**Expected behavior**

```yaml
https://localhost:1234
```

**Additional context**
Running exact same command on WSL works just fine
