### ISSUE TITLE
Sort broken for date

### ISSUE THREAD

**Issue by julianbarg** [mikefarah/yq#1412]
**Describe the bug**
I am trying to sort by a dictionary by a value that contains numbers. The sorting does not work, regardless of whether I use the value as-is or convert it to string.

Version of yq: 4.29.2
Operating system: linux
Installed via: snap

**Input**
```yaml
- key: a
  date: 2011-09-12
- key: c
  date: 2011-10-05
- key: b
  date: 2010-12-09
- key: d
  date: 2011-10-20
- key: e
  date: 2010-09-29
```
I tried the following:

**Command 1**
```bash
yq '. | sort_by(.date)' ~/input.yaml
```

**Output 1**
```yaml
- key: e
  date: 2010-09-29
- key: d
  date: 2011-10-20
- key: b
  date: 2010-12-09
- key: c
  date: 2011-10-05
- key: a
  date: 2011-09-12
```

**Command 2**
```bash
yq '[.[] | .date style="double"] | sort_by(.date)' input.yaml
```

**Output 2**
```yaml
- key: e
  date: "2010-09-29"
- key: d
  date: "2011-10-20"
- key: b
  date: "2010-12-09"
- key: c
  date: "2011-10-05"
- key: a
  date: "2011-09-12"
```

**Command 3**
```bash
yq '[.[] | .date style="double"] |= sort_by(.date)' input.yaml

```

```yaml
- key: a
  date: "2011-09-12"
- key: c
  date: "2011-10-05"
- key: b
  date: "2010-12-09"
- key: d
  date: "2011-10-20"
- key: e
  date: "2010-09-29"
```

**Expected behavior**

```yaml
- key: e
  date: "2010-09-29"
- key: b
  date: "2010-12-09"
- key: a
  date: "2011-09-12"
- key: c
  date: "2011-10-05"
- key: d
  date: "2011-10-20"
```

**Additional context**
Looks like for some reason yq is reversing the order of the list. Except for the third command that is. I have no idea what is going on, but certainly is not expected behavior.
