### ISSUE TITLE
Roundtrip to/from a property file breaks

### ISSUE THREAD

**Issue by Kopfbremse** [mikefarah/yq#1415]
**Version of yq**: 4.29.2
**Operating system**: linux
**Installed via**: binary release

**Describe the bug**
If a YAML contains keys that are numbers, the roundtrip YAML --> PROP and back PROP --> YAML fails.
This is because numbers are interpreted as array indexes and not as key names. See my feature proposal below.

**Input Yaml**
```yaml
error:
  count:
    404: 1
    500: 3
  msg:
    404: unavailable
    500: internal server error
```

**Command 1**
Step 1: Convert YAML to PROPS
`yq --output-format props '.' "$FILE_YAML"`

```text
error.count.404 = 1
error.count.500 = 3
error.msg.404 = unavailable
error.msg.500 = internal server error
```

**Command 2**
Step 2: Convert PROPS back to YAML
`yq --input-format props $FILE_PROPS`

```yaml
error:
  count:
    - null
    - (...)
    - "1"
    - null
    - (...)
    - "3"
  msg:
    - null
    - (...)
    - unavailable
    - null
    - (...)
    - internal server error
```

**Expected behavior**
Command 2 should generate the input of step 1 to achieve a working roundtrip

**Feature proposal**
It would be nice if there were new options to control the conversion from PROP to YAML more detailed,
e.g. `--props-number-handling` = `[arrayIndex, keyName]`.
I love the yq support of property files. However, since it is perfectly valid to use numbers in property files, I consider it an incomplete feature.
