### ISSUE TITLE
yq output  will omit  yaml version directive header

### ISSUE THREAD

**Issue by zhiyuan-liao** [mikefarah/yq#1424]
**Describe the bug**
yq output  will omit  yaml version directive header,
 yq should not modify or omit any part that not selected, especially compatible directive

Version of yq: 4.28.2
Operating system: mac/linux/windows/....
Installed via: docker/binary release/homebrew/snap/...

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
data1.yml:
```yaml
%YAML 1.1
---

this: should really work
but: it strangely didn't
```

**Command**
The command you ran:
```
yq -i '.this= "no"'  data1.yml
```

**Actual behavior**

```yaml
test: no
but: it strangely didn't
```

**Expected behavior**

```yaml
%YAML 1.1
---

this: no
but: it strangely didn't
```

**Additional context**
