### ISSUE TITLE
Support multiple document in a stream

### ISSUE THREAD

**Issue by hadigoh** [mikefarah/yq#144]
If there's a document separator, only the first document is preserved.

Example:
```yaml
foo:
    bar: baz
---
baz:
    bar: foo
```

```sh
yq w example.yaml foo.bar newValue
```

Output:
```yaml
foo:
    bar: newValue
```

Expected Output:
```yaml
foo:
    bar: newValue
---
baz:
    bar: foo
```

Maybe we'll need to prefix an index to the path, if non given it defaults to first document.
```sh
yq w example.yaml [1]baz.bar newValue
```
