### ISSUE TITLE
Update operator updates although RHD is an empty sequence

### ISSUE THREAD

**Issue by Kopfbremse** [mikefarah/yq#1443]
**Version of yq**: 4.30.2
**Operating system**: linux
**Installed via**: binary release

**Bug description**
I want to wrap an object in an array if it is not already an array, using the update operator.
I have encountered an error, or at least some unexpected behaviour.

```bash
INPUT='
Angels:
  Name: Michael
  AddressHistory:
    Address:
      AddressLine: Heaven
'

yq '.Angels.AddressHistory.Address |= (select(type == "!!map") | [.])' <<< "$INPUT"
```

**Output (as expected)**
```yaml
Angels:
  Name: Michael
  AddressHistory:
    Address:
      - AddressLine: Heaven
```

-----

```bash
INPUT2='
Angels:
  Name: Michael
  AddressHistory:
    Address:
      - AddressLine: Cloud 9
      - AddressLine: Heaven
'

yq '.Angels.AddressHistory.Address |= (select(type == "!!map") | [.])' <<< "$INPUT2"
```

**Output (unexpected)**
```yaml
Angels:
  Name: Michael
  AddressHistory:
    Address: []
```

**Expected behaviour**
`select(type == "!!map")` produces an empty sequence. The node '.Angels.AddressHistory.Address' should not be updated.
