### ISSUE TITLE
Inplace updates incorrectly rewrites multi-line yaml strings

### ISSUE THREAD

**Issue by greenatatlassian** [mikefarah/yq#1468]
**Describe the bug**
When updating YAML, e.g. with the `-i` (inplace) option, the updated file has incorrectly modified multi-line strings.

Version of yq: 4.26.1
Operating system: mac
Installed via: homebrew

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
input.yml:
```yaml
name: A name
description: -<
  A description that uses multi-line format.
value: one
```

**Command**
The command you ran:
```
yq -i ".value=\"two\"" input.yaml 
```

**Actual behavior**

```yaml
name: A name
description: -< A description that uses multi-line format.
value: two
```

**Expected behavior**

```yaml
name: A name
description: -<
  A description that uses multi-line format.
value: two
```

It would also be valid if it at least rewrote the YAML in a valid way, i.e.:
```yaml
name: A name
description: A description that uses multi-line format.
value: two
```
(i.e. without the YAML formatting characters added to the string value.)

**Additional context**

The behaviour is the same without the `-i` option, and if the multi line string spans more lines, and if it has a blank line after it. 
This may be related to/have the same root cause as #439 and #566.
