### ISSUE TITLE
how to convert file from dot notation to object notation using yq command?

### ISSUE THREAD

**Issue by tobiasz-gleba** [mikefarah/yq#1470]
Hello, I can not find the answer for my case.
I have file like this: 
```yml
configEnv:
  FROM_HELM: true
configEnv: {APP_DEBUG: true}
```
My goal is to convert this file to object YAML structure. For my example, it will be:
```yml
configEnv:
  FROM_HELM: true
  APP_DEBUG: true
```
I want to do this globaly in my file. I have planty of values like that, so adding "configEnv" in command, from my example, won't be solution for me. This solution shoult to be as generic as we can.
