### ISSUE TITLE
Want to manage docker-compose.yml via yq - via a yarn file script....

### ISSUE THREAD

**Issue by kmjones1979** [mikefarah/yq#1490]
**Describe the bug**
Trying to pass my yq command via docker-compose using yarn and I appear to be having issues with escaping the double quotes around the field update.

Version of yq: v4.30.6
Operating system: mac
Installed via: docker
version of yarn: v3.3.0

**Input Yaml**
```yaml
this works...
```

again using strait docker command this works....
docker run -it -v $(pwd)/packages/docker/docker-compose.yml:/workdir/docker-compose.yml mikefarah/yq -i '.services.nginx-web.profiles.[0] = "disabled"' /workdir/docker-compose.yml

data2.yml:
```yaml
services:
  nginx-web:
    image: nginx:latest
    build: ./nginx-web
    hostname: nginx-web
    container_name: nginx-web
    command: 'nginx -g "daemon off;"'
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx-web/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./nginx-web/etc/nginx/conf.d:/etc/nginx/conf.d:rw
    profiles:
      - enabled
```

**Command**
The command you ran: via yarn - notice the escaped chars on enabled and disabled, basically a toggle... '${0}' represents the name for the service I want enable or disable

my yarn file scripts
```
{
  "name": "@nginx-sk/foo",
  "scripts": {
    "docker-compose-enable": "docker run -it -v $(pwd)/packages/docker/docker-compose.yml:/workdir/docker-compose.yml mikefarah/yq -i '.services.${0}.profiles.[0] = \"enabled\"' /workdir/docker-compose.yml",
    "docker-compose-disable": "docker run -it -v $(pwd)/packages/docker/docker-compose.yml:/workdir/docker-compose.yml mikefarah/yq -i '.services.${0}.profiles.[0] = \"disabled\"' /workdir/docker-compose.yml"
  }
}

```

yarn docker-compose-disable nginx-web
Error: bad expression, please check expression syntax

**Additional context**
Is there a better way to do this? Ideally I want a simple yarn command to run my docker exec for me via yarn.
