### ISSUE TITLE
Some comment reformatted or removed when ireduce is used

### ISSUE THREAD

**Issue by KTAtkinson** [mikefarah/yq#1519]
**Describe the bug**
Head comments at the top of YAML documents are removed when `ireduce` is used on a YAML file. In addition foot comments appear to be reformatted.

Note, the head comment on the first document was removed and the foot comment on the last document is indented where it was not before.                                                                  

Version of yq: 4.30.6
Operating system: linux (ubuntu 22.04)
Installed via: binary

Given this YAML file:

```yaml
---
# Head comment at top of file
document: first
some_object:
  field: value # line comment
---
# Head comment on document two
document: second
some_object:
  # Head comment on field
  field: value
---
document: third
some_object:
  field: value
# foot comment
```

And this yq command:

```
yq '. as $i ireduce({}; . *  {($i | .document): $i}) ' sample.yaml 
```

This is the result:

```yaml
first:
  document: first                                                                                                                             
  some_object:                                                         
    field: value # line comment
                                                                       
second:                                                                
  # Head comment on document two                                                                                                              
  document: second
  some_object:                                                         
    # Head comment on field
    field: value                                                       
third:                                                                 
  document: third                                                                                                                             
  some_object:
    field: value                                                       
  # foot comment                                                       
```
**Expected behavior**

```yaml
first:
  # Head comment at top of file
  document: first                                                                                                                             
  some_object:                                                         
    field: value # line comment
                                                                       
second:                                                                
  # Head comment on document two                                                                                                              
  document: second
  some_object:                                                         
    # Head comment on field
    field: value                                                       
third:                                                                 
  document: third                                                                                                                             
  some_object:
    field: value                                                       
# foot comment     
```

**Additional context**
