### ISSUE TITLE
Explode operator with nested anchors

### ISSUE THREAD

**Issue by jtyr** [mikefarah/yq#1528]
I have a document that is using nested YAML anchors. I'm using the `explode()` operator to resolve the anchors but if I have multiple nested anchors, it seems to only resolve the first level of of the nested anchors.

The following command:

```shell
cat <<END > aaa.yaml
aaa:
  - &first
    aaa: bbb
  - &second
    <<: *first
    ccc: ddd
  - <<: *second
    eee: fff
END
yq '.aaa[2] | explode(.)' aaa.yaml
```

produces the following output:

```yaml
!!merge <<:
  aaa: bbb
ccc: ddd
eee: fff
```

where I would expect it to produce this:

```yaml
aaa: bbb
ccc: ddd
eee: fff
```

I'm running `yq` in the version `4.30.6` on Arch Linux.

**Comment by mikefarah** [comment]
Hmm not sure why that's not working, need to look into it. As a workaround, if you run explode first then it works:

```
yq 'explode(.) | .aaa[2]' aaa.yaml
```

**Comment by jpicht** [comment]
I am running into basically the same issue but with `del`:

testcase.yaml:
```yaml
tmp:
  a: &a
    a: 1
  b: &b
    <<: *a
    b: 2
c:
  <<: *b
```

When I run
```bash
yq eval 'del(.tmp)' < testcase.yaml
```

`yq` produces following output:
```yaml
c:
  !!merge <<: *b
```

I can work around this, but it looses all formatting:
```bash
yq eval  -oj < testcase.yaml | yq 'del(.tmp)' -oy -P
```
