### ISSUE TITLE
First comment is lost while collecting into array

### ISSUE THREAD

**Issue by amorozkin** [mikefarah/yq#1536]
**Describe the bug**
First comment of in multi-doc yaml file is lost when "converting" map into array

Version of yq: 4.30.8
Operating system: linux (Ubuntu 20.04.4 LTS)
Installed via: binary release

**Input Yaml**
data.yml:
```yaml
---
# Source: ingress-nginx/templates/controller-configmap.yaml
apiVersion: v1
kind: ConfigMap
---
# Source: ingress-nginx/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
```

**Command**
```
yq '[.]' data.yml
```

**Actual behavior**

```yaml
- apiVersion: v1
  kind: ConfigMap
---
- # Source: ingress-nginx/templates/clusterrole.yaml
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
```

**Expected behavior**

```yaml
- # Source: ingress-nginx/templates/controller-configmap.yaml
  apiVersion: v1
  kind: ConfigMap
---
- # Source: ingress-nginx/templates/clusterrole.yaml
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
```
