### ISSUE TITLE
Extra newline in the output when using line folding

### ISSUE THREAD

**Issue by ragnarpa** [mikefarah/yq#1539]
**Describe the bug**

```
$cat yq.yaml
folded_value: >-
  {
    "key": "value"
  }
$ yq yq.yaml
folded_value: >-
  {

    "key": "value"
  }
$ yq --version
yq (https://github.com/mikefarah/yq/) version v4.30.4
```

Version of yq: 4.30.4
Operating system: mac
Installed via: homebrew

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
data1.yml:
```yaml
folded_value: >-
  {
    "key": "value"
  }
```

**Command**
The command you ran:
```
yq data1.yaml
```

**Actual behavior**

```yaml
folded_value: >-
  {

    "key": "value"
  }
```

**Expected behavior**

```yaml
folded_value: >-
  {
    "key": "value"
  }
```

**Additional context**
