### ISSUE TITLE
More complex queries

### ISSUE THREAD

**Issue by estahn** [mikefarah/yq#155]
How would I do something like this?
```
yq -r '.www | .[] | keys | .[]'
```

```yaml
www:
  - foo:
       name: a
  - foo2:
       name: a
```

Should return `foo` and `foo2`.
