### ISSUE TITLE
Weird query result

### ISSUE THREAD

**Issue by notorand-it** [mikefarah/yq#1578]
**Describe the bug**
Extra `null`s from what I would define a simple query
More details below.

Version of yq: 4.31.1
Operating system: linux (archlinux)
Installed via: archlinux native package management (`pacman`)

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
data1.yml:
```yaml
something:
  - one:
      prop: 1
  - two:
      prop: 2
  - three:
      prop: 3
```

data2.yml: n/a
```yaml

```

**Command 1**
The command you ran:
```
yq e '.something[].one' < test.yaml
```

**Actual behavior 1**

```yaml
prop: 1
null
null
```

**Expected behavior 1**

```yaml
prop: 1
```

**Command 2**
The command you ran:
```
yq e '.something[].one.prop' < test.yaml
```

**Actual behavior 2**

```yaml
1
null
null
```

**Expected behavior 2**

```yaml
1
```

**Additional context**
N/A

**Comment by notorand-it** [comment]
**Extra note**
If I trym the YAML file to:
```yaml
something:
  - one:
      prop: 1
  - two:
      prop: 2
```
Then the output has 1 fewer `null` !
```
$ yq e '.something[].one.prop' < test.yaml 
1
null
```
