### ISSUE TITLE
Only the last element of an array is considered (not working like jq)

### ISSUE THREAD

**Issue by bleleve** [mikefarah/yq#1579]
Version of yq: 4.31.1
Operating system: wsl windows
Installed via: binary release

**Input Yaml**
bufbuild_grpc_node.yml:
```yaml
version: v1
name: buf.build/grpc/node
plugin_version: v1.12.4
source_url: https://github.com/grpc/grpc-node
description: Generates Node client and server stubs for the gRPC framework.
deps:
  - plugin: buf.build/protocolbuffers/js:v3.21.2
output_languages:
  - javascript
registry:
  npm:
    import_style: commonjs
    deps:
    - package: '@grpc/grpc-js'
      version: '^1.8.0'
    - package: 'google-protobuf'
      version: '^3.21.2'
  opts:
  - grpc_js
spdx_license_id: Apache-2.0
license_url: 'https://github.com/grpc/grpc-node/blob/grpc-tools%401.12.4/LICENSE'
```

**Command**
The command you ran:
```
yq -r '.registry.npm.deps[]' bufbuild_grpc_node.yml | yq -r '.package + "@" + .version'
```

**Actual behavior**

```
google-protobuf@^3.21.2
```

**Expected behavior**

```
@grpc/grpc-js@^1.8.0
google-protobuf@^3.21.2
```

**Additional context**
This is working as expected using jq :
```
yq -r -o json '.registry.npm.deps[]' bufbuild_grpc_node.yml | jq -r '.package + "@" + .version'
```
