### ISSUE TITLE
Inconsistent nesting of XML

### ISSUE THREAD

**Issue by planeiii-te** [mikefarah/yq#1583]
## Description

When transforming XML, the nesting is created inconsistently. Arrays are created seemingly based on the number of children. One child is created as a string. More than one child is created as an array of strings.

## Details

Version of yq: v4.31.1
Operating system: mac
Installed via: homebrew

### Input XML

Concise XML document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)

data.xml:
```xml
<root>
  <heading>
    <member>one</member>
  </heading>
  <heading>
    <member>two</member>
    <member>three</member>
  </heading>
</root>
```

### Command

The command you ran:
```
yq --input-format xml . data.xml
```

### Actual behavior

```yaml
root:
  heading:
    - member: one
    - member:
        - two
        - three

```

## Expected behavior

```yaml
root:
  heading:
    - member:
        - one
    - member:
        - two
        - three
```
