### ISSUE TITLE
Unexpected change of the variable in yml file

### ISSUE THREAD

**Issue by richie189** [mikefarah/yq#1591]
**Describe the bug**

Note that any how to questions should be posted in the discussion board and not raised as an issue.

Version of yq: 4.25.2
Operating system: mac/linux/windows/....
Installed via:  wget

**Input Yaml**
I have a yaml file which consists this below value and upon runnning to update the other value in my yml file, I saw this value is auto changed:
```yaml
chart:
  image:
     tag: "2454.0"
  hook:
     config:
         commit: {{ .Values.image.tag }}
```

This is the output:
```yaml
chart:
  image:
     tag: "2514.0"
  hook:
     config:
         commit: {? {.Values.image.tag: ''} : ''}
```

**Command**
```
 yq e '.chart.image.tag = "2514.0" ' -i "file.yaml"
```

**Expected behavior**
We expect only `tag` value that will be changed, but it also changed other variable using in the file.

```yaml
chart:
  image:
     tag: "2514.0"
  hook:
     config:
         commit: {{ .Values.image.tag }}
```

**Additional context**
Is it updated in a certain version of yq that would need an option to use variable in the file or is it caused by something?
<img width="284" alt="Screenshot 2023-03-09 at 5 31 03 PM" src="https://user-images.githubusercontent.com/70510216/224001131-e0e34d67-f502-4472-a323-5590d919acae.png">
