### ISSUE TITLE
Several multiline docs can't be handled

### ISSUE THREAD

**Issue by malcolm061990** [mikefarah/yq#1597]
**Describe the bug**
I want to update image.tag in multiline document **only** in specific item in array.
Several multiline docs can't be handled.

Version of yq: v4.31.2
Operating system: mac
Installed via: homebrew

**Input Yaml** - we can't change this format
2.yaml:
```yaml
spec:
  source:
    plugin:      
      env:
        - name: VALUE_FILES
          value: |
            - dev.yaml
        - name: OVERRIDE_VALUES
          value: |
            image:
              tag: v1.0.0
```

**Command**
```
yq '.spec.source.plugin.env[].value |= (from_yaml | .image.tag = "v1.1.1" | to_yaml)' 2.yaml -r
```

**Actual behavior**

```
Error: cannot index array with 'image' (strconv.ParseInt: parsing "image": invalid syntax)
```

**Expected behavior**

```yaml
spec:
  source:
    plugin:      
      env:
        - name: VALUE_FILES
          value: |
            - dev.yaml
        - name: OVERRIDE_VALUES
          value: |
            image:
              tag: v1.1.1
```

**Additional context**
1) If I hardcode the item number from array - it works (but I don't want to hardcode item in number array):
`yq '.spec.source.plugin.env[1].value |= (from_yaml | .image.tag = "v1.1.1" | to_yaml)' 2.yaml -r`
```yaml
spec:
  source:
    plugin:
      name: plugin
      env:
        - name: VALUE_FILES
          value: |
            - dev.yaml
        - name: OVERRIDE_VALUES
          value: |
            image:
              tag: v1.1.1
```

2) If I choose item in array using `select` - the output will NOT be full (but I need full output like in expected behaviour):
`yq '.spec.source.plugin.env[] | select(.name == "OVERRIDE_VALUES") | .value |= (from_yaml | .image.tag = "v1.1.1" | to_yaml)' 2.yaml`
```yaml
name: OVERRIDE_VALUES
value: |
  image:
    tag: v1.1.1
```

3) If I set `- dev.yaml` to `dev.yaml` in input yaml in first multiline document - it works:
```yaml
spec:
  source:
    plugin:
      name: plugin
      env:
        - name: VALUE_FILES
          value: |
            dev.yaml ### removed "-" here
        - name: OVERRIDE_VALUES
          value: |
            image:
              tag: v1.1.1
```

`yq '.spec.source.plugin.env[].value |= (from_yaml | .image.tag = "v1.1.1" | to_yaml)' 2.yaml -r`
```yaml
spec:
  source:
    plugin:
      name: plugin
      env:
        - name: VALUE_FILES
          value: |
            dev.yaml
        - name: OVERRIDE_VALUES
          value: |
            image:
              tag: v1.1.1
```
