### ISSUE TITLE
Allow raw, unquoted string output even when JSON format is specified

### ISSUE THREAD

**Issue by mcandre** [mikefarah/yq#1615]
**Please describe your feature request.**

Please allow `style=""` to work as documented in https://mikefarah.gitbook.io/yq/operators/style#reset-style-or-pretty-print when JSON mode is active.

Note:
- how to questions should be posted in the discussion board and not raised as an issue.
- V3 will no longer have any enhancements.

**Describe the solution you'd like**

```toml
[target.aarch64-apple-darwin]
image = "freeznet/aarch64-apple-darwin-cross:11.3"

[target.x86_64-apple-darwin-cross]
image = "freeznet/x86_64-apple-darwin-cross:11.3"
```

And we run a command:

```bash
yq -o json ".target | keys | .[] | . style=\"\"" Cross.toml
```

it could output

```text
aarch64-apple-darwin
x86_64-apple-darwin-cross
```

Currently the command outputs:

```text
"aarch64-apple-darwin"
"x86_64-apple-darwin-cross"
```

**Describe alternatives you've considered**

As a workaround, I am having to use YAML mode, even though my query results in an array of raw strings, that shouldn't care about any kind of larger JSON/TOML/YAML envelope.
