### ISSUE TITLE
Don't fret about output format when the result data set is a raw array of unquoted strings

### ISSUE THREAD

**Issue by mcandre** [mikefarah/yq#1616]
**Please describe your feature request.**

When the result data set is just a list of raw, unquoted strings, then yq could in practice go ahead and emit the output without terminating or warning about lack of TOML support.

**Describe the solution you'd like**

```toml
[target.aarch64-apple-darwin]
image = "freeznet/aarch64-apple-darwin-cross:11.3"

[target.x86_64-apple-darwin-cross]
image = "freeznet/x86_64-apple-darwin-cross:11.3"
```

And we run a command:

```bash
yq ".target | keys | .[] | . style=\"\"" Cross.toml
```

it could output

```text
aarch64-apple-darwin
x86_64-apple-darwin-cross
```

instead of

```text
Error: toml is not yet supported as an output format. Please specify another output format using the [--output-format/-o] flag
```

**Describe alternatives you've considered**

I tried working around this by specifying JSON as the output format. But that corrupted the output text by ignoring the blank quoting style.

As another workaround, I am using the "YAML" output format, even though the data set has no nested or ambiguously syntaxed elements, and even though the output text is not actually valid YAML.
