### ISSUE TITLE
Github actions attempts to build docker container every time

### ISSUE THREAD

**Issue by spencer-cdw** [mikefarah/yq#1620]
If a user attempts to use the yq@v4 github actions like so:

```
      - name: Show inspec failures report
        uses: mikefarah/yq@v4
        with: 
          cmd: yq .error foobar.yaml
```

They will get a pipeline failure

```
Build container for action use: '/data/_work/_actions/mikefarah/yq/v4/github-action/Dockerfile'.
  Error: docker: command not found
  ```
  
  
  ## Desired result
  
  The github action should not attempt to rebuild a container every time the pipeliene runs. The docker container should be provided for the end user.
  Users should not be expected to setup docker-in-docker to use a github action
