### ISSUE TITLE
--inplace removing the rest of the file when using select

### ISSUE THREAD

**Issue by KevinUre** [mikefarah/yq#1626]
**Describe the bug**
I'm trying to use yq in a Github Actions Workflow to inject environment variables into a helm chart. to find the correct env var I need to use a select statement. when i run `yq -i` with a select in the command it replaces the contents of the chart with the results of the select 

Version of yq: 4.31.2
Operating system: ubuntu
Installed via: _unknown_, it comes on the runner

**Input Yaml**
values.yaml before the command (with some information removed for brevity):
```yaml
replicaCount: 1

image:
  repository: myrepourl
  pullPolicy: Always
  tag: ""

env:
  - name: OTEL_ENDPOINT
    value: OTEL_ENDPOINT
```

**Command**
The command you ran:
```
yq -i '.env[] | select(.name == "OTEL_ENDPOINT").value |="new value"' ./values.yaml
```

**Actual behavior**

values.yaml after the command (entire file):
```yaml
name: OTEL_ENDPOINT
value: new value
```

**Expected behavior**

```yaml
replicaCount: 1

image:
  repository: myrepourl
  pullPolicy: Always
  tag: ""

env:
  - name: OTEL_ENDPOINT
    value: new value
```

**Additional context**
I'm also using yq to set the app version in the Chart.yaml and that works fine. after playing around with it for quite a bit the problem only happens with a select is involved

i've tried a few other commands as well, all have the same behavior
```
yq -i '.env[] | select(.name == "OTEL_ENDPOINT") | .value="new value"' ./values.yaml
yq -i '.env[] | select(.name == "OTEL_ENDPOINT").value |="new value"' ./values.yaml
yq -i '.env[] | select(.name == "OTEL_ENDPOINT").value="new value"' ./values.yaml
```
