### ISSUE TITLE
Is there an operator like `walk` in jq ?

### ISSUE THREAD

**Issue by smalnote** [mikefarah/yq#1642]
**Please describe your feature request.**
A clear and concise description of what the request is and what it would solve. 
Eg. I wish I could use yq to iterate a yaml recursive, find all key-value pairs, which key is `image` and value type is `string`(!!str), then add a prefix to the original value.

Input: 
``` yaml
serving:
  template:
    image: "docker.io/serving"
custom:
  template:
    image: 
      type: string
      description: "..."
eventing:
  image: "docker.io/eventing"
```
Add a prefix `private.io/" to all `image` if its value type is `string`(!!str) recursively.

Output:
``` yaml
serving:
  template:
    image: "private.io/docker.io/serving"
custom:
  template:
    image: 
      type: string
      description: "..."
eventing:
  image: "private.io/docker.io/eventing"
```

For a equivalent json, I can use the `walk` operator to do such thing:
``` bash
jq 'walk(if type == "object" and has("image") and (.image|type) == "string" then .image = "private.io/" + .image else . end)' input.json
```

Is there any equivalent operator like `walk`, I have tried the `..` operator
``` yaml
yq '.. | select(tag == "!!str" and key == "image") |= "private.io/" + . ' input.json
```
But this command add some entries to the yaml, result in:
``` yaml
erving:
  template:
    image: "private.io/docker.io/serving"
custom:
  template:
    image:
      type: string
      description: "..."
eventing:
  image: "private.io/docker.io/eventing"
template:
  image: "private.io/docker.io/serving"
image: "private.io/docker.io/serving"
private.io/docker.io/serving
template:
  image:
    type: string
    description: "..."
image:
  type: string
  description: "..."
type: string
description: "..."
string
...
image: "private.io/docker.io/eventing"
private.io/docker.io/eventing
```

Any ideas or walk around ? Thanks, sincerely~
