### ISSUE TITLE
Multiplication of nodes with identical names but different tags merges values

### ISSUE THREAD

**Issue by Nyefan** [mikefarah/yq#1647]
**Describe the bug**

Note that any how to questions should be posted in the discussion board and not raised as an issue.

Version of yq: 4.30.5
Operating system: mac
Installed via: homebrew

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
data1.yml:
```yaml
cart:
  banana: !!fruit
    skin: true
    seeds: false
    isFruit: true
```

data2.yml:
```yaml
cart:
  banana: !!berry
    skin: true
    seeds: false
    isFruit: false
```

**Command**
The command you ran:
```
yq eval-all 'select(fileIndex == 0) * select(fileIndex == 1)' data1.yml data2.yml
```

**Actual behavior**

```yaml
cart:
  banana: !!berry
    skin: true
    seeds: false
    isFruit: true
```

**Expected behavior**

```yaml
cart:
  banana: !!fruit
    skin: true
    seeds: false
    isFruit: true
  banana: !!berry
    skin: true
    seeds: false
    isFruit: false

```

**Additional context**
Using:

data1.yml:
```yaml
cart:
  bananas: !!fruit
    skin: true
    seeds: false
    isFruit: true
```

the above command resolves correctly to:

```yaml
cart:
  bananas: !!fruit
    skin: true
    seeds: false
    isFruit: true
  banana: !!berry
    skin: true
    seeds: false
    isFruit: false
```

According to [the yaml spec](https://yaml.org/spec/1.2.2/#3213-node-comparison), "Two [nodes](https://yaml.org/spec/1.2.2/#nodes) must have the same [tag](https://yaml.org/spec/1.2.2/#tags) and [content](https://yaml.org/spec/1.2.2/#nodes) to be equal.", so I believe this to be a bug.

**Comment by Nyefan** [comment]
Separately, in the evaluation of application-specific tags, the merge order of the tag itself is backwards, so the result is:

```yaml
cart:
  banana: !fruit
    skin: true
    seeds: false
    isFruit: false
```

**Comment by mikefarah** [comment]
That right, it overwrites the values. You cannot have two keys with the same value in a map.

Another way to think of it is merging two maps, one:
```
a: hello
```

with another

```
a: 123
```
First one has a '!!str' tag and the other has a '!!int' tag. The result of the merge is you get

```
a: 123
```

That is the value is overwritten.

**Comment by Nyefan** [comment]
Ah, that does make sense, thank you.  In that case I suppose the only potential bug is the inconsistent behavior between replacement of global and application-specific tags, though I may be missing something there as well:

```yaml
# yq ea 'select(di == 0)* select(di ==1)' - <<<$(<yaml1) <<<$(<yaml2)
cart:
  banana: !!berry
    skin: true
    seeds: false
    isFruit: false
```

```yaml
# yq ea 'select(di == 0)* select(di ==1)' - <<<$(sed 's/!!/!/g' yaml1) <<<$(sed 's/!!/!/g' yaml2)
cart:
  banana: !fruit
    skin: true
    seeds: false
    isFruit: false
```
