### ISSUE TITLE
Ability to parse string to integer

### ISSUE THREAD

**Issue by austince** [mikefarah/yq#1664]
**Please describe your feature request.**

Sometimes there are integers encoded as strings (because, sigh) and it would be nice to be able to parse them dynamically for things like sorting.

**Describe the solution you'd like**
If we have data1.yml like:
(please keep to around 10 lines )

```yaml
- version: "10"
- version: "9"
- version: "11"
```

And we run a command:

```bash
yq 'sort_by(.version | parseint)'
```

it could output

```yaml
- version: "9"
- version: "10"
- version: "11"
```

**Describe alternatives you've considered**

I tried adding a `0` to try to force integer evaluation to no avail. 

**Additional context**
Generally being able to change the data type of a field while processing would be useful. Is this already available in some way I haven't found?
