### ISSUE TITLE
Running GH Action works fine, but fails when running locally with ACT

### ISSUE THREAD

**Issue by andrewconnell** [mikefarah/yq#1665]
When using the GitHub action of the YQ container to extract a value from a YAML file in the repo, it works as expected when the workflow is run in GitHub. But when using the popular [act](https://github.com/nektos/act) runner to develop & debug workflows locally, it fails in the container's **entrypoint.sh** file with the following error:

```
[Refresh (latest) version/Initialize variables]   🐳  docker run image=mikefarah/yq:4-githubaction platform=linux/amd64 entrypoint=[] cmd=["yq '.latest' 'versions.yml'"]
[Refresh (latest) version/Initialize variables]   💬  ::debug::$cmd: yq '.latest' 'versions.yml'
[Refresh (latest) version/Initialize variables]   💬  ::debug::$RESULT: 1.17.0
| /entrypoint.sh: line 10: can't create : nonexistent directory
```

The YAML file it's reading from:

```yaml
latest: 1.17.0
next: 1.17.0-rc.1
```

... and the workflow steps...

```yaml
- name: Checkout repo codebase
  uses: actions/checkout@v3
  with:
    fetch-depth: 1
    clean: true
    submodules: false
- name: Get local version
  id: get-local-version
  uses: mikefarah/yq@master
  with:
    cmd: yq '.latest' 'versions.yml'
- name: DEBUG local
  run: echo ${{ steps.get-local-version.outputs.result }}
```

I'm unclear on exactly what the problem is though... when I run the latest version of YQ locally, it works just fine. Looking at the repo's container codebase, I can't tell exactly what's wrong. 

Here's the output from GH:
![Screenshot 2023-05-10 at 1 43 46 PM](https://github.com/mikefarah/yq/assets/2068657/3dfb4961-8bff-490e-bab8-8975d18b7323)
