### ISSUE TITLE
Multiplying documents (merge) doesn't work when it's not the first expression

### ISSUE THREAD

**Issue by tnozicka** [mikefarah/yq#1675]
**Describe the bug**
`. as $item ireduce({}; . * $item)` can't merge multiple documents when preceded by other commands.

Version of yq: v4.34.1
Operating system: linux
Installed via: go install

**Input Yaml**
```console
$ input_data=$( echo -e 'unique:  value\ndata:\n  foo:\n    alpha\n---\ndata:\n  bar:\n    beta' )
```
```yaml
unique: value
data:
  foo: alpha
---
data:
  bar: beta
```

**Command**
```console
$ yq eval-all -e '. as $all | $all as $item ireduce({}; . * $item)' < <( echo "${input_data}" )
```

**Actual behavior**
```yaml
unique: value
data:
  foo: alpha
data:
  bar: beta
```

**Expected behavior**
```yaml
unique: value
data:
  foo: alpha
  bar: beta
```

**Additional context**
Based on https://mikefarah.gitbook.io/yq/operators/reduce#merge-all-yaml-files-together

When `. as $item ireduce` is the first command it all works as expected.

```console
$ yq eval-all -e '. as $item ireduce({}; . * $item)' < <( echo "${input_data}" )
```
```yaml
unique: value
data:
  foo: alpha
  bar: beta
```

When the `ireduce` is preceded by an expression, it no longer works the same way and instead of merging it will output duplicate keys (`.data`). This is similar to what happens when using `eval` instead of `eval-all`. (Maybe it's no longer evaluated as multifile internally or something.)

Another manifestation may be a document duplication with a similar command, or maybe I misunderstand how it should work there.

```console
$ yq eval-all -e '. as $all | . as $item ireduce({}; . * $item)' < <( echo "${input_data}" )
```
```yaml
unique: value
data:
  foo: alpha
  bar: beta
unique: value
data:
  foo: alpha
  bar: beta

```

I tried to simplify the command for a reproducer but for a context I was after something like
`yq eval-all -e '. as $all | select(fi==0) | .data = null | $all as $item ireduce({}; . * $item)' < <( echo "${input_data}" )`
that would merge keys on `.data` from all files except the first one which should be discarded.
