### ISSUE TITLE
In-place edit with multiple changes duplicates all lines

### ISSUE THREAD

**Issue by SKisContent** [mikefarah/yq#1680]
**Describe the bug**
An in-place edit with multiple replacements duplicates the contents of the file

Note that any how to questions should be posted in the discussion board and not raised as an issue.

Version of yq: yq (https://github.com/mikefarah/yq/) version v4.34.1
Operating system: MacOS and Ubuntu
Installed via: MacOS installed via homebrew, Ubuntu installed via github actions

**Input Yaml**
data1.yml:

```
replicaCount: 1
image:
  repository: xxx
  pullPolicy: Always
  tag: yyy
  digest: "zzz"
```

**Command**
The command you ran:
```
yq eval '.image.repository = "foo",
            .image.tag = "bar",
            .image.digest = "baz"' \
            -i helm/values.yaml
```

**Actual behavior**

```yaml
replicaCount: 1
image:
  repository: foo
  pullPolicy: Always
  tag: bar
  digest: "baz"
replicaCount: 1
image:
  repository: foo
  pullPolicy: Always
  tag: bar
  digest: "baz"
```

**Expected behavior**
```yaml
replicaCount: 1
image:
  repository: foo
  pullPolicy: Always
  tag: bar
  digest: "baz"
```

**Additional context**
I replaced the eval expressions with simple strings (foo, bar, baz) for this report, and truncated the file. The behavior is present when evaluating expressions and with a much longer yaml file.
