### ISSUE TITLE
Add item to an nested array which uses an environment variable

### ISSUE THREAD

**Issue by unmarshall** [mikefarah/yq#1686]
### Discussed in https://github.com/mikefarah/yq/discussions/1685

<div type='discussions-op-text'>

<sup>Originally posted by **unmarshall** June  2, 2023</sup>
Consider the following yaml
```yaml
spec:
  template:
    spec:
      containers:
        - args:
            - start-app
            - --tls-enabled=true
          image: app-image:dev
          imagePullPolicy: IfNotPresent
        - command:
            - ctl
            - bingo
            - --tls-enabled=true
            - --schedule=42 16 * * *
          image: another-app-image:dev
          imagePullPolicy: IfNotPresent
      serviceAccountName: app-sa
      volumes:
        - name: secret-1
           secret:
              defaultMode: 420
               secretName: secret-bingo
```
I wanted to add an element to an array '.spec.template.spec.containers[0].args' the value to be added is constructed using an environment variable.

I tried 

```bash
server_name="main-local" yq -i '.spec.template.spec.containers[0].args +="--server-name=env(server_name)"' <file_path>
```
But this appends `--server-name=env(server_name)` and does not evaluate/expand the environment variable.
I also played around with using `eval` or `with` operator but could not make this work. 

However if i had to add an object to '.spec.template.spec.volumes' then the following works:
```bash
another_secret_name="secret-tringo" yq -i '.spec.template.spec.volumes += {"name": "secret-2", "secret":  {"defaultMode": 420, "secretName": env(another_secret_name)}}' <file-path>
```
So it seems that using env operator has different behavior when adding an object to an existing array and when adding a string to an existing array. Confused a bit on why is this or am i missing something?</div>

**Comment by unmarshall** [comment]
When i try and add a map to an array then it works but obviously that is not a desired result that i look for.
```bash
export server_name=main-local && yq '.spec.template.spec.containers[0].args += {"server-name": strenv(server_name)}' test.yaml
```
This will give:
```yaml
spec:
  template:
    spec:
      containers:
        - args:
            - start-app
            - --tls-enabled=true
            - etcd-server-name: main-local
          image: app-image:dev
          imagePullPolicy: IfNotPresent
        - command:
            - ctl
            - bingo
            - --tls-enabled=true
            - --schedule=42 16 * * *
          image: another-app-image:dev
          imagePullPolicy: IfNotPresent
```
So it seems that env substitution does not work for array when you want to add an element to an array which is not a map.
