### ISSUE TITLE
Quotes are being removed

### ISSUE THREAD

**Issue by IdanAdar** [mikefarah/yq#169]
Given this:

```
env:
            - name: "CLUSTER_NAME"
              value: "<YOUR_CLUSTER_NAME>"
            - name: "NRIA_LICENSE_KEY"
              value: "<YOUR_LICENSE_KEY>"
            - name: "NRIA_VERBOSE"
              value: "0"
```

How can I insert a new value but preserve the quotes?
```
yq w -d3 -i newrelic-infrastructure-k8s-latest.yaml spec.template.spec.containers[0].env[1].value 1234
```
The above command inserts it w/out quotes, but `"1234"` also doesn't.

The result is:
```
env:
        - name: CLUSTER_NAME
          value: <YOUR_CLUSTER_NAME>
        - name: NRIA_LICENSE_KEY
          value: 1234
        - name: NRIA_VERBOSE
          value: "0"
        - name: NRIA_DISPLAY_NAME
```
