### ISSUE TITLE
[Feature Request] Add Option to 'Keep Order' of Items When Converting

### ISSUE THREAD

**Issue by luxlogica** [mikefarah/yq#170]
When yq converts from yaml to json, it seems to reverse the order of items (key-value pairs). Given the following _'input.yml'_ yaml document...:

``` yaml
title: Page
pages: true
options:
  template: true
files: false
fields:
  title:
    label: Title
    type:  text
  text:
    label: Text
    type:  textarea
```

...and running `yq r -j input.yml > output.json`, in _'output.json'_ we get:

``` json 
{
  "fields": {
    "text": {
      "label": "Text",
      "type": "textarea"
    },
    "title": {
      "label": "Title",
      "type": "text"
    }
  },
  "files": false,
  "options": {
    "template": true
  },
  "pages": true,
  "title": "Page"
}
```

It seems that the order of items - at the root and first-child levels - is reversed. While this may not be an issue in most use-cases, it does present a problem for some. It would be wonderful if we could have a flag/option to keep the same order of key-value pairs as in the original yaml file.
