### ISSUE TITLE
Multiply (merge) support appending arrays without creating duplicates

### ISSUE THREAD

**Issue by mikkelnygard** [mikefarah/yq#1702]
**Request**
When merging yaml files containing arrays using the "+" flag, it will create duplicates if some of the arrays are equal in the two documents. I would like an additional flag("a" in the example) which appends lists without creating duplicates.

**Example**
If we have data1.yml like:

```yaml
equalList:
  - a
  - b
changedList:
  - a
  - b
```

And data2.yml like:

```yaml
equalList:
  - a
  - b
changedList:
  - c
```

And we run a command:

```bash
yq eval-all '. as $item ireduce ({}; . *+ $item)' data1.yml data2.yml
```

the current output is:

```yaml
equalList:
  - a
  - b
  - a
  - b
changedList:
  - a
  - b
  - c
```

With a  new flag ("a" in this example) the output should be:
```bash
yq eval-all '. as $item ireduce ({}; . *a $item)' data1.yml data2.yml
```

```yaml
equalList:
  - a
  - b
changedList:
  - a
  - b
  - c
```
