### ISSUE TITLE
Unexpected entry when doing a deep search update.

### ISSUE THREAD

**Issue by mjallday** [mikefarah/yq#1704]
**Describe the bug**
When using the [deep splat](https://mikefarah.gitbook.io/yq/v/v3.x/usage/path-expressions#deep-splat) I'm experiencing unexpected behavior where it adds child elements instead of matching.

Version of yq: yq (https://github.com/mikefarah/yq/) version v4.33.3
Operating system: osx 13.4 (22F66)
Installed via: homebrew

**Input Yaml**

`data1.yml`:
```yaml
global:
  # we disable this in ci since it creates a new rollout by default.
  experiments:
    enabled: true

some-app:
  containers:
    app:
      image:
        repository: my-container
        tag: development-1.381.1
        pullPolicy: IfNotPresent

```

**Command**
The command you ran:
```sh
yq eval -i '.*.containers.**.image |= select(.repository=="my-container").tag |= "foo"' data1.yml
```

**Actual behavior**

```yaml
global:
  # we disable this in ci since it creates a new rollout by default.
  experiments:
    enabled: true
  containers:
    '**':
      image: null
some-app:
  containers:
    app:
      image:
        repository: my-container
        tag: foo
        pullPolicy: IfNotPresent
```

**Expected behavior**

```yaml
global:
  # we disable this in ci since it creates a new rollout by default.
  experiments:
    enabled: true
some-app:
  containers:
    app:
      image:
        repository: my-container
        tag: foo
        pullPolicy: IfNotPresent
```

**Additional context**
Looking for help to stop it writing in the following when running

```yaml
containers:
    '**':
      image: null
```

**Comment by mikefarah** [comment]
You're looking at the v3 docs when running v4 of yq - which is quite different.

To get what you want, you can do it like so:

```
yq '(.. | select(.repository == "my-container") | .tag) = "foo"' examples/sample.yaml
```

Explanation:
- `..` matches all the nodes in the yaml file
- `select(.repository == "my-container")` selects the node that has a key repository and value 'my-container'
- I used `=` instead of `|=`, though both will work in this case, typically you'd use `|=` when you want to update the value w.r.t the previous value (e.g. increment a number, concat a string).

**Comment by mjallday** [comment]
@mikefarah I've noticed unexpected behavior when the yaml gets more complex. are you able to comment on this (or lmk if I should open an additional ticket)

when i extend the yaml like so

```yaml
global:
  # we disable this in ci since it creates a new rollout by default.
  experiments:
    enabled: true

some-app:
  containers:
    app:
      image:
        repository: my-container
        tag: development-1.381.1
        pullPolicy: IfNotPresent

      # any list here will crash us
      volumeMounts: []
```

When I run the above command it will start crashing with 

```
Error: cannot index array with 'repository' (strconv.ParseInt: parsing "repository": invalid syntax)
```

Any ideas how to work around this?
