### ISSUE TITLE
Comments are missing when querying sub nodes

### ISSUE THREAD

**Issue by stang** [mikefarah/yq#1726]
**Describe the bug**
When querying a sub node that contains comments, it looks like the _foot comment_ are associated with the _parent node_ instead of the correct one.

Version of yq: v4.34.2
Operating system: mac
Installed via: binary release

**Input Yaml**

data1.yml:
```yaml
foo:
  bar:
    # comment1 - which is under the 'bar' key. It's preserved, as expected.
    - baz: value
      # comment2 - which is under the 'baz' value. It's also preserved when requesting '.foo.bar'
    # comment3 - which is missing but i'd expect to see since it's at the same level of indentation as comment1.
```

**Command**
The command you ran:
```
yq '.foo.bar' data1.yml
```

**Actual behavior**

```yaml
# comment1 - which is under the 'bar' key. It's preserved, as expected.
- baz: value
  # comment2 - which is under the 'baz' value. It's also preserved when requesting '.foo.bar'
```

**Expected behavior**

```yaml
# comment1 - which is under the 'bar' key. It's preserved, as expected.
- baz: value
  # comment2 - which is under the 'baz' value. It's also preserved when requesting '.foo.bar'
# comment3 - which is missing but i'd expect to see since it's at the same level of indentation as comment1. Note: it shows up when querying '.foo'
```

**Additional context**

Note: the `comment3` shows up if we query `.foo`, which is the parent of the node which the comment belongs to (ie: `.bar`)
