### ISSUE TITLE
Document selection of elements by value

### ISSUE THREAD

**Issue by rgm3** [mikefarah/yq#173]
If there is a way to select an array element by value then please add it to the read examples.
Perhaps this ticket could be blocked by "add a way to select portions of the array by value."

For example, given:
```yaml
outputs:
  - foo:
    enabled: false
  - bar:
    enabled: true
  - baz:
    cat: pretty
```

I'm hoping to understand how to select the 'baz' array element at index 2 to examine its interesting properties.  I'm also hoping to understand how to select the "bar" element at index 1 by filtering for "enabled=true."

**Comment by mikefarah** [comment]
This would be a very cool feature, but unfortunately you cannot do that in yq yet.

**Comment by djsd123** [comment]
Yep, filtering by value would be a major improvement.  💯

**Comment by fentas** [comment]
I have a use case based on this but is somewhat different.

**input**
```yaml
kind: Ingress
metadata:
  name: test
---
kind: Deployment
metadata
  name: foo
---
[...]
---
kind: Ingress
metadata:
  name: second
```

Now I would like to do
```sh
$ yq 'filter(.kind == "Ingress")'
```
```yaml
kind: Ingress
metadata:
  name: test
---
kind: Ingress
metadata:
  name: second
```
