### ISSUE TITLE
Ignore non-utf8 entries when base64 decoding

### ISSUE THREAD

**Issue by timtimtalabim** [mikefarah/yq#1731]
**Please describe your feature request.**
Hello, I wish I could use yq to decode base64 entries while skipping/ignoring entries that are non-utf8 entries

**Describe the solution you'd like**
If we have data1.yml like:
```yaml
data:
   secretutf-8: U2FtcGxlIEJhc2U2NCBFbmNvZGluZw==
   secretbinarydata: "binary data encoded into base64"
   secretutf-8again: aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj1kUXc0dzlXZ1hjUQ==
```
And we run a command like:

yq '.data[] |= @base64d' 'data1.yml'

**Expected Behavior**

```yaml
data:
  secretutf-8: "Sample Base64 String"
  secretbinarydata: "binary data encoded into base64"
  secretutf-8again: "Sample Base64 String 2"
```

**Actual Behavior**

```yaml
data:
  secretutf-8: "Sample Base64 String"
  secretbinarydata: "binary data encoded into base64"
```

It stops at secretbinarydata due to the error

**Describe alternatives you've considered**
My temporary solution involves using select to skip entries containing binary data, however for future updates, I will have to manually input an entry if it contains any binary data.
