### ISSUE TITLE
Can't delete elements by wildcard, but can read them

### ISSUE THREAD

**Issue by dbsanfte** [mikefarah/yq#175]
Given the following Docker Compose yml:

```
version: '3.3'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      SOME_VAR: 1234
    ports:
      - 1234:1234
  db2:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      SOME_OTHER_VAR: 5678
    ports:
      - 1234:1234
```

Listing items by wildcard works:

`yq r docker-compose.yml 'services.*.environment' `

But deleting them doesn't:

`yq d docker-compose.yml 'services.*.environment' `

Any chance this could be fixed?
