### ISSUE TITLE
Unexpected repeated output.

### ISSUE THREAD

**Issue by vx-github** [mikefarah/yq#1754]
**Describe the bug**
I was trying to create some yaml, but got some unexpected outcome:

First I added one element and than a second:
```
❯ yq --null-input '.first = "1"'
first: "1"

❯ yq --null-input '.first = "1", .second = ["2"]'
first: "1"
second:
  - "2"
```

When the third element was added, something unexpected happened:
```
❯ yq --null-input '.first = "1", .second = ["2"], .third = "3"'
first: "1"
second:
  - "2"
third: "3"
first: "1"
second:
  - "2"
third: "3"
```
I didn't expect the output to repeat itself, I guess a bug?

```
❯ yq --version
yq (https://github.com/mikefarah/yq/) version v4.34.2
```
The same happened with the Docker image:
```
❯ docker run -ti --rm --name yq mikefarah/yq:4.34.2 --null-input '.first = "1", .second = ["2"], .third = "3"'
```

Version of yq: 4.34.2
Operating system: linux + windows + docker
Installed via: binary release + docker image

**Input Yaml**
```
--null-input OR file
```

**Command**
```
yq --null-input '.first = "1", .second = ["2"], .third = "3"'
```

**Actual behavior**
Got output:
```yaml
first: "1"
second:
  - "2"
third: "3"
first: "1"
second:
  - "2"
third: "3"
```

**Expected behavior**
Expected output:
```yaml
first: "1"
second:
  - "2"
third: "3"
```
