### ISSUE TITLE
TOML nested array of tables with arrays breaks v4.35.1

### ISSUE THREAD

**Issue by mbigras** [mikefarah/yq#1758]
**Describe the bug**

Hi! First of all, thank you so much for making and maintaining yq; I happily use your tool everyday and especially thank you for starting work on TOML support—see _https://github.com/mikefarah/yq/issues/1364_ issue!

**Issue:** I noticed that yq breaks when parsing TOML nested array of tables _with arrays_ (lol)—see _[Array of Tables](https://toml.io/en/v1.0.0#array-of-tables)_ section. **Workaround:** To work around, you can parse TOML with [_tomljson_](https://github.com/pelletier/go-toml) command, then pipe JSON to yq.

Version of yq: v4.35.1
Operating system: Mac and Linux
Installed via: Homebrew and Docker

**Input TOML**
data1.toml:
```toml
[[fruits]]
name = "apple"
[[fruits.varieties]]  # nested array of tables
name = "red delicious"
```

**Command**
The command you ran:
```
yq -ptoml -oyaml data1.toml
```

**Actual behavior**

```
Error: bad file 'data1.toml': cannot index array with 'varieties' (strconv.ParseInt: parsing "varieties": invalid syntax)
```

**Expected behavior**

```yaml
fruits:
  - name: apple
    varieties:
      - name: red delicious
```

**Additional context**
I suspect this is a problem with yq because the [_tomljson_](https://github.com/pelletier/go-toml) command can handle _data1.toml_ like the following shell session illustrates:

```bash
$ tomljson /dev/stdin <<'TOML' | yq -P
[[fruits]]
name = "apple"
[[fruits.varieties]]  # nested array of tables
name = "red delicious"
TOML
fruits:
  - name: apple
    varieties:
      - name: red delicious
```

Again, thank you for yq and please advise if I should do any other experiments.
