### ISSUE TITLE
dot want to point at document root node absolutely

### ISSUE THREAD

**Issue by wangrongjun** [mikefarah/yq#1759]
I have a yaml as below, and I want to do a pre-handle, replace ${xxx} to actual value, which from yaml itself.

```yaml
es-host: 192.168.1.101
gerrit-host: 192.168.1.102
deploy-info:
  es:
    server: ${es-host}:9200
  gerrit:
    server: ${gerrit-host}:8080
```

So, I replace by sub and eval:

```bash
yq -i '(.. | select(tag=="!!str")) |= (. | sub("\$\{(.+?)\}", eval(".$1")))' test.yaml
```

I expected:

```yaml
es-host: 192.168.1.101
gerrit-host: 192.168.1.102
deploy-info:
  es:
    server: 192.168.1.101:9200
  gerrit:
    server: 192.168.1.102:8080
```

But actually is:

```yaml
es-host: 192.168.1.101
gerrit-host: 192.168.1.102
deploy-info:
  es:
    server: :9200
  gerrit:
    server: :8080
```

You see, the eval can't get expected value, it just null. Because dot point at current node position after select, no longer point at document root position, and .deploy-info.es.server.es-host not exist, so eval return null.

Is there any way or a sign, can point at document root node absolutely? 
Such as !, if I use eval("!.es-host"), it will find by document root absolutely, not relatively.
Thanks.
