### ISSUE TITLE
load_props can't read dotted key

### ISSUE THREAD

**Issue by steled** [mikefarah/yq#1764]
**Describe the bug**
I'm trying to use merge from properties to set a yaml value via `load_props` with a properties file.
Unfortunately the yaml key is dotted and it seems that this is not working currently. 

Note that any how to questions should be posted in the discussion board and not raised as an issue.

Version of yq: 4.34.1
Operating system: Ubuntu 22.04.2 LTS
Installed via: binary release

**Input Yaml**

flatcar.yml:
```yaml
apiVersion: cluster.k8s.io/v1alpha1
kind: MachineDeployment
metadata:
  annotations:
    k8c.io/operating-system-profile: test
  name: test
  namespace: kube-system
```

machines_flatcar.properties:
```properties
metadata.name = flatcar
metadata.annotations.k8c.io/operating-system-profile = flatcar
```

**Command**
The command you ran:
```
yq '. *= load_props("machines_flatcar.properties:")' flatcar.yml
```

**Actual behavior**

```yaml
apiVersion: cluster.k8s.io/v1alpha1
kind: MachineDeployment
metadata:
  annotations:
    k8c.io/operating-system-profile: test
  k8c:
      io/operating-system-profile: flatcar
  name: flatcar
  namespace: kube-system
```

**Expected behavior**

```yaml
apiVersion: cluster.k8s.io/v1alpha1
kind: MachineDeployment
metadata:
  annotations:
    k8c.io/operating-system-profile: flatcar
  name: flatcar
  namespace: kube-system
```
