### ISSUE TITLE
yq del with vars

### ISSUE THREAD

**Issue by evelizg** [mikefarah/yq#1771]
**yq del with vars doesn't work**

Version of yq: 4.35.1
Operating system: linux
Installed via: docker

**Input Yaml**
I put this shell but doesn't work:
yaml is an environment variable
echo $yaml=.application.atlas.resource-bundle.test

data1.yml:
```yaml
application:
  atlas:
    resource-bundle:
      test: 7000
```

**Command**

```
yq -i 'del(yaml)' data1.yml
yq -i 'del(env(yaml))' data1.yml
yq -i 'del(strenv(yaml))' data1.yml
```

**Actual behavior**

```yaml
application:
  atlas:
    resource-bundle:
      test: 7000
```

**Expected behavior**

```yaml
application:
  atlas:
    resource-bundle:
```

**Additional context**
Please your support, I tried all ways but doesn't work
