### ISSUE TITLE
Roundtrip to/from json breaks yaml

### ISSUE THREAD

**Issue by eddiewebb** [mikefarah/yq#179]
Taking a simple yml file with long, or multi-line values, a roundtrip to and from JSON breaks it.

Given
```
steps:
  - run:
      name: Configure JFrog CLI
      command: jfrog rt c rt-server-1 --url=${ARTIFACTORY_URL} --apikey=${ARTIFACTORY_API_KEY} --interactive=false
```

When
`yq r -j sample.yml | yq r -`

The result is not consistent, and in fact breaks (in this example the value is a command that must remain on single line.

Output
```
steps:
- run:
    command: jfrog rt c rt-server-1 --url=${ARTIFACTORY_URL} --apikey=${ARTIFACTORY_API_KEY}
      --interactive=false
    name: Configure JFrog CLI
```

Related, if a pipe `|` is used in a value for multi-line, `yq` inserts an extraneous `-`

```
steps:
  - run:
      name: Some name
      command: |
        line 1
        line 2
```

```
steps:
  - run:
      name: Some name
      command: |-
        line 1
        line 2
```
