### ISSUE TITLE
Is there a way to add a comment to all values only?

### ISSUE THREAD

**Issue by jkaye2012** [mikefarah/yq#1807]
Hi there, thank you for this awesome tool!

I've been banging my head against a problem for a couple of hours and figured I might be able to get a quick answer here. Given a document like this one:

```yaml
flink:
  sources:
    trade_fills:
      type: TradeFill
      maxFetchTimeMs: 10
    inventory_updates:
      type: InventoryUpdate
      maxFetchTimeMs: 10
  sinks:
    total_inventory:
      type: TotalInventory
app: !!bt.inventory.InventoryAppConfig
  minimumRefreshIntervalMs: 86400000
```

Is there any way to get `yq` to output:

```yaml
flink:
  sources:
    trade_fills:
      type: TradeFill # comment
      maxFetchTimeMs: 10 # comment
    inventory_updates:
      type: InventoryUpdate # comment
      maxFetchTimeMs: 10 # comment
  sinks:
    total_inventory:
      type: TotalInventory # comment
app: !!bt.inventory.InventoryAppConfig
  minimumRefreshIntervalMs: 86400000 # comment
```

I've tried many different variations of selecting, recursing with `..`, `with_entries`, etc. but I can't seem to find a way to annotate only the values and not also the keys. The closest I've gotten is one of the first things I tried:

```bash
$ yq '.. line_comment='filename'' app/env\=prod/team\=combine/tg\=treasuries/app\=inventory/app.yaml 
flink:
  sources:
    trade_fills:
      type: TradeFill # app/env=prod/team=combine/tg=treasuries/app=inventory/app.yaml
      maxFetchTimeMs: 10 # app/env=prod/team=combine/tg=treasuries/app=inventory/app.yaml
    inventory_updates: # app/env=prod/team=combine/tg=treasuries/app=inventory/app.yaml
      type: InventoryUpdate # app/env=prod/team=combine/tg=treasuries/app=inventory/app.yaml
      maxFetchTimeMs: 10 # app/env=prod/team=combine/tg=treasuries/app=inventory/app.yaml
  sinks: # app/env=prod/team=combine/tg=treasuries/app=inventory/app.yaml
    total_inventory:
      type: TotalInventory # app/env=prod/team=combine/tg=treasuries/app=inventory/app.yaml
app: # app/env=prod/team=combine/tg=treasuries/app=inventory/app.yaml
!!bt.inventory.InventoryAppConfig
  minimumRefreshIntervalMs: 86400000 # app/env=prod/team=combine/tg=treasuries/app=inventory/app.yaml
```

But as you can see, some of the map keys get annotated (and, more importantly, the custom tag gets broken because of it!).

If there is a better place for me to ask this question, please let me know. And thanks again!
