### ISSUE TITLE
Decoding yaml with `from_yaml` only returns first document in a multi-doc yaml.

### ISSUE THREAD

**Issue by kirmsi** [mikefarah/yq#1812]
When trying to edit inline yaml values which consists of multiple documents, I would expect that I can concat commands which work normally. It seems that after decoding with `from_yaml` only the first document is getting decoded and the other documents not being read. 

Version of yq: v4.35.2
Operating system: linux
Installed via: snap

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
data1.yml:
```yaml
a: |
  ---
  b: another
  c: foo
  ---
  b: another
  d: baz
```

**Command**
The command you ran:
```
yq '.a |= (from_yaml | select(document_index==0).b = "boef" | to_yaml )' data1.yml
```

**Actual behavior**

```yaml
a: |-
  b: boef
  c: foo
```

**Expected behavior**

```yaml
a: |
  b: boef
  c: foo
  ---
  b: another
  d: baz
```

**Additional context**
My assumption that only the first document is accounted somewhat proves when you just try to get the data with different document_index after using `from_yaml`. With the command:
```
yq '.a | (from_yaml | select(document_index==0))' data1.yml
```
I get the first document; with the command:
```
yq '.a | (from_yaml | select(document_index==1))' data1.yml
``` 
I get an empty response. 

I also tried some shenanigans with defining the actual documents in a variable, but that didn't worked out as well.
```
yq '.a |= (from_yaml | select(di==0) as $a | select (di==1) as $b | $a.b = "boef" | ($a, $b) | to_yaml)' data1.yml
```

If I somehow did something wrong on my command, and there is a way to get the expected behaviour, please let me know.
