### ISSUE TITLE
yq can't parse yaml elements which has '.' separator

### ISSUE THREAD

**Issue by hpsocket** [mikefarah/yq#1818]
**Describe the bug**
yq can't parse yaml elements which has '.' separator.

Version of yq: 4.X.X
Operating system: mac/linux/windows/....
Installed via: docker/binary release/homebrew/snap/...

**Input Yaml**

sample1.yml
```yaml
hp.soa.web:
  app:
    id: "0010100001"
    name: hp-demo-bff-basic
    version: 0.3.0-SNAPSHOT
    organization: HP-Socket
    owner: Kingfisher
```

sample2.yml:
```yaml
management:
  endpoints:
    jmx.exposure.include: "*"
    web.base-path: /__admin
    web.exposure.include: "*"
```

**Command**
The command you ran:
```
yq '.hp.soa.web' sample1.yml
yq '.management.endpoints.web' sample2.yml
```

**Actual behavior**

```yaml
output: null
```

**Expected behavior**

```yaml
this: should really work
but: it strangely didn't
```
