### ISSUE TITLE
Inconsistent symbol processing of '.' separator

### ISSUE THREAD

**Issue by ldcsaa** [mikefarah/yq#1821]
**Describe the bug**
Inconsistent symbol processing of '.' separator.

Version of yq: 4.X.X
Operating system: mac/linux/windows/....
Installed via: docker/binary release/homebrew/snap/...

**Input Yaml**

bootstrap.yml:
```yaml
hp.soa.web:
  app:
    id: "0010100001"
management:
  endpoint:
    health.show-details: when-authorized
```

**Command**
The command you ran:
```
yq '.["hp.soa.web"].app.id' bootstrap.yml    # 1. OK
yq '.["hp.soa.web"]app.id' bootstrap.yml    # 2. FAIL
yq '.management.endpoint.["health.show-details"]' bootstrap.yml    # 3. OK
yq '.management.endpoint["health.show-details"]' bootstrap.yml    # 4. OK
```

**Actual behavior**

command 2 run fail: `Error: 1:16: invalid input text "app.id"`
but command 4 run OK

**Expected behavior**

both of command 2 and 4 run ***success*** or ***fail***.
