### ISSUE TITLE
Add ability to not eliminate blank lines when using sort_keys

### ISSUE THREAD

**Issue by snuggie12** [mikefarah/yq#1834]
**Please describe your feature request.**
Currently `sort_keys` eliminates blank lines. I'm curious if it would be possible to not do that.

**Describe the solution you'd like**
Given the following yaml

```yaml
# Overall comment unrelated to first key

# Comment related to first key
zfirstKey:
  asubKey: foo

# Comment related to second key
secondKey:
  subKey: bar
```

And we run a command:

```bash
yq 'sort_keys(..)' foo.yaml
```

it could output

```yaml
# Overall comment unrelated to first key

# Comment related to second key
secondKey:
  subKey: bar

# Comment related to first key
zfirstKey:
  asubKey: foo
```

**Additional context**
I'm unsure if additional options would need to be provided on what to do if people use a different format like a blank line on both the top and bottom of the comment. Honestly this is just an annoyance at best and I can see this problem possibly being too complicated that it's not worth implementing.
