### ISSUE TITLE
yq strips document separator when adding a comment

### ISSUE THREAD

**Issue by pcppcp** [mikefarah/yq#1836]
**Describe the bug**
I am trying to add a comment at the top of a multi-document yaml file. `yq` unfortunately strips the first document separator line that is expected by downstream yaml linters I use.

Version of yq: 4.35.2
Operating system: linux
Installed via: binary release

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
data1.yml:
```yaml
---
key: a
---
key: b
```

**Command**
The command you ran:
```
yq eval-all 'select(documentIndex == 0) headComment|="A comment..."' data1.yml
```

**Actual behavior**

```yaml
# I am a comment

key: a
---
key: b
```

**Expected behavior**

```yaml
---
# I am a comment
key: a
---
key: b
```
