### ISSUE TITLE
Allow shebang on the first line of a file of `yq` filters

### ISSUE THREAD

**Issue by rlee-arx** [mikefarah/yq#1851]
**Please describe your feature request.**
To enable the creation of `.yq` executable files, I would like `yq` to allow the first line of a `--from-file` to be a "shebang" (`#!`) which is subsequently ignored in the interpretation of the file contents.

**Describe the solution you'd like**
If we have data1.yml like:

```yaml
country:
  Australia:
    - city: Perth
```

and data2.yml like:

```yaml
country:
  Australia:
    - city: Brisbane
```

and merge-aus.yq like:
```
#!/usr/bin/env yq --null-input --from-file
load("data1.yml") as $perth |
load("data2.yml") as $bris |
$perth *+ $bris
```

And we run a command:

```bash
./merge-aus.yq
```

it could output

```yaml
country:
  Australia:
  - city: Perth
  - city: Brisbane
```

**Describe alternatives you've considered**
I usually just write a shell script wrapper called `merge-aus.yq` which calls the appropriate `yq --from-file` command, but first class support would be awesome.

I have cloned the source locally, and will fork to create a PR if I can get to it :)
