### ISSUE TITLE
Breaking change in v4.40.1 pre-release - explode (merge using anchors) no longer works

### ISSUE THREAD

**Issue by kirici** [mikefarah/yq#1861]
**Describe the bug**

Note that any how to questions should be posted in the discussion board and not raised as an issue.

Version of yq: 4.40.1
Operating system: Linux 6.5.6-300.fc39.x86_64
Installed via: go install github.com/mikefarah/yq/v4@v4.40.1 (also tested using latest (currently 79a50b9c2007669d60c45bcaffc4917e6e4c0760))

**Input Yaml**

template.yaml:
```yaml
.defaults: &defaults
  pantry: [sauce]
options:
- &lunch
  protein: meat
- &dinner
  protein: eggs
---
# 1.
<<: *defaults
buy:
- *lunch
---
# 2.
<<: *defaults
buy:
- *lunch
- *dinner
```

**Command**
The command you ran:
```
yq 'explode(.) | select(di == 2)' template.yaml
```

**Actual behavior**
```yaml
buy:
  - *lunch
  - *dinner
```

**Expected behavior**

```yaml
pantry: [sauce]
buy:
  - protein: meat
  - protein: eggs
```

**Additional context**
Working up until v4.35.2
