### ISSUE TITLE
CRLF Issue with document headers

### ISSUE THREAD

**Issue by mikefarah** [mikefarah/yq#1871]
@mikefarah I'm not sure if I should be reporting this here, as it seems to be related to the CrLf handling, or if I should open a new issue for this.... Let me know if I need to move this to a new issue.

Platform: Windows
Input file:
```yaml
---
# document 1 start comment
test:
  sub:
   key: value
---
# document 2 start comment
foo:
  bar:
   key: value
```
**Line Ending**: CrLf

`yq '.' test-in.yaml`:
```yaml
---
# document 1 start comment
test:
  sub:
    key: value
# document 2 start comment
---
foo:
  bar:
    key: value
```
Note how the "document 2 start comment" has **moved** from the top of the second document to the bottom of the first document!

This is causing havoc with the Kubernetes manifest that I'm manipulating with `yq`...

If I explicitly change the line endings of `test-in.yaml` to UNIX-style "Lf", the issue does not appear.

_Originally posted by @boekhold in https://github.com/mikefarah/yq/issues/1860#issuecomment-1812482835_

**Comment by mikefarah** [comment]
Digging into this - it seems like its an issue with the underlying go-yaml parse :/ possibly related to https://github.com/go-yaml/yaml/issues/893. If it helps, I noticed that if the input yaml has an extra line break between the document separator and the document 2 comment, then it works

```
---
# document 1 start comment
foo: dog
---

# document 2 start comment
foo: cat

```

**Comment by boekhold** [comment]
I noticed release https://github.com/mikefarah/yq/releases/tag/v4.40.1 which mentions removing the dependency on go-yaml, so I figured I give this a test (with v4.43.1), and unfortunately this didn't fix this issue. In fact, the output is different now:
```
# document 1 start comment
test:
  sub:
    key: value
# document 2 start comment

---
foo:
  bar:
    key: value
```
Notice the additional blank line between "document 2 start comment" and the document separator.
