### ISSUE TITLE
Comments stripped when using `env(VAR)`

### ISSUE THREAD

**Issue by sboardwell** [mikefarah/yq#1873]
**Describe the bug**

Note that any how to questions should be posted in the discussion board and not raised as an issue.

Version of yq: 4.40.2
Operating system: linux
Installed via: docker, binary release, and homebrew

**Input Yaml**

commented.yml:
```yaml
drinks:
  # first
  - id: beer
  # overriding occurrence
  - id: beer
```

**Command**
The command you ran (NOTE: the `deDupes` var contains the comment):
```
deDupes=$(yq '.drinks|reverse|unique_by(.id)' commented.yaml) yq eval '.drinks = env(deDupes)' commented.yaml
```

**Actual behavior**

```yaml
drinks:
  - id: beer
```

**Expected behavior**

```yaml
drinks:
  # overriding occurrence
  - id: beer
```
