### ISSUE TITLE
how to use yq for variable parse.

### ISSUE THREAD

**Issue by zszen** [mikefarah/yq#1878]
yaml:
```
a:
  b: ${c.c1}{d.d1}
c:
  c1: http://
d:
  d1: domain.com
```

I want get a.b with "http://domain.com" value

**Comment by mikefarah** [comment]
You could do it like this:

```
a:
  b: .c.c1 + .d.d1
c:
  c1: http://
d:
  d1: domain.com
```

Then:

```
yq '.a.b = eval(.a.b)' file.yaml
```

Idea is to put a yq expression as the 'b'  value, then evaluate it :)

**Comment by mikefarah** [comment]
Output:

```
a:
  b: http://domain.com
c:
  c1: http://
d:
  d1: domain.com

```
