### ISSUE TITLE
Change in behaviour around merge between 4.35.2 and 4.40.3

### ISSUE THREAD

**Issue by Thrillpool** [mikefarah/yq#1881]
**Describe the bug**
```
./yq '(.a | map(select(.b == "1")))[] *= load("override.yml")' blah.yml
```
has different output between 4.35.2 and 4.40.3

Version of yq: 4.40.3
Operating system: windows
Installed via: binary release

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
blah.yml:
```yaml
a:
  - b: 1
    c: 2
```

override.yml:
```yaml
c: 7
```

**Command**
The command you ran:
```
yq  '(.a | map(select(.b == "1")))[] *= load("override.yml")' blah.yml
```

**Actual behavior**

```yaml
a:
  - b: 1
    c: 2
```

**Expected behavior**

```yaml
a:
  - b: 1
    c: 7
```
