### ISSUE TITLE
merge example not working

### ISSUE THREAD

**Issue by sombriks** [mikefarah/yq#1882]
**Describe the bug**

trying to merge two distinct kubeconfig files

read this example https://mikefarah.gitbook.io/yq/usage/tips-and-tricks#merge-combine-all-documents-into-one

it's not working

```bash
[sombriks@lucien .kube]$ yq ea '(..  lineComment |= filename + ":" + line) | select(fi==0) * select(fi==1)' config-eks config-k0s 
```

Version of yq: 4.40.3
Operating system: Fedora 39 Linux
Installed via: go install github.com/mikefarah/yq/v4@latest

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
config-eks:
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: somedata==
    server: https://someaddr.gr7.us-east-1.eks.amazonaws.com
  name: cluster-dev
- cluster:
    certificate-authority-data: anotherdata==
    server: https://anotheraddr.gr7.us-east-1.eks.amazonaws.com
  name: cluster-stage
- cluster:
    certificate-authority-data: moredata==
    server: https://moreaddr.gr7.us-east-1.eks.amazonaws.com
  name: cluster-prod
contexts:
- context:
    cluster: cluster-dev
    user: cluster-dev
  name: cluster-dev
- context:
    cluster: cluster-stage
    user: cluster-stage
  name: cluster-stage
- context:
    cluster: cluster-prod
    user: cluster-prod
  name: cluster-prod
current-context: cluster-prod
kind: Config
preferences: {}
users:
- name: cluster-dev
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - cluster-dev
      - --output
      - json
      command: aws
      env:
      - name: AWS_PROFILE
        value: myprofile
- name: cluster-stage
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - cluster-stage
      - --output
      - json
      command: aws
      env:
      - name: AWS_PROFILE
        value: myprofile
- name: cluster-prod
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - cluster-prod
      - --output
      - json
      command: aws
      env:
      - name: AWS_PROFILE
        value: myprofile

```

config-k0s:
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: distinctdata=
    server: https://192.168.1.105:6443
  name: local
contexts:
- context:
    cluster: local
    user: user
  name: Default
current-context: Default
kind: Config
preferences: {}
users:
- name: user
  user:
    client-certificate-data: otherdistinctdata=
    client-key-data: distinctdataagain==

```

**Command**

The command you ran:
```
yq ea '(..  lineComment |= filename + ":" + line) | select(fi==0) * select(fi==1)' config-eks config-k0s
```

**Actual behavior**

```yaml
apiVersion: v1 # config-k0s:1
clusters:
  - cluster:
      certificate-authority-data: distinctdata= # config-k0s:4
      server: https://192.168.1.105:6443 # config-k0s:5
    name: local # config-k0s:6
contexts: # config-k0s:3
  - context:
      cluster: local # config-k0s:9
      user: user # config-k0s:10
    name: Default # config-k0s:11
current-context: Default # config-k0s:12
kind: Config # config-k0s:13
preferences: {} # config-k0s:14
users: # config-k0s:8
  - name: user # config-k0s:16
    user:
      client-certificate-data: otherdistinctdata= # config-k0s:18
      client-key-data: distinctdataagain== # config-k0s:19
```

**Expected behavior**

the two kubeconfig merged

**Additional context**
