### ISSUE TITLE
number sign # cause blank line

### ISSUE THREAD

**Issue by willzhang** [mikefarah/yq#1883]
**Describe the bug**

If there is a # sign at the end of a yaml file, a blank line will appear when using yq -- inplace.

Version of yq: v4.40.2
Operating system: ubuntu 22.04
Installed via: binary release

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
data1.yml:
```yaml
apiVersion: pingcap.com/v1alpha1
kind: TidbDashboard
metadata:
  name: basic
spec:
  baseImage: pingcap/tidb-dashboard
  version: latest
  ## tidb cluster to be monitored
  ## ** now only support monitoring one tidb cluster **
  clusters:
    - name: basic
  ## describes the compute resource requirements and limits.
  ## Ref: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
  requests:
    #   cpu: 1000m
    #   memory: 1Gi
    storage: 10Gi
  # limits:
  #   cpu: 2000m
  #   memory: 2Gi
```

**Command**
The command you ran:
```
yq --inplace '.spec.service.type="NodePort"' tidb-dashboard.yaml
```

**Actual behavior**

```yaml
apiVersion: pingcap.com/v1alpha1
kind: TidbDashboard
metadata:
  name: basic
spec:
  baseImage: pingcap/tidb-dashboard
  version: latest
  ## tidb cluster to be monitored
  ## ** now only support monitoring one tidb cluster **
  clusters:
    - name: basic
  ## describes the compute resource requirements and limits.
  ## Ref: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
  requests:
    #   cpu: 1000m
    #   memory: 1Gi
    storage: 10Gi
  # limits:
  #   cpu: 2000m
  #   memory: 2Gi

  service:
    type: NodePort
```

**Expected behavior**

```yaml
apiVersion: pingcap.com/v1alpha1
kind: TidbDashboard
metadata:
  name: basic
spec:
  baseImage: pingcap/tidb-dashboard
  version: latest
  ## tidb cluster to be monitored
  ## ** now only support monitoring one tidb cluster **
  clusters:
    - name: basic
  ## describes the compute resource requirements and limits.
  ## Ref: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
  requests:
    #   cpu: 1000m
    #   memory: 1Gi
    storage: 10Gi
  # limits:
  #   cpu: 2000m
  #   memory: 2Gi
  service:
    type: NodePort
```

**Additional context**
i don't want this blank line
![image](https://github.com/mikefarah/yq/assets/33590311/2be8b652-7eec-4776-8948-94f7000f4db8)
