### ISSUE TITLE
Preserve formatting with in place writing

### ISSUE THREAD

**Issue by anoop-ayla** [mikefarah/yq#1884]
**Describe the bug**
`yq w -i file.yaml key value` it does the expected work but breaks the default preexisting formatting if my files are having values as reference variables like following
```yaml
key: {{ xxx }}-{{ yyy }}
#or
key: "{{ xxx }}-{{ yyy }}"
```
then after yq cmd execution each lines having formation like above breaks into something like below
```yaml
key: {{ xxx }}-{{ yyy
}}
#or
key: "{{ xxx }}-{{ yyy
}}"
```
and also if file having key values pair like following
```yaml
key: {{ .Values.cluster.aws_region }}
```
It gets strangely broken as followed
```yaml
region: {? {.Values.cluster.aws_region: ''} : ''}
```

**Version of yq:** yq version 3.1.2
**Operating system:** linux Ubuntu 20.04.2 LTS

**Yaml**
aws.yaml:

```yaml
aws:
  endpoint: "https://s3.{{ .Values.cluster.aws_region }}.amazonaws.com/"
  region: {{ .Values.cluster.aws_region }}
  topic_prefix: "arn:aws:sns:{{ .Values.cluster.aws_region }}:{{ .Values.cluster.aws_uri }}"
  sns:
    endpoint: sns.{{ .Values.cluster.aws_region }}.amazonaws.com
```

**Command**
The command I ran:
```
yq w -i aws.yaml testkey testvalue
```

**Actual behavior**

```yaml
aws:
  endpoint: "https://s3.{{ .Values.cluster.aws_region }}.amazonaws.com/"
  region: {? {.Values.cluster.aws_region: ''} : ''}
  topic_prefix: "arn:aws:sns:{{ .Values.cluster.aws_region }}:{{ .Values.cluster.aws_uri
    }}"
  sns:
    endpoint: sns.{{ .Values.cluster.aws_region }}.amazonaws.com
  testkey: testvalue
```

**Expected behavior**

```yaml
aws:
  endpoint: "https://s3.{{ .Values.cluster.aws_region }}.amazonaws.com/"
  region: {{ .Values.cluster.aws_region }}
  topic_prefix: "arn:aws:sns:{{ .Values.cluster.aws_region }}:{{ .Values.cluster.aws_uri }}"
  sns:
    endpoint: sns.{{ .Values.cluster.aws_region }}.amazonaws.com
  testkey: testvalue
```

**Additional context**
I have already tried `yq w -i file.yaml 'key' 'value'` or `yq w -i file.yaml "key" "value"` but it didn't help.
