### ISSUE TITLE
github action with `uses: mikefarah/yq@v4` actually uses v3

### ISSUE THREAD

**Issue by m-kuhn** [mikefarah/yq#1908]
**Describe the bug**

When trying to use the latest version of a major series in a github action, it is common practice to use a moving tag (random example: https://github.com/actions/cache). So instead of using directly the current `@v4.40.5` specify `@v.4`.
On the yq repository, there is currently a branch available with the version `3.4.1`, which can be quite confusing as this will just error out with "unknown command" with the examples provided in the documentation.

```yaml
      - name: Get yq version
        id: get_yq_version
        uses: mikefarah/yq@v4
        with:
          cmd: yq -V
```

Will print

```
yq version 3.4.1
```

### Proposal
Either delete the `v4` branch to be clear that this scheme is not supported or create a moving `v4` tag that's updated to the latest release in the series.

Thanks !
