### ISSUE TITLE
Make `--color` and `--prettyPrint` work together

### ISSUE THREAD

**Issue by qilyn** [mikefarah/yq#1927]
**Please describe your feature request.**
Just installed `yq` today, please bear with me :)
Great tool so far, I would love it if the arguments `prettyPrint` and `color` would play nicely together, i.e. create a nice diff and then color it.

Given the diff of two files (`yq compare --color`) is:
```yaml
Tags:
-  Project: ProjectName
-  Environment: staging
+  Environment: staging
+  Project: ProjectName
   product: ProjectName
   program: name_program
```
and the same input but with the command `yq compare -P`:
```text
 Tags:
-  Project: ProjectName
   Environment: staging
+  Project: ProjectName
   product: ProjectName
   program: name_program
```

When we run a command asking for "pretty" and "color":

```bash
yq compare -CP file1.yaml file2.yaml
```

Then it could output the diff both prettily and with syntax highlighting:

```yaml
 Tags:
-  Project: ProjectName
   Environment: staging
+  Project: ProjectName
   product: ProjectName
   program: name_program
```

**Describe alternatives you've considered**
This is a nice to have, again I'm fresh to the tool, so no suggestions or additional context! (Honestly `-P` is the most useful feature and I'm going to be using it a lot. Thanks so much for developing this tool :+1:)
