### ISSUE TITLE
yq cannot recognize YAML keys with the same name and indentation

### ISSUE THREAD

**Issue by mylovesaber** [mikefarah/yq#1955]
yq   v4.41.1
Operating system: linux(seems not caused by system but the design of yq)
Installed via: standalone binary release from github

# Question 1
aa.yml:
```yaml
aaa:
  bbb: [1 2]
  bbb:
```

**Command**

```bash
# will not treat it as an error. Is this yaml file legal?
# command:  yq '.' aa.yml


# command:  yq  '.aaa.bbb[] | tag'  aa.yml
# yq output:  !!seq    [if set value of bbb like this:]
aaa:
  bbb: 
  bbb: [1 2]

# yq output:  !!null    [if set value of bbb like this:]
aaa:
  bbb: [1 2]
  bbb:


# command:  yq  '.aaa.bbb[]'  aa.yml
# if set value of bbb like this:
aaa:
  bbb: [1 2]
  bbb: [3 4]
# yq output:
3
4
```

My question:  

Is it legal in YAML for the 'aaa' object to have two objects both named 'bbb'? 
If legal, why not merge the values of the two objects, but only output the values of the last 'bbb' object ? Is it a bug?

# Question 2

Four command execute one by one:
```bash
yq   '.group.exclude | tag'    bbb.yml
yq   '.group.exclude[] | tag'    bbb.yml
yq   '.group.exclude'    bbb.yml
yq   '.group.exclude[]'     bbb.yml
```

（The lines with comments are the output results）
Different  output  with  different  yaml  info:
```yaml
group:
  exclude: system
  # !!str
  # no output
  # system
  # no output


group:
  exclude: aaa
    - system
  # !!str
  # no output
  # aaa - system
  # no output


group:
  exclude: aaa
    - 
    - system
  # !!str
  # no output
  # aaa - - system
  # no output


group:
  exclude: aaa
    - 
  # !!str
  # no output
  # aaa -
  # no output
```
My question: 

Is it legal for the value of an object to include both a string and a list? 
If legal, how should it be determined?
