### ISSUE TITLE
gitlab env variables with yq

### ISSUE THREAD

**Issue by Nurlan199206** [mikefarah/yq#1959]
i'm trying replace image tag with yq

version:  `yq (https://github.com/mikefarah/yq/) version v4.42.1`
 
in console my result working perfect, but in gitlab ci it's not putting env variables in `deployment.yaml` file

`cat deployment.yaml | yq '.spec.template.spec.containers.[0].image = "$CI-REGISTRY:$CI_COMMIT_BRANCH-$CI_PIPELINE_ID-$CI_COMMIT_SHORT_SHA"' deployment.yaml | sponge deployment.yaml`

```
         image: $CI-REGISTRY:$CI_COMMIT_BRANCH-$CI_PIPELINE_ID-$CI_COMMIT_SHORT_SHA
          livenessProbe:
            failureThreshold: 3
            httpGet:

```

also i've tried like in this thread https://github.com/mikefarah/yq/issues/643

but no luck
