### ISSUE TITLE
Why is the output duplicated when trying to add three or more fields?

### ISSUE THREAD

**Issue by LittleWat** [mikefarah/yq#1960]
**Describe the bug**

the output duplicated when trying to add three or more fields using yq.

```shell
❯ yq --version
yq (https://github.com/mikefarah/yq/) version 4.27.2
```
Operating system: mac
Installed via:  homebrew

**Input Yaml**

data1.yml:
```yaml
test:
  a1: aaa
```

**Command**

```
yq e '.test.name = "name", .test.namespace = "ns", .test.label = "foo"' data1.yaml
```

**Actual behavior**

the output is duplicated 

```yaml
test:
  a1: aaa
  name: name
  namespace: ns
  label: foo
test:
  a1: aaa
  name: name
  namespace: ns
  label: foo
```

**Expected behavior**

not duplicated
```yaml
test:
  a1: aaa
  name: name
  namespace: ns
  label: foo
```

**Additional context**

It works when adding one or two field.

```shell
❯ yq e '.test.name = "name"' data1.yaml
test:
  a1: aaa
  name: name
❯ yq e '.test.name = "name", .test.namespace = "ns"' data1.yaml
test:
  a1: aaa
  name: name
  namespace: ns
```
