### ISSUE TITLE
'xpack.security.enabled: true' How can this format be read or modified?

### ISSUE THREAD

**Issue by super-vip** [mikefarah/yq#1973]
In the elasticsearch.yaml file, there is the following content:
```
# Enable security features
xpack.security.enabled: true
# Enable encryption for HTTP API client connections, such as Kibana, Logstash, and Agents
xpack.security.http.ssl:
  enabled: true
  keystore.path: /etc/elasticsearch/certs/http.p12
# Enable encryption and mutual authentication between cluster nodes
xpack.security.transport.ssl:
  enabled: true
  verification_mode: certificate
  keystore.path: /etc/elasticsearch/certs/transport.p12
  truststore.path: /etc/elasticsearch/certs/transport.p12
```
Can you provide some examples of syntax for reading or modifying YAML files using yq?
