### ISSUE TITLE
Invalid yaml output when deleting list/object with comment

### ISSUE THREAD

**Issue by edonin** [mikefarah/yq#1976]
**Describe the bug**
When you delete the last element of a list or a map, but if there is a comment on this list, the generated yaml is not valid. The empty list/map is put on a new line without any space behind.

Version of yq: 4.42.1
Operating system: windows
Installed via: binary release

**Input Yaml**
data1.yml:
```yaml
test:
  foo: #bar
    - bar
```

data2.yml:
```yaml
test:
  foo: #bar
    bar: 1
```

**Command**
The command you ran:
```
yq e "del(.test.foo[])" data1.yaml
yq e "del(.test.foo.bar)" data2.yaml

```

**Actual behavior**

```yaml
test:
  foo: #bar
[]

test:
  foo: #bar
{}
```

**Expected behavior**

```yaml
test:
  foo: #bar
    []

test:
  foo: #bar
    {}
```
