### ISSUE TITLE
Octal Numbers are handled incorrectly in equality and comparison checks

### ISSUE THREAD

**Issue by dikderoy** [mikefarah/yq#1977]
**Describe the bug**

equality and math gt and lt checks (`==`, `>`, `<`) evaluate to false
when they should evaluate to true

Version of yq: 4.42.1
Operating system: mac
Installed via: homebrew

**Input Yaml**

data1.yml:
```yaml
old_octal: 0644 # YAML 1.1
new_octal: 0o644 # YAML 1.2
```

**Command**

```
cat data1.yml | yq '
to_entries | [ .[] | with( . 
 ; ._type = (.value | type)
 | .eq0644 = (.value == 0644)
 | .eq420 = (.value == 420)
 | .gt419 = (.value > 419)
 | .lt421 = (.value < 421)
 | .gt0643 = (.value > 0643)
 | .lt0645 = (.value < 0645)
) ]'
```

**Actual behavior**

```yaml
- key: old_octal
  value: 0644
  _type: '!!int'
  eq0644: true
  eq420: false
  gt419: true
  lt421: false
  gt0643: true
  lt0645: true
- key: new_octal
  value: 0o644
  _type: '!!int'
  eq0644: false
  eq420: false
  gt419: true
  lt421: true
  gt0643: false
  lt0645: true
```

**Expected behavior**

```yaml
- key: old_octal
  value: 0644
  _type: '!!int'
  eq0644: true
  eq420: true
  gt419: true
  lt421: true
  gt0643: true
  lt0645: true
- key: new_octal
  value: 0o644
  _type: '!!int'
  eq0644: true
  eq420: true
  gt419: true
  lt421: true
  gt0643: true
  lt0645: true
```

**Additional information**

probably connected - difference between YAML 1.1 and YAML 1.2 for octals when exporting to JSON:

command:
```
> cat data1.yml | yq -o json
```
output:
```json
{
  "old_octal": 644,
  "new_octal": 420
}
```
