### ISSUE TITLE
XML mangles order of heterogeneous elements

### ISSUE THREAD

**Issue by mrnoname1000** [mikefarah/yq#1983]
**Describe the bug**
yq tries to convert XML documents to mappings wherever possible, however this heuristic looks to be broken. Non-consecutive elements with the same tag name are grouped together, mangling the original document.

Version of yq: 4.42.1
Operating system: mac
Installed via: homebrew

**Input XML**
input.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<plist version="1.0">
<dict>
	<key>AKLastIDMSEnvironment</key>
	<integer>0</integer>
	<key>AKLastLocale</key>
	<string>en_US</string>
	<key>AppleAntiAliasingThreshold</key>
	<integer>4</integer>
</dict>
</plist>
```

**Command**
```
yq -px -ox < input.xml > output.xml
```

**Actual behavior**

output.xml
```yaml
<?xml version="1.0" encoding="UTF-8"?>
<plist version="1.0">
  <dict>
    <key>AKLastIDMSEnvironment</key>
    <key>AKLastLocale</key>
    <key>AppleAntiAliasingThreshold</key>
    <integer>0</integer>
    <integer>4</integer>
    <string>en_US</string>
  </dict>
</plist>
```

**Expected behavior**

(the exact same document that we started with)

**Additional context**
In my opinion, trying to represent XML as key/value pairs is an anti-pattern. Any XML element can contain any XML element or node in any order and any number of times. Since YAML can't handle duplicate keys, using arrays to represent all sequences would be more consistent and correct, if a little clunky:
```yaml
- +p_xml: version="1.0" encoding="UTF-8"
- plist:
  - +@version: "1.0"
  - dict:
    - key: AKLastIDMSEnvironment
    - integer: "0"
    - key: AKLastLocale
    - string: en_US
    - key: AppleAntiAliasingThreshold
    - integer: "4"
```
