### ISSUE TITLE
Strange behaviour of YAML merge operator - creates an empty object

### ISSUE THREAD

**Issue by pcppcp** [mikefarah/yq#1984]
**Describe the bug**
I know, I know. Merge operator is no longer supported in YAML 1.2, though its use is still widespread.
What I can't wrap my head around is role of indentation when using `<<:`.

Is there a 'correct' level of indent that is expected? Why is `foo` in the example evaluated to an empty object?

Version of yq: 4.42.1
Operating system: linux
Installed via: github release binary

**Input Yaml**
```yaml
---
foo:
  <<:
    x: 1
    y: 2
bar:
  <<:
  x: 1
  y: 2

```

**Command**
```shell
yq e 'explode(.)' data.yml
```

**Actual behavior**

```yaml
---
foo: {}
bar:
  x: 1
  y: 2

```

**Expected behavior**

```yaml
---
foo:
  x: 1
  y: 2
bar:
  x: 1
  y: 2

```

**Additional context**
N/A
