### ISSUE TITLE
Adding extra entries in yaml file

### ISSUE THREAD

**Issue by chimanjain** [mikefarah/yq#1996]
**Describe the bug**
When I am running the command: `yq -i '.b.c.d = 2' test.yaml` in the following `test.yaml` file. A new entry is being added at the end after `---` operator. How can I only update the existing key if present and not add a new key in the yaml file

Note that any how to questions should be posted in the discussion board and not raised as an issue.

Version of yq: 4.43.1
Operating system: linux
Installed via: binary release

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
test.yaml:
```yaml
a: 1
b:
  c:
    d: 1
---
e: 2

```

updated_test.yml:
```yaml
a: 1
b:
  c:
    d: 2
---
e: 2
b:
  c:
    d: 2
```

**Command**
The command you ran:
```
yq -i '.b.c.d = 2' test.yaml
```

**Actual behavior**

```yaml
a: 1
b:
  c:
    d: 2
---
e: 2
b:
  c:
    d: 2
```

**Expected behavior**

```yaml
a: 1
b:
  c:
    d: 2
---
e: 2
```

**Additional context**
How can I only update the existing key and not create a new key in case of `---` operator.
