### ISSUE TITLE
weird behavior when updating a property with String value 'y' 

### ISSUE THREAD

**Issue by pkainz** [mikefarah/yq#201]
With the latest yq version, we experienced a weird behaviour.

```yaml
# source.yaml
this:
  is-an:
    array:
      - key: x
        value: the x value
      - key: y
        value: the y value
      - key: z
        value: the z value
  value: y
```
I want to replace the `value` of the third element in the array using a file
```yaml
# replace-script.yaml
this.is-an.array[2].value: test
```

Then, I run 
```bash
cat replace-script.yaml | yq w -s - source.yaml
```
which awkwartdly transforms my 'y' key into 'true':
```yaml
# output
this:
  is-an:
    array:
    - key: x
      value: the x value
    - key: true
      value: the y value
    - key: z
      value: test
  value: true
```
We have tested this with longer and shorter arrays, always with the same outcome.
Any ideas why `yq` substitutes **every** standalone 'y' letter with 'true'?
