### ISSUE TITLE
Head comments retrieval incomplete from list of objects

### ISSUE THREAD

**Issue by fpfuetsch** [mikefarah/yq#2022]
**Describe the bug**
I have a list of yaml objects (each containing a head comment) from which I want to retrieve these comments. Unfortunately the comments are "empty" after as the first non-empty object.

Version of yq: 4.43.1
Operating system: mac
Installed via: homebrew

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)

input.yml:
```yaml
# firstComment
---
# secondComment
key: value
---
# thirdComment
otherKey: otherValue
---
# fourthComment
```

**Command**
The command you ran:
```
yq eval-all '. | head_comment' input.yaml
```

**Actual behavior**

```yaml
firstComment
secondComment


```

**Expected behavior**

```yaml
firstComment
secondComment
thirdComment
fourthComment
```
