### ISSUE TITLE
Replace email in a list 

### ISSUE THREAD

**Issue by marunmohan** [mikefarah/yq#2029]
```
I want to append an entry in namespaceAdmin,namespaceDebugger in the below yaml file using yq. Basically it has got multiple patches and I want to make changes in some of the helmrelease patches. Is that possible?
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: test
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infra
  sourceRef:
    kind: GitRepository
    name: applications
  prune: true
  postBuild:
    substitute:
      test: "dev"
  patches:
      - patch: |-
          apiVersion: v1
          kind: Namespace
          metadata:
            name: test
            labels:
              app-name: test
      - patch: |-
          apiVersion: helm.toolkit.fluxcd.io/v2beta2
          kind: HelmRelease
          metadata:
            name: test
          spec:
            values:
              ingress:
                ipAddress: "11.22.333.33"
              roleBinding:
                namespaceAdmin:
                  - kk3@test.com
                  - kk2@test1.com
                  - kk1@test2.com
                namespaceDebugger:
                   - kk@test3.com
      - patch: |-
          apiVersion: helm.toolkit.fluxcd.io/v2beta2
          kind: HelmRelease
          metadata


```
