### ISSUE TITLE
Multiline Stings lose their formatting. Line breaks replaces with \n

### ISSUE THREAD

**Issue by Jeansen** [mikefarah/yq#2030]
**Describe the bug**

Note that any how to questions should be posted in the discussion board and not raised as an issue.

Version of yq: 4.34.2
Operating system: Linux / Debian 12
Installed via: Github Release

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
data1.yml:
```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector-daemonset
  namespace: "observability"
#  namespace: opentelemetry-operator-system
spec:
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
    - operator: Exists
      effect: NoSchedule
    - operator: Exists
      effect: NoExecute
  mode: daemonset
  config: |
    receivers:
    # Make sure to add the otlp receiver.
    # This will open up the receiver on port 4317
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"
    opencensus:
    zipkin:
    jaeger:
      protocols:
        grpc:
        thrift_http:
        thrift_compact:
        thrift_binary:
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 50
        spike_limit_percentage: 30
      batch:
    extensions:
      health_check:
    exporters:
      debug:
      otlp/jaeger:
        endpoint: "jaeger-collector.observability.svc.cluster.local:4317"
        tls:
          insecure: true
    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlp/jaeger]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter]
          exporters: [debug]

```

**Command**
The command you ran:
```
yq file.yaml
```

**Actual behavior**

```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector-daemonset
  namespace: "observability"
#  namespace: opentelemetry-operator-system
spec:
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
    - operator: Exists
      effect: NoSchedule
    - operator: Exists
      effect: NoExecute
  mode: daemonset
  config: "receivers:\n# Make sure to add the otlp receiver.\n# This will open up the receiver on port 4317\notlp:\n  protocols:\n    grpc:\n      endpoint: \"0.0.0.0:4317\"\n    http:\n      endpoint: \"0.0.0.0:4318\" \nopencensus:\nzipkin:\njaeger:\n  protocols:\n    grpc:\n    thrift_http:\n    thrift_compact:\n    thrift_binary:\nprocessors:\n  memory_limiter:\n    check_interval: 1s\n    limit_percentage: 50\n    spike_limit_percentage: 30\n  batch:\nextensions:\n  health_check:\nexporters:\n  debug:\n  otlp/jaeger:\n    endpoint: \"jaeger-collector.observability.svc.cluster.local:4317\"\n    tls:\n      insecure: true\nservice:\n  extensions: [health_check]\n  pipelines:\n    traces:\n      receivers: [otlp]\n      processors: [memory_limiter, batch]\n      exporters: [otlp/jaeger]\n    metrics:\n      receivers: [otlp]\n      processors: [memory_limiter]\n      exporters: [debug]\n"

```

**Expected behavior**
 No changes at all. Should be identical to input file.  Instead each line break is replaced by `\n` and quotes with `\"`. 

**Additional context**
