### ISSUE TITLE
Replace with_entries broken

### ISSUE THREAD

**Issue by alexpenev-s** [mikefarah/yq#2050]
Version of yq: v4.44.1

**Input Yaml**
data1.yml:
```yaml
a:
  b:
    c: 1
```

**Command**
The command you ran:
```
yq e  '(.a | with_entries(select(.key | test("b$"))) | .[].c) = "5504881"' data1.yml
```

**Actual behavior**

```yaml
a:
  b:
    c: 1
```

**Expected behavior**

```yaml
a:
  b:
    c: "5504881"
```

**Additional context**
with yq version 4.22.1 The replace is done corretly.

**Comment by mikefarah** [comment]
When using `with_entries` you have to perform the update within the brackets of that operator - not out.
To get what you want here, you'd need to do something like:

```
yq '.a |= with_entries(select(.key | test("b$")) | .value.c = "5504881")' examples/data1.yaml

a:
  b:
    c: "5504881"

```

Explanation:
- `|=` to update `.a`, w.r.t to itself
- Use `with_entries` to find the right key to update the value of
