### ISSUE TITLE
Question. How to prepend tags at the start

### ISSUE THREAD

**Issue by mailsanchu** [mikefarah/yq#2051]
Given the file a.yml with the following contents and I would like to add some tags as parent 

Contents of a.yml

```
- id: v1_conditions
  uri: http://xyz.com
  predicates:
    - Path=/v1/conditions
    - Header=X-Forwarded-Host, .*\.ae\.biz
  filters:
    - RewritePath=/v1/conditions,/v1/conditions
    - CopyCustomerFromFQDNToHeader
```

and I would like to add the following structure to the above file 
```
spring
 gateway
   contents
     routes
```

and the final results should be the following 
```
spring
 gateway
   contents
     routes
       - id: v1_conditions
         uri: http://xyz.com
         predicates:
           - Path=/v1/conditions
           - Header=X-Forwarded-Host, .*\.ae\.biz
        filters:
            - RewritePath=/v1/conditions,/v1/conditions
            - CopyCustomerFromFQDNToHeader
```
