### ISSUE TITLE
`with_entries` doesn't work with `with`

### ISSUE THREAD

**Issue by jancespivo** [mikefarah/yq#2066]
**Describe the bug**

`yq 'with_entries(.key |= "KEY_" + .)' sample.yml` according to the https://mikefarah.gitbook.io/yq/operators/entries#use-with_entries-to-update-keys works however nested one using `with` does not:
`yq 'with(.nested; with_entries(.key |= "KEY_" + .))' sample.yml`

Version of yq: 4.44.1
Operating system: linux
Installed via: pacman

**Input Yaml**

sample.yml:
```yaml
nested:
  a: 1
  b: 2
```

**Command**
The command you ran:
```
yq 'with(.nested; with_entries(.key |= "KEY_" + .))' sample.yml
```

**Actual behavior**

```yaml
nested:
  a: 1
  b: 2
```

**Expected behavior**

```yaml
nested:
  KEY_a: 1
  KEY_b: 2
```

**Additional context**
Related to https://github.com/mikefarah/yq/issues/210
