### ISSUE TITLE
Encoding to yaml only encodes the first document to a string

### ISSUE THREAD

**Issue by mackaybe** [mikefarah/yq#2067]
**Describe the bug**
Encoding to yaml only encodes the first document to a string

Note that any how to questions should be posted in the discussion board and not raised as an issue.

Version of yq: 4.42.1
Operating system: osx or linux
Installed via: homebrew and manual build

**Input Yaml**

foo.yml:
```yaml
build: no
data:
  test.yaml: |
    a: b
    type: plain
    ---
    c: d
    type: juicy
    ---
    e: f
    type: greenish

```

**Command**
The command you ran:
```
yq '.data."test.yaml" = (.data."test.yaml" | from_yaml | select(.type == "juicy").c = "DD" | to_yaml)' foo.yaml
```

**Actual behavior**

```yaml
build: no
data:
  test.yaml: |
    a: b
    type: plain
```

**Expected behavior**

```yaml
build: no
data:
  test.yaml: |
    a: b
    type: plain
    ---
    c: DD
    type: juicy
    ---
    e: f
    type: greenish
```

**Additional context**
none
