### ISSUE TITLE
Yaml file with regex is parsed with invalid characters in json format on s390x platform (>v4.35.2)

### ISSUE THREAD

**Issue by chegde20121** [mikefarah/yq#2093]
**Describe the bug**
When I parse a yaml file which contains regex with escape characters into json format on s390x platform,
Note that any how to questions should be posted in the discussion board and not raised as an issue.

Version of yq: 4.X.X
Operating system: mac/linux/windows/....
Installed via: docker/binary release/homebrew/snap/...

**On s390x:- **
version: v4.44.2
Platform: s390x
input yaml:-
```
divisor:
  anyOf:
  - type: integer
  - type: string
  description: Specifies the output format of the exposed resources, defaults to "1"
  pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
  x-kubernetes-int-or-string: true
```
```
./yq_linux_s390x eval -o=json postgres_edb.yaml > postgres_edb.json
```
```
jq . postgres_edb.json
```
```
parse error: Invalid escape at line 1989, column 165
```
Parsed line from yq in s390x is 

Actual Output:- 
```
 "pattern": "^(\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))))?$",
```

** On x86**
version: v4.44.2
Platform: x86
input yaml:-
```
divisor:
  anyOf:
  - type: integer
  - type: string
  description: Specifies the output format of the exposed resources, defaults to "1"
  pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
  x-kubernetes-int-or-string: true
```
command:
```
./bin/yq eval -o=json postgres_edb.yaml > postgres_edb.json
```

Output
```
 "pattern": "^(\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))))?$"
```

In x86 there is no issue. But only in s390x the yaml with escape charecters is not parsed as expected

**Command**
The command you ran:
```
./yq_linux_s390x eval -o=json postgres_edb.yaml > postgres_edb.json
```

**Actual behavior**

```
"pattern": "^(\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))))?$"
```

**Expected behavior**

```
 "pattern": "^(\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\\+|-)?(([0-9]+(\\.[0-9]*)?)|(\\.[0-9]+))))?$"
```
```

**Additional context**
This issue is occurring in all the versions above v4.35.2 of s390x distribution

**Comment by mikefarah** [comment]
Weird - I'm not doing anything special for s390x other than using the go-compiler to build the binary. So you're saying it produces a different JSON output to the x86 binary?

**Comment by andyedwardsibm** [comment]
I've just started hitting this as well.  It is indeed "very weird"

I think it relates to https://github.com/goccy/go-json/issues/466 where I've put some simple recreates, both for `yq` and for goccy/go-json native

I don't think goccy/go-json works properly on big-endian systems.  It seems to try chopping the value into chunks of characters and then does some clever bit-shifting and OR-ing in an attempt to quickly spot escape characters, and this seems to go hideously wrong on s390

As @chegde20121 says, `yq` behaves fine in version 4.35.2, but version 4.40.1 doesn't escape the backslash properly on s390...

```
$ curl -L https://github.com/mikefarah/yq/releases/download/v4.35.2/yq_linux_s390x -o yq-4.35.2 && chmod u+x yq-4.35.2
$ echo 'foo: xx\xxxxxxx' | ./yq-4.35.2 -o json
{
  "foo": "xx\\xxxxxxx"
}
```
versus
```
$ curl -L https://github.com/mikefarah/yq/releases/download/v4.40.1/yq_linux_s390x -o yq-4.40.1 && chmod u+x yq-4.40.1
$ echo 'foo: xx\xxxxxxx' | ./yq-4.40.1 -o json
{
  "foo": "xx\xxxx"
}
```

Maybe https://github.com/mikefarah/yq/pull/1829 was the trigger?

**Comment by andyedwardsibm** [comment]
Got another example of a difference in behaviour

`file1.yaml`
```yaml
A: |-
  |
  B: BB
```

Both amd64 and s390x produce the same output:

```
$ yq '.' -o json file1.yaml
{
  "A": "|\nB: BB"
}
```

Add a 3rd "B" on the last line...

`file2.yaml`
```yaml
A: |-
  |
  B: BBB
```

amd64 produces this...
```
$ yq '.' -o json file2.yaml
{
  "A": "|\nB: BBB"
}
```

s390x produces this...
```
$ yq4 '.' -o json file2.yaml 
{
  "A": "|
B: BBB"
}
```
... which is invalid JSON
