### ISSUE TITLE
--prettyPrint does not canonicalise quotes around yes/no/on/off

### ISSUE THREAD

**Issue by willvousden** [mikefarah/yq#2096]
**Describe the bug**

When formatting `yes`/`no`/`on`/`off` pseudo-boolean strings, `--prettyPrint` preserves the quoting that was used in the input.

This means that diffing two YAML documents that have such values can have false-positives when different quoting styles were used, when when using `--prettyPrint`.

Version of yq: v4.44.2
Operating system: macOS
Installed via: homebrew

**Input Yaml**
test.yaml:
```yaml
hello:
  a: hello
  b: 'hello'
  c: "hello"
"true":
  a: true
  b: 'true'
  c: "true"
yes:
  a: yes
  b: 'yes'
  c: "yes"
```

**Command**
```
yq -P test.yaml
```

**Actual behavior**

Both `'yes'` and `"yes"` appear unmodified:

```yaml
hello:
  a: hello
  b: hello
  c: hello
"true":
  a: true
  b: "true"
  c: "true"
yes:
  a: yes
  b: 'yes'
  c: "yes"
```

**Expected behavior**

I expect them both to have the same quote style – either double, or unquoted. Probably double-quoted is better, for compatibility with the YAML 1.1 spec.

```yaml
hello:
  a: hello
  b: hello
  c: hello
"true":
  a: true
  b: "true"
  c: "true"
yes:
  a: yes
  b: "yes" # or unquoted
  c: "yes" # or unquoted
```
