### ISSUE TITLE
Redundant printing can occur when using null-input

### ISSUE THREAD

**Issue by echlebek** [mikefarah/yq#2100]
**Describe the bug**

When using `yq -n` with assignment expressions, some expressions can cause the resulting document to be printed more than once.

Version of yq: 
```
$ yq --version
yq (https://github.com/mikefarah/yq/) version v4.44.2
```
Installed via: `go install`

**Command**
```
$ yq -n '.a.b.c = "foo", .a.b.d = "bar", .a.b.e = "baz"'
```

**Actual behavior**

```yaml
a:
  b:
    c: foo
    d: bar
    e: baz
a:
  b:
    c: foo
    d: bar
    e: baz
```

**Expected behavior**

```yaml
a:
  b:
    c: foo
    d: bar
    e: baz
```

**Additional context**
Discovered while using yqlib to build a document dynamically, found a minimal reproduction quite quickly on the full command-line application. I tried using the -P flag as well to see if that would mitigate it, but it did not.
