### ISSUE TITLE
Json to Yaml Mangling Large Integer

### ISSUE THREAD

**Issue by MatthewChau** [mikefarah/yq#2122]
**Describe the bug**

Note that any how to questions should be posted in the discussion board and not raised as an issue.

Version of yq: 4.44.2
Operating system: linux_amd64 (running in WSL)
Installed via: Binary release

**Input json**
```json
"schema": {
    "maximum": 9223372036854775807,
    "minimum" 1,
    "type": "integer",
    "format": "int64"
}
```

**Command**
The command you ran:
```
./yq_linux_amd64 -P -oy test.json
```

**Actual behavior**

```yaml
schema:
    maximum: 9.223372036854776e+18
    minimum 1
    type: integer
    format: int64
```

**Expected behavior**

```yaml
schema:
    maximum: 9.223372036854775807
    minimum 1
    type: integer
    format: int64
```

**Additional context**
Expected behavior does occur when testing with v4.14.1
```
./yq_linux_amd64 eval -P -oy test.json
```
