### ISSUE TITLE
Trailing spaces before newlines prevent styling string as literal

### ISSUE THREAD

**Issue by CRThaze** [mikefarah/yq#2147]
**Describe the bug**
When styling strings as literals that have whitespace preceding newlines, the styling fails.

Version of yq: 4.44.3
Operating system: linux
Installed via: binary

**Input Yaml**

test.yml:
```yaml
- foo: 2024-09-09T09:53:58+00:00
  bar: "hello"
  baz: "hello\nworld"
- foo: 2024-09-10T09:53:58+00:00
  bar: "hi"
  baz: "\"hi\nworld\""
- foo: 2024-09-11T09:53:58+00:00
  bar: "bye"
  baz: "good \"bye\n    cruel\" world!"
- foo: 2024-09-12T09:53:58+00:00
  bar: "bye"
  baz: "good \"bye \n    cruel\" world!"
```

**Command**

```
yq '.[] |= with(.[] | select(type == "!!str" and test("\n")); . style="literal" )' test.yml
```

**Actual behavior**

```yaml
- foo: 2024-09-09T09:53:58+00:00
  bar: "hello"
  baz: |-
    hello
    world
- foo: 2024-09-10T09:53:58+00:00
  bar: "hi"
  baz: |-
    "hi
    world"
- foo: 2024-09-11T09:53:58+00:00
  bar: "bye"
  baz: |-
    good "bye
        cruel" world!
- foo: 2024-09-12T09:53:58+00:00
  bar: "bye"
  baz: "good \"bye \n    cruel\" world!"
```

**Expected behavior**

```yaml
- foo: 2024-09-09T09:53:58+00:00
  bar: "hello"
  baz: |-
    hello
    world
- foo: 2024-09-10T09:53:58+00:00
  bar: "hi"
  baz: |-
    "hi
    world"
- foo: 2024-09-11T09:53:58+00:00
  bar: "bye"
  baz: |-
    good "bye
        cruel" world!
- foo: 2024-09-12T09:53:58+00:00
  bar: "bye"
  baz: |-
    good "bye 
        cruel" world!
```

**Additional context**

Work-around is to strip whitespace before newlines:

`yq '.[] |= with(.[] | select(type == "!!str" and test("\n")); . |= sub("\s+\n", "\n") | . style="literal" )' test.yml`

Result:

```
- foo: 2024-09-09T09:53:58+00:00
  bar: "hello"
  baz: |-
    hello
    world
- foo: 2024-09-10T09:53:58+00:00
  bar: "hi"
  baz: |-
    "hi
    world"
- foo: 2024-09-11T09:53:58+00:00
  bar: "bye"
  baz: |-
    good "bye
        cruel" world!
- foo: 2024-09-12T09:53:58+00:00
  bar: "bye"
  baz: |-
    good "bye
        cruel" world!
```
