### ISSUE TITLE
yq line operator ignores head comment and therefore reports wrong line numbers

### ISSUE THREAD

**Issue by ba3n3** [mikefarah/yq#2157]
**Describe the bug**
yq doesn't count the head comment(s) and its following newlines when reporting line numbers

Version of yq: 4.44.3
Operating system: linux
Installed via: binary release

**Input Yaml**
data1.yml:
```yaml
---
# head comment

bar:
  # i can put many
  # comments here
  foo: bar

# extra mid file comment

baz: bam
...

```

data2.yml:
```yaml
---
bar:
  # i can put many
  # comments here
  foo: bar

# extra mid file comment

baz: bam
...

```

**Command**
The command you ran:
```
yq eval '".bar.foo: " + (.bar.foo | line) + ", .baz: " + (.baz | line)' data1.yml data2.yml
```
(_just for demonstration, same result when just evaluating `.bar | line`_)

**Actual behavior**

```text
.bar.foo: 4, .baz: 8
.bar.foo: 4, .baz: 8
```

**Expected behavior**

```text
.bar.foo: 6, .baz: 10
.bar.foo: 4, .baz: 8
```
The 2 lines from the head comment count.

**Additional context**
It doesn't matter how many following newlines are there.
