### ISSUE TITLE
`delete` doesn't work as expected in `ireduce`

### ISSUE THREAD

**Issue by zozowell** [mikefarah/yq#2172]
**Describe the bug**
When I use `delete` operator in the `ireduce` block, the del doesn't work as I expected.

Version of yq: 4.44.3
Operating system: mac
Installed via: homebrew

**Input Yaml**
test.yml:
```yaml
- a: cat
- b: dog
- c: bat
```

**Command**
The command you ran:
```
A="[cat, bat]" yq 'env(A)[] as $a ireduce(.; del(.[] | select(.[] == $a)))' test.yaml
```

**Actual behavior**

```yaml
bash-3.2$ A="[cat, bat]" yq 'env(A)[] as $a ireduce(.; del(.[] | select(.[] == $a)))' test.yaml
- b: dog
- c: bat
```

**Expected behavior**

```yaml
bash-3.2$ A="[cat, bat]" yq 'env(A)[] as $a ireduce(.; del(.[] | select(.[] == $a)))' test.yaml
- b: dog
```

**Additional context**
The behavior is very weird as the input variable `A` changed; another strange behavior is that: I can't delete all the elements, even deleting the array index 0 every time.

```
bash-3.2$ A="[cat, bat, dog]" yq 'env(A)[] as $a ireduce(.; del(.[0]))' test.yaml
- b: dog
```
