### ISSUE TITLE
`evaluate` command moves comments to a different line

### ISSUE THREAD

**Issue by guymeron** [mikefarah/yq#2176]
**Describe the bug**
`evaluate` command moves comments to a different line

Version of yq: 4.44.3
Operating system: mac
Installed via: homebrew

**Input Yaml**
data1.yml:
```yaml
level1:
  level2:
    - name: foo
      array:
        # comment1
        - key1: val1
          key2: val2
        # comment2

        # comment3
        - key1: val10
          key2: val20
```

**Command**
```
cat data1.yml |  yq eval .level
```

**Actual behavior**

```yaml
level2:
  - name: foo
    array:
      # comment1
      - key1: val1
        key2: val2
      # comment3
      - key1: val10
        # comment2

        key2: val20
```

**Expected behavior**

```yaml
level2:
  - name: foo
    array:
      # comment1
      - key1: val1
        key2: val2
      # comment2

      # comment3
      - key1: val10        
        key2: val20
```

**Additional context**
It works OK when there is no empty line between the comments (line number 9).
