### ISSUE TITLE
feature req: partial splats on key names

### ISSUE THREAD

**Issue by nergdron** [mikefarah/yq#218]
I've got a yaml file full of host details, structured like:
```yaml
hostname:
  ip: some.ip.add.ress
  other: keys
  with: data
```

I wanted to get all the IPs for hosts matching a certain pattern, but yq doesn't seem to support that:
```shell
# yq r hosts.yml 'some-prefix*.ip'
null
# yq r hosts.yml 'some-prefix-rest-of-single-hostname.ip'
a.valid.ip.address
```
