### ISSUE TITLE
select errors with "invalid input text" 

### ISSUE THREAD

**Issue by mfschumann** [mikefarah/yq#2180]
**Describe the bug**
Running a `select(.name==something)` command fails with error `invalid input text "something)"`.

Version of yq: 4.44.3
Operating system: arch linux
Installed via: aur package

**Input Yaml**
data1.yml:
```yaml
modules:
  - name: libdbusmenu
    build-options:
      cflags: -Wno-error
  - name: pcsc-lite
    config-opts:
      - --disable-libudev
      - --disable-libsystemd
```

**Command**
The command you ran:
```
yq '.modules[] | select(.name==libdbusmenu)' < data1.yml
```

**Actual behavior**

```
Error: 1:28: invalid input text "libdbusmenu)"
```

**Expected behavior**

no error

**Additional context**
Seems to have worked in 4.43.1 as per [this issue](https://github.com/mikefarah/yq/issues/2026#issue-2275972219).
