### ISSUE TITLE
Case insensitive sort_keys

### ISSUE THREAD

**Issue by DAVe3283** [mikefarah/yq#2194]
**Please describe your feature request.**
Ability to sort keys ignoring case (not case sensitive).

**Describe the solution you'd like**
If we have data1.yml like:

```yaml
Foo: 3
apple: 1
bar: 2
```

And we run a command:

```bash
yq -P 'sort_keys_insensitive(..)' data1.yml
```

it could output

```yaml
apple: 1
bar: 2
Foo: 3
```

**Describe alternatives you've considered**
I tried to use `'sort_keys(..|downcase)'` but it does not work (probably as expected).

**Additional context**
While I don't want to consider case for the purpose of the sort, I would like to _retain_ the case of the keys in the output.

**Comment by mikefarah** [comment]
Will accept a PR for this, this should be done by adding a `sort_keys_by` function (just as there is a `sort_by` function [here](https://mikefarah.gitbook.io/yq/operators/sort#sort-by-numeric-field))  

You will then be able to: `sort_keys_by(downcase)`

**Comment by mikefarah** [comment]
Otherwise I may get to it in a few weeks :)

**Comment by DAVe3283** [comment]
Sorry, I don't have much experience with Go, otherwise I would put together a PR for this. If I get some time when work slows down, I can try my hand at it, assuming someone familiar with the language/tool hasn't gotten to it first.

**Comment by mikefarah** [comment]
Will be fixed in the next release :) - you will be able to sort a map by keys by doing `sort_by(key | downcase)` on the map

**Comment by DAVe3283** [comment]
Hmm, I am probably just not thinking about this right, but I can't seem to get this to sort recursively like `sort_keys(..)` does.

Sample input:
```yaml
---
zulu:
  list:
    - 456
    - 9
    - 123
  cat: 0
  Banana: 0
  apple: 0
alpha:
  cat: 0
  Banana: 0
  apple: 0
Bravo:
  cat: 0
  Banana: 0
  apple: 0
```

If I run `yq -P 'sort_by(key | downcase)' sample.yaml` it only sorts the first level:

```yaml
---
alpha:
  cat: 0
  Banana: 0
  apple: 0
Bravo:
  cat: 0
  Banana: 0
  apple: 0
zulu:
  list:
    - 456
    - 9
    - 123
  cat: 0
  Banana: 0
  apple: 0
```

Is there a way to do it recursively, like `sort_keys(..)`?
