### ISSUE TITLE
Merge new fields only is missing comments

### ISSUE THREAD

**Issue by jandubois** [mikefarah/yq#2201]
I'm trying to merge 2 data files, but only want to merge keys from the second file that don't exist in the first. I expect that all comments on copied keys are merged as well.

Version of yq: 4.44.3
Operating system: macOS 12.7.6 (Monterey)
Installed via: homebrew

**Input Yamls**

empty.yaml:
```yaml
empty: true
```

comments.yaml:
```yaml
# foo head comment
foo: 1 # foo line comment

# bar head comment
bar: # bar line comment
  # baz head comment
  baz: # baz line comment
    # yolo head comment
    yolo: 2 # yolo line comment
```

**Command**

```
yq eval-all -n 'load("empty.yaml") *n load("comments.yaml")'
```

**Actual behavior**

```yaml
empty: true
foo: 1 # foo line comment
bar:
  baz:
    yolo: 2 # yolo line comment
```

**Expected behavior**

I expected **all** the comments to be merged as well. Since none of the fields in `comments.yaml` exist in `empty.yaml` the result of `*n` to be identical to `*`:

```
yq eval-all -n 'load("empty.yaml") * load("comments.yaml")'
```

```yaml
empty: true
# foo head comment
foo: 1 # foo line comment
# bar head comment
bar: # bar line comment
  # baz head comment
  baz: # baz line comment
    # yolo head comment
    yolo: 2 # yolo line comment
```

**Comment by jandubois** [comment]
It looks like the comments attached to the keys are not copied over, probably because they  are auto-created when the values are copied.

**Comment by mikefarah** [comment]
Yep, you are right. I'll need to find spare time to fix this.

**Comment by d-enk** [comment]
```bash
yq eval-all '. as $item ireduce ({}; . * $item)' empty.yaml comments.yaml
```

```yaml
empty: true
# foo head comment
foo: 1 # foo line comment
# bar head comment
bar: # bar line comment
  # baz head comment
  baz: # baz line comment
    # yolo head comment
    yolo: 2 # yolo line comment
```
