### ISSUE TITLE
yaml format is changed after update this file 

### ISSUE THREAD

**Issue by yahliu** [mikefarah/yq#2235]
**Describe the bug**

Note that any how to questions should be posted in the discussion board and not raised as an issue.

Version of yq: v4.44.5
Operating system: mac/linux
Installed via: homebrew/snap

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
data1.yml:
```yaml
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform:
    aws:
      type: m6g.2xlarge
  replicas: 3
metadata:
  name: test
```

**Command**
The command you ran:
```
yq e -i '.metadata.name="test1" data1.yml
```

**Actual behavior**

```yaml
compute:
  - architecture: arm64
    hyperthreading: Enabled
    name: worker
    platform:
      aws:
        type: m6g.2xlarge
    replicas: 3
metadata:
  name: test1

```

**Expected behavior**

```yaml
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform:
    aws:
      type: m6g.2xlarge
  replicas: 3
metadata:
  name: test1
```

**Additional context**
