### ISSUE TITLE
--properties-array-brackets does not seem to work when reading properties files

### ISSUE THREAD

**Issue by Northcode** [mikefarah/yq#2253]
**Describe the bug**
--properties-array-brackets does not seem to work when reading properties files.

Version of yq: v4.44.6
Operating system: linux
Installed via: archlinux package https://archlinux.org/packages/extra/x86_64/go-yq/

**Input Properties**
```properties
arr[0].name=test
arr[0].value=5
arr[1].name=test2
arr[1].value=10
```

**Command**
The command you ran:
```
yq -p=props -o=y --properties-array-brackets input.properties
```

**Actual behavior**

```yaml
arr[0]:
  name: test
  value: "5"
arr[1]:
  name: test2
  value: "10"
```

**Expected behavior**

```yaml
arr:
  - name: test
    value: "5"
  - name: test2
    value: "10"
```

**Comment by Northcode** [comment]
This might be intended behavior, and the option is only supported for properties output instead of input.
But it wasn't very clear from the documentation since that also mentions `.0` style arrays and those do work for both input and output.

```
$ cat | yq -p=props -o=y -
arr.0.name=test
arr.1.name=test2
^D
arr:
  - name: test
  - name: test2
```

```
$ cat | yq -p=props -o=y --properties-array-brackets -
arr[0].name=test
arr[1].name=test2
^D
arr[0]:
  name: test
arr[1]:
  name: test2
```

**Comment by GrahamHannington** [comment]
I was about to create a new issue for this, but then I found this existing issue.

In brief: :+1: to this issue as a feature request.

In detail...

# Working with Properties: Decode properties with array brackets

## Problem

Given the following input `test.properties` file (with "Spring Boot"-style array paths in brackets):

```
person.name=Mike Wazowski
person.pets[0].name=Felix
person.pets[0].species=cat
person.pets[1].name=Fido
person.pets[1].species=dog

```

the following yq command:

```
yq -p=props -o=yaml test.properties
```

outputs the following YAML:

```yaml
person:
  name: Mike Wazowski
  pets[0]:
    name: Felix
    species: cat
  pets[1]:
    name: Fido
    species: dog
```

### What I want instead

I want:

```yaml
person:
  name: Mike Wazowski
  pets:
    - name: Felix
      species: cat
    - name: Fido
      species: dog
```

### Workaround

I can get want I want by preprocessing `test.properties` to remove the brackets:

```
person.name=Mike Wazowski
person.pets.0.name=Felix
person.pets.0.species=cat
person.pets.1.name=Fido
person.pets.1.species=dog

```

but I'd prefer not to have to do that preprocessing step.

### (Proposed) solution

The existing `--properties-array-brackets` works for _encoding_ properties.

Please make it work for _decoding_ properties, too.
