### ISSUE TITLE
Docker hub image pull rate limit.

### ISSUE THREAD

**Issue by saireddyzepto** [mikefarah/yq#2268]
How to use self hosted dockerhub mirror the this github action.
Is there any way to mention my self hosted dockerhub image company.com/dockehub/mikefarah/yq:4-githubaction
Here this image company.com/dockehub/mikefarah/yq:4-githubaction is copy of mikefarah/yq:4-githubaction can this be achieved ?

**Comment by younsl** [comment]
In GitHub Enterprise Server and GitHub self-hosted runners environment, you can resolve this issue as follows:

I solved dockerhub rate limit issue by setting up a public mirror ECR and changing the image reference in the action. This approach doesn't require container registry login since it runs within the action itself.
 
1. Mirror source container image`mikefarah/yq:4-githubaction` by [ECR Pull Through Cache](https://docs.aws.amazon.com/AmazonECR/latest/userguide/pull-through-cache.html) feature
2. Change `image` value reference in the action to use this public ECR address.

```yaml
# yq/action.yml
runs:
  # To avoid docker rate limit, change my public ECR
  using: 'docker'
  image: 'docker://<YOUR_PUBLIC-MIRRORED.CONTAINER_REGISTRY.COM>/github-actions/yq:4-githubaction'
  args:
    - ${{ inputs.cmd }}
```
