### ISSUE TITLE
yq does not recognize helm template yaml `key: {{...}}:{{...}}`

### ISSUE THREAD

**Issue by amir-hoseyn77** [mikefarah/yq#2270]
**Describe the bug**
I have a "helm" template whose line contains `key: {{aaa}}:{{bbb}}` that causes a parsing error not found key! The `{{aaa}}:{{bbb}}` must be evaluated as value for `key` but yq thinks that `{{aaa}}` is a new key so must be in a new line!

I have checked this file with some YAML validator websites and they have trouble with that line.

Version of yq: v4.44.6
Operating system: Ubuntu 24.04
Installed via: wget binary release

**Input Yaml**
data1.yml:
```yaml
tracing:
  enabled: {{ .Values.jaeger.enabled }}
  exporter:
    endpoint: {{ .Values.jaeger.collector.host }}:{{ include "policy-clamp-ac-a1pms-ppnt.exporter-port" . }}
```

**Command**
A simple eval even `.`
```
yq eval '.tracing.enabled' data1.yaml
```

**Actual behavior**
Error:
```
Error: bad file 'data1.yaml': yaml: line 3: did not find expected key
```

**Expected behavior**

```yaml
{{ .Values.jaeger.enabled }}
```

**Additional context**
I have installed yq with `wget`. It seems snap-installed yq has some inconsistency with root privilege.

**Comment by jandubois** [comment]
The problem is that `data1.yaml` is not valid YAML until **after** the Go template has been evaluated.

If all your template substitutions are strings, then you can work around this by putting template code in quotes:

```yaml
tracing:
  enabled: "{{ .Values.jaeger.enabled }}"
  exporter:
    endpoint: "{{ .Values.jaeger.collector.host }}:{{ include \"policy-clamp-ac-a1pms-ppnt.exporter-port\" . }}"
```

But in general this is not possible, e.g. when you need the substitution to be a number or a boolean. Or if you have multi-line logic using `{{ if … }}`. In that case you must process the file with `helm template` first to turn it into valid YAML, and only then can you parse it.
