### ISSUE TITLE
Replace value in specific profile

### ISSUE THREAD

**Issue by rickywu** [mikefarah/yq#229]
Try this springboot property file: yq w -i bootstrap.yml server.port 1000

```
---
spring:
  profiles: native
server:
  port: 2003

---
spring:
  profiles: dev
server:
  port: 2002
```
Only profile native changed, dose it support specify profile?
