### ISSUE TITLE
work with complex key like :   ../out/webhooks/index.js

### ISSUE THREAD

**Issue by amg-web** [mikefarah/yq#2307]
how can i work with yaml like below?

yaml [example](https://github.com/bigbluebutton/bbb-webhooks/blob/7ed5fdb4178f8148f1863342827ab42522e12cae/config/default.example.yml#L99)

need to edit value of the key **permanentURLs**
```
modules:
  ../out/webhooks/index.js:
    type: out
    config:
      permanentURLs: []
```
