### ISSUE TITLE
when i import complex string into yaml file,how can i persist | or |-?

### ISSUE THREAD

**Issue by mingmingshiliyu** [mikefarah/yq#2347]
```
apiVersion: v1
data:
  dex: |-
    connectors:
    - type: ldap
      name: ldap
      id: ldap
      config:
        host: openldap.default.svc.cluster.local:389
        insecureNoSSL: true
```

when dex value is complex, I have to persist |- signal, otherwise my system can`t diagnose the value content. when i use yq, |- will dispear, how to keep it ?  and not only |-, | ,etc
