### ISSUE TITLE
Regression: select() selects empty nodes since version 4.45.2

### ISSUE THREAD

**Issue by bguijt** [mikefarah/yq#2353]
**Describe the bug**

The `select()` expression, or the pipe (`|`) construct is passing empty nodes.

Version of yq: 4.45.2
Operating system: mac
Installed via: homebrew

**Input Yaml**
Given this document `manifest.yaml`:
```yaml
---
kind: Cluster
metadata:
  name: database-a
---
kind: Cluster
metadata:
  name: database-b
---
kind: Secret
metadata:
  name: secrets-a
---
kind: ExternalSecret
metadata:
  name: secrets-b
```

**Command**
```
cat manifest.yaml | yq --no-doc 'select(.kind == "Cluster") | .kind + "/" + .metadata.name'
```

**Actual behavior**
```
Cluster/database-a
Cluster/database-b
Cluster/
Cluster/
```

**Expected behavior**
```
Cluster/database-a
Cluster/database-b
```

This bug seems to be introduced with version 4.45.2, before this I did not have this problem.

Thanks for looking into it!
