### ISSUE TITLE
Duplicated array entry when using multiple input files

### ISSUE THREAD

**Issue by halamix2** [mikefarah/yq#2383]
**Describe the bug**
Added array entry is duplicated the same number of times there are input files.
Duplicated entries are garbled, missing some data (`$registryPath` in this case)

Note that any how to questions should be posted in the discussion board and not raised as an issue.

Version of yq: 4.45.4
Operating system: mac
Installed via: homebrew

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
sec-scanners-config.yaml:
```yaml
bdba:
  - europe-docker.pkg.dev/kyma-project/prod/dockerregistry-operator:main
  - europe-docker.pkg.dev/kyma-project/prod/external/library/registry:2.8.3-v1
  - europe-docker.pkg.dev/kyma-project/prod/registry-init:v20240506-57d31b1d

```

values.yaml:
```yaml
containerRegistry:
  path: europe-docker.pkg.dev/kyma-project
images:
  registry:
    name: "registry"
    version: "2.8.3-v1"
    directory: "prod/external/library"
  registry_init:
    name: "registry-init"
    version: "v20240506-57d31b1d"
    directory: "prod"
```

**Command**
The command you ran:
```sh
yq eval-all '
    select(fileIndex == 0).bdba=[
        select(fileIndex == 1)
        | .containerRegistry.path as $registryPath
        | (
            {
                "dockerregistry_operator" : {
                    "name" : "dockerregistry-operator",
                    "directory" : "prod",
                    "version" : "test"
                }
            }
            + .images
          )[]
        | $registryPath + "/" + .directory + "/" + .name + ":" + .version
    ]
    | select(fileIndex == 0)
    ' sec-scanners-config.yaml values.yaml
```

**Actual behavior**

```yaml
bdba:
  - /prod/dockerregistry-operator:test
  - europe-docker.pkg.dev/kyma-project/prod/dockerregistry-operator:test
  - europe-docker.pkg.dev/kyma-project/prod/external/library/registry:2.8.3-v1
  - europe-docker.pkg.dev/kyma-project/prod/registry-init:v20240506-57d31b1d
```

**Expected behavior**

```yaml
bdba:
  - europe-docker.pkg.dev/kyma-project/prod/dockerregistry-operator:test
  - europe-docker.pkg.dev/kyma-project/prod/external/library/registry:2.8.3-v1
  - europe-docker.pkg.dev/kyma-project/prod/registry-init:v20240506-57d31b1d
```

**Additional context**
- Commit where the issue was observed in the `.github/scripts/upgrade-sec-scanners-config.sh` script: https://github.com/kyma-project/docker-registry/tree/53052b1bf8efe190502beedd2c67ff990ccf2159
