### ISSUE TITLE
Select and format in an array with missing keys still outputs elements

### ISSUE THREAD

**Issue by piaverous** [mikefarah/yq#2396]
**Describe the bug**
When running a yq eval command with a select on an array, piped into an output in the form of string formatting, the behaviour changed from 4.45.2 onward.

Version of yq: 4.45.2
Operating system: tested on mac & linux
Installed via: binary release or homebrew (tested both)

**Input Yaml**
Here is the input file I have that poses problems
data1.yml:
```yaml
sources:
  first:
    repoURL: my-repo-url
    prop: path/to/first

  second:
    repoURL: my-repo-url
    name: second

  third:
    name: third
```

**Command**
The command you ran:
```
yq eval '.sources | to_entries | map(select(.value.repoURL)) | .[] | .key + " " + .value.repoURL + " " + .value.name' ./data.yaml
```

**Current behavior (in 4.45.2 and later)**

```bash
first my-repo-url 
second my-repo-url second
```

**Previous behavior (in 4.45.1 and earlier)**

```bash
second my-repo-url second
```

**Additional context**
I am not sure whether this new behavior is the "normal" behavior, or if the previous one was "normal". Just thought I'd raise an issue to validate this is indeed intentional.
