### ISSUE TITLE
Array splatting in write mode doesn't work

### ISSUE THREAD

**Issue by paescuj** [mikefarah/yq#244]
Using the example of array splatting in write mode like described on [documentation page](http://mikefarah.github.io/yq/write/) doesn't work.

Instead it results in the following output:
```
bob:
  '*':
    cats: meow
```

I've tried it using version 1.15.0 - 2.4.0.

**Comment by mikefarah** [comment]
I just tried it with 2.4.0 downloaded from the releases page (for mac):

```
~/Downloads/yq_darwin_amd64_2_4_0 w sample.yml bob.item*.cats meow
bob:
  item1:
    cats: meow
  item2:
    cats: meow
  thing:
    cats: oranges
```
