### ISSUE TITLE
Numeric text data is getting mangled

### ISSUE THREAD

**Issue by gharris999** [mikefarah/yq#245]
Given:

```
#!/bin/bash
LDEV='wlx4cedfb37602e'
ESSID='SomeSSID'
WPA_PSK='123456789012'

yq n "network.wifis.${LDEV}.access-points.${ESSID}.password" "$WPA_PSK"
```

..yields:

```
network:
  wifis:
    wlx4cedfb37602e:
      access-points:
        SomeSSID:
          password: 1.23456789012e+11
```
..which won't do, of course.  I need to store that wifi passkey string so that it can be interpreted literally. The interpreting program, netplan, isn't going to know that it needs to convert that scientific notation back into a string.

**Comment by gharris999** [comment]
..this is with yq version 2.4.0

**Comment by gharris999** [comment]
So, I haven't looked at the source code yet, as I'm *completely unfamiliar* with go, but looking at: 

https://golang.org/pkg/fmt/

..I'm guessing that create/write/update actions add data using the %v format, which defaults to %g, which in turn defaults to %e for data interpreted as large exponents.

Perhaps yq could get an optional --fmt-override=%x flag argument for reads/writes that would allow run-time control over how data is interpreted and expressed.  For my purposes, above, --fmt-override=%s would do nicely.  For more complicated string data, fmt even supports %q, " a double-quoted string safely escaped with Go syntax", which presumably would allow reading and writing virtually string data.

**Comment by gharris999** [comment]
Actually, 

```
yq n "network.wifis.${LDEV}.access-points.${ESSID}.password" "\"${WPA_PSK}\""
```
..yields:

```
network:
  wifis:
    wlx4cedfb37602e:
      access-points:
        SomeSSID:
          password: "123456789012"
```
..which netplan is OK with.  So maybe this isn't the show-stopper issue I thought it was.
