### ISSUE TITLE
how to search for file if version match

### ISSUE THREAD

**Issue by thatsk** [mikefarah/yq#257]
```YAML
deliveries:
  releases:
    latest_Rel:
      aaa:
        file_name: some.tar
        md5: xxxxxxxxxxxxxxx
        product_name: aaa
        product_number: aaa 902 8057
        release_candidate: Rel
        version: 25.1.1
      bbb:
        file_name: some1.tar
        md5: xxxxxxxxxxxxx
        product_name: bbb
        product_number: bbb 903 6746
        release_candidate: Rel
        version: 25.0.0
      abc:
        file_name: some2.gz
        md5: xxxxxxx
        product_name: abc
        product_number: None
        release_candidate: None
        version: ABC
      abd:
        file_name: some3.tar
        md5: xxxxxx
        product_name: abd
        product_number: abd 902 7815
        release_candidate: Rel
        version: 25.1.1
      abe:
        file_name: some4.gz
        md5: xxxxxxxxxxxxxxxxx
        product_name: abe
        product_number: abe 123 456
        release_candidate: Rel
        version: 25.1.1
```

Find out file name with version matching 25.1.1
