### ISSUE TITLE
feature req: support retaining full paths of matching keys

### ISSUE THREAD

**Issue by nergdron** [mikefarah/yq#262]
generally speaking, when I'm doing key matching, I'd like a feature which retains the full paths to all keys matched, basically working as a document filter instead of just returning the deepest values for the pattern.

for example, given a yaml doc like so:
```
host1:
  some:
    - data
  and:
    something:
      - else
```
I'd like to see an option where I can do the following:
```
yq r --filter test.yml '*.some.*'
host1:
  some:
    -data
```
