### ISSUE TITLE
Extend not suported

### ISSUE THREAD

**Issue by ajilk** [mikefarah/yq#264]
Extending nodes is not working as expected

Given sample.yaml:
```
---
foo: &anchor
  K1: "One"
  K2: "Two"
bar:
  <<: *anchor
  K2: "I Changed"
  K3: "Three"
```

Running:
`yq r sample.yaml`

Expected Result:
```
foo: &anchor
  K1: One
  K2: Two
bar:
  K1: One
  K2: I Changed
  K3: Three
```
Actual Result:
```
foo:
  K1: One
  K2: Two
bar:
  K2: I Changed
  K3: Three
```
