### ISSUE TITLE
not working when yaml file contains `---`

### ISSUE THREAD

**Issue by ykfq** [mikefarah/yq#275]
Example file `test.yaml`:
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    qcloud-app: my-app
  name: my-app
spec:
  ports:
  - name: tcp-3000-3000
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    qcloud-app: my-app
  type: ClusterIP

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    qcloud-app: my-app
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      qcloud-app: my-app
  template:
    metadata:
      labels:
        qcloud-app: my-app
    spec:
      containers:
        image: my-app:latest
        imagePullPolicy: Always
        name: my-app
      restartPolicy: Always
```

```bash
yq r test.yaml  # only gets the first part above ---

yq r -d "*" wx-collection-service.yaml  # this will get all data of test.yaml
```

**Comment by mikefarah** [comment]
What didn't work?

**Comment by fabianotessarolo** [comment]
Hi @mikefarah , in my case, YQ strips off the --- , also double quotes, also another thing I noticed was the yaml indentation for the first level:

```yaml
---
version: "0.17.0"
java_opts:
  - "-Djavax.net.ssl.1=2"
  - "-Djavax.net.ssl.test='3'"
java_tool_options:
  - "-Xmx1g"
  - "-Xms1g"
  - "-javaagent:{{ nova_home_dir }}/app/lib/cinnamon-agent.jar"
```

 Becomes:
```yaml
---
java_opts:
- -Djavax.net.ssl.1=2
- -Djavax.net.ssl.test='3'
java_tool_options:
- -Xmx1g
- -Xms1g
- -javaagent:{{ nova_home_dir }}/app/lib/cinnamon-agent.jar
version: 0.17.0
```
