### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by vdvince9874** [mikefarah/yq#281]
Hi,

Trying to use yq, I wonder how to describe path for such a yaml file content. I don't succeed to define the right path

```
spec:
  template:
    spec:
      containers:
      - env:
        volumeMounts:
        - mountPath: /myMountPath
          name: ...
....
```

Is it something like that :
spec.template.spec.containers[?????]

Great tool 
Thx
