### ISSUE TITLE
array indexed with [] fails on Kubeconfig files but works with .

### ISSUE THREAD

**Issue by MaurGi** [mikefarah/yq#282]
save file below in ~/tmp/test.yaml
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: blah
    server: server1
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: data
    client-key-data: data
```

This should work but fails:
```
> cat ~/tmp/test.yaml | yq r - clusters[0].cluster

zsh: no matches found: clusters[0].cluster
```

This works:
```
> cat ~/tmp/test.yaml | yq r - clusters.0.cluster

certificate-authority-data: blah
server: server1
```

Version:
```
> yq --version

yq version 2.4.0
```

Running on Ubuntu 18.04 on WSL2
