### ISSUE TITLE
merge multiple documents file with another multiple docs file

### ISSUE THREAD

**Issue by HerrmannHinz** [mikefarah/yq#285]
maybe it is possible already but i can't get it to work, here is my idea: 

i have  an `cluster.yaml`: 

``` 
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2019-09-11T07:24:11Z"
  generation: 5
  name: cicd.dev.my-cluster.io
spec:
  api:
    loadBalancer:
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    kubernetes.io/cluster/cicd.dev.my-cluster.io: owned
    service: KUBERNETES
    stage: DEV
  cloudProvider: aws
  configBase: s3://k8s.cicd.dev.my-cluster.io.configs.kops/cicd.dev.my-cluster.io
  dnsZone: cicd.dev.my-cluster.io
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-eu-central-1a
      name: a
    - encryptedVolume: true
      instanceGroup: master-eu-central-1b
      name: b
    - encryptedVolume: true
      instanceGroup: master-eu-central-1c
      name: c
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-eu-central-1a
      name: a
    - encryptedVolume: true
      instanceGroup: master-eu-central-1b
      name: b
    - encryptedVolume: true
      instanceGroup: master-eu-central-1c
      name: c
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    oidcClientID: gangway-dev
    oidcIssuerURL: https://auth.my-cluster.io/auth/realms/myrealm
    oidcUsernameClaim: sub
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: v1.15.3
  masterInternalName: api.internal.cicd.dev.my-cluster.io
  masterPublicName: api.cicd.dev.my-cluster.io
  networkCIDR: 10.241.164.0/22
  networkID: vpc-xxxxxxxxx
  networking:
    flannel:
      backend: vxlan
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.241.164.128/25
    name: eu-central-1a
    type: Private
    zone: eu-central-1a
  - cidr: 10.241.165.0/25
    name: eu-central-1b
    type: Private
    zone: eu-central-1b
  - cidr: 10.241.165.128/25
    name: eu-central-1c
    type: Private
    zone: eu-central-1c
  - cidr: 10.241.164.0/28
    name: utility-eu-central-1a
    type: Utility
    zone: eu-central-1a
  - cidr: 10.241.164.16/28
    name: utility-eu-central-1b
    type: Utility
    zone: eu-central-1b
  - cidr: 10.241.164.32/28
    name: utility-eu-central-1c
    type: Utility
    zone: eu-central-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2018-09-14T12:20:46Z"
  generation: 8
  labels:
    k8s.io/cluster-autoscaler/enabled: "true"
    kops.k8s.io/cluster: cicd.my-cluster.io
    kubernetes.io/cluster/cicd.my-cluster.io: owned
  name: nodes
spec:
  image: kope.io/k8s-1.14-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: m5.2xlarge
  maxSize: 19
  minSize: 6
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - eu-central-1a
  - eu-central-1b
  - eu-central-1c
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2018-09-14T12:20:46Z"
  generation: 8
  labels:
    k8s.io/cluster-autoscaler/enabled: "true"
    kops.k8s.io/cluster: cicd.my-cluster.io
    kubernetes.io/cluster/cicd.my-cluster.io: owned
  name: nodes
spec:
  image: kope.io/k8s-1.14-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: m5.2xlarge
  maxSize: 19
  minSize: 6
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - eu-central-1a
  - eu-central-1b
  - eu-central-1c
--- 
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2018-09-14T12:20:46Z"
  generation: 8
  labels:
    k8s.io/cluster-autoscaler/enabled: "true"
    kops.k8s.io/cluster: cicd.my-cluster.io
    kubernetes.io/cluster/cicd.my-cluster.io: owned
  name: nodes
spec:
  image: kope.io/k8s-1.14-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: m5.2xlarge
  maxSize: 19
  minSize: 6
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - eu-central-1a
  - eu-central-1b
  - eu-central-1c  
``` 

also  an `overrides.yaml`: 

```
---
kind: InstanceGroup
spec:
  additionalUserData:
  - content: |
      #!/bin/sh
      # download Qualy Agent from S3 bucket
      aws s3 cp s3://qualys-agent-location/qualys-cloud-agent.x86_64.deb /tmp/
      # installing the Qualys Agent
      sudo apt install /tmp/qualys-cloud-agent.x86_64.deb
      # stop Qualys Agent for configuration
      sudo service qualys-cloud-agent stop
      # configure Qualys Agent
      sudo /usr/local/qualys/cloud-agent/bin/qualys-cloud-agent.sh ActivationId=xxxxxxxx-568b-4910-8f52-xxxxxxxx CustomerId=xxxxxxxxxx
      # starting Qualys Agent after configuration
      sudo service qualys-cloud-agent start
    name: qualys-agent-install.sh
    type: text/x-shellscript
---
kind: Cluster
spec:
  additionalPolicies:
    master: |-
      [
          {
              "Sid": "kopsK8sIngressControllerAws",
              "Effect": "Allow",
              "Action": [
                  "acm:GetCertificate",
                  "acm:ListCertificates",
                  "acm:DescribeCertificate",
                  "autoscaling:DescribeAutoScalingGroups",
                  "autoscaling:AttachLoadBalancers",
                  "autoscaling:DetachLoadBalancers",
                  "autoscaling:DetachLoadBalancerTargetGroups",
                  "autoscaling:AttachLoadBalancerTargetGroups",
                  "autoscaling:DescribeLoadBalancerTargetGroups",
                  "cloudformation:*",
                  "elasticloadbalancing:*",
                  "elasticloadbalancingv2:*",
                  "ec2:DescribeInstances",
                  "ec2:DescribeSubnets",
                  "ec2:DescribeSecurityGroups",
                  "ec2:DescribeRouteTables",
                  "ec2:DescribeVpcs",
                  "iam:GetServerCertificate",
                  "iam:ListServerCertificates"
              ],
              "Resource": [
                  "*"
              ]
          }
      ]
    node: |
      [
          {
              "Sid": "kopsK8sIngressControllerAws",
              "Effect": "Allow",
              "Action": [
                  "acm:GetCertificate",
                  "acm:ListCertificates",
                  "acm:DescribeCertificate",
                  "autoscaling:DescribeAutoScalingGroups",
                  "autoscaling:AttachLoadBalancers",
                  "autoscaling:DetachLoadBalancers",
                  "autoscaling:DetachLoadBalancerTargetGroups",
                  "autoscaling:AttachLoadBalancerTargetGroups",
                  "autoscaling:DescribeLoadBalancerTargetGroups",
                  "cloudformation:*",
                  "elasticloadbalancing:*",
                  "elasticloadbalancingv2:*",
                  "ec2:DescribeInstances",
                  "ec2:DescribeSubnets",
                  "ec2:DescribeSecurityGroups",
                  "ec2:DescribeRouteTables",
                  "ec2:DescribeVpcs",
                  "iam:GetServerCertificate",
                  "iam:ListServerCertificates"
              ],
              "Resource": [
                  "*"
              ]
          }
      ]
``` 

my desired result would be: 

patch everything into `cluster.yaml` what has been defined in `overrides.yaml`.
patch `spec.additionalUserData` from `overrides.yaml` into each document of `kind: InstanceGroup` into `cluster.yaml` 

i think you get the idea. 

would that be possible? 

thanks in ahead for your help. :)

**Comment by mikefarah** [comment]
This should do the trick

```
yq merge --doc '*' cluster.yaml overrides.yaml
```

**Comment by HerrmannHinz** [comment]
partially working: 

``` 
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2019-09-11T07:24:11Z"
  generation: 5
  name: cicd.dev.my-cluster.io
spec:
  additionalUserData:
  - content: |
      #!/bin/sh
      aws s3 cp s3://qualys-agent-location/qualys-cloud-agent.x86_64.deb /tmp/
      sudo apt install /tmp/qualys-cloud-agent.x86_64.deb
      sudo service qualys-cloud-agent stop
      sudo /usr/local/qualys/cloud-agent/bin/qualys-cloud-agent.sh ActivationId=xxxxxxxx-568b-4910-8f52-xxxxxxxx CustomerId=xxxxxxxxxx
      sudo service qualys-cloud-agent start
    name: qualys-agent-install.sh
    type: text/x-shellscript
  api:
    loadBalancer:
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    kubernetes.io/cluster/cicd.dev.my-cluster.io: owned
    service: KUBERNETES
    stage: DEV
  cloudProvider: aws
  configBase: s3://k8s.cicd.dev.my-cluster.io.configs.kops/cicd.dev.my-cluster.io
  dnsZone: cicd.dev.my-cluster.io
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-eu-central-1a
      name: a
    - encryptedVolume: true
      instanceGroup: master-eu-central-1b
      name: b
    - encryptedVolume: true
      instanceGroup: master-eu-central-1c
      name: c
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-eu-central-1a
      name: a
    - encryptedVolume: true
      instanceGroup: master-eu-central-1b
      name: b
    - encryptedVolume: true
      instanceGroup: master-eu-central-1c
      name: c
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    oidcClientID: gangway-dev
    oidcIssuerURL: https://auth.my-cluster.io/auth/realms/myrealm
    oidcUsernameClaim: sub
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: v1.15.3
  masterInternalName: api.internal.cicd.dev.my-cluster.io
  masterPublicName: api.cicd.dev.my-cluster.io
  networkCIDR: 10.241.164.0/22
  networkID: vpc-xxxxxxxxx
  networking:
    flannel:
      backend: vxlan
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.241.164.128/25
    name: eu-central-1a
    type: Private
    zone: eu-central-1a
  - cidr: 10.241.165.0/25
    name: eu-central-1b
    type: Private
    zone: eu-central-1b
  - cidr: 10.241.165.128/25
    name: eu-central-1c
    type: Private
    zone: eu-central-1c
  - cidr: 10.241.164.0/28
    name: utility-eu-central-1a
    type: Utility
    zone: eu-central-1a
  - cidr: 10.241.164.16/28
    name: utility-eu-central-1b
    type: Utility
    zone: eu-central-1b
  - cidr: 10.241.164.32/28
    name: utility-eu-central-1c
    type: Utility
    zone: eu-central-1c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2018-09-14T12:20:46Z"
  generation: 8
  labels:
    k8s.io/cluster-autoscaler/enabled: "true"
    kops.k8s.io/cluster: cicd.my-cluster.io
    kubernetes.io/cluster/cicd.my-cluster.io: owned
  name: nodes
spec:
  additionalUserData:
  - content: |
      #!/bin/sh
      aws s3 cp s3://qualys-agent-location/qualys-cloud-agent.x86_64.deb /tmp/
      sudo apt install /tmp/qualys-cloud-agent.x86_64.deb
      sudo service qualys-cloud-agent stop
      sudo /usr/local/qualys/cloud-agent/bin/qualys-cloud-agent.sh ActivationId=xxxxxxxx-568b-4910-8f52-xxxxxxxx CustomerId=xxxxxxxxxx
      sudo service qualys-cloud-agent start
    name: qualys-agent-install.sh
    type: text/x-shellscript
  image: kope.io/k8s-1.14-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: m5.2xlarge
  maxSize: 19
  minSize: 6
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - eu-central-1a
  - eu-central-1b
  - eu-central-1c
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2018-09-14T12:20:46Z"
  generation: 8
  labels:
    k8s.io/cluster-autoscaler/enabled: "true"
    kops.k8s.io/cluster: cicd.my-cluster.io
    kubernetes.io/cluster/cicd.my-cluster.io: owned
  name: nodes
spec:
  additionalUserData:
  - content: |
      #!/bin/sh
      aws s3 cp s3://qualys-agent-location/qualys-cloud-agent.x86_64.deb /tmp/
      sudo apt install /tmp/qualys-cloud-agent.x86_64.deb
      sudo service qualys-cloud-agent stop
      sudo /usr/local/qualys/cloud-agent/bin/qualys-cloud-agent.sh ActivationId=xxxxxxxx-568b-4910-8f52-xxxxxxxx CustomerId=xxxxxxxxxx
      sudo service qualys-cloud-agent start
    name: qualys-agent-install.sh
    type: text/x-shellscript
  image: kope.io/k8s-1.14-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: m5.2xlarge
  maxSize: 19
  minSize: 6
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - eu-central-1a
  - eu-central-1b
  - eu-central-1c
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2018-09-14T12:20:46Z"
  generation: 8
  labels:
    k8s.io/cluster-autoscaler/enabled: "true"
    kops.k8s.io/cluster: cicd.my-cluster.io
    kubernetes.io/cluster/cicd.my-cluster.io: owned
  name: nodes
spec:
  additionalUserData:
  - content: |
      #!/bin/sh
      aws s3 cp s3://qualys-agent-location/qualys-cloud-agent.x86_64.deb /tmp/
      sudo apt install /tmp/qualys-cloud-agent.x86_64.deb
      sudo service qualys-cloud-agent stop
      sudo /usr/local/qualys/cloud-agent/bin/qualys-cloud-agent.sh ActivationId=xxxxxxxx-568b-4910-8f52-xxxxxxxx CustomerId=xxxxxxxxxx
      sudo service qualys-cloud-agent start
    name: qualys-agent-install.sh
    type: text/x-shellscript
  image: kope.io/k8s-1.14-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: m5.2xlarge
  maxSize: 19
  minSize: 6
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - eu-central-1a
  - eu-central-1b
  - eu-central-1c
``` 

hmm. 🤔  u have any other idea? if not nevermind. i wrote a little python script to do the magic: 

```python
import ruamel.yaml as yaml
import os
import sys

with open(os.path.expanduser("selected.yaml"), "rb") as fc:
    # load and parse cluster yaml
    docs = yaml.load_all(fc, Loader=yaml.RoundTripLoader)
    for doc in docs:
        with open(os.path.expanduser("yaml-merge-overrides.yaml"), "rb") as fo:
            # load and parse overrides yaml
            overrides = yaml.load_all(fo, Loader=yaml.RoundTripLoader)
            for override in overrides:
                # if kind in overrides matches the current one in cluster.yaml - GOOOO
                if override['kind'] == doc['kind'] and "spec" in override:
                    for spec_data in override['spec']: 
                        doc['spec'][spec_data] = override['spec'][spec_data]
        # apped updated yaml node doc to out.yaml                
        doc_out = yaml.dump(doc,Dumper=yaml.RoundTripDumper, explicit_start=True)   
        with open("cluster.yaml", "a") as file:
            file.write(doc_out)
    print("#### cluster.yaml updated ")                  
```
