### ISSUE TITLE
When the yaml file has * then it will consume a lot of memory and cpu, also the process will be stuck there.

### ISSUE THREAD

**Issue by hlxwell** [mikefarah/yq#296]
## Sample data
```
grpc:
  port: *grpc_server_port
auth:
  port: *http_server_port
```

## Command line
```
yq r -d'*' file.yaml
```

## Version
```
➜  ~ yq --version
yq version 2.4.1
```

## Result
The process is stuck there and CPU and Memory is soaring.
