### ISSUE TITLE
[Feature request] subtraction between two YAML files

### ISSUE THREAD

**Issue by LinuxSuRen** [mikefarah/yq#301]
Here are two YAML files:

## a.yaml
```
jenkins:
  clouds:
  - kubernetes:
      name: kubernetes-1
  - kubernetes:
      name: kubernetes-2
  - kubernetes:
      name: kubernetes-3
```

## b.yaml
```
jenkins:
  clouds:
  - kubernetes:
      name: kubernetes-1
```

I expect is that subtract `b.yaml` from `a.yaml. The expected result like this:

```
jenkins:
  clouds:
  - kubernetes:
      name: kubernetes-2
  - kubernetes:
      name: kubernetes-3
```

If anyone has other ways can archive that goal, please leave a comment here. Thanks for your time.
