### ISSUE TITLE
Can't delete using wild card 

### ISSUE THREAD

**Issue by nat2k5us** [mikefarah/yq#309]
I am trying to delete all the x-go-package key & values in swagger.yaml

There are multiple lines and sections these values are present. I want to remove this node & value completely from the whole file
```
definitions:
  AdvancedOption:
    description: AdvancedOption for an order
    properties:
    type: object
    x-go-package: gitlab.xxxx.xxxxxxxxx.com/xxxxxxxxxxxx
```

what I tried:

```
 yq d -i  swagger.yaml definitions.[*].x-go-package  
no matches found: definitions.[*].x-go-package

yq d -i  swagger.yaml definitions.AdvancedOption.x-go-package     
the above works but I need to be able to remove it using a wild card like
yq d -i  swagger.yaml definitions.*.x-go-package  
or
yq d -i  swagger.yaml definitions.[*].x-go-package  
```

but it does not work with a message saying it was not found
