### ISSUE TITLE
YQ Does Not Properly Handle Merge Keys

### ISSUE THREAD

**Issue by apeschel** [mikefarah/yq#310]
## Version

Using yq 2.4.1 -- latest stable release at time of writing.

## Description

yq's appears to just drop merge keys (`<<:`), rather than produce any output or an error.

### Example 1:

**Input:**

```
foo: &foo
  a: 1

bar: &bar
  b: 2

foobar:
  <<: [*foo,*bar]
  c: 3
```

**Expected output:**

```
bar:
  b: 2
foo:
  a: 1
foobar:
  a: 1
  b: 2
  c: 3
```

**Actual output:**

```
foo:
  a: 1
bar:
  b: 2
foobar:
  c: 3
```

### Example 2:

**Input:**

```
foo: &foo
  a: 1

foobar:
  <<: *foo
  c: 3
```

**Expected output:**

```
foo:
  a: 1
foobar:
  a: 1
  c: 3
```

**Actual output:**

```
foo:
  a: 1
foobar:
  c: 3
```

### Example 3:

**Input:**

```
list:
  - &foo
    a: 1
  - &bar
    b: 2

foobar:
  <<: [*foo,*bar]
  c 3
```

**Expected output:**

```
list:
- a: 1
- b: 2
foobar:
  a: 1
  b: 2
  c: 3
```

**Actual output:**

```
list:
- a: 1
- b: 2
foobar:
  c: 3
```

### Example 4:

yq does handle simple aliases correctly.

**Input:**

```
foo: &foo "foo"
bar: &bar "bar"

foobar:
  foo: *foo
  bar: *bar
  foobar: "foobar"
```

**Expected output:**

```
foo: foo
bar: bar
foobar:
  foo: foo
  bar: bar
  foobar: foobar
```

**Actual output:**

```
foo: foo
bar: bar
foobar:
  foo: foo
  bar: bar
  foobar: foobar
```
