### ISSUE TITLE
yq merge with wrong indentation

### ISSUE THREAD

**Issue by winacid** [mikefarah/yq#326]
i tryed to merge two yaml files, but something is wrong.

a.yaml
```
version: "3.7"
services:
  hello:
    image: hello-world
    port:
      - 80
```
b.yaml
```
version: "3.7"
services:
  hello:
    port:
      - 90
```

i run yq like this
`yq m -x a.yaml b.yaml`

what i expect:
```
version: "3.7"
services:
  hello:
    image: hello-world
    port:
      - 90
```
and what i get is (yq version 2.4.1)
```
services:
  hello:
    image: hello-world
    port:
    - 90
version: "3.7"
```
and (yq version 3.0.0 beta)
```
version: '3.7'
services:
  hello:
    image: hello-world
    port:
    - 90
```

the main problem in latest version is the wrong order and indentation
in the first beta order is fixed but still issues with the indentation
