### ISSUE TITLE
Json output fails when using merge anchors

### ISSUE THREAD

**Issue by AngryGami** [mikefarah/yq#339]
Latest 3.0.1 release when given following sample yaml:
```yaml
test-map: &testmap
  key1: 1
  key2: "hello"
test2-map:
  <<: *testmap
```
with command like this:
`./yq r -j test.yaml`
Print out usage and bark with error in the end:
```
...
17:21:02 main [ERRO] json: unsupported type: map[interface {}]interface {}
```
I've seen #151 though it talks about merging files while this error happens with single file. I understand that json doesn't support anchors and therefore it is unclear what should be printed (or rather printing properly resolved json could be hard). Maybe you can make yq print empty object in place where merge was used instead failing?
