### ISSUE TITLE
3.0.1 still breaks formatting and comments

### ISSUE THREAD

**Issue by hassomehide** [mikefarah/yq#343]
From the release notes:

> Keeps yaml comments and formatting, can specify yaml tags when updating. #19, #169, #107, #171, #245, #303

Unfortunately some issues are still present.

**Formatting:**

```
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
```
is formatted to:
```
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
```
Notice the whitespace difference before the array element.

**Comments:**

Even though comments are now preserved, they seem to be re-encoded in some other encoding than UTF-8 because I'm getting back ��� instead of the symbols that were originally present in the comments.

This is the yq command I'm using:
```
yq write -i -d1 test.yaml 'spec.template.spec.containers(name==test).image' test-value
```
