### ISSUE TITLE
Merging -x with map where sequence was originally

### ISSUE THREAD

**Issue by coryrc** [mikefarah/yq#348]
f1.yaml:
```yaml
a:
 - b: b
   c: c
```
f2.yaml:
```yaml
a:
  d: d
  e: e
```
yq m -x f1.yaml f2.yaml
```yaml
a:
- b: b
  c: c
```

I would expect either an error or the output should match f2.yaml, but I might be wrong.
