### ISSUE TITLE
Handle merging things like Kubernetes EnvVars

### ISSUE THREAD

**Issue by coryrc** [mikefarah/yq#349]
Kubernetes team reinvented maps with EnvVars; instead of:

```yaml
var_name:
  value: x
other_name:
  valuesFrom: whatever
```
it's a sequence
```yaml
- name: var_name
  value: x
- name: other_name
  valuesFrom: whatever
```
I handled this by have my source templates specify them in the first form above, then transform them at the last stage with a custom built program.

I was trying to think up how `yq` could have helped:
1. A config file where you could specify "when yq reaches this path, apply a transform before and after merging". I think the transforms would have to be hard-coded though?
2. A command to do this transform
