### ISSUE TITLE
yq -d removes '---' header

### ISSUE THREAD

**Issue by 030** [mikefarah/yq#351]
If a file contain a `---` header and `yq -d` is issued, then the header gets removed.

**Comment by bquenin** [comment]
it's not only on `-d`, any write would remove the document header

**Comment by bquenin** [comment]
I had a look at the issue and it looks like this behavior comes from the `gopkg.in/yaml.v3` library itself.
For some reason, it doesn't output document separators.
 
Strangely enough, the information about document separator is decoded and kept in the AST during parsing and later available to the encoder (in `Node.Line`). But since the behavior of the encoder is not configurable, there's no way to use this information.

The only thing I can think of is to rewrite an encoder supporting document separators or maybe submit a feature request to the official yaml library so that the encoder gets configurable.

**Comment by puffan** [comment]
It also happens when running `yq r -I2 xxx.yaml`, the output remove the '---'

**Comment by sebastian-philipp** [comment]
this is indeed some strange behavior. My original document is:

```yaml
created: '2020-06-19T09:29:52.800086'
daemon_id: ubuntu
daemon_type: crash
hostname: ubuntu
last_refresh: '2020-06-19T09:33:50.400609'
started: '2020-06-19T09:29:53.002004'
status: 1
status_desc: running
version: 16.0.0-901-g713ef3c
---
container_image_name: foobar
created: '2020-06-19T09:33:32.265147'
daemon_id: ubuntu
daemon_type: mon
hostname: ubuntu
last_refresh: '2020-06-19T09:33:50.400690'
status: -1
status_desc: unknown
```

running `cat document.yaml | yq -C r -d'*' -` writes:

```yaml
container_id: e8cdc5d68c36
container_image_id: 74803e884bea289d2d2d3ebdf6d37cd560499e955595695b1390a89800f4e37a
container_image_name: foobar
created: '2020-06-19T09:29:52.800086'
daemon_id: ubuntu
daemon_type: crash
hostname: ubuntu
last_refresh: '2020-06-19T09:33:50.400609'
started: '2020-06-19T09:29:53.002004'
status: 1
status_desc: running
version: 16.0.0-901-g713ef3c
container_image_name: foorbar
created: '2020-06-19T09:33:32.265147'
daemon_id: ubuntu
daemon_type: mon
hostname: ubuntu
last_refresh: '2020-06-19T09:33:50.400690'
status: -1
status_desc: unknown
```

which makes `ya` pretty much useless for me.
