### ISSUE TITLE
yq 3 removes empty inline-style objects and arrays

### ISSUE THREAD

**Issue by tedslittlerobot** [mikefarah/yq#355]
With these two yaml files:

```yaml
foo:
    bar:
        type: monkeys
```

```yaml
foo:
    bar:
        hello: world
        disappearing_object: {}
        disappearing_array: []
        kept_object:
```

Running `yq m one.yml two.yml` results in the following output:

In yq 2.4.1:

```yaml
foo:
  bar:
    disappearing_array: []
    disappearing_object: {}
    hello: world
    type: monkeys
```

In yq 3.0.1:

```yaml
foo:
  bar:
    type: monkeys
    hello: world
    kept_object:
```

The behaviour of keeping empty objects has flipped entirely from 2 to 3, and is not documented in the "upgrading from 2.x". This has caused quite a few issues when constructing configuration files for say, docker, which rely on certain keys existing.

Just for the record, I am very happy that the `kept_object:` syntax is now supported! But it does seem like a bug that the empty object syntax resolves to no key being present in the final file.

The ideal output, i think (ignoring any sorting etc.) would be:

```yaml
foo:
  bar:
    type: monkeys
    hello: world
    kept_object:
    disappearing_array:
    disappearing_object:
```

I am aware that it appears to attempt to convert inlines into classic yaml dictionaries / arrays - this may be where the error is occurring.
