### ISSUE TITLE
Write to empty document removes path

### ISSUE THREAD

**Issue by glindstedt** [mikefarah/yq#359]
Given a document `foo.yaml`:

```yaml
foo: bar
---
# empty
---
hello: world
```

If you run `yq w -d'*' foo.yaml foo test` produces the following output:
```yaml
foo: test
---
test

# empty
---
hello: world
foo: test
```

The expected result would be the empty document containing `foo: test`, not simply `test`.

yq version tested: 3.1.0
