### ISSUE TITLE
Add new object to existing array object is failing in 3.1.1

### ISSUE THREAD

**Issue by dben1713** [mikefarah/yq#361]
Using the latest version of yq appears to break being able to add new objects to an existing array object, this was working fine as of version 2.4.1.

With this file:
```yaml
applications:
  - name: app
    env:
```

I cannot use write to add an additional field to the 'env' object. I would expect this 
`yq w hello.yml "applications[0].env.hello" "world"`
to output the following:

```yaml
applications:
  - name: app
    env:
      hello: world
```

However, I am just getting the follow output:
```yaml
applications:
  - name: app
    env:
```

I'm not sure if this is a result of the breaking change regarding "reading paths that don't exist" with the new version or not.

Adding new nodes to the array seems to work fine:
`yq w -v hello.yml "applications[0].hello" "WORLD"`
```yaml
applications:
  - name: app
    env:
    hello: WORLD
```

`yq w -v hello.yml "applications[0].hello.foo" "WORLD"`
```yaml
applications:
  - name: app
    env:
    hello:
      foo: WORLD
```

But I need to be able to update an existing node in the array.  This is probably related to #356.
