### ISSUE TITLE
Breaking from 2 to 3 (array and comments)

### ISSUE THREAD

**Issue by mfouilleul** [mikefarah/yq#364]
I have a breaking change in the version 3 with array and comment, can you help debug this, maybe there is a flag which can help me.

The file 1.txt
```
# any class that implements the SeedProvider interface and has a
# constructor that takes a Map<String, String> of parameters will do.
seed_provider:
    # Addresses of hosts that are deemed contact points.
    # Cassandra nodes use this list of hosts to find each other and learn
    # the topology of the ring.  You must change this if you are running
    # multiple nodes!
    - class_name: org.apache.cassandra.locator.SimpleSeedProvider
      parameters:
          # seeds is actually a comma-delimited list of addresses.
          # Ex: "<ip1>,<ip2>,<ip3>"
          - seeds: "127.0.0.1"
```

The file 2.txt
```
authenticator: PasswordAuthenticator
authorizer: org.apache.cassandra.auth.CassandraAuthorizer
```

I want to merge the both, 

With the version 2, the result is:
```
docker run --rm -it  mikefarah/yq:2 sh
/workdir # yq m 1.txt 2.txt
authenticator: PasswordAuthenticator
authorizer: org.apache.cassandra.auth.CassandraAuthorizer
seed_provider:
- class_name: org.apache.cassandra.locator.SimpleSeedProvider
  parameters:
  - seeds: 127.0.0.1
```

With the version 3, the result is:
```
# yq m 1.txt 2.txt
# any class that implements the SeedProvider interface and has a
# constructor that takes a Map<String, String> of parameters will do.
seed_provider:
- # Addresses of hosts that are deemed contact points.
  # Cassandra nodes use this list of hosts to find each other and learn
  # the topology of the ring.  You must change this if you are running
  # multiple nodes!
  class_name: org.apache.cassandra.locator.SimpleSeedProvider
  parameters:
  - # seeds is actually a comma-delimited list of addresses.
    # Ex: "<ip1>,<ip2>,<ip3>"
    seeds: "127.0.0.1"
```

My issue is the integration of the comment inside the array:
```
- # seeds is actually a comma-delimited list of addresses.
    # Ex: "<ip1>,<ip2>,<ip3>"
    seeds: "127.0.0.1"
```

The format `- seeds:` is necessary in the official cassandra's docker-entrypoint. 

Thanks!
