### ISSUE TITLE
Incorrect fields are replaced by empty dicts (3.1.2)

### ISSUE THREAD

**Issue by stolam** [mikefarah/yq#375]
**Description**
When path is not matched `yq d` replaces some values with `{}`

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug)
bad.yml:
```yaml
name: a
field1: type_1
field2: ['a', 'b', 'c']
```
**Command**
The command you ran:
```
yq d bad.yml '[type==type_1].array[*]'
```

**Actual behavior**
For some reason, even though the input does not conform to schema (does not contain list on upper most level), it deletes first 2 values.
```yaml
name: {}
field1: {}
field2: ['a', 'b', 'c']
```

**Expected behavior**
I would expect the file to be unchanged as nothing matches the pattern.
```yaml
name: a
field1: type_1
field2: ['a', 'b', 'c']
```

**Additional context**
When the pattern is matched, everything works as expected:
```yaml
- name: a
  type: type_1
  array: ['a', 'b', 'c']

- name: b
  type: different_type
  array: ['a', 'b', 'c']
```

yields 
```yaml
- name: a
  type: type_1
  array: []
- name: b
  type: different_type
  array: ['a', 'b', 'c']
```

The previous version (3.1.1) was working correctly.
