### ISSUE TITLE
Lots of breakages when moving to v3

### ISSUE THREAD

**Issue by Jab2870** [mikefarah/yq#382]
**Describe the bug**

I am experiencing a lot of breakages after upgrading to v3

**Input Yaml**

```yaml
title: Example Title
tags:
  - Tag1
  - Tag2
  - Tag3
description: An example description
date: 2020-02-29
```

**Command**
The command you ran:
```
date="$(echo "$info" | yq -r '.date' )"
tags="$(echo "$info" | yq -r 'if ( .tags | type ) == "array" then .tags else [ .tags ] end | join("\n")')"
```

**Actual behavior**

```
Error: unknown shorthand flag: 'r' in -r
```

I have read through the [upgrade page](https://mikefarah.gitbook.io/yq/upgrading-from-v2) but it doesn't give any help with this problem.

Thanks
