### ISSUE TITLE
'write' command updates and appends

### ISSUE THREAD

**Issue by kppullin** [mikefarah/yq#384]
**Describe the bug**
I'm running a `write` command and it appears to be both updating _and_ appending content incorrectly.

In the "actual behavior" section you'll see a duplicate `deploy: command: testing123`  chunk at the end of the output.  I'd expect to _just_ see the existing `deploy: command:` value updated.

**Input Yaml**
data1.yml:
```yaml
jobs:
  deploy_dev:
    steps:
      - checkout
      - deploy:
          command: |
            <redacted>
      - push_slack_notification:
          envType: "dev"
```

**Command**
The command you ran:
```
yq write data1.yml 'jobs.deploy_dev.steps[*].deploy.command' testing123
```

**Actual behavior**

```yaml
jobs:
  deploy_dev:
    steps:
    - checkout
    - deploy:
        command: testing123
    - push_slack_notification:
        envType: "dev"
      deploy:
        command: testing123
```

**Expected behavior**

```yaml
jobs:
  deploy_dev:
    steps:
    - checkout
    - deploy:
        command: testing123
    - push_slack_notification:
        envType: "dev"
```
