### ISSUE TITLE
Add a strip comments flag that will remove all comments from the output

### ISSUE THREAD

**Issue by momoYB** [mikefarah/yq#385]
**Is your feature request related to a problem? Please describe.**
Add a strip comments flag, as it will help resolve some minor incompatible changes produced by the "keeping YAML comments" feature in YQ 3.X.X

> [mikefarah commented 14 days ago](https://github.com/mikefarah/yq/issues/364#issuecomment-589398998)
...
Failing a yaml.v3 fix - the only thing I can think of is adding a strip comments flag that will remove all the comments...

**Describe the solution you'd like**
If we have countries.yaml like:

```yaml
country:
    name: USA
    # name: United States of America
    capital: Washington, D.C.
    monuments:
        - Statue of Liberty
        - Grand Canyon
        # - Giant Sequoia
        # - Washington Monument
        - Mount Rushmore
    # currency: USD
```

Currently, if we run the command:

```bash
yq r countries.yaml "country.monuments"
```
the output is:

```yaml
- Statue of Liberty
- Grand Canyon
# - Giant Sequoia
# - Washington Monument
- Mount Rushmore
```
With **strip comments** flag like:
```bash
yq r countries.yaml --stripComments "country.monuments"
```

the wanted output should be:

```yaml
- Statue of Liberty
- Grand Canyon
- Mount Rushmore
```
