### ISSUE TITLE
Writing strings with double quotes from env var

### ISSUE THREAD

**Issue by ppatierno** [mikefarah/yq#387]
I have a script with a variable as follow:

`MESSAGE="Hello World"`

I am trying to write this value in a YAML file deployment for Kubernetes:

```yaml
...
spec:
      containers:
      - name: producer
        image: strimzi/hello-world-producer:latest
        env:
        - name: BOOTSTRAP_SERVERS
          value: demo2020-kafka-bootstrap:9092
        - name: TOPIC
          value: topic
        - name: DELAY_MS
          value: 1000
        - name: LOG_LEVEL
          value: "INFO"
        - name: MESSAGE_COUNT
          value: "1000000"
        - name: MESSAGE
          value: test
...
```

Using the following command:

```
yq w -i $DIR/producer-deployment.yaml spec.template.spec.containers[0].env.name==MESSAGE.value $MESSAGE
```

but what I got is the following:

```
- name: MESSAGE
  value: Hello
```

so the value is cut.

What's the right way to have:

```
- name: MESSAGE
  value: "Hello world"
```

So the entire string but with double quotes as well, otherwise it will be an invalid value for the Kubernetes API server.
