### ISSUE TITLE
not a bug - how to include key in the result while parsing yaml file with yq command

### ISSUE THREAD

**Issue by infa-ddeore** [mikefarah/yq#390]
**Describe the bug**
I know this isnt a bug but i ddn't get an answer on [stackoverflow](https://stackoverflow.com/questions/60712339/how-to-include-key-in-the-result-while-parsing-yaml-file-with-yq-command) and couldn't find on google so asking same question here. 

how to get values including the key?

**Input Yaml**
data1.yml:
```yaml
istio_cni:
  enabled: false
  repair:
    enabled: true

istiocoredns:
  enabled: false

global:
  hub: docker.io/istio
  tag: 1.4.5
  logging:
    level: "default:info"
```

**Command**
The command you ran:
```
yq r data1.yaml global
```

**Actual behavior**

```yaml
hub: docker.io/istio
tag: 1.4.5
logging:
  level: "default:info"
```

**Expected behavior**

```yaml
global:
  hub: docker.io/istio
  tag: 1.4.5
  logging:
    level: "default:info"
```
