### ISSUE TITLE
Writing to a file "in-place" when the yaml is invalid results in an empty file.

### ISSUE THREAD

**Issue by denniswebb** [mikefarah/yq#393]
**Describe the bug**
When yq encounters invalid yaml during an in-place write process, it empties the file then exits 1.

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug)
data1.yml:
```yaml
image:
  tag: foo
  - bar
```

**Command**
```
yq w -i data1.yaml image.tag: foobar
```

**Actual behavior**
File is emptied
```yaml

```

**Expected behavior**
Error is thrown and file left unchanged
```yaml
image:
  tag: foo
  - bar
```
