### ISSUE TITLE
Weird behaviour when merging files that use splat operator as keys

### ISSUE THREAD

**Issue by glynnforrest** [mikefarah/yq#399]
I'm getting strange results when trying to merge two files that both have `'*'` as a key.

**Input Yaml**
data1.yml:
```yaml
base:
  '*':
    - one
  'foo':
    - three
```

data2.yml:
```yaml
base:
  '*':
    - two
  'bar':
    - four
```

**Command**
```
yq merge -a data1.yml data2.yml
```

**Actual behavior**

```yaml
base:
  '*':
  - one
  - two
  'foo':
  - three
  - two
  bar:
  - four
```

**Expected behavior**

```yaml
base:
  '*':
  - one
  - two
  'foo':
  - three
  'bar':
  - four
```

Note how `two` has been added to both `'*'` and `'foo'` in the output. I'm also not sure why `'foo'` is quoted but `bar` is not.

I also see the problem for `'**'`, but not with `'*.*'`.

`yq --version` = `3.2.1`.

I'm working with [SaltStack top files](https://docs.saltstack.com/en/latest/ref/states/top.html#getting-started-with-top-files), hence the silly key names.

Thanks for the great tool! 🎉
