### ISSUE TITLE
Regression from 3.1.1: Creating new nested dict and adding a key results in overwriting the entire hierarchy

### ISSUE THREAD

**Issue by dbsanfte** [mikefarah/yq#400]
**Describe the bug**

In yq 3.1.1 given this yaml, which we'll call values.yaml:

```
stacks:
- containers:
  - image: some/image/name:1.0.45
    imagePullPolicy: ""
    name: svc
    resources: {}
    livenessProbe:
      httpGet:
        path: /health
        port: "12345"
    traefikConfigs:
    - port: "12345"
      rule: "PathPrefixStrip: /some-path"
    ports:
    - containerPort: "12345"
  restartPolicy: Always
  serviceAccountName: ""
  volumes: null
  name: some-name
appFamilyName: some-other-name
defaultReplicas: 2
```

I can do this:

`cat ./values.yaml | yq w - 'stacks[].containers[].env[0].name' ENV_NAME`

And that results in this:

```
stacks:
- containers:
  - image: some/image/name:1.0.45
    imagePullPolicy: ""
    name: svc
    resources: {}
    livenessProbe:
      httpGet:
        path: /health
        port: "12345"
    traefikConfigs:
    - port: "12345"
      rule: "PathPrefixStrip: /some-path"
    ports:
    - containerPort: "12345"
  env:
  - name: ENV_NAME
  restartPolicy: Always
  serviceAccountName: ""
  volumes: null
  name: some-name
appFamilyName: some-other-name
defaultReplicas: 2
```

But in yq 3.2.1, the same operation results in this:

```
stacks:
  '':
    containers:
      '':
        env:
        - name: ENV_NAME
appFamilyName: some-other-name
defaultReplicas: 2
```
