### ISSUE TITLE
.yaml data formatting which should be get used by Docker.

### ISSUE THREAD

**Issue by avinashGuptaIos** [mikefarah/yq#411]
**Describe the bug**
There is a formatting issues there, like spacing issues .

**Command**
The command you ran:
```

FILE_NAME="tempFile"
read -p "Enter file name for generating file with default file name as $FILE_NAME : " p0
FILE_NAME=${p0:-$FILE_NAME}

VERSION=3
read -p "Enter version with default version as $VERSION : " version
VERSION=${version:-$VERSION}

defaultInformation1Array=(89999:4356)
echo "Enter Information1 array with default value as ${defaultInformation1Array[@]} : "
while read line 
do
    Information1Array=("${Information1Array[@]}" $line)
done
Information1Array=("${Information1Array[@]:-${defaultInformation1Array[@]}}")
echo ${Information1Array[@]}


defaultInformation2Array=("A" "B" "C" "D" "E" "F" "G" 'H' "I" "J" "K" "L" "M" "N")
echo "Enter Information2 array with default value as ${defaultInformation2Array[@]} : "
while read line 
do
    Information2Array=("${Information2Array[@]}" $line)
done
Information2Array=("${Information2Array[@]:-${defaultInformation2Array[@]}}")

echo ${Information2Array[@]}


defaultInformation3Array=("2423")
echo "Enter Information3 array with default value as ${defaultInformation3Array[@]} : "
while read line 
do
    Information3Array=("${Information3Array[@]}" $line)
done
Information3Array=("${Information3Array[@]:-${defaultInformation3Array[@]}}")

echo ${Information3Array[@]}


defaultInformation4Array=("23445.7557.8667")
echo "Enter Information4 array with default value as ${defaultInformation4Array[@]} : "
while read line 
do
    Information4Array=("${Information4Array[@]}" $line)
done
Information4Array=("${Information4Array[@]:-${defaultInformation4Array[@]}}")

echo ${Information4Array[@]}


touch $FILE_NAME.yaml


var=$(cat $FILE_NAME.yaml |
yq w - version "\"$VERSION\"" )

echo "$var" > $FILE_NAME.yaml


for i in "${Information1Array[@]}"
do
    yq w -i $FILE_NAME.yaml X.Y.Information1[+] $i
done

for i in "${Information2Array[@]}"
do
    yq w -i $FILE_NAME.yaml X.Y.Information2[+] $i
done

for i in "${Information3Array[@]}"
do
    yq w -i $FILE_NAME.yaml X.Y.Information3[+] $i
done

for i in "${Information4Array[@]}"
do
    yq w -i $FILE_NAME.yaml P.Q.R.Information4[+].LMN $i
done

echo "Output is........."
cat $FILE_NAME.yaml

```

**Actual behavior**

```
version: '"3"'
X:
  Y:
    Information1:
    - 89999:4356
    Information2:
    - A
    - B
    - C
    - D
    - E
    - F
    - G
    - H
    - I
    - J
    - K
    - L
    - M
    - N
    Information3:
    - 2423
P:
  Q:
    R:
      Information4:
      - LMN: 23445.7557.8667

```

**Expected behavior**

```
version: "3"
X:
  Y:
    Information1:
      - 89999:4356
    Information2:
      - A
      - B
      - C
      - D
      - E
      - F
      - G
      - H
      - I
      - J
      - K
      - L
      - M
      - N
    Information3:
      - 2423
P:
  Q:
    R:
      Information4:
        - LMN: 23445.7557.8667

```

**Additional context**

I want it to generate a .yaml data in Docker Composable format, where its formatting should be understandable by Docker .
Its yaml data formatting should follow the Docker Compose Guidelines.

Similarly,

 ****i am facing one more issue :**** 

The command you ran:
```
yq w -i tempFile.yaml number \"4\"

```
**Actual behavior** :- like this its coming in a tempfile
```
number: '"4"'
```

**Expected behavior** 
```
number: "4"
```
