### ISSUE TITLE
3.2.1 does not parse json properly.

### ISSUE THREAD

**Issue by DonBower** [mikefarah/yq#414]
**Describe the bug**
Previously, in 2.2.1 (perhaps others), yq would read my simple JSON, and provide a properly formatted YAML file. Now, with 3.2.1, it just spits it back out without any conversion.

**Input JSON**
```
test.json
{
  "compilation": {
    "instances": 6,
    "instance_type": {
      "id":"m5.xlarge"
    }
  }
}
```

YQ Command:
```
yq r test.json
```

expected output:

```
compilation:
  instances: 6
  instance_type:
    id: m5.xlarge
```

Actual output:
```
{"compilation": {"instances": 6, "instance_type": {"id": "m5.xlarge"}}}
```
