### ISSUE TITLE
yq filter all documents matching criteria, from multiple documents

### ISSUE THREAD

**Issue by sankarp-kavach** [mikefarah/yq#415]
**Is your feature request related to a problem? Please describe.**
Provide a way to filter all the document(s) that match a search criteria from multiple documents.

**Describe the solution you'd like**
If we have data1.yml like:

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
     name: mycrd1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
     name: mycrd2
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: Deployment
metadata:
     name: my-deployment
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
     name: mycrd3
```

And we run a command:

```bash
yq r -d'*' data1.yaml (kind==CustomResourceDefinition)
```

it could output

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
     name: mycrd1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
     name: mycrd2
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
     name: mycrd3
```

**Additional context**
One place where this will be extremely useful is when we have a yaml file, with a bunch of CRDs and the instances of these CRDs. Some times, we will not be able to create the CRD instances and the CRDs themselves from a single file, as the CRD creation may take some time. See https://stackoverflow.com/questions/61267334/kubectl-create-apply-synchronously-until-each-object-is-created for example. Having this facility in `yq` will make it easy to extract all the CRDs into a single yaml file, apply it, check the `CRD establish` status and then attempt to create the CRD instance.
