### ISSUE TITLE
yq not found, installed with snap in GH actions

### ISSUE THREAD

**Issue by itaysk** [mikefarah/yq#418]
- I [have a GitHub actions workflow](https://github.com/itaysk/kubectl-neat/blob/master/.github/workflows/ci.yml) that uses yq
- it does `sudo snap install yq`
- It was working well, and recently starting to fail (a couple of weeks ago it was fine)
- it [fails](https://github.com/itaysk/kubectl-neat/runs/598195472?check_suite_focus=true) for not finding yq (`yq: command not found`)
- I even tried the following action which fails: `sudo snap install yq && yq --version`
- if I ssh into the worker to debug (using the tmate action), I can use yq. took this debugging info:
```
$ which yq
/snap/bin/yq

$ echo $PATH
/usr/share/rust/.cargo/bin:/home/runner/.config/composer/vendor/bin:/home/runner/.dotnet/tools:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/runner/.dotnet/tools
```

This might be a Github Actions issue, or a snapcraft issue, but I thought to check here as well if you know about a change to yq (or it's packaging) that might cause this.

**Comment by mikefarah** [comment]
Not a clue sorry - I tried snap on a VM and is seems to work.

There is an official github action you can use: https://github.com/marketplace/actions/yq-portable-yaml-processor.

Alternatively, you could also download the binary using wget or something from the releases...

**Comment by itaysk** [comment]
thanks

**Comment by pranas** [comment]
I noticed the same thing. Snap release was updated on April 18 which is when it stopped working. Still trying to figure out whether it's Snap or yq packaging issue.

**Comment by itaysk** [comment]
thanks for reporting @pranas , let me know if I should reopen this issue or not

**Comment by itaysk** [comment]
@mikefarah I just want to point out that the yq GH action does't work as well. Here's a minimal failing pipeline, am I doing something wrong?:

```yaml
name: test
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: yq
        uses: mikefarah/yq@3.3.0
      - name: test
        run: yq --version
```

**Comment by itaysk** [comment]
it seems that the gh action is using docker so yq won't be available outside the step. still trying to make the original use case (snap install) work.

**Comment by pranas** [comment]
We switched to installing binaries from GitHub Releases:

```
- name: Install yq
  run: |
    sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/3.3.0/yq_linux_amd64
    sudo chmod +x /usr/local/bin/yq
```

**Comment by itaysk** [comment]
@pranas I was about to do the same thing, thanks for confirming!

**Comment by mikefarah** [comment]
Yeah not sure what's going on with snap - downloading the binary direct makes sense to me...

**Comment by sarumont** [comment]
FYI, `brew` seems to work still (Homebrew for Linux is installed on `ubuntu-latest`):

```yaml
      - name: install tooling
        run: |
          brew install yq
```

**Comment by remi-debette** [comment]
Hi, 

brew is working but is kind of slow (circa 1min) and it cannot pin a specific version of `yq`, which could break the pipelines.
In comparison the yq action installs in seconds.

I found that I cannot run multiline command in the current yq action. The following does not execute but returns a success:
```yaml
    - name: Apply YQ
      uses: mikefarah/yq@3.4.0
      with:
        cmd: |
          cd ./somedir

          yq w -i ${HELM_VALUES_FILE} flask.image.tag ${{ needs.set-data.outputs.version }}
          yq w -i ${HELM_VALUES_FILE} nginx.image.tag ${{ needs.set-data.outputs.version }}
```

So is only the binary what is supported in real github action use cases?
