### ISSUE TITLE
Is there a way to merge nested lists?

### ISSUE THREAD

**Issue by edemen** [mikefarah/yq#423]
The usecase for this is merging yaml files for a k8s deployment that has a list of env vars nested inside a list of containers. Currently using `yq merge -a` will produce something like in the top example below.

Simple example:
```
containers:
- env:
  - a
  - b
- env:
  - c
  - d
```
Any way to turn this into the below?
```
containers:
- env:
  - a
  - b
  - c
  - d
```

**Comment by mikefarah** [comment]
Not directly, but with a few commands and piping you can:

```
yq r ~/Desktop/sample.yaml 'containers[*].env' | yq p - 'containers[0].env'
```

**Comment by edemen** [comment]
This is amazing, thank you!

**Comment by edemen** [comment]
In case somebody ends up here when googling the usecase above, here is the solution:
For each deployment, there is a minimal `deplo.yaml` to hold deployment-specific stuff, e.g.:
```
metadata:
  name: my-app
spec:
  selector:
      matchLabels:
        app: my-app
  replicas: 1
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: calculator
        env:
        - name: WAPI_TIMEOUT_BUSY
          value: "10800"
        - name: WAPI_TTL
          value: "5400"
        - name: WAPI_TTGC
          value: "30"
        - name: WAPI_MAX_ATTEMPTS
          value: "2"
```
Then, there is a `common.yaml` that is the same for multiple deployments:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-template
spec:
  selector:
      matchLabels:
        app: my-app-template
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: my-app-template
    spec:
      containers:
      - name: calculator
        image: example/image:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 8081

        livenessProbe:
          httpGet:
            path: /private/health
            port: 8081
            httpHeaders:
            - name: Probe
              value: live
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 2
        
        readinessProbe:
          httpGet:
            path: /private/health
            port: 8081
            httpHeaders:
            - name: Probe
              value: ready
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 1
        env:
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: password
```
and a helper `novar.yaml` with an empty array of env vars (I had to include this to avoid `value` being merged into env vars with `valueFrom`):
```
spec:
  template:
    spec:
      containers:
      - env:
```

The code to produce a merged yaml is:
```
yq merge -a common.yaml deplo.yaml | yq r - 'spec.template.spec.containers[*].env' | yq p - 'spec.template.spec.containers[0].env' | yq merge -x common.yaml deplo.yaml novar.yaml -
```
Not sure if possible to avoid this `novar.yaml` and also avoid having to create intermediary files. Ideally it would be replaced by a command to clear the env list before merging piped content.
