### ISSUE TITLE
Incorrect `Compare` example in GitBook docs

### ISSUE THREAD

**Issue by combinatorist** [mikefarah/yq#425]
**Describe the bug**
The example here does not execute as described: https://mikefarah.gitbook.io/yq/commands/compare#example-data. My guess is that data1.yaml should end with the line: `noDifference: it's the same` so that it shows as the same in the result.

I would happily fix this, but couldn't find where to edit the gitbook.

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug)
data1.yml:
```yaml
"apples": are nice
somethingElse: cool # this is nice
favouriteNumbers: [1,2,3]
```

data2.yml:
```yaml
apples: are nice
somethingElse: cool # yeah i like it
favouriteNumbers:
- 1
- 3
- 4
noDifference: it's the same
```

**Command**
The command you ran:
```
yq compare data1.yaml data2.yaml
```

**Actual behavior**
(as run)
```yaml
-"apples": are nice
-somethingElse: cool # this is nice
-favouriteNumbers: [1, 2, 3]
+apples: are nice
+somethingElse: cool # yeah i like it
+favouriteNumbers:
+- 1
+- 3
+- 4
+noDifference: it's the same
```

**Expected behavior**
(as documented)
```yaml
-"apples": are nice
-somethingElse: cool # this is nice
-favouriteNumbers: [1, 2, 3]
+apples: are nice
+somethingElse: cool # yeah i like it
+favouriteNumbers:
+- 1
+- 3
+- 4
 noDifference: it's the same
```

**Additional context**
To be clear, the actual behavior makes sense to me, but I think your docs are wrong. Those inputs do not (and should not) make that output. But, given you said called that line: `noDifference`, I'm guessing you actually meant to have it both inputs so there wouldn't be A difference.

And once again, I would have happily made a PR and just fixed it instead of documenting a bug, but I couldn't find where to edit your gitbook. :(
