### ISSUE TITLE
merge split long lines into multiple

### ISSUE THREAD

**Issue by wolszakp** [mikefarah/yq#426]
**Describe the bug**
Thanks for the tool I am using it in few scenarios and was very happy to see that it got merge yaml options.
So I want to use `yq` to merge few files with variables. 
As an output I get merged files however my output yaml has split long lines into multiple shorter

**Input Yaml**
data1.yml:
```yaml
variables:
  SUB_DNS_OVERRIDES: '{ "buildVersion": { "value": "$(Build.BuildNumber)" }, "dnsZoneName": { "value": "$(SUB_DNS_NAME)" } }'
```

data2.yml:
```yaml
variables:
  SUB_DNS_NAME: 'testvalue'
```

**Command**
The command you ran:
```
yq merge data1.yml data2.yml
```

**Actual behavior**

```yaml
variables:
  SUB_DNS_NAME: 'testvalue'
  SUB_DNS_OVERRIDES: '{ "buildVersion": { "value": "$(Build.BuildNumber)" }, "dnsZoneName":
    { "value" "$(SUB_DNS_NAME)" } }'
```

**Expected behavior**

```yaml
variables:
  SUB_DNS_NAME: 'testvalue'
  SUB_DNS_OVERRIDES: '{ "buildVersion": { "value": "$(Build.BuildNumber)" }, "dnsZoneName": { "value" "$(SUB_DNS_NAME)" } }'
```

**Additional context**
For me it would be best if tool will only merge yamls without changing original formatting. 
Alternative will be to give an user option to select what format is preferred.
