### ISSUE TITLE
yq creates a file it cannot parse by moving comments

### ISSUE THREAD

**Issue by jstangroome** [mikefarah/yq#427]
**Describe the bug**

Begin with yaml file with a comment placed within an array. Use `yq` to modify an unrelated document in the same file several times and watch the comment move each time until `yq` eventually fails with `Error reading document...`

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug)
`a.yaml`:
```yaml
rules:
  # comment
  - apiGroups: [""]
---
name: a
```

**Command**
The command you ran:
```
yq write -d1 a.yaml name b >b.yaml
yq write -d1 b.yaml name c >c.yaml
yq write -d1 c.yaml name d >d.yaml
```

**Actual behavior**

b.yaml
```yaml
rules:
- # comment
  apiGroups: [""]
---
name: b
```

c.yaml
```yaml
rules:
- apiGroups: # comment
[""]
---
name: c
```

and `d.yaml` fails to be created.

**Expected behavior**

d.yaml
```yaml
rules:
  # comment
  - apiGroups: [""]
---
name: d
```

**Additional context**

Using: https://github.com/mikefarah/yq/releases/download/3.3.0/yq_linux_amd64
