### ISSUE TITLE
Get array values without dash

### ISSUE THREAD

**Issue by CAMOBAP** [mikefarah/yq#429]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
If we have data1.yml like:

```yaml
---
metanorma:
  source:
    files:
      - sources/amendment/rice-amd.awi.adoc
      - sources/amendment/rice-amd.cd.adoc
      - sources/amendment/rice-amd.damd.adoc
```

And we run a command:

```bash
yq r data1.yml metanorma.source.files
```

it could output

```yaml
- sources/amendment/rice-amd.awi.adoc
- sources/amendment/rice-amd.cd.adoc
- sources/amendment/rice-amd.damd.adoc
```

**Describe alternatives you've considered**
It will be nice to get value without dashes

**Additional context**

Maybe it's already implemented, but I cannot find a way how to achieve this
