### ISSUE TITLE
Filtering strips out delimiters

### ISSUE THREAD

**Issue by silasb** [mikefarah/yq#431]
**Is your feature request related to a problem? Please describe.**
I'd love a way to filter documents out of a multi-document file while still keeping the document delimiters.

**Describe the solution you'd like**
With this input:
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
     name: mycrd1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
     name: mycrd2
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: Deployment
metadata:
     name: my-deployment
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
     name: mycrd3
```

And we run a command:

```bash
yq r data1.yml -d'*' {{kind==CustomResourceDefinition}}
```

it could output

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
     name: mycrd1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
     name: mycrd2
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
     name: mycrd3
```

**Describe alternatives you've considered**

The solution in https://github.com/mikefarah/yq/issues/415 comes close, but it strips out document delimiters.  Having a flag to leave in the document delimiters might also work.

**Additional context**
