### ISSUE TITLE
missing/ merged comments with yq write

### ISSUE THREAD

**Issue by infa-ddeore** [mikefarah/yq#433]
**Describe the bug**
comments are messed up while using yq write

**Input Yaml**
data1.yml:
```yaml
$ cat /tmp/4
# comment 1

---
# comment 2

---
# comment 3
 
---
# comment 4

---
# comment 5
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: some-label-gw
    istio: some-other-value
    release: istio
  minReplicas: 2

```

**Command**
The command you ran:
```
yq w -d3 /tmp/input.yaml metadata.labels.test value
```

**Actual behavior**
1) `comment 1` is removed
2) `comment 2` and `comment 3` are merged
3) blank element between `comment 4` and `comment 5`
```yaml


# comment 2
# comment 3
---


# comment 4
---

---
# comment 5
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: some-labels-like-custom-istio-ingressgateway
    istio: some-other-value
    release: istio
    test: value
  minReplicas: 2

```

**Expected behavior**
comments should be intact

**Additional context**
```
yq version 3.2.1
```
