### ISSUE TITLE
Issues to find a key

### ISSUE THREAD

**Issue by juliofalbo** [mikefarah/yq#441]
**Describe the bug**
I'm trying to use `yq` to get the length of the `service` array because I want to iterate and get the other tags like `container_prefix` and `internal_port`. So I tried to execute the command to get this I'm getting an error.

Also getting error when I try to get the value of the `target_json_path` key.

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug)
data1.yml:
```yaml
---
target_json_path: "/mypath"
- service: appA
  container_prefix: "prefix_"
  internal_port: 8080
- service: appB
  container_prefix: "prefix_"
  internal_port: 8900
```
Note: I created this yml based on this example: https://github.com/mikefarah/yq/blob/master/examples/array.yaml

**Command**
The command you ran:
```
yq r sample.yml --length service;
yq r sample.yml 'target_json_path';
```

**Actual behavior**

```yaml
01:01:46 main [ERRO] yaml: line 2: did not find expected key
```

**Expected behavior**

```yaml
2
/mypath
```

**Comment by juliofalbo** [comment]
My bad, the yml file was wrong.

Here is the correct way to do what I want:
```yaml
target_json_path: "/mypath"
services:
  - service: appA
    container_prefix: "prefix_"
    internal_port: 8080
  - service: appB
    container_prefix: "prefix_"
    internal_port: 8900

```
