### ISSUE TITLE
yq is losing comments during merge

### ISSUE THREAD

**Issue by kerak19** [mikefarah/yq#442]
**Describe the bug**
Merging two files causes comment of the second one to be lost. I didn't see this issue listed. 
Is it an expected behaviour?

**Input Yaml**

data1.yml:
```yaml
# Some random comment

# hi
v1: var
# hi 2
v2: var
```

data2.yml:
```yaml
# some comment about second file

# hi
unknown_var: hi
```

**Command**
The command you ran:
```
yq merge data1.yml data2.yml
```

**Actual behavior**

```yaml
# Some random comment

# hi
v1: var
# hi 2
v2: var
unknown_var: hi
```

**Expected behavior**

```yaml
# Some random comment

# hi
v1: var
# hi 2
v2: var
# some comment about second file

# hi
unknown_var: hi
```

**Additional context**
