### ISSUE TITLE
Update (w) in array?

### ISSUE THREAD

**Issue by PlainMartin** [mikefarah/yq#445]
I would like to transform

```
a: 
  - b: 1
    c: foo
  - b: 2
    c: bar
```

into

```
a: 
  - b: 1
    c: baz
  - b: 2
    c: baz
```

But with `yq w in.yml a.c baz`, I only get

```
a:
  c: Baz
```

What am I doing wrong? Thank you. (Also, I wanted to label this as a question, not as a bug, but can’t seem to find how.)

**Comment by mikefarah** [comment]
Have you had a look at the docs? Here's a link to what you are trying to do:

https://mikefarah.gitbook.io/yq/usage/path-expressions#arrays-1

**Comment by PlainMartin** [comment]
Yes, I read the docs. Twice. :) And I actually copied this particular example.

For

```
a:
  b:
  - c: thing0
    d: what..ever
  - c: thing1
    d: blah
  - c: thing2
    f: thingamabob
```

For `yq r test.yaml a.b[*].c` and `yq r test.yaml a.b[1].c`, I only get `zsh: no matches found`

Same with `w` (and a new value) instead of `r`.

It seems I can’t get arrays to work. This here does work:

```
a:
  b:
    c: foo
    d: bar

yq w in2.yaml a.b.c BAZ

a:
  b:
    c: BAZ
    d: bar

```

(macOS 10.15.5, yq 3.3.0 installed via homebrew)
