### ISSUE TITLE
Getting the line number of extracted value

### ISSUE THREAD

**Issue by adelin-b** [mikefarah/yq#448]
**Is your feature request related to a problem? Please describe.**
Finding the lines at which the values are is hard

**Describe the solution you'd like**
If we have data1.yml like:

```yaml
country:
  Australia: 
      language: English
language: English
```

And we run a command:

```bash
yq r data1.yml --printMode l 'country.Australia'
```

it could output
```
2
```

**Describe alternatives you've considered**
It seem that we need to reparse by hand to find at which like the reader key is and I think it would be better if it could be built in
