### ISSUE TITLE
Add support for Comma

### ISSUE THREAD

**Issue by kenjones-cisco** [mikefarah/yq#45]
Add support for [Comma](https://stedolan.github.io/jq/manual/#example7)

```
If two filters are separated by a comma, then the same input will be fed into both and the two filters’
output value streams will be concatenated in order: first, all of the outputs produced by the left expression, and then all of the outputs produced by the right. For instance, filter .foo, .bar, produces both the “foo” fields and “bar” fields as separate outputs.
```

## Expected

```yaml
a: Easy! as one two three
b:
  c: 2
  d: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
  e:
    - name: fred
      value: 3
    - name: sam
      value: 4
```

```bash
$ yaml r sample.yaml 'b.e[0].name,b.e[1].name'
```

```
fred sam
```
