### ISSUE TITLE
Merging 2 files with the -x/--overwrite option in version 3 does not behave consistently with version 2 in a list or array.

### ISSUE THREAD

**Issue by jak74** [mikefarah/yq#455]
**Describe the bug**
Merge with the -x/--overwrite option only replaces select values and not the entire list or array.  This seems to be true for multiple (or all?) releases of version 3 including 3.01 and 3.3.0.  The expected behavior is representative of how version 2 handles overwrite in a merge.

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug)
data1.yml:
```yaml
a: value
b:
  - orig1
  - orig2
  - orig3
  - orig4
  - orig5
  - orig6
c: true
```

data2.yml:
```yaml
b:
  - new1
  - new2
  - new3
```

**Command**
The command you ran:
```
yq merge -x data1.yml data2.yml
```

**Actual behavior**

```yaml
a: value
b:
- new1
- new2
- new3
- orig4
- orig5
- orig6
c: true
```

**Expected behavior**

```yaml
a: value
b:
- new1
- new2
- new3
c: true
```

**Additional context**
