### ISSUE TITLE
Allow chaining/more complex children matching patterns.

### ISSUE THREAD

**Issue by whitleykeith** [mikefarah/yq#458]
**Is your feature request related to a problem? Please describe.**
The core problem is that the child matching feature isn't chainable (as far as I can see, maybe I'm not using the right syntax). Ideally I'd be able to chain them together which would be super powerful, even moreso than the current implementation which is already incredibly useful for me. 

**Describe the solution you'd like**
If we have data1.yml like:

```yaml
myList:
- name: something
  type: SomeType
  dataToShow: me
- name: somethingElse
  type: SomeType
  dataToShow: notme

```

And we run a command:

```bash
yq r  data1.yml 'myList.(type==SomeType).(name==something).dataToShow
```

it could output

```yaml
me
```

**Describe alternatives you've considered**
This command, which doesn't work

**Additional context**
Essentially I may want to filter lists by more than just one filter. I really want to replace values here but the query would be the same.
