### ISSUE TITLE
Keeping a JSON formatted inside a YAML

### ISSUE THREAD

**Issue by IdanAdar** [mikefarah/yq#460]
Given this YAML:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: xxx
  namespace: xxx
data:
  json: |
    {
      "stuff": {
        "foo": {
          "1.0.0": {
            "bar": {
              "db": "",
              "mgmt": ""
            }
          }
        }
      }
    }
```

I would like to edit the JSON and put it back as it looks like above.
After processing:

```
json=$(yq r release.yaml data[json])
updatedJson=$(echo $json | yq w - foo.stuff["1.0.0"].bar.db $something/$somethingelse | yq r -j -)
yq w -i release.yaml data[json] $updatedJson
```

It looks like this:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: xxx
  namespace: xxxx
data:
  json: '{"foo":{"stuff":{"1.0.0":{"bar":{"db":""bla""}}}}}'
```

How can I keep it as it was before?
