### ISSUE TITLE
Preserve formatting with in place writing

### ISSUE THREAD

**Issue by tamalsaha** [mikefarah/yq#465]
**Describe the bug**
`yq w -1` command removes blank lines and changes spacing before comments.

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug)
data1.yml:
```yaml
# Log level for operator
logLevel: 3

# Annotations applied to operator deployment
annotations: {}

# Annotations passed to operator pod(s).
podAnnotations: {}

# Node labels for pod assignment
nodeSelector:  # +doc-gen:break
  beta.kubernetes.io/os: linux
  beta.kubernetes.io/arch: amd64
```

**Command**
The command you ran:
```
yq w -i test.yaml logLevel 4
```

**Actual behavior**

```yaml
# Log level for operator
logLevel: 4
# Annotations applied to operator deployment
annotations: {}
# Annotations passed to operator pod(s).
podAnnotations: {}
# Node labels for pod assignment
nodeSelector: # +doc-gen:break
  beta.kubernetes.io/os: linux
  beta.kubernetes.io/arch: amd64
```

**Expected behavior**

```yaml
# Log level for operator
logLevel: 4

# Annotations applied to operator deployment
annotations: {}

# Annotations passed to operator pod(s).
podAnnotations: {}

# Node labels for pod assignment
nodeSelector:  # +doc-gen:break
  beta.kubernetes.io/os: linux
  beta.kubernetes.io/arch: amd64
```

**Additional context**

```
$ yq --version
yq version 3.3.2
```

**Comment by mikefarah** [comment]
Yep - this is due to the underlying go-yaml parser, I see someone has already raised an issue there:

https://github.com/go-yaml/yaml/issues/627

**Comment by tamalsaha** [comment]
Thanks for the confirmation. Something else is also broken between `v3.3.0` (working) and `v3.3.2`. I am running the following command:

```
yq r api/crds/installer.voyagermesh.com_voyageroperators.v1.yaml spec.versions[0].schema.openAPIV3Schema.properties.spec > /tmp/voyager-values.openapiv3_schema.yaml
```

You can see the files here: https://gist.github.com/tamalsaha/eeee8d9d2db6623bf1c77717ba3b2c2d

In `v3.3.0`, the formatting of strings remain unchanged (newlines are preserved). In `v3.3.2`, the newlines are gone.

**Comment by mikefarah** [comment]
Ah yeah I updated the go-yaml library in 3.3.1 which had a number of changes and fixes. That is an open issue against the lib (https://github.com/go-yaml/yaml/issues/627)

**Comment by tamalsaha** [comment]
Looks like go-yaml decided to not fix the issue, rather just document it. :disappointed:

**Comment by aakrem** [comment]
Would be helpful to preserve the original formatting!

**Comment by twbecker** [comment]
It would also be nice to be able to preserve document markers (---). Seems like a great tool but unfortunately not being able to preserve virtually all the formatting is a dealbreaker for us.

**Comment by markzporter** [comment]
Just wanted to second this, love the tool but also love our blank lines 😁

**Comment by Justinzobel** [comment]
It also changes our yml files from 4 spaces indentation to 2 :(

**Comment by ryenus** [comment]
@mikefarah, FYI, just saw https://github.com/yaml/libyaml/issues/269#issuecomment-1567370045, notably there's https://github.com/pantoniou/libfyaml

> This is not on the TODO list for libyaml. None of us has time for this. I recommend to try out https://github.com/pantoniou/libfyaml which has support for this.

**Comment by jake-lewis** [comment]
@escummy 's answer above does work well, with an unfortunate exception: multiline literal scalars.

Example file:
```yml
root:
    branch: |
        #Multiline string
        blah = blah2

        #continue string
        example = example2

    branch2: example
```

Replacing newlines with comments would give:

```yml
root:
    branch: |
        #Multiline string
        blah = blah2
#blankline
        #continue string
        example = example2
#blankline2
    branch2: example
```

The first #blankline comment makes the multiline string into invalid yaml. If you have whitespace on the blank lines to match the other indentation you can make it work using a capture group e.g. `'s/\(^[[:space:]]*\)$/\1#blankline/'`

Example with indentation (note github text spacing makes this look off, it's equivelant to 8 spaces):
```yml
root:
....branch: |
........#Multiline string
........blah = blah2
........
........#continue string
........example = example2

....branch2: example
```

Running `sed -i 's/\(^[[:space:]]*\)$/\1#blankline/'` will result in this:
```yml
root:
....branch: |
........#Multiline string
........blah = blah2
........#blankline
........#continue string
........example = example2
#blankline
....branch2: example
```

Which is valid yaml that can be parsed by `yq`, with the caveat that when reverting back and removing the `#blankline` you should probably take care to preserve preceding whitespace so that future automation vai cli will still work.
