### ISSUE TITLE
--explodeAnchors / -X doesn't explode keys (work in 3.3.1 and 3.3.2)

### ISSUE THREAD

**Issue by OnkelTem** [mikefarah/yq#466]
**Describe the bug**

`-X` / `--explodeAnchors` doesn't work now in 3.3.2 or 3.3.1 (for the `read` command at least).
The last version when it worked was 3.3.0.

This should work: 

1.yaml
```yaml
errors:
  - &ts_sync_loss ts_sync_loss
properties:
  *ts_sync_loss: int
```

but outputs:

```
errors:
  - ts_sync_loss
properties:
  *ts_sync_loss: int
```

i.e. `ts_sync_loss` is not dereferenced .

**Command**
```
$ <1.yml yq r -X -
```

Version 3.3.0 does work right.

**Comment by mikefarah** [comment]
please follow the bug template - there is not enough information in this for me to replicate

**Comment by OnkelTem** [comment]
Have you even tried to replicate it or just closed this because you didn't like the report? :)

Ok, let me prepare something. Because my API is covered by NDA and I cannot publish it.

**Comment by OnkelTem** [comment]
@mikefarah Mike, I updated the issue. Try it now please.

**Comment by mikefarah** [comment]
That's not how you use anchors and aliases, I can't quite work out what you are trying to do, but it needs to be something like:

```yaml
errors:
  - &ts_sync_loss ts_sync_loss # this creates a variable for the value 'ts_sync_loss'
properties: *ts_sync_loss # this references that variable
```

**Comment by OnkelTem** [comment]
@mikefarah I don't think you're right. 

You can try out my example with any of the available validators/parsers:
https://yaml-online-parser.appspot.com/
https://codebeautify.org/yaml-validator
http://www.yamllint.com/

It's works just fine, so it's definitely a bug.

**Comment by OnkelTem** [comment]
Sorry, but we are you keeping this closed @mikefarah?

**Comment by OnkelTem** [comment]
Just to clarify things.

It [transpired](https://github.com/nodeca/js-yaml/issues/559) that the original YAML was actullay INCORRECT.

Specifically, this:
```yaml
errors:
  - &ts_sync_loss ts_sync_loss
properties:
  *ts_sync_loss: int
```
should read as:
```yaml
errors:
  - &ts_sync_loss ts_sync_loss
properties:
  *ts_sync_loss : int
```
(note the extra space after `*ts_sync_loss`).
Thus the reference PyYaml parser was actually **wrong** by allowing for space-less colons after anchors (but works well with the correct syntax).

Unfortunately for this tool it doesn't make any difference, **it still fails**.

Consider this YAML:
```yaml
devs:
  - &dev1  Alice
  - &dev2  Bob
  - &devop Jane
time:
  - name: Project 1
    devs:
      *dev1 : 120 hours
      *devop : 32 hours 
  - name: Project 2
    devs:
      *dev2 : 154 hours
      *devop : 21 hours 
```
It works with these popular YAML parsers:
- [PyYAML](https://pypi.org/project/PyYAML/) [[Link to a demo]](https://bit.ly/2NmQVQR)
- NPM [js-yaml](https://www.npmjs.com/package/js-yaml) [[Link to a demo]](http://nodeca.github.io/js-yaml/#yaml=ZGV2czoKICAtICZkZXYxICBBbGljZQogIC0gJmRldjIgIEJvYgogIC0gJmRldm9wIEphbmUKdGltZToKICAtIG5hbWU6IFByb2plY3QgMQogICAgZGV2czoKICAgICAgKmRldjEgOiAxMjAgaG91cnMKICAgICAgKmRldm9wIDogMzIgaG91cnMgCiAgLSBuYW1lOiBQcm9qZWN0IDIKICAgIGRldnM6CiAgICAgICpkZXYyIDogMTU0IGhvdXJzCiAgICAgICpkZXZvcCA6IDIxIGhvdXJzIA==) 
- NPM [yaml](https://www.npmjs.com/package/yaml)
- PHP's [yaml_parse()](https://www.php.net/manual/en/function.yaml-parse.php)
