### ISSUE TITLE
Allow to generate multi yaml docs from json file

### ISSUE THREAD

**Issue by marcosnils** [mikefarah/yq#470]
**Is your feature request related to a problem? Please describe.**

`yq` allows exporting a multi-document yaml file to json but it doesn't allow the opposite direction

**Describe the solution you'd like**
If we have data1.yml like:

```yaml
country: Australia
---
country: Argentina
```

And we run a command:

```bash
yq r -jd '*' data1.yaml | yq r - -d '*'
```

it could output

```yaml
country: Australia
---
country: Argentina
```

**Additional context**
Yq is currently outputing this: 

```
Error: yaml: line 1: did not find expected <document start>
```
