### ISSUE TITLE
How can I search elements in an array?

### ISSUE THREAD

**Issue by yfried** [mikefarah/yq#475]
Hi,
If I understand the doc correctly, I should be able to search the following array for an app called `app2`
```yaml
apps:
- name: app1
  slackChannel: my-team
- name: app2
  autoSync: true
```

But the following doesn't work: `yq read myfile.yaml "apps[*](.name==app2)"`.

Am I missing something?

I am using the the docker image for `mikefarah/yq:3.3.2`
