### ISSUE TITLE
How to delete non array/map types from multiple files?

### ISSUE THREAD

**Issue by inianv** [mikefarah/yq#476]
The [Path Expressions](https://mikefarah.gitbook.io/yq/usage/path-expressions) does not cover a way to delete multiple types that are neither array nor map types in the YAML file. I have this sample 

```
apiVersion: v1
data:
  username: foo
  password: bar
kind: Secret
metadata:
  name: my-secret-foo
type: Opaque
---
apiVersion: v1
data:
  username: duh
  password: duhdoh
kind: Secret
metadata:
  name: my-secret-duh
type: Opaque
```

How do I go about deleting  `kind == Secret` and the `metadata` associated with it.

```
yq d -d'*' yaml kind
yq d -d'*' yaml 'kind==Secret'
```

did not work at all. 

I can do a workaround, by doing multiple invocations as below, but here, it is not guaranteed  that `metadata` for the record related to 'Secret' alone will be deleted. If there other records, those will also be deleted.

```
yq d -d'*' yaml kind | yq d -d'*' - metadata
```

Running `yq version 3.3.0` on CentOS Linux release 7.5.1804 (Core)

**Comment by mikefarah** [comment]
Just to be clear - what is the output you are expecting, are you expecting the first document to be removed?

**Comment by inianv** [comment]
Just to be clear @mikefarah , I would like the `kind: Secret` and its associated `metadata` to be removed in both the occurrences. So expected output would be

```
apiVersion: v1
data:
  username: foo
  password: bar
type: Opaque
---
apiVersion: v1
data:
  username: duh
  password: duhdoh
type: Opaque
```
