### ISSUE TITLE
Scalar issue with write command

### ISSUE THREAD

**Issue by sebarre-talend** [mikefarah/yq#477]
**Describe the bug**
Write into a specific path remove quotes onto other path

version of yq: 2.4.1
operating system: mac/linux

**Input Yaml**
data1.yml:
```yaml
spec:
  repository: "toto"
  version: 2.5.1
```

**Command**
```
yq write data1.yml spec.version 2.6.0
```

**Actual behavior**

```yaml
spec:
  repository: toto
  version: 2.6.0
```

**Expected behavior**

```yaml
spec:
  repository: "toto"
  version: 2.6.0
```
