### ISSUE TITLE
[Question] How to delete all but one field?

### ISSUE THREAD

**Issue by whitleykeith** [mikefarah/yq#478]
Essentially I want to take a docker compose file and get all images in it, but I want to preserve the top level key for each service. 

Example yaml

```yaml
version: "3.7"
services:
   image1:
    image: image1
    build: {}
```

Granted there's multiple images under "services". What I would like as an output is:

```yaml
image1:
 image: image1
image2:
 image: image2


```

I'm pretty sure there's a way to write this, but I'm having trouble figuring it out. 

I think what I really want is a way to delete all but one child element of a node. i.e. `yq -d !image`
