### ISSUE TITLE
Parsing variables that are passed to YML

### ISSUE THREAD

**Issue by g3kr** [mikefarah/yq#481]
I have a yml file that resembles the one below

```
functionbeat.provider.aws.functions:
    - name: cloudwatch
      enabled: true
      type: cloudwatch_logs
      description: "lambda function for cloudwatch logs"
      triggers:
        - log_group_name: "my-application-1"
```
I want to be able to extend log_group_name key here. The idea is the log_group_name key is passed in as a list through a variable, for instance

`logGroups = my-application-1,my-application-2,my-application-3,my-application-4
`
I am expecting this to translate to this in the yml

```
functionbeat.provider.aws.functions:
    - name: cloudwatch
      enabled: true
      type: cloudwatch_logs
      description: "lambda function for cloudwatch logs"
      triggers:
        - log_group_name: "my-application-1"
        - log_group_name: "my-application-2"
        - log_group_name: "my-application-3"
        - log_group_name: "my-application-4"
```
Is it possible to do this using `yq`? Any help is much appreciated.
