### ISSUE TITLE
add --style to yq merge

### ISSUE THREAD

**Issue by teebszet** [mikefarah/yq#483]
**Is your feature request related to a problem? Please describe.**
I'm trying to merge an env.yaml file into a values.yaml file for helm charts, which necessitates quoting for numbers

Previously, I used a line by line yq write with --style double, but trying to use merge instead, and it removes double quotes in my env.yaml files before merging to the values.yaml.

**Describe the solution you'd like**

env.yaml:
```
env:
  - name: "EXAMPLE_ENV"
    value: "3"
```

values.yaml:
```
some: other stuff
other: fields
env:
```

`yq merge --inplace --style double values.yaml env.yaml`

would output all merge entities in values.yaml with double quotes

```
some: other stuff
other: fields
env:
  - name: "EXAMPLE_ENV"
    value: "3"
```

**Comment by teebszet** [comment]
Never mind, it does retain quotes.

**Comment by fuero** [comment]
It does so on values, but doesn't on keys. I ran into this with Fedora Modularity metadata files:

Input yaml files:

init.yml
```yaml
---
document: modulemd-defaults
version: 1
data:
```
yml01
```yaml
---
document: modulemd-defaults
version: 1
data:
        module: go-toolset
        profiles:
                '1.12': [common]
...
```
yml02
```yaml
---
document: modulemd-defaults
version: 1
data:
        module: go-toolset
        profiles:
                '1.14': [common]
...
```

yq merge init.yml yml01 yml02

```yaml
document: modulemd-defaults
version: 1
data:
  module: go-toolset
  profiles:
    1.12:
      - common
    1.14:
      - common
```

I'd expect yq to retain the quoting style on dict keys as well.
