### ISSUE TITLE
Searching on children of children not working as expected

### ISSUE THREAD

**Issue by jtackaberry** [mikefarah/yq#489]
Hopefully this is a legit bug report and not a newb in need of a cluebatting. :)

yq version: 3.3.2 (downloaded from releases page)
OS: Ubuntu 18.04

Given this input example:

`test.yaml`:
```yaml
spec:
  template:
    spec:
      containers:
      - image: one
        env:
          - name: WANT
            value: dummy
      - image: two
        env:
          - name: IGNORE
            value: dummy
```
I want to return the inner `spec` for all specs that have a container which matches `env.name==WANT`.   I intend to use this on a multi doc input (`-d '*'`), but for now let's stick with the simple case of one document that should always match.

The command I expected to work, given the [Search by Child Nodes](https://mikefarah.gitbook.io/yq/usage/path-expressions#search-by-children-nodes) docs.

```
yq r test.yaml 'spec.template.spec.(containers.env.name==WANT)'
```

Expected output:

```yaml
      containers:
      - image: one
        env:
          - name: WANT
            value: dummy
      - image: two
        env:
          - name: IGNORE1
            value: dummy
```

Actual output: empty

I tried quite a number of variations based on trial and error and got close.  This:

```
yq r test.yaml 'spec.template.spec.containers.(env.*.name==WANT)'
```

Outputs this:

```yaml
image: one
env:
  - name: WANT
    value: dummy
```

Which is getting there (although I'm unsure why the `*` is necessary, perhaps it has something to do with being a nested list).  However I want it to output starting at `spec` instead of the matching child of `containers`.  So I just moved the paren up a level:

```
yq r test.yaml 'spec.template.spec.(containers.env.*.name==WANT)'
```

But that outputs nothing.  Then I thought perhaps, well, containers itself is a list, and the `env` list needed some cajoling by means of the `*` so maybe `containers` does too:

```
yq r test.yaml 'spec.template.spec.(containers.*.env.*.name==WANT)'
```
But that also outputs nothing.

Is this a legitimate problem with searching nested child lists, or user error?
