### ISSUE TITLE
yq read multi path expression

### ISSUE THREAD

**Issue by abourree** [mikefarah/yq#501]
**Is your feature request related to a problem? Please describe.**
I want to read multiple values from one file with only one command

If we have data1.yml like:

```yaml
a: b
c: d
e: f
f: g
```

And we run a command:

```bash
yq read data1.yml 'a' 'e'
```
Or
```bash
yq read data1.yml 'a;e'
```
it could output

```yaml
b
f
```

**Describe alternatives you've considered**
Alternative should be run command twice:
```bash
yq read data1.yml 'a'; yq read data1.yml 'e'
```

**Additional context**
1/ Order path expression was found in file could be important and not retrieve easyly
2/ Case of multi document
With:
```yaml
a: b
c: d
e: f
f: g
---
a: z
c: y
e: w
f: v
```
I expect:
```yaml
b
f
---
z
w
```

**Comment by jghal** [comment]
Additionally supporting a syntax to concat/join the selected paths into a single line would be welcome. Use case it to print a single-line output of selected list element values

```yaml
---
- name: foo
  id: 1
  user: bob
  port: 1234
- name: bar
  id: 2
  user: fred
  port 5678
```
then doing something like 

```shell
$ yq r example.yml '* | .name + ": " + .id'
foo: 1
bar: 2
$
```
