### ISSUE TITLE
Feature Request - Merge at a particular location

### ISSUE THREAD

**Issue by vikas027** [mikefarah/yq#508]
I am trying to copy a nested

**Describe the solution you'd like**
If we have `orig.yaml` like:

```yaml
country: Australia
aws:
  clouds:
    - ec2:
         abc:
            - 1
            - 2
xyz1: 123
xyz2: 456
```

Now, I can get the firs cloud element by 
```bash
$ yq r orig.yaml 'aws.clouds[0]' > new.yaml
$ cat new.yaml
ec2:
  abc:
    - 1
    - 2
```
And then make some change (manually for now) in `new.yaml`, say
```yaml
ec2:
  xyz:
    - 4
    - 5
```

Now, I want to merge the new yaml at a particular point (`aws.clouds[1]`) to the `orig.yaml`
This is what I want
```yaml
country: Australia
aws:
  clouds:
    - ec2:
         abc:
            - 1
            - 2
    - ec2:
         xyz:
            - 4
            - 5
xyz1: 123
xyz2: 456
```
