### ISSUE TITLE
Filtering multiple documents

### ISSUE THREAD

**Issue by MichaelJDrK** [mikefarah/yq#513]
**Is your feature request related to a problem? Please describe.**

I've got a YAML file with multiple documents. Example

```
kind: Service
spec:
  foo:bar
---
kind: Deployment
spec:
  containers:
    - image: foobar
    - image: barbaz
```

I want to filter the document at first (the document with "kind: Deployment", for example) and then write only to the filtered document - and be able to use filters again (to set only one of the two images).

How can I do this? Is this possible or has something be added?

**Comment by aabouzaid** [comment]
I have the same use case and couldn't' find a way to do it using `yq`.

**Comment by ruicao93** [comment]
I also have the same issue. I just want to update the value in filered documents. But the '-w' will take affect on all documents.

**Comment by estahn** [comment]
Apparently like this #173 ... but didn't get it to work either.

```yaml
---
kind: Ingress
metadata:
  name: foo
---
kind: Deployment
metadata:
  name: foo
```

```bash
yq r -c -d'*' test.yaml '(kind==Ingress)'
```

**Comment by steve-todorov** [comment]
@estahn and others - the "correct" answer is:

```
yq e '. | select(.kind == "Ingress")'
```

Check these links:
* https://mikefarah.gitbook.io/yq/operators/select
* https://mikefarah.gitbook.io/yq/operators/document-index

**Comment by lexey-evergreen** [comment]
My use case is similar to the OP: I have two documents with similar paths inside them, and I only want to write to a single document based on a `select()`. Thanks to @steve-todorov's previous comment, I was able to figure out a way to do this.

Given the OP's YAML, I want to write to an object in one document that both documents share, such as `spec`.
To be clear, I want to update the a single document _in place_ without modifying any of the other documents, and the output should include all other documents as well.
I'm using `yq version 4.9.3` for these commands.

test-template.yml
```yml
kind: Service
spec:
  foo: bar
---
kind: Deployment
spec:
  containers:
    - image: foobar
    - image: barbaz
```
Adding a value to `spec` on only one document is possible via this command:
```
yq e '. | select(.kind == "Deployment") as $deployment | select(.kind != "Deployment") as $other | $deployment.spec.foo = "baz" | ($deployment, $other)' -i test-template.yml
```

which would result in this:
```yml
kind: Service
spec:
  foo: bar
---
kind: Deployment
spec:
  containers:
    - image: foobar
    - image: barbaz
  foo: baz
```

Whereas a command like this
```
yq e '.spec.foo = "baz"' -i test-template.yml
```
would overwrite both `spec.foo` values:
```yml
kind: Service
spec:
  foo: baz
---
kind: Deployment
spec:
  containers:
    - image: foobar
    - image: barbaz
  foo: baz
```
