### ISSUE TITLE
Mulitdocument specific selection write

### ISSUE THREAD

**Issue by cr22rc** [mikefarah/yq#514]
**Is your feature request related to a problem? Please describe.**
Multi document selection write. I have a large file with many documents 
I don't know the the order they're in but I need to change a few dependent on properties
Take below simplified sample I only want to change replicas to 3 in kind=Deployment&&metadata.name=eventing-controller
One option might be to have a query that returns the matching documents like in this case 1 so I could use -d 1 
note this would have to be an array as more than one might match
The other option would be to use -d'*' but have some type of selection like the above 
```
apiVersion: v1
kind: Namespace
metadata:
  name: knative-eventing
  labels:
    eventing.knative.dev/release: "v0.16.1"
spec:
 replicas: 1

---

kind: Deployment
metadata:
  name: eventing-controller
  namespace: knative-eventing
  labels:
    eventing.knative.dev/release: "v0.16.1"
    knative.dev/high-availability: "true"
spec:
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    eventing.knative.dev/release: "v0.16.1"
    role: eventing-webhook
  name: eventing-webhook
  namespace: knative-eventing
spec:
  ports:
```
