### ISSUE TITLE
yq write strips completely blank lines from the output

### ISSUE THREAD

**Issue by scanfield** [mikefarah/yq#515]
**Is your feature request related to a problem? Please describe.**
```
foo:
  bar: 1

  baz: 2
```

when run through `yq w - foo.baz 3`

produces

```
foo:
  bar: 1
  baz: 3
```

**Describe the solution you'd like**
Keep my extra blank line (it's better for readability / produces less of a diff)

**Comment by warder** [comment]
Same story, sorry but this issue looks more like a bug nether then enhancement.
When you process yaml file with yq it corrupts a whole file

**Comment by AceHack** [comment]
Any update on this, this is a really nice feature.

**Comment by sathiyams** [comment]
Any update on this ? It's getting difficult when it comes to readability

**Comment by mikefarah** [comment]
This is an effect of the underlying yaml parser, an issue was raised there https://github.com/go-yaml/yaml/issues/627 - the owner said 

```
..the content when re-encoded will not
 have its original textual representation preserved. An effort is made to
 render the data plesantly, and to preserve comments near the data they
 describe, though. 
```

**Comment by arcesino** [comment]
I've been dealing with this issue for a couple of days when updating very large YAML files and found a workaround using `diff` & `patch` commands that restores the stripped blank lines in most of the cases. Suppose you have the following YAML file:

```yaml
doc:
  version: 1.0.0
  name: numbers & letters

numbers:
  - 1

letters:
  - a
```
we call this file `a.yaml`. Now let's update the version using `yq` and store the result in new file `a-updated.yaml`:

```sh-session
yq e '.doc.version = "1.0.1"' a.yaml > a-updated.yaml
```
as expected, command above stripped all blank lines so `a-updated.yaml` looks like:
```yaml
doc:
  version: 1.0.1
  name: numbers & letters
numbers:
  - 1
letters:
  - a
```
at this point, the first step to get the blank lines back is to create a diff file that ignores blank lines changes:
```sh-session
diff -U0 -w -b --ignore-blank-lines a.yaml a-updated.yaml > a.diff
```
`a.diff` looks like this:
```diff
--- a.yaml	2021-04-30 15:28:38.000000000 -0500
+++ a-updated.yaml	2021-04-30 15:18:53.000000000 -0500
@@ -2 +2 @@
-  version: 1.0.0
+  version: 1.0.1
``` 
then final step is to patch original file with the diff:
```sh-session
patch a.yaml < a.diff
```
after that, the original file looks like:
```yaml
doc:
  version: 1.0.1
  name: numbers & letters

numbers:
  - 1

letters:
  - a
```
the issue comes when the updated line is right before a blank line. For example, let's add an element to one of the arrays:
```sh-session
yq e '.numbers += 2' a.yaml > a-updated.yaml
```
the updated file is now:
```yaml
doc:
  version: 1.0.1
  name: numbers & letters
numbers:
  - 1
  - 2
letters:
  - a
```
if we generate the diff file as before we'll get the following:
```diff
--- a.yaml	2021-04-30 15:30:22.000000000 -0500
+++ a-updated.yaml	2021-04-30 15:35:26.000000000 -0500
@@ -7 +6 @@
-
+  - 2
```
and patching the original file with diff above results in:
```yaml
doc:
  version: 1.0.1
  name: numbers & letters

numbers:
  - 1
  - 2
letters:
  - a
```
notice how the blank line after the new element in `numbers` array remains stripped while others are back. This is due since the diff file considers the blank line deletion and the addition of the new array element as part of the same diffset so it's not ignored by `--ignore-blank-lines`.

This is not ideal in any means but in my case it has helped a lot since my files are big and with lots of blank lines. I'm sharing this in case someone else can find it useful too.

**Comment by lirlia** [comment]
Thanks ! I use @arcesino approach for this 1 liner.

```
filename=xxx
version=xxx

patch "$filename" <<< $(diff -U0 -w -b --ignore-blank-lines $filename <(yq eval ".my.version = \"$version\"" $filename))
```

**Comment by vladimir259** [comment]
Thanks for the idea with patch @arcesino .

I my case the removal of blanks introduced by patch were unfortunately unacceptable, so i had to dig further.

And found a solution.

Approach is following: i remove blanks from the original yaml and create a diff between **that** and my altered yaml.
The patch then is applied to the original and no new spaces are introduced.

**Here an example:**

Starting point is my original yaml where the value of key "secrets.TEST" should be updated
```
---
config:

  # mysql
  DATABASE_PROTOCOL: "mysql"
  # instance fqdn
  DATABASE_HOST: "mysql"

secrets:
  # db password
  DATABASE_PASSWORD: "password"

  # example
  TEST: "foo"

# other values
#[...]
```

### Step 1: updating the value & creating a copy
```
yq '.secrets.TEST = "NewValue"' sample.yaml > sample.yaml.new
```

### Step 2: removing blanks from the original
```
yq '.' sample.yaml > sample.yaml.noblanks
```

### Step 3: creating a patch
```
diff -B sample.yaml.noblanks <(yq "." sample.yaml.new) > patch.file
```
the patch contains then only the value diffs:
```
$> cat patch.file
11c11
<   TEST: "foo"
---
>   TEST: "NewValue"
```

### Step 4: apply the patch to the original
```
patch sample.yaml patch.file
```
![image](https://user-images.githubusercontent.com/79702343/155680957-9ac04302-fc13-425b-b326-b1ede62df0ae.png)

**Comment by clementnuss** [comment]
good idea! I turned that in a fish and bash functions in [this Gist](https://gist.github.com/clementnuss/c3e021d5669d60c1a9ae44f2eeacce2b):
```shell
#fish
function yqblank;
  yq eval "$argv[1]" "$argv[2]" | diff -B "$argv[2]" - | patch "$argv[2]" -o -
end

#bash
yqblank() {
  yq eval $1 $2 | diff -B $2 - | patch $2 -o -
}
```

this makes it possible to use yq without changing (most) of the blank lines. usage as follows:
```
yqblank '.' file_name.yml
```

**Comment by raQai** [comment]
@clementnuss I think `patch $2 -o -` does not work and `-o` should be removed there.

```bash
#bash
yqblank() {
  yq eval $1 $2 | diff -B $2 - | patch $2 -
}
```

**Comment by ryenus** [comment]
> @clementnuss I think `patch $2 -o -` does not work and `-o` should be removed there.

@raQai, thank you! Just that the arguments have to be quoted properly, also [`eval/e` can be omitted since yq 4.18.1][1]:
```sh
#bash
yqblank() {
  yq "$1" "$2" | diff -B "$2" - | patch "$2" -
}
```

[1]: https://mikefarah.gitbook.io/yq/#notice-for-v4.x-versions-prior-to-4.18.1

**Comment by raQai** [comment]
Oh yeah, I forgot about the quote part :sweat_smile: 
Was on a hurry so thanks for adding this :+1:

**Comment by msdobrescu** [comment]
I'm hit by this too. No fix, only workarounds?

**Comment by andry81** [comment]
> Approach is following: i remove blanks from the **original** yaml and create a diff between **that** and my altered yaml.
> The patch then is applied to the original and no new spaces are introduced.

Unfortunately this only works for changes in already existed values. The patch would be with offsetted blank lines if try to **add** lines to the yaml.

I've already tested that and it does not work as expected for additions:
https://github.com/andry81-devops/gh-workflow/blob/master/bash/github/init-yq-workflow.sh
https://github.com/andry81-devops/gh-workflow/blob/master/bash/cache/accum-content.sh

Search for: `yq_edit`, `yq_diff`, `yq_patch`

So, only the diff-versus-edited-yaml instead of diff-versus-original-yaml looks reliable.

**Comment by andry81** [comment]
@arcesino
> I've been dealing with this issue for a couple of days when updating very large YAML files and found a workaround using `diff` & `patch` commands that restores the stripped blank lines in most of the cases. Suppose you have the following YAML file:

This one has one disadvantage, it does remove comments. And there is no any complete way to completely correctly retain comments outside the yq utility, because the comments format depends on yaml syntax.

**Comment by andry81** [comment]
I've new implementation of bash scripts which is better of all above.

Implementation: https://github.com/andry81-devops/gh-workflow/tree/HEAD/bash/github/init-yq-workflow.sh
Example of usage: https://github.com/andry81-devops/gh-workflow/tree/HEAD/bash/cache/accum-content.sh

```sh
# Usage example:
#
>yq_edit '<prefix-name>' 'edit' "<input-yaml>" "$TEMP_DIR/<output-yaml-edited>" \
  <list-of-yq-eval-strings> && \
  yq_diff "$TEMP_DIR/<output-yaml-edited>" "<input-yaml>" "$TEMP_DIR/<output-diff-edited>" && \
  yq_restore_edited_uniform_diff "$TEMP_DIR/<output-diff-edited>" "$TEMP_DIR/<output-diff-edited-restored>" && \
  yq_patch "$TEMP_DIR/<output-yaml-edited>" "$TEMP_DIR/<output-diff-edited-restored>" "$TEMP_DIR/<output-yaml-edited-restored>" "<output-yaml>"
#
# , where:
#
#   <input-yaml>  - input yaml file path
#   <output-yaml> - output yaml file path
#
#   <output-yaml-edited>          - output file name of edited yaml
#   <output-diff-edited>          - output file name of difference file generated from edited yaml
#   <output-diff-edited-restored> - output file name of restored difference file generated from original difference file
#   <output-yaml-edited-restored> - output file name of restored yaml file stored as intermediate temporary file
```

Example with `test.yml`:

```yml
# This file is automatically generated
#

content-index:

  timestamp: 1970-01-01T00:00:00Z

  entries:

    - dirs:

        - dir: dir-1/dir-2

          files:

            - file: file-1.dat
              md5-hash:
              timestamp: 1970-01-01T00:00:00Z

            - file: file-2.dat
              md5-hash:
              timestamp:

            - file: file-3.dat
              md5-hash:
              timestamp:

        - dir: dir-1/dir-2/dir-3

          files:

            - file: file-1.dat
              md5-hash:
              timestamp:

            - file: file-2.dat
              md5-hash:
              timestamp:
```

```sh
export GH_WORKFLOW_ROOT='<path-to-gh-workflow-root>' # https://github.com/andry81-devops/gh-workflow

source "$GH_WORKFLOW_ROOT/bash/github/init-yq-workflow.sh"

[[ -d "./temp" ]] || mkdir "./temp"

export TEMP_DIR="./temp"

! tkl_get_include_nest_level || tkl_execute_calls -s gh || exit $? # execute init functions only after the last include and exit on first error

yq_edit 'content-index' 'edit' "test.yml" "$TEMP_DIR/test-edited.yml" \
  ".\"content-index\".timestamp=\"2022-01-01T00:00:00Z\"" && \
  yq_diff "$TEMP_DIR/test-edited.yml" "test.yml" "$TEMP_DIR/test-edited.diff" && \
  yq_restore_edited_uniform_diff "$TEMP_DIR/test-edited.diff" "$TEMP_DIR/test-edited-restored.diff" && \
  yq_patch "$TEMP_DIR/test-edited.yml" "$TEMP_DIR/test-edited-restored.diff" "$TEMP_DIR/test.yml" "test-patched.yml" || exit $?
```

**PROs**:
* Can restore blank lines together with standalone comment lines: `  # ... `
* Can restore line end comments: `  key: value # ...`
* Can restore quotes around values
* Can restore line endings
* Can detect a line remove/change/add altogether.

**CONs**:
* Because of has having a guess logic, may leave artefacts or invalid corrections.
* Does not restore line end comments, where the yaml data is changed.

> [!NOTE]
> YQ implementation may not remove or can add some comments. So the function must correctly process these.

Related issues:

* https://github.com/mikefarah/yq/issues/19
* https://github.com/mikefarah/yq/issues/127
* https://github.com/mikefarah/yq/issues/465
* https://github.com/mikefarah/yq/issues/2578
* https://github.com/go-yaml/yaml/issues/627
* https://github.com/yaml/libyaml/issues/42
