### ISSUE TITLE
Filter objects by  value of member array

### ISSUE THREAD

**Issue by dcode** [mikefarah/yq#517]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to filter a document based upon an expression of a value included in an array.

**Describe the solution you'd like**
If we have data1.yml like:

```yaml
- country: Australia
   tags:
     - oceania
     - commonwealth
- country: Canada
  tags:
    - north america
    - commonwealth
- country: Philippines 
  tags:
    - oceania
    - republic
```

And we run a command:

```bash
yq r '[].(tags(. == "commonwealth")).name' data1.yml
```

it could output

```yaml
Australia
Canada
```

**Describe alternatives you've considered**
I've tried combinations of the syntax in the docs, but can't figure this out. I can get this to work by chaining to `jq`, however:

```bash
yq r -j  data1.yml | jq -r '.[]|select(.tags[]|select(.=="commonwealth")).name'
```
