### ISSUE TITLE
Merge without exploding or validating anchors

### ISSUE THREAD

**Issue by AndreSteenveld** [mikefarah/yq#520]
I have several yaml documents I'd like to merge, but without exploding the anchors.

**Describe the solution you'd like**
These are based on the docker-compose files I'm working with for a lack of a more imaginative example. 

`./first.yaml`:
```yaml
version: '3.7'

x-cool-labels: &cool-labels
  labels:
    - "cold"
    - "ice"
    - "snow"

x-hot-labels: &hot-labels
  labels:
    - "warm"
    - "lava"
    - "fire"
```

`second.yaml`:
```yaml
version: '3.7'

services:
  cool-container:
    << : *cool-labels
```

`third.yaml`:
```yaml
version: '3.7'

services:
  hot-container:
    << : *hot-labels
```

```bash
$ yq merge --overwrite ./*.yaml
Error: yaml: unknown anchor 'cool-labels' referenced
#
# Snipped the output of yq merge --help
#
```

The output I was expecting was a yaml file looking something like this:
```
x-cool-labels: &cool-labels
  labels:
    - "cold"
    - "ice"
    - "snow"
x-hot-labels: &hot-labels
  labels:
    - "warm"
    - "lava"
    - "fire"
services:
  cool-container:
    << : *cool-labels
  hot-container:
    << : *hot-labels
version: '3.7'
```

**Describe alternatives you've considered**
concatenating the files and "cleaning" them up, by doing a single file merge. The thinking here was that `yq` would go top to bottom and merge duplicate nodes.

```
$ cat ./*.yaml | yq merge --overwrite -
```

I've also thought about just concatenating the files and running them through `read` to get them cleanly formatted, this also doesn't remove duplicate nodes though.

```bash
# The version of yq I'm running
$ yq --version
yq version 3.3.2
```

**Comment by AndreSteenveld** [comment]
Tomorrow is today and I thought of a new approach:

1. Concatenate the yaml files properly (splitting them with `---`)
2. Then select all values with the full paths from all documents in the file
3. Remove duplicate lines

In bash this would look something like this:
```bash
$ find . -name "*.yaml" \
    | xargs -I{} sh -c 'printf "%s\n%s\n%s\n" "---" "# File : {}" "$(cat {})"' \
    | yq read --printMode pv --doc '*' - '**' \
    | sort -u
```

Using the same files from the initial post the output is now:
```yaml
services.cool-container.labels.[0]: "cold"
services.cool-container.labels.[1]: "ice"
services.cool-container.labels.[2]: "snow"
services.hot-container.labels.[0]: "warm"
services.hot-container.labels.[1]: "lava"
services.hot-container.labels.[2]: "fire"
version: '3.7'
x-cool-labels.labels.[0]: "cold"
x-cool-labels.labels.[1]: "ice"
x-cool-labels.labels.[2]: "snow"
x-hot-labels.labels.[0]: "warm"
x-hot-labels.labels.[1]: "lava"
x-hot-labels.labels.[2]: "fire"
```

The anchors are exploded which is fine, the output doesn't look very pretty but then again that's fine as well. Doing this with a few docker compose files almost works. I did run in to the following issues:

* docker-compose will not validate your input anymore (checking for duplicate services, different version numbers across files, etc).
* It seems that multi-line strings get reduces to a single (first) line.
```yaml
# This is the service definition which by itself does work
services:
  030.020.060--mqtt-broker--migrate-database:
    build:
      context: ./mqtt-broker/mqtt-broker/prepare-database
      dockerfile: ./mqtt-broker-migrate-database.dockerfile
      target: migrate-database
    env_file:
      - ./mqtt-broker/mqtt-broker/mqtt-broker.env
    environment: 
      - PGHOST=postgres
    command: >-
      sh -c "sleep 5 && evolve migrate postgresql
      --erase-disabled true
      --command-timeout 3600
      --connection-string \"Server=$$PGHOST;Database=$$DB_DATABASE;Username=$$DB_USER;Password=$$DB_PASSWORD;Pooling=true;\""
```

But in the output it looks like this:
```yaml
# Note that the command is empty
services."030.020.060--mqtt-broker--migrate-database".build.context: ./mqtt-broker/mqtt-broker/prepare-database
services."030.020.060--mqtt-broker--migrate-database".build.dockerfile: ./mqtt-broker-migrate-database.dockerfile
services."030.020.060--mqtt-broker--migrate-database".build.target: migrate-database
services."030.020.060--mqtt-broker--migrate-database".command: >-
services."030.020.060--mqtt-broker--migrate-database".env_file.[0]: ./mqtt-broker/mqtt-broker/mqtt-broker.env
services."030.020.060--mqtt-broker--migrate-database".environment.[0]: PGHOST=postgres
```

For now I think that just making sure all strings are on a single line is a half way decent work around but it was rather surprising though.

Regarding the exploding anchors, I did see a ticket somewhere here with a bug report to that affect.

**Comment by AndreSteenveld** [comment]
So it turns out that docker-compose wasn't as happy with the output as I hoped it was there for forming it back in to a proper document is necessary yielding this shell monstrosity:

```bash
find . -name "docker-compose.*.yml" \
    | xargs -I{} sh -c 'printf "%s\n%s\n%s\n" "---" "# File : {}" "$(cat {})"' \
    | yq read --tojson --stripComments --printMode pv --doc '*' - '**' \
    | sort -u \
    | jq --raw-output 'to_entries | map( "'\''\(.key)'\'' '\''\(.value|tostring)'\''" ) | .[]' | sed 's/^M//' \
    | xargs -d '\n' -I{} sh -c "yq write --inplace ./docker-compose.yaml {}"
```

Besides being pretty slow in MSYS it has opinions about what constitutes a path, and for the life of me I can't figure it out. For example this configuration:

```yaml
volumes:
  - ./datamodel/datamodel/create-user:/usr/local/bin/create-user

# Would become

volumes:
  - .\datamodel\datamodel\create-user;C:\msys64\usr\local\bin\create-user
```` 

This can be easily be prevented by escaping the absolute path this way:

```yaml
volumes:
  - ./datamodel/datamodel/create-user://usr/local/bin/create-user
```

I am going to look if I can replace the call to `jq` with `yq` to keep it a little more focused but this sort of works though.
