### ISSUE TITLE
Unable to make create_instructions.yaml work 

### ISSUE THREAD

**Issue by inianv** [mikefarah/yq#521]
**Describe the bug**

For some reason, I can't get the create script to work following the instructions from [Creating using a create script](https://mikefarah.gitbook.io/yq/commands/create#creating-using-a-create-script) 

version of yq: 3.3.2
operating system: CentOS Linux release 7.5.1804 (Core)

**Command**

```
echo '- command: update 
  path: b.c
  value:
    #great 
    things: frog # wow!' | yq new -s -
```

which fails with error

```
Error: Must provide <path_to_update> <value>
```

The same happens when I run it from a file also

```
yq new --script create.yaml
yq new -s create.yaml
yq n --script create.yaml
yq n -s create.yaml
```
