### ISSUE TITLE
Write deep splat makes more changes than read shows

### ISSUE THREAD

**Issue by yuriylesyuk** [mikefarah/yq#523]
**Describe the bug**

Read correctly identifies paths for nodes deep splat path expression.

Then write replaces correct nodes, but adds additional nodes in unexpected places.

version of yq: 
3.3.2

operating system:
linux

**Input Yaml**
deepsplat.yaml:
```yaml
a:
 x: 3
b:
  c:
    x: 3
  d:
    x: 3
    y: 0
  e:
  f:
    x: 3
  g:
    y: 0
  e:
    z: 0
  f: 0
```

read correctly shows
```
$ yq r deepsplat.yaml 'b.**.x' -p p
b.c.x
b.d.x
b.f.x
```
write incorrectly produces 2 extra `x: 5` nodes
```yaml
$ yq w deepsplat.yaml 'b.**.x' 5
a:
  x: 3
b:
  c:
    x: 5
  d:
    x: 5
    y: 0
  e:
  f:
    x: 5
  g:
    y: 0
    x: 5
  e:
    z: 0
    x: 5
  f: 0
```

Expectation:
```yaml
a:
 x: 3
b:
  c:
    x: 5
  d:
    x: 5
    y: 0
  e:
  f:
    x: 5
  g:
    y: 0
  e:
    z: 0
  f: 0
```

Another anomaly. For same input as above, [single star] splat incorrectly add extra nodes with no values
```
$ yq w deepsplat.yaml 'b.*.x' 5
a:
  x: 3
b:
  c:
    x: 5
  d:
    x: 5
    y: 0
  e:
    x: 5
  f:
    x: 5
  g:
    y: 0
    x: 5
  e:
    z: 0
    x:
  f:
    x:
```
