### ISSUE TITLE
Comments in the node line are not preserved

### ISSUE THREAD

**Issue by yuriylesyuk** [mikefarah/yq#524]
**Describe the bug**
When updating/writing a node line with a comment, the comment at the end of the line is removed.

version of yq: 3.3.2
operating system: linux

**Input Yaml**

data.yml:
```yaml
# things
a:
  b: # inventory
    c: fly # animal
    d: chair # furniture
```

**Command**
The command you ran:
```
yq w data.yaml a.b.c dog
```

**Actual behavior**

```yaml
# things
a:
  b: # inventory
    c: dog
    d: chair # furniture
```

**Expected behavior**

```yaml
# things
a:
  b: # inventory
    c: dog # animal
    d: chair # furniture
```

**Comment by olets** [comment]
Might not be an option for you, but it's possible to get close to your desired output by putting the comments on their own lines

```yaml
# data.yaml
# things
a:
  # inventory
  b:
    # animal
    c: fly
    # furniture
    d: chair
```

```shell
% yq w git-replay.yaml a.b.c dog
# data.yaml
# things
a:
  # inventory
  b:
    # animal
    c: dog
    # furniture
    d: chair
```
