### ISSUE TITLE
Extra newline possible when appending to an array ending in commented out entry

### ISSUE THREAD

**Issue by olets** [mikefarah/yq#528]
**Describe the bug**

When appending to array an extra newline is appended before the new element _if the last element in the array is commented out at the indentation level where the `-` would be._

This does no harm, reporting in case it reflects a parsing bug that is problematic in some other scenario.

version of yq: 3.3.2 (installed w/ Homebrew)
operating system: macOS 10.15.6

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug)

data.yml:
```yaml
b:
  c: 2
  d:
    - new thing
    # - foo thing
```

**Command**
The command you ran:
```shell
yq w data.yaml "b.d[+]" "bar thing"
```

**Actual behavior**

```yaml
b:
  c: 2
  d:
    - new thing
    # - foo thing

    - bar thing
```

**Expected behavior**

```yaml
b:
  c: 2
  d:
    - new thing
    # - foo thing
    - bar thing
```

or

```yaml
b:
  c: 2
  d:
    - new thing
    - bar thing
    # - foo thing
```

**Additional context**

Compare to when the `#` is in a different position. In all cases the command is the same

```yaml
b:
  c: 2
  d:
    - new thing
#    - foo thing
```
```shell
% yq w git-replay.yaml "b.d[+]" "bar thing"
b:
  c: 2
  d:
    - new thing
    - bar thing
#    - foo thing
```

and

```yaml
b:
  c: 2
  d:
    - new thing
 #   - foo thing
```

```shell
b:
  c: 2
  d:
    - new thing
    - bar thing
#   - foo thing
```

and

```yaml
b:
  c: 2
  d:
    - new thing
  #  - foo thing
```

```shell
% yq w git-replay.yaml "b.d[+]" "bar thing"
b:
  c: 2
  d:
    - new thing
    - bar thing
  #  - foo thing
```
