### ISSUE TITLE
set bash variables from yaml config file

### ISSUE THREAD

**Issue by splaisan** [mikefarah/yq#529]
I would like to use a yaml file to set a number of **bash** variables and export them for my scripts to use them. 

Could you please send me in the right direction?

 Thanks in advance

The following example shows what I aim at

```
## global definitions

database:
  path: "/some/path/databases"
  name: "database.sqlite"
  dump: "structure_dump.sql"

mount:
  point: "/mnt/nas"
  path: "my/path/to/data"
```

running a bash command (?) will set and export:

```
database.path="/some/path/databases"
database.name="database.sqlite"
database.dump="structure_dump.sql"
mount.point="/mnt/nas"
mount.path="my/path/to/data"

```
