### ISSUE TITLE
Better handling of wildcards that aren't the last portion of an key or value

### ISSUE THREAD

**Issue by JJJJJones** [mikefarah/yq#536]
**Describe the bug**
Wildcards that aren't positioned as the last portion of an entry break yq.

version of yq: 3.3.2 and 3.3.4
operating system: macOS Catalina 10.15.6

**Input Yaml**
release.yaml:
```yaml
release:
  - name: repo-app-deployment
    location: repo/app
    payload: app
```

**Command**
The command you ran:
```
yq r release.yaml 'release(location==repo/*)'
yq r release.yaml 'release(location==*/app)'
yq r release.yaml 'release.[0].nam*'
yq r release.yaml 'release.[0].*ame'
yq r release.yaml 'release.*.name'
```

**Actual behavior**

```yaml
name: repo-app-deployment
location: repo/app
payload: app

repo-app-deployment

repo-app-deployment
```

**Expected behavior**

```yaml
name: repo-app-deployment
location: repo/app
payload: app
name: repo-app-deployment
location: repo/app
payload: app
repo-app-deployment
repo-app-deployment
repo-app-deployment
```

**Additional context**
