### ISSUE TITLE
yq write changes the original intent 2 to 4

### ISSUE THREAD

**Issue by patrickzhe** [mikefarah/yq#541]
**Describe the bug**
I use yq write to add a label in my YAML files. This part is ok. 
But yq changes other part of my YAML file, inplace seems not work.

version of yq:  3.3.3
operating system: mac os

**Input Yaml**
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd-gke
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch
```

data2.yml:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: declarative-infra-fluentd-gke
  labels:
    velero.io/exclude-from-backup: "true"
rules:
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
    verbs:
      - list
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
    verbs:
      - get
      - list
      - watch
```

**Command**
The command you ran:
```
yq w -d'*' -i sample.yaml --style double 'metadata.labels."velero.io/exclude-from-backup"' "true"
```

**Actual behavior**
yq change the structure of rules

**Expected behavior**

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: declarative-infra-fluentd-gke
  labels:
    velero.io/exclude-from-backup: "true"
rules:
- apiGroups:
    - rbac.authorization.k8s.io
  resources:
    - rolebindings
  verbs:
    - list
- apiGroups:
    - ""
  resources:
    - pods
    - namespaces
  verbs:
    - get
    - list
    - watch

```

Is there any options I miss? thanks for the help
