### ISSUE TITLE
Yq Compare Not Providing Expected Differences in values

### ISSUE THREAD

**Issue by angelotinho** [mikefarah/yq#548]
**Describe the bug**
I have to yaml files.
```yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name:  delivery-test
```

```yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name:  delivery-sandbox
```

version of yq: 3.4.0
operating system: ubuntu 16.04 LTS

**Input Yaml**
data1.yml:
```yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name:  delivery-test

```

data2.yml:
```yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name:  delivery-sandbox
```

**Command**
```
yq x  -pp file1.yaml file2.yaml '**'
```

**Actual behavior**

```yaml
returned with exit 0. No differences
```

**Expected behavior**

```yaml
 apiVersion
 kind
+metadata.name

```

**Additional context**
But if I do diff
```sh
4c4
<   name:  delivery-test
---
>   name:  delivery-sandbox
```
