### ISSUE TITLE
cannot read value when the key's name contains a dot

### ISSUE THREAD

**Issue by zhangguanzhang** [mikefarah/yq#549]
```
$ echo '{"key.a":1}' | yq r - key.a
$ echo '{"key.a":1}' | yq r - key\.a
$ yq --version
yq version 3.4.0
```

**Comment by mikefarah** [comment]
https://mikefarah.gitbook.io/yq/usage/path-expressions#keys-with-dots

**Comment by hudi1** [comment]
How to solve this issue in version 4 ?

**Comment by mikefarah** [comment]
https://mikefarah.gitbook.io/yq/traverse#special-characters

**Comment by hudi1** [comment]
thx but I tried this like:

sample.yaml:

data:
  application.yaml: |-
    config:

 yq e '.data.application"."yaml' sample.yaml

will return null

**Comment by hudi1** [comment]
nice thx

**Comment by elpoutro** [comment]
I have got troubles finding values in this kind of structure:

```
parameters:
    router.request_context.host: my_host.com
    router.request_context.scheme: https
    router.request_context.base_url: test
```
    
Finally, i use the wildcard to replace dot in key names and this work great:
`yq eval .parameters.router*request_context*host sample.yml`
