### ISSUE TITLE
Can't append value to key with array

### ISSUE THREAD

**Issue by oz123** [mikefarah/yq#554]
**Describe the bug**
Suppose I want to create the following structure:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: topology-aware-standard
provisioner: cinder.csi.openstack.org
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: topology.cinder.csi.openstack.org/zone
    values:
    - baz
    - bar
    - foo
```
It is not clear how one can access elements inside `allowedTopologies`.
The following command has a different meaning:
```
yq w ta.yml allowedTopologies.matchLabelExpressions.values foo
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: topology-aware-standard
provisioner: cinder.csi.openstack.org
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
  matchLabelExpressions:
    values: foo
```
Adding  ' - ' isn't helping too.

version of yq:  3.1.0

operating system:
Linux

Not being able to solve the problem with yq, I was able to solve the problem with sed ... but it's so ugly.

```
$ cat ta.yml 
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: topology-aware-standard
provisioner: cinder.csi.openstack.org
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: topology.cinder.csi.openstack.org/zone
    values: [ %%ZONES%% ]
$ sed  's/%%ZONES%%/foo, bar, baz/' ta.yml 
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: topology-aware-standard
provisioner: cinder.csi.openstack.org
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: topology.cinder.csi.openstack.org/zone
    values: [ foo, bar, baz ]
```

Any chance we can do it in yq?

**Comment by mikefarah** [comment]
allowedTopologies is an _array_, the first element in the array is an object with the key 'matchLabelExpressions'.

so
```
allowedTopologies[0].matchLabelExpressions.values foo
```

**Comment by oz123** [comment]
This is still not reaching the goal:
```
$ yq w test.yml allowedTopologies[0].matchLabelExpressions[0].values  foo
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: topology-aware-standard
provisioner: cinder.csi.openstack.org
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
  - matchLabelExpressions:
      - values: foo
```
This is somewhat better,
```
yq w test.yml allowedTopologies[0].matchLabelExpressions[keys]+  foo
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: topology-aware-standard
provisioner: cinder.csi.openstack.org
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
  - matchLabelExpressions:
      keys: foo
```
 but I still can't append the following:
````
values: [ foo, bar, baz ]
```
Can you maybe post how you would do it?
