### ISSUE TITLE
Search by suffix

### ISSUE THREAD

**Issue by sylvainbx** [mikefarah/yq#556]
**Describe the bug**
Unable to search in array by suffix

version of yq: 3.3.4
operating system: Debian 9.11 (stretch)

**Input Yaml**
docker-compose.yml:
```yaml
version: '2'
services:
  fabmanager:
    volumes:
      - ${PWD}/public/assets:/usr/src/app/public/assets
      - ${PWD}/public/uploads:/usr/src/app/public/uploads
      - ${PWD}/invoices:/usr/src/app/invoices
      - ${PWD}/exports:/usr/src/app/exports
      - ${PWD}/log:/var/log/supervisor
      - ${PWD}/plugins:/usr/src/app/plugins
```

**Command**
The command you ran:
```
yq r docker-compose.yml "services.$SERVICE.volumes(.==*assets)"
```

**Actual behavior**
Nothing is returned by yq

**Expected behavior**

```yaml
${PWD}/public/assets:/usr/src/app/public/assets
```

**Additional context**
It works when using a "prefix search": (like `yq r docker-compose.yml "services.$SERVICE.volumes(.==\${PWD}/public/assets*)"`. However, #88 closed let me think that it should work with a suffix.
