### ISSUE TITLE
Searching across documents to get the index to update

### ISSUE THREAD

**Issue by inianv** [mikefarah/yq#557]
There is no straightforward way to get the index of the object to which a write needs to be attempted. The Path expressions documentation wasn't quite helpful for this regard

version of yq:  3.3.2
operating system: CentOS

**Input YAML**

```yaml
apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: nodejs-10
  spec:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: openshift45
  spec:
    lookupPolicy:
      local: false
```

**Desired YAML**

```yaml
apiVersion: v1
items:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      name: nodejs-10
    spec:
      lookupPolicy:
        local: false
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      name: openshift45
    spec:
      lookupPolicy:
        local: false
```

**Command**

First tried to query the value using `read` to confirm the path expression, so that I can use it later for write. Basically find the object inside `.items` for which `.metadata.name` is `openshift45` and `kind` is `ImageStream`

```
yq r yaml 'items(metadata.name == openshift45)(kind==ImageStream)
yq r yaml 'items(metadata.name == openshift45).(kind==ImageStream)

```
