### ISSUE TITLE
YAML files containing anchor references can not be merged

### ISSUE THREAD

**Issue by RussellLuo** [mikefarah/yq#570]
**Describe the bug**
YAML files containing anchor references can not be merged.

version of yq: 3.4.1
operating system: macOS

**Input Yaml**

data1.yml:
```yaml
foo: &foo
  a: 1

foobar: 
  <<: *foo
```

data2.yml:
```yaml
foobar:
  bar: 2
```

**Command**
The command you ran:
```
yq merge -x data1.yml data2.yml
```

**Actual behavior**

```yaml
foo: &foo
  a: 1
foobar:
  !!merge <<: *foo
  bar: 2
```

**Expected behavior**

```yaml
foo: &foo
  a: 1
foobar:
  <<: *foo
  bar: 2
```
