### ISSUE TITLE
Do you know how to parse a piped configmap ?

### ISSUE THREAD

**Issue by sunnypatel2141** [mikefarah/yq#571]
Here's the configmap.yaml:

```
apiVersion: v1
data:
  config.yaml: |-
    sinks:
    - name: stdout
    - name: newRelicInfra
      config:
        agentEndpoint: http://localhost:8001/v1/data
        clusterName: <ADD YOUR CLUSTER NAME>
        agentHTTPTimeout: 30s
kind: ConfigMap
metadata:
  name: nri-kube-events
  namespace: default
```

And I want to update clusterName to my cluster name. Any idea how to achieve this using `yq` ?
