### ISSUE TITLE
Provide a way to persist document delimiters (`---`) when reading a multi-document file

### ISSUE THREAD

**Issue by bioball** [mikefarah/yq#573]
Currently, reading multiple documents strips the `---` delimiter that denotes the start of each document. For instance, take the following file:

```yaml
---
a: 1
---
a: 2
---
a: 3
```

And run the following

```bash
yq r -d'*' test.yaml ""
```

It outputs the following:

```yaml
a: 1
a: 2
a: 3
```

The output here is invalid yaml, and moreover; there might be times where you might want to keep the output as multiple documents. Ideally there should be a way to produce this output:

```yaml
---
a: 1
---
a: 2
---
a: 3
```
