### ISSUE TITLE
yq and Jinja2 templates 

### ISSUE THREAD

**Issue by denis-ev** [mikefarah/yq#574]
**Describe the bug**
Error: Error reading document at index 0, yaml: line 79: found character that cannot start any token: yaml: line 79: found character that cannot start any token

The .yml file has this Jinja2 variable on line 79 `{% raw %}` which creates this problem.

version of yq: 3.4.1
operating system: Docker `python:3.8-alpine`

**Input Yaml**
this should be merged into a config.yml which contains `{% raw %}` multiple times
data1.yml:
```yaml
kutt:
  enable: { { kutt.enable | default(False) } }
  https_only: { { kutt.https_only | default(False) } }
  auth: { { kutt.auth | default(False) } }
  domain: { { kutt.domain | default(False) } }
  subdomain: { { kutt.subdomain | default("kutt") } }
  version: { { kutt.version | default("latest") } }
```

data2.yml:
```yaml
# This configuration dictionary sets various details of your bastion host.
# see the docs for more information about what a bastion host is and how
# the VivumLab bastion host works.
bastion:
  # should VivumLab utilize a bastion server?
  enable: {{ bastion.enable | default(False) }}
  # Bastion host main ethernet interface name
  interface: {{ bastion.interface | default("eth0") }}
  # must provide passwordless sudo
  server_ssh_user: {{ bastion.server_ssh_user | default('root') }}
  # Can be an IP or a hostname
  server_address: {{ bastion.server_address | default(False) }}
  wireguard:
    bastion_vpn_address: {{ bastion.wireguard.bastion_vpn_address | default("10.0.1.1") }}
    vlab_vpn_address: {{ bastion.wireguard.vlab_vpn_address | default("10.0.1.2") }}
    netmask: {{ bastion.wireguard.netmask | default("/24") }}
    port: {{ bastion.wireguard.port | default("51820") }}
    keepalive: {{ bastion.wireguard.keepalive | default("25") }}
  ports_to_forward:
    2222: 22
    80: 80
    443: 443
    25: 25
    143: 143
    587: 587
    998: 998
    4190: 4190
  # MIGRATION v0.7
  # Should VivumLab reset the bastion server IP tables rules?
  # Enable this if you are upgrading a Tinc bastion host
  reset_iptables: {{ bastion.reset_iptables | default(False) }}
  # END MIGRATION

{% raw %}
# Minio access keys
minio_access_key: "{{ vault.minio_access_key }}"
minio_secret_access_key: "{{ vault.minio_secret_access_key }}"

# VPN For Transmission to use for Downloads
openvpn_provider: "{{ vault.openvpn_provider }}"
openvpn_username: "{{ vault.openvpn_username }}"
openvpn_password: "{{ vault.openvpn_password }}"
openvpn_config: "{{ vault.openvpn_config }}"

# Cloud Servers
aws:
  secret_key: "{{ vault.aws.secret_key }}"
  access_key: "{{ vault.aws.access_key }}"
  region: "{{ vault.aws.region }}"

do_access_token: "{{ vault.do_access_token }}"
do_region: "{{ vault.do_region }}"

# After claiming your token at https://www.plex.tv/claim/ you will only have four minutes to run make and deploy plexinc
plex_claim: "{{ vault.plex_claim }}"

# Mapbox Api keys: Used for OwnPhotos
mapbox_api_key: "{{ vault.mapbox_api_key }}"

# Restic S3 Backup Server Information name: Docs: https://vivumlab.com/setup/backups/
s3_access_key: "{{ vault.s3_access_key }}"
s3_secret_key: "{{ vault.s3_secret_key }}"
s3_backup_password: "{{ vault.s3_backup_password }}"

# Home Assitant API Key
homeassistant_api_key: "{{ vault.homeassistant_api_key }}"

# SMTP Settings
smtp:
  host: "{{ vault.smtp.host }}"
  port: "{{ vault.smtp.port }}"
  user: "{{ vault.smtp.user }}"
  pass: "{{ vault.smtp.pass }}"
  from_email: "{{ vault.smtp.from_email }}"
  from_name: "{{ vault.smtp.from_name }}"

traefik:
  https_only: "{{ vault.traefik.https_only }}"
  domain: "{{ vault.traefik.domain }}"
  subdomain: "{{ vault.traefik.subdomain }}"
  auth: "{{ vault.traefik.auth }}"
  expose_internally: "{{ vault.traefik.expose_internally }}"
  expose_externally: "{{ vault.traefik.expose_externally }}"
  # Enable sendAnonymousUsage?
  # Reference: https://docs.traefik.io/master/contributing/data-collection/
  send_anonymous_usage: "{{ vault.traefik.send_anonymous_usage }}"
  dns_challenge_provider: "{{ vault.traefik.dns_challenge_provider }}"
# use key:value pairs here to add additional environment variables to your traefik docker image.
# for instance, if you're using a dns challenge provider place your api keys etc here.
  additional_env_vars:
    # DUMMY_KEY: DUMMY_VALUE
    CF_API_EMAIL: "{{ vault.traefik.additional_env_vars.CF_API_EMAIL }}"
    CF_API_KEY: "{{ vault.traefik.additional_env_vars.CF_API_KEY }}"
{% endraw %}

# Features

# You can enable/disable different VivumLab features here by changing False to True and vice versa.

enable_tor: {{ enable_tor | default(False) }}

# Force SSL Usage
# Only set this to true after everything is working, and https certificates have been generated.
# https_only: {{ https_only | default(False) }}

# Services
docs:
  enable: {{ docs.enable | default(False) }}
  https_only: {{ docs.https_only | default(False) }}
  auth: {{ docs.auth | default(False) }}
  domain: {{ docs.domain | default(False) }}
  subdomain: {{ docs.subdomain | default("docs") }}
  version: {{ docs.version | default("1.1.2") }}
  amd64: False # False or verified or supported or unsupported
  arm64: False # False or verified or supported or unsupported
  armv7: False # False or verified or supported or unsupported
apache2:
  enable: {{ apache2.enable | default(False) }}
  https_only: {{ apache2.https_only | default(False) }}
  auth: {{ apache2.auth | default(False) }}
  domain: {{ apache2.domain | default(False) }}
  subdomain: {{ apache2.subdomain | default("apache2") }}
  version: {{ apache2.version | default("2.4") }}
  amd64: False # False or verified or supported or unsupported
  arm64: False # False or verified or supported or unsupported
  armv7: False # False or verified or supported or unsupported
```

**Command**
The command you ran:
```
yq merge -i roles/vivumlab_config/templates/config.yml package_template/tmpfile.yml
```

**Actual behavior**

Error: Error reading document at index 0, yaml: line 79: found character that cannot start any token: yaml: line 79: found character that cannot start any token

**Expected behavior**

should merge the data1.yml into data2.yml

**Additional context**

This is the project https://github.com/VivumLab/VivumLab

**Comment by mikefarah** [comment]
sorry but a jinga yaml template is not valid yaml -

**Comment by denis-ev** [comment]
@mikefarah alright, I hoped there would have been a way.
Right now I'm searching and replacing the Jinja2 template variable raw/endraw.
But when I run `yq merge -I data1.yml data2.yml` (no error shown) it changes almost everything.

Is this related to jinja2, because this should just be a value, even tho it's a variable for jinja2.

> data1.yml
```data1.yml
# temporary_raw_placeholder
# Minio access keys
minio_access_key: "{{ vault.minio_access_key }}"
minio_secret_access_key: "{{ vault.minio_secret_access_key }}"

# VPN For Transmission to use for Downloads
openvpn_provider: "{{ vault.openvpn_provider }}"
openvpn_username: "{{ vault.openvpn_username }}"
openvpn_password: "{{ vault.openvpn_password }}"
openvpn_config: "{{ vault.openvpn_config }}"

# Cloud Servers
aws:
  secret_key: "{{ vault.aws.secret_key }}"
  access_key: "{{ vault.aws.access_key }}"
  region: "{{ vault.aws.region }}"

do_access_token: "{{ vault.do_access_token }}"
do_region: "{{ vault.do_region }}"

# After claiming your token at https://www.plex.tv/claim/ you will only have four minutes to run make and deploy plexinc
plex_claim: "{{ vault.plex_claim }}"

# Mapbox Api keys: Used for OwnPhotos
mapbox_api_key: "{{ vault.mapbox_api_key }}"

# Restic S3 Backup Server Information name: Docs: https://vivumlab.com/setup/backups/
s3_access_key: "{{ vault.s3_access_key }}"
s3_secret_key: "{{ vault.s3_secret_key }}"
s3_backup_password: "{{ vault.s3_backup_password }}"

# Home Assitant API Key
homeassistant_api_key: "{{ vault.homeassistant_api_key }}"

# SMTP Settings
smtp:
  host: "{{ vault.smtp.host }}"
  port: "{{ vault.smtp.port }}"
  user: "{{ vault.smtp.user }}"
  pass: "{{ vault.smtp.pass }}"
  from_email: "{{ vault.smtp.from_email }}"
  from_name: "{{ vault.smtp.from_name }}"

traefik:
  https_only: "{{ vault.traefik.https_only }}"
  domain: "{{ vault.traefik.domain }}"
  subdomain: "{{ vault.traefik.subdomain }}"
  auth: "{{ vault.traefik.auth }}"
  expose_internally: "{{ vault.traefik.expose_internally }}"
  expose_externally: "{{ vault.traefik.expose_externally }}"
  # Enable sendAnonymousUsage?
  # Reference: https://docs.traefik.io/master/contributing/data-collection/
  send_anonymous_usage: "{{ vault.traefik.send_anonymous_usage }}"
  dns_challenge_provider: "{{ vault.traefik.dns_challenge_provider }}"
# use key:value pairs here to add additional environment variables to your traefik docker image.
# for instance, if you're using a dns challenge provider place your api keys etc here.
  additional_env_vars:
    # DUMMY_KEY: DUMMY_VALUE
    CF_API_EMAIL: "{{ vault.traefik.additional_env_vars.CF_API_EMAIL }}"
    CF_API_KEY: "{{ vault.traefik.additional_env_vars.CF_API_KEY }}"
# temporary_endraw_placeholder

# Features

# You can enable/disable different VivumLab features here by changing False to True and vice versa.

enable_tor: {{ enable_tor | default(False) }}

```

>data2.yml
```data2.yml
kutt:
  enable: {{ kutt.enable | default(False) }}
  https_only: {{ kutt.https_only | default(False) }}
  auth: {{ kutt.auth | default(False) }}
  domain: {{ kutt.domain | default(False) }}
  subdomain: {{ kutt.subdomain | default("kutt") }}
  version: {{ kutt.version | default("latest") }}
```

**Actual behavior**
```yml
traefik:
  https_only: "{{ vault.traefik.https_only }}"
  domain: "{{ vault.traefik.domain }}"
  subdomain: "{{ vault.traefik.subdomain }}"
  auth: "{{ vault.traefik.auth }}"
  expose_internally: "{{ vault.traefik.expose_internally }}"
  expose_externally: "{{ vault.traefik.expose_externally }}"
  # Enable sendAnonymousUsage?
  # Reference: https://docs.traefik.io/master/contributing/data-collection/
  send_anonymous_usage: "{{ vault.traefik.send_anonymous_usage }}"
  dns_challenge_provider: "{{ vault.traefik.dns_challenge_provider }}"
  # use key:value pairs here to add additional environment variables to your traefik docker image.
  # for instance, if you're using a dns challenge provider place your api keys etc here.
  additional_env_vars:
    # DUMMY_KEY: DUMMY_VALUE
    CF_API_EMAIL: "{{ vault.traefik.additional_env_vars.CF_API_EMAIL }}"
    CF_API_KEY: "{{ vault.traefik.additional_env_vars.CF_API_KEY }}"
# temporary_endraw_placeholder

# Features

# You can enable/disable different VivumLab features here by changing False to True and vice versa.
enable_tor: {? {enable_tor | default(False): ''} : ''}
# Force SSL Usage
# Only set this to true after everything is working, and https certificates have been generated.
# https_only: {{ https_only | default(False) }}
kutt:
  enable:
  https_only:
  auth:
  domain:
  subdomain:
  version:
```
**Expected behavior**
```yml
traefik:
  https_only: "{{ vault.traefik.https_only }}"
  domain: "{{ vault.traefik.domain }}"
  subdomain: "{{ vault.traefik.subdomain }}"
  auth: "{{ vault.traefik.auth }}"
  expose_internally: "{{ vault.traefik.expose_internally }}"
  expose_externally: "{{ vault.traefik.expose_externally }}"
  # Enable sendAnonymousUsage?
  # Reference: https://docs.traefik.io/master/contributing/data-collection/
  send_anonymous_usage: "{{ vault.traefik.send_anonymous_usage }}"
  dns_challenge_provider: "{{ vault.traefik.dns_challenge_provider }}"
  # use key:value pairs here to add additional environment variables to your traefik docker image.
  # for instance, if you're using a dns challenge provider place your api keys etc here.
  additional_env_vars:
    # DUMMY_KEY: DUMMY_VALUE
    CF_API_EMAIL: "{{ vault.traefik.additional_env_vars.CF_API_EMAIL }}"
    CF_API_KEY: "{{ vault.traefik.additional_env_vars.CF_API_KEY }}"
# temporary_endraw_placeholder

# Features

# You can enable/disable different VivumLab features here by changing False to True and vice versa.
enable_tor: {{ enable_tor | default(False) }}
# Force SSL Usage
# Only set this to true after everything is working, and https certificates have been generated.
# https_only: {{ https_only | default(False) }}
kutt:
  enable: {{ kutt.enable | default(False) }}
  https_only: {{ kutt.https_only | default(False) }}
  auth: {{ kutt.auth | default(False) }}
  domain: {{ kutt.domain | default(False) }}
  subdomain: {{ kutt.subdomain | default("kutt") }}
  version: {{ kutt.version | default("latest") }}
```
