### ISSUE TITLE
yq merge MkDocs.yml

### ISSUE THREAD

**Issue by denis-ev** [mikefarah/yq#575]
**Describe the bug**
The merge removes a dash in front of the first nav point, but leaves the other dashes.

version of yq: 3.4.1
operating system: Docker `python:3.8-alpine`

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug)
tmpmkdocsfile.yml:
```yaml
nav:
  - Included Software:
      - Misc/Other:
          - package_name: software/package_filename.md
```

mkdocs.yml:
```yaml
nav:
  - Home: index.md
  - Installation: core/Installation.md
  - Getting Started: core/Next-Step.md
  - Troubleshooting / FAQ: FAQ-Troubleshoot.md
  - Setup:
      - Backups: core/Backup.md
      - Bastion Server: core/Bastion.md
      - Storage: core/Storage.md
      - Terraform: core/Terraform.md
      - Tor Onion Services: core/Tor.md
  - Included Software:
      - Analytics:
          - Matomo: software/matomo.md
```

**Command**
The command you ran:
```
yq m -i mkdocs.yml tmpmkdocsfile.yml
```

**Actual behavior**

```yaml
nav:
  - Home: index.md
    Included Software:
      - Misc/Other:
          - package_name: software/package_filename.md
  - Installation: core/Installation.md
  - Getting Started: core/Next-Step.md
  - Troubleshooting / FAQ: FAQ-Troubleshoot.md
  - Setup:
      - Backups: core/Backup.md
      - Bastion Server: core/Bastion.md
      - Storage: core/Storage.md
      - Terraform: core/Terraform.md
      - Tor Onion Services: core/Tor.md
  - Included Software:
      - Analytics:
          - Matomo: software/matomo.md
```

**Expected behavior**

```yaml
nav:
  - Home: index.md
  - Installation: core/Installation.md
  - Getting Started: core/Next-Step.md
  - Troubleshooting / FAQ: FAQ-Troubleshoot.md
  - Setup:
      - Backups: core/Backup.md
      - Bastion Server: core/Bastion.md
      - Storage: core/Storage.md
      - Terraform: core/Terraform.md
      - Tor Onion Services: core/Tor.md
  - Included Software:
      - Analytics:
          - Matomo: software/matomo.md
      - Misc/Other:
          - package_name: software/package_filename.md
```

**Additional context**
