### ISSUE TITLE
Setting empty object results in single-quotes

### ISSUE THREAD

**Issue by KojanAbzakh** [mikefarah/yq#580]
yaml w foo.yaml a {}

want: a: {}
got: a: '{}'

What am trying to do is add empty scope to my swagger.yaml [swagger scope](https://swagger.io/docs/specification/authentication/oauth2/)
```yaml
components:
  securitySchemes:
    oAuthNoScopes:
      type: oauth2
      flows: 
        implicit: 
          authorizationUrl: https://api.example.com/oauth2/authorize
          scopes: {}   # <-----
```
using yq version 3.4.0
Basically the same as the fixed [yq/issues/21](https://github.com/mikefarah/yq/issues/21)
