### ISSUE TITLE
How to read a file which has a full stop

### ISSUE THREAD

**Issue by shinokada** [mikefarah/yq#585]
**Describe the bug**
version of yq: 3.4.1
operating system: macOS 11.0

yaml file

```
github.com:
    user: shinokada
    oauth_token: abcabcabcabcabc
    git_protocol: ssh
```

I'd like to get the user name "shinokada" from the above file.

I tried the following but didn't output anything.

Is it because it has a full stop in github.com?

```
cat ~/.config/gh/hosts.yml | yq r - 'github.com'.user
```
