### ISSUE TITLE
Adding arrays to non-object nodes and object nodes simultaneously?

### ISSUE THREAD

**Issue by zackproser** [mikefarah/yq#586]
Hi, thanks for this excellent and useful tool! It's been very helpful. I'm wondering if my use-case is currently supported by [path expressions](https://mikefarah.gitbook.io/yq/usage/path-expressions). 

I've got a YAML file that looks like the following (truncated). 

**What I'm trying to accomplish**: append to, or add, a `context` array to every job under `workflows -> jobs`. In other words, after running `yq`, I want every job that is a child of `workflows` to have a `context` array with member "foo". 

```
workflows:
  version: 2
  build-and-test:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
      - build:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/


  frequently:
    triggers:
      - schedule:
          cron: "0 0,3,6,9,12,15,18,21 * * *"
          filters:
            branches:
              only: master
    jobs:
      - test
      - nuke_phx_devops:
          requires:
            - test

  nightly:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only: master
    jobs:
      - test
      - nuke_sandbox:
          requires:
            - test
```

**What I have working**:  `yq w test.yaml workflows.*.jobs[*].*.*.context[+] "Foo"` - which results in the following output: 

```
workflows:
  version:
    jobs: {}
  build-and-test:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
           context:
              - Foo
      - build:
          requires:
           context:
              - Foo
          filters:
            tags:
              only: /^v.*/
           context:
              - Foo
      - deploy:
          requires:
          context:
              - Foo
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
            context:
              - Foo
  frequently:
    triggers:
      - schedule:
          cron: "0 0,3,6,9,12,15,18,21 * * *"
          filters:
            branches:
              only: master
    jobs:
      - test
      - nuke_phx_devops:
          requires:
          context:
              - Foo
  nightly:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only: master
    jobs:
      - test
      - nuke_sandbox:
          requires:
          context:
              - Foo
```
So, the jobs that are objects or maps work just fine - they end up with the desired `context` array with member `Foo`. 

However, jobs such as `-test` that are not maps are not updated - I'm curious if this is in fact expected, or if there's some means of having even these single `-test` jobs expanded into objects with the `context` array as well. 

Thanks very much for any assistance you can give!
