### ISSUE TITLE
Array indentation issue

### ISSUE THREAD

**Issue by emas80** [mikefarah/yq#589]
**Describe the bug**
If I start with a yaml file like this one:

```yaml
b:
  d: be gone
  c: 2
  e:
  - name: Billy Bob # comment over here
```

and I apply this patch:

```yaml
- command: update 
  path: b.c
  value:
    #great 
    things: frog # wow!
- command: delete
  path: b.d

```

by running `yq w -s update_instructions.yaml sample.yaml`

I get:

```yaml
b:
  c:
    #great 
    things: frog # wow!
  e:
    - name: Billy Bob # comment over here
```

version of yq: 3.4.0 
operating system: Fedora

It's taken directly from the examples found at  https://mikefarah.gitbook.io/yq/commands/write-update

**Command**
The command you ran:
```
yq w -s update_instructions.yaml sample.yaml
```

**Actual behavior**

```yaml
b:
  c:
    #great 
    things: frog # wow!
  e:
    - name: Billy Bob # comment over here
```

**Expected behavior**

```yaml
b:
  c:
    #great 
    things: frog # wow!
  e:
  - name: Billy Bob # comment over here
```

**Additional context**
I know it sounds odd, but it's really what I am getting... 
Given it's practically THE EXAMPLE found into the documentaton, is that possible that as some point the behaviour was changed?
