### ISSUE TITLE
dictionary in not overwritten in merge command

### ISSUE THREAD

**Issue by gorgitko** [mikefarah/yq#591]
**Describe the bug**
When `yq merge` is run with parameters `-a overwrite -x`, dictionary items are not overwritten by second file.

Version of yq: 3.4.1
Operating system: Linux
Installed via: binary release

**Input Yaml**
data1.yml:
```yaml
dict:
  item1: "item1"
  item2: "item2"
```

data2.yml:
```yaml
dict:
  item3: "item3"
```

**Command**
The command you ran:
```
yq merge -a overwrite -x data1.yaml data2.yaml
```

**Actual behavior**

```yaml
dict:
  item1: "item1"
  item2: "item2"
  item3: "item3"
```

**Expected behavior**

```yaml
dict:
  item3: "item3"
```

Thanks for this useful library and thanks in advance for looking at this problem.

**Comment by mikefarah** [comment]
The overwrite flag means it will recursively overwrite existing fields - not delete fields that are not present. 
So, for instance, if overwrite was false and data1.yml had item3 in the dict, it will not be overwritten by data2's item3.

**Comment by gorgitko** [comment]
OK, I got it. In my case I need to replace the whole `dict` by that in data2.yml. I have made it by enclosing `dict` items in array:

*Input YAML*
data1.yaml:

```yaml
dict:
  - item1: "item1"
    item2: "item2"
```

data2.yaml:

```yaml
dict:
  - item3: "item3"
```

Command same as in the opening comment, result:

```yaml
dict:
  - item3: "item3"
```

In code (R language) I just need to check that imported YAML is list of length one.
