### ISSUE TITLE
Cannot match values with special characters (e.g. `()`)

### ISSUE THREAD

**Issue by pmalek-sumo** [mikefarah/yq#601]
**Describe the bug**
Cannot match values with special characters (e.g. `()`)

Version of yq: 3.4.1
Operating system: mac
Installed via: homebrew

**Input Yaml**

`reg.yml`:

```yaml
prometheus-operator:
  prometheus:
    prometheusSpec:
      remoteWrite:
        - url: http://$(CHART).$(NAMESPACE).svc.cluster.local:9888/prometheus.metrics.state
          writeRelabelConfigs:
            - action: keep
              regex: kube-state-metrics;(?:kube_statefulset_status_observed_generation)
```

**Command**

This works:

```
$ yq r reg.yaml 'prometheus-operator.prometheus.prometheusSpec.remoteWrite.(url==http://$(CHART*)'
url: http://$(CHART).$(NAMESPACE).svc.cluster.local:9888/prometheus.metrics.state
writeRelabelConfigs:
  - action: keep
    regex: kube-state-metrics;(?:kube_statefulset_status_observed_generation|kube_statefulset_status_replicas)
    sourceLabels: [job, __name__]
```

This doesn't work (mark one more parenthesis taken from the url from the input yaml):

```yaml
$ yq r reg.yaml 'prometheus-operator.prometheus.prometheusSpec.remoteWrite.(url==http://$(CHART)*)'
$
```

Neither does this (exact match - no `*`):

```yaml
$ yq r reg.yaml 'prometheus-operator.prometheus.prometheusSpec.remoteWrite.(url==http://$(CHART).$(NAMESPACE).svc.cluster.local:9888/prometheus.metrics.state)'
$
```

Same thing with script file.

**Expected behavior**

I should be able to match by values even with special characters in them

**Comment by pmalek-sumo** [comment]
Same thing happens when changing `'` to `"` (add `$` escaping):

This works:

```yaml
yq r reg.yaml "prometheus-operator.prometheus.prometheusSpec.remoteWrite.(url==http://\$(CHART*"
url: http://$(CHART).$(NAMESPACE).svc.cluster.local:9888/prometheus.metrics.state
writeRelabelConfigs:
  - action: keep
    regex: kube-state-metrics;(?:kube_statefulset_status_observed_generation|kube_statefulset_status_replicas)
    sourceLabels: [job, __name__]
```

This doesn't:

```yaml
$yq r reg.yaml "prometheus-operator.prometheus.prometheusSpec.remoteWrite.(url==http://\$(CHART)*"`
$
```

Closing parenthesis seems to be the problem somehow.
