### ISSUE TITLE
unknown command "yq" for "yq"

### ISSUE THREAD

**Issue by volkmydj** [mikefarah/yq#603]
**Describe the bug**
docker run --rm -v ${PWD}:/workdir mikefarah/yq:4.0.0 yq write --inplace --verbose $CD_MANIFEST_FILE appVersion $TAG.

Version of yq: 4.0.0
Operating system: linux
Installed via: docker

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
Chart.yml:
```yaml
apiVersion: v2
name: content-svc-chart
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: 1.16.0

```

**Command**
The command you ran:
```
docker run --rm -v ${PWD}:/workdir mikefarah/yq:4.0.0 yq write --inplace --verbose $CD_MANIFEST_FILE appVersion $TAG.
```

**Expected behavior**

Output:

```
Status: Downloaded newer image for mikefarah/yq:4.0.0
Error: unknown command "yq" for "yq"
Run 'yq --help' for usage.
```

**Additional context**
Not work in v 4.0.0
