### ISSUE TITLE
Cannot delete based on full path

### ISSUE THREAD

**Issue by bjw-s** [mikefarah/yq#609]
**Describe the bug**

Version of yq: 4.0.0
Operating system: mac
Installed via: homebrew

**Input Yaml**
data1.yml:
```yaml
metadata:
  creationTimestamp: null
  name: helm-values
  namespace: value
```

**Command**
The command you ran:
```
yq eval 'del(.metadata.creationTimestamp)' data1.yml
```

**Actual behavior**

```yaml
metadata:
  creationTimestamp: null
  name: helm-values
  namespace: value
```

**Expected behavior**

```yaml
metadata:
  name: helm-values
  namespace: value
```

**Additional context**
Running `yq eval 'del(.metadata)' data1.yml` actually does remove the entire `.metadata` block
