### ISSUE TITLE
Github actions to publish yq

### ISSUE THREAD

**Issue by mikefarah** [mikefarah/yq#615]
I've just finished adding github actions for github releases (after @bahetiamit lead the way with an action for multiarch docker releases!) and I would love to see more actions for the different installation methods of `yq` so that everything is kept up to date in an automated fashion.

This would mean we wouldn't need to bother @chillum, @herbygillot, @rmescandon and Tuan Hoang to get the latest releases...

Any help (or guidance) is appreciated...

**Comment by mkrakowitzer** [comment]
Not sure this comment belongs here, but it's unclear to me how to use your action.
```
      - name: yq - portable yaml processor
        uses: mikefarah/yq@4.0.0-beta1
      - name: Get stages from meta.yaml
        run: yq -j e '.terraform.stages' meta.yaml
```
which results in `/home/runner/work/_temp/f2eff4c7-4a78-446f-a2e6-5e741b926e02.sh: line 1: yq: command not found`
in the end I settled for installing it with wget.

**Comment by harryttd** [comment]
@mkrakowitzer 

Like so:
```
name: yq - portable yaml processor
        uses: mikefarah/yq@4.0.0-beta1
        with:
          cmd:
```

Although there is a bug. 4.0.0-beta1 action is actually still running `yq` in version 3x. The `yq eval` command doesn't work with the above action.

Any way the latest version of yq can be updated on github actions? @mikefarah

**Comment by mikefarah** [comment]
That's a valid point and should be raised as a separate issue - this card is about having github actions in the release pipeline of `yq` so that it can be automatically released to apt/snap/chocolate/...

**Comment by hholst80** [comment]
I think we need a few examples on how this can be used in a CI/CD context.

I think this action works exactly like I expected it to work (just install the tool in the PATH and be done)
```
      - uses: azure/setup-kubectl@v1
```

**Comment by ryenus** [comment]
Maybe use the [mislav/bump-homebrew-formula-action][1] upon the [release event][2]?

Something like:

```yaml
on:
  release:
    types: [published]

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v1
        with:
          # A PR will be sent to github.com/Homebrew/homebrew-core to update this formula:
          formula-name: yq
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
``` 

[1]: https://github.com/mislav/bump-homebrew-formula-action
[2]: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#release
