### ISSUE TITLE
Json to Yaml leaves quotes around keys

### ISSUE THREAD

**Issue by ethanabrooks** [mikefarah/yq#623]
**Describe the bug**
Parsing a json file leaves quotes around keys.

Version of yq: 4.1.0
Operating system: mac
Installed via: homebrew

**Input JSON**
sample.json:
```json
{"a":"Easy! as one two three","b":{"c":2,"d":[3,4]}}
```

**Command**
```
yq eval '.. style= ""' sample.json
```

**Actual behavior**

```yaml
"a": Easy! as one two three
"b":
  "c": 2
  "d":
    - 3
    - 4
```

**Expected behavior** (per https://mikefarah.gitbook.io/yq/usage/convert#json-to-yaml)

```yaml
a: Easy! as one two three
b: # look ma, no quotes
  c: 2
  d:
  - 3
  - 4
```
