### ISSUE TITLE
Github Actions: Run multiple commands in a single action

### ISSUE THREAD

**Issue by harryttd** [mikefarah/yq#627]
**Please describe your feature request.**
As of now you have to do this:
```yaml
name: yq - portable yaml processor
uses: mikefarah/yq@3.4.1
   with:
      cmd: >-
         yq w ... &&
         yq w ...
```
Every command needs to be chained on one line with `&&`. I need to do more logic and it would be nice if you could run all the bash you need as part of the action without keeping all of the commands on one line.

**Describe the solution you'd like**
If we have data1.yml like:
```yaml
name: yq - portable yaml processor
uses: mikefarah/yq@3.4.1
   with:
      cmd: |
         echo hello
         yq w ...
         yq w ...
```
