### ISSUE TITLE
How to update a multiline value in yq 4?

### ISSUE THREAD

**Issue by MartijnErmersI** [mikefarah/yq#631]
I've read the entire documentation, however I cannot seem to find it.

In yq 3 it's possible to update a multiline value like:
`yq w -i configmap.yml 'data.[config.yml]' -- "$(< config.yml)"`

We like to upgrade to yq 4, however I cannot seem to find the way to do this in yq 4.

Our document looks like:

```
apiVersion: v1
data:
  config.yml: |
    version: 0.1
    log:
      fields:
        service: registry
      level: warn
```

I've found the solution for the `.` in the LHS: replace the brackets by double quotes. 
The issue here however is how to insert the file contents of config.yml into the value` .data."config.yml"`

Thanks for your help!
