### ISSUE TITLE
Support Go / Helm templates (at least variables)

### ISSUE THREAD

**Issue by gajus** [mikefarah/yq#636]
**Describe the solution you'd like**
If we have data1.yml like:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.spec.destination.server | quote }}

```

And we run a command:

```bash
yq eval data1.yml
```

it could output

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.spec.destination.server | quote }}

```

Instead I am getting:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {? {.Values.spec.destination.server | quote: ''}: ''}

```

**Additional context**

I understand that Helm templates are not valid yaml, but this tool would be so much more useful in Kubernetes ecosystem if it could just ignore Helm template elements without messing with them.

For a bit of context, I am working with ArgoCD and I need to patch Helm templates using `yq`.

**Comment by mikefarah** [comment]
I see how it would be useful - however this is using a yaml parser under the hood, and as you say, it's not valid yaml.

**Comment by gajus** [comment]
After thinking about this for a while, this is not feasible unfortunately.

Consider this simple example:

```yaml
data:
  {{ if eq .Values.favorite.drink "coffee" }}
    mug: true
  {{ end }}
  {{ if eq .Values.favorite.drink "tea" }}
    mug: false
  {{ end }}
```

so even if yq understood Helm syntax, it couldn’t update data.mug because it is not clear which path it should take.

If you really wanted to, you could do something like this though:

```yaml
data:
  {{ if eq .Values.favorite.drink "coffee" }}
    mug: true
  {{ end }}
  {{ if eq .Values.favorite.drink "tea" }}
    # @i-am-a-variable-reference
    mug: false
  {{ end }}
```
and then:

```bash
./a-tool-that-does-not-exist-yet --arg-i-am-a-variable-reference = 'foo'
```

which would then interpolate to:

```yaml
ddata:
  {{ if eq .Values.favorite.drink "coffee" }}
    mug: true
  {{ end }}
  {{ if eq .Values.favorite.drink "tea" }}
    # @i-am-a-variable-reference
    mug: 'foo'
  {{ end }}
```

though the latter would be a completely different tool from yq

**Comment by willzhang** [comment]
Same here
```
root@ubuntu:/data/cluster-image/spinnaker/latest/manifests# cat halyard_deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: halyard
  name: halyard
  namespace: default
spec:
  selector:
    matchLabels:
      app: halyard
  template:
    metadata:
      labels:
        app: halyard
    spec:
      serviceAccountName: spinnaker-service-account
      # access apiserver.cluster.local
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      # install yq
      initContainers:
        - name: yq
          image: docker.io/mikefarah/yq:4.40.2
          command: ["/bin/sh"]
          args: ["-c", "cp -a -f /usr/bin/yq /yq-volume/yq"]
          volumeMounts:
            - name: yq-volume
              mountPath: /yq-volume
      containers:
        - name: halyard
          image: us-docker.pkg.dev/spinnaker-community/docker/halyard:stable
          imagePullPolicy: IfNotPresent
          env:
            - name: spinnaker_version
              value: "1.32.5"
            - name: ENDPOINT
              value: {{ default "http://minio.minio:9000" .s3_endpoint }}
            - name: MINIO_ACCESS_KEY
              value: {{ default "admin" .s3_accessKeyId }}
            - name: MINIO_SECRET_KEY
              value: {{ default "minio123" .s3_secretAccessKey }}
          volumeMounts:
            - name: yq-volume
              mountPath: /usr/bin/yq
              subPath: yq
            - name: halyard-volume
              mountPath: /opt/halyard/config/halyard-local.yml
              subPath: halyard-local.yml
      volumes:
        - name: yq-volume
          emptyDir: {}
        - name: halyard-volume
          configMap:
            name: halyard-config
root@ubuntu:/data/cluster-image/spinnaker/latest/man
```

```
# yq e  '.spec.template.spec.containers[0].env[0].value = env(spinnaker_version)' halyard_deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: halyard
  name: halyard
  namespace: default
spec:
  selector:
    matchLabels:
      app: halyard
  template:
    metadata:
      labels:
        app: halyard
    spec:
      serviceAccountName: spinnaker-service-account
      # access apiserver.cluster.local
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      # install yq
      initContainers:
        - name: yq
          image: docker.io/mikefarah/yq:4.40.2
          command: ["/bin/sh"]
          args: ["-c", "cp -a -f /usr/bin/yq /yq-volume/yq"]
          volumeMounts:
            - name: yq-volume
              mountPath: /yq-volume
      containers:
        - name: halyard
          image: us-docker.pkg.dev/spinnaker-community/docker/halyard:stable
          imagePullPolicy: IfNotPresent
          env:
            - name: spinnaker_version
              value: "1.32.5"
            - name: ENDPOINT
              value: {? {'default "http://minio.minio:9000" .s3_endpoint': ''}: ''}
            - name: MINIO_ACCESS_KEY
              value: {? {default "admin" .s3_accessKeyId: ''}: ''}
            - name: MINIO_SECRET_KEY
              value: {? {default "minio123" .s3_secretAccessKey: ''}: ''}
          volumeMounts:
            - name: yq-volume
              mountPath: /usr/bin/yq
              subPath: yq
            - name: halyard-volume
              mountPath: /opt/halyard/config/halyard-local.yml
              subPath: halyard-local.yml
      volumes:
        - name: yq-volume
          emptyDir: {}
        - name: halyard-volume
          configMap:
            name: halyard-config
```
