### ISSUE TITLE
How to add new, multipline object to existing array

### ISSUE THREAD

**Issue by bigjew92** [mikefarah/yq#653]
**Describe the bug**
Probably not a bug, just not just how to accomplish goal.

Note that any how to questions should be posted in the discussion board and not raised as an issue.

Version of yq: 4.2.1
Operating system: mac
Installed via: homebrew

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
data1.yml:
```
applications:
  - name: app
    path: path/to/app
```

**Command**
The command you ran:
```
yq e ".applications.name += \"$1\"" -i data1.yml
```

**Actual behavior**

```
Error: Cannot index array with 'name' (strconv.ParseInt: parsing "name": invalid syntax)
```

**Expected behavior**

```
applications:
  - name: app
     path: path/to/app
  - name: app2
     path: path/to/app2
```

**Additional context**
This sort of worked in v3
```
yq w -i data1.yml '.applications[+].name' $1
```

It would add a new object to the array, but I couldn't figure out how to add a new value to that object, so I tried upgrading to v4 and now can't even get it to add a new object to the array.

**Comment by bigjew92** [comment]
```
yq e ".applications += [\"$1\"]" -i data1.yml
``` 
This gets me a little closer

```
applications:
  - name: app1
    path: path/to/app1
  - $1
```

**Comment by bigjew92** [comment]
Was able to accomplish this by using json and passing that in.

```
yq e ".applications += [{\"name\":\"$1\",\"path\":\"apps/$1\"}]" -P -i data1.yaml
```
Produces this
```
applications:
  - name: app1
    path: apps/app1
  - name: $1
    path: apps/$1
```

would be nice if this was a little cleaner, but at least this seems to work.
