### ISSUE TITLE
Removing all comments does not work

### ISSUE THREAD

**Issue by ogruene** [mikefarah/yq#661]
**Describe the bug**
Removing all comments from yaml as described [here](https://mikefarah.gitbook.io/yq/v/v4.x/operators/comment-operators#remove-all-comments) does not remove all comments.

Version of yq: 4.3.2
Operating system: windows
Installed via: binary release (yq_windows_amd64.exe)

**Input Yaml**
sample.yml:
```yaml
# root comment  
root:           
  # sub comment 
  sub1: #comment
  sub2: #comment
```

**Command**
```
 yq eval '.. comments=""' sample.yaml
```

**Actual behavior**

```yaml
root:
  # sub comment
  sub1: #comment
  sub2: #comment
```

**Expected behavior**

```yaml
root:
  sub1:
  sub2:
```

**Additional context**
With yq 3.4.0 and command ` yq read --stripComments sample.yaml` everything works fine and all comments are removed.

Oliver Grüneberg <<oliver.grueneberg@daimler.com>>, Daimler TSS GmbH
[Legal Imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)
