### ISSUE TITLE
problem adding arg to container spec

### ISSUE THREAD

**Issue by bobdonat** [mikefarah/yq#662]
I would like to set an arg on a container spec. 

Version of yq: 4.3.2
Operating system: mac
Installed via: go get

This is the command I am using:
```
./yq -i eval ".spec.template.spec.containers.[0].args = \"-- enable-webhook-validation=true\"" /tmp/operator.yaml
```
This is the output I am seeing:
```
spec:
  template:
    spec:
      containers:
        - args: -- enable-webhook-validation=true
```
Expected output is:
```
spec:
  template:
    spec:
      containers:
         - args: 
           -- enable-webhook-validation=true
```
What am I doing wrong?

**Comment by mikefarah** [comment]
As far as I cant tell, your expected output isn't actually valid yaml and what `yq` is doing is correct...

**Comment by bobdonat** [comment]
this is the full expected yaml which is valid and is working.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: verrazzano-platform-operator
  namespace: verrazzano-install
  labels:
    app: verrazzano-platform-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: verrazzano-platform-operator
  template:
    metadata:
      labels:
        app: verrazzano-platform-operator
    spec:
      containers:
        - name: verrazzano-platform-operator
          imagePullPolicy: IfNotPresent
          image: IMAGE_NAME
          ports:
            - containerPort: 9443
              name: webhook
              protocol: TCP
          startupProbe:
            httpGet:
              path: /validate-install-verrazzano-io-v1alpha1-verrazzano
              port: webhook
              scheme: HTTPS
              httpHeaders:
                - name: Content-Type
                  value: application/json
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 15
          args:
            - -- enable-webhook-validation=true
```
I was trying to add 
          args:
            - -- enable-webhook-validation=true
