### ISSUE TITLE
Not able to read  ~/.config/gh/hosts.yml 

### ISSUE THREAD

**Issue by shinokada** [mikefarah/yq#666]
I'm sorry for posting this for Bug report, even it isn't a bug.

I am trying to get my user from hosts.yml:

```
cat ~/.config/gh/hosts.yml 
github.com:
  user: shinokada
  oauth_token: 123456789123456789abcde
  git_protocol: ssh
```

I used the following but I'm not getting my user name "shinokada".

```
yq e '"github.com".user' ~/.config/gh/hosts.yml
Error: expected end of expression but found 'user', please check expression syntax
```

When it was v3, following the [doc](https://mikefarah.gitbook.io/yq/upgrading-from-v3) I could use like this:

```
cat ~/.config/gh/hosts.yml | yq r - '"github.com".user'
```

How can I do it with version 4?
