### ISSUE TITLE
Combine multiple sources (i.e. reduce)

### ISSUE THREAD

**Issue by hobti01** [mikefarah/yq#674]
**Please describe your feature request.**
I wish I could use yq to combine a dynamic list of multiple yaml files with merge/merge+append like I can do with jq:
```
jq -s 'reduce .[] as $i (.[0]; . * $i)' *.json
```

**Describe the solution you'd like**
If we have data1.yml like:
```yaml
country:
  name: Australia
  cities:
    - Melbourne
```

data2.yml like:
```yaml
country:
  name: Australia
  cities:
    - Sydney
```

And we run a command:

```bash
# merge with append:
yq eval-all "select(fileIndex == 0) *+ select(fileIndex > 0)" *.yaml
```

it could output the same as this command
```bash
yq eval-all "select(fileIndex == 0) *+ select(fileIndex == 1)" data1.yaml data2.yaml
```

```yaml
country:
  name: Australia
  cities:
    - Melbourne
    - Sydney
```

**Describe alternatives you've considered**
```bash
  cfg=$$.yaml
  cfg_dir=config
  # Create yaml file to merge into.  The file must contain more than comments
  if [[ ! -f "$cfg" ]]; then
    mkdir -p "$(dirname "$cfg")"
    yq eval '.delete = "me"' --null-input > "$cfg"
  fi
  for f in "$cfg_dir"/*; do
    yq eval-all "select(fileIndex == 0) *+ select(fileIndex == 1) | explode(.)" \
      "$cfg" \
      "$f" \
      --inplace
  done
  # Remove noop element
  yq eval 'del(.delete)' "$cfg" --inplace
```

**Additional context**
Maybe there are other use cases, but we only want to merge multiple files with the existing merge/merge+append operators
```bash
# merge without append:
yq eval-all "select(fileIndex == 0) * select(fileIndex > 0)" *.yaml
# use different index as base (is there a use case for this?)
yq eval-all "select(fileIndex == 1) * select(fileIndex <> 1)" *.yaml
```

❤️  for your work
