### ISSUE TITLE
yq renders strange "!!merge" string in a --inplace modified file

### ISSUE THREAD

**Issue by holgerstolzenberg** [mikefarah/yq#680]
Using `yq` in version `4.4.1`.

I am trying to in place modify a given yaml file with the following simplified structure:

```yml
platform:
  artifactDefinitions:
    - artifact: &api-gate
        id: "api-gateway"
        version: "v2.3.2"
    - artifact: &static-resources-provider
        id: static-resources-provider
        version: latest
    - artifact: &global-cfg-provider
        id: global-cfg-provider
        version: latest
  aZone:
    - <<: *api-gate
    - <<: *static-resources-provider
  bZone:
    - <<: *api-gate
    - <<: *static-resources-provider
    - <<: *global-cfg-provider
```

The task is to promote the lastest version to a SHA, I am issuing the following command (in a bash loop for each artifact):

```bash
  yq --inplace -M eval "(.platform.artifactDefinitions[] | select(.artifact.id==\"${the_artifact}\")).artifact.version = \"${sha256}\"" my-file.yml
```

In general it works, but an strange string `!!merge` gets rendered to the `aZone` and `bZone` parts of the docs, the should not be touched at all.

The result looks like:

```yml
platform:
  artifactDefinitions:
    - artifact: &api-gate
        id: "api-gateway"
        version: "v2.3.2"
    - artifact: &static-resources-provider
        id: static-resources-provider
        version: abcdefg
        autoPromote: true
    - artifact: &global-cfg-provider
        id: global-cfg-provider
        version: xyzuvw
        autoPromote: true
  aZone:
    - !!merge <<: *api-gate
    - !!merge <<: *static-resources-provider
  bZone:
    - !!merge <<: *api-gate
    - !!merge <<: *static-resources-provider
    - !!merge <<: *global-cfg-provider
```

Looks like a bug to me, or am I overlooking something.
