### ISSUE TITLE
v4 multiply operator (merge) dropping object level anchors

### ISSUE THREAD

**Issue by nknotts** [mikefarah/yq#694]
**Describe the bug**
When using the V4 yq multiply operator, any anchor associated with an object node appears to be dropped in the output.

Version of yq: 4.4.1
Operating system: macOS 11.1
Installed via: homebrew

**Input Yaml**

a.yml:
```yaml
foo: &foo-alias
  bar: &bar-alias baz
  a: &c-node
    b: &b-node c
```

b.yml:
```yaml
test: &test-alias
  node: &node-alias 1
```

**Command**

```
yq eval-all 'select(fileIndex == 0) * select(fileIndex == 1)' a.yml b.yml
```

**Actual behavior**

```yaml
foo:
  bar: &bar-alias baz
  a:
    b: &b-node c
test:
  node: &node-alias 1
```

**Expected behavior**

```yaml
foo: &foo-alias
  bar: &bar-alias baz
  a: &c-node
    b: &b-node c
test: &test-alias
  node: &node-alias 1
```

**Additional context**
When using yq version 3.4.1 command `yq merge a.yml b.yml`, the expected behavior is generated
