### ISSUE TITLE
Support converting yaml to properties

### ISSUE THREAD

**Issue by eldada** [mikefarah/yq#697]
**Please describe your feature request.**
I have use cases where I want to flatten a yaml into a properties file format.

**Describe the solution you'd like**
If we have data.yml like:

```yaml
a:
  array:
    - name: "element1"
      value: "value1"
    - name: "element2"
      value: "value2"
      sub-array:
        - sub1: "x"
        - sub2: "y"
        - sub3: "z"
```

And we run a command:

```bash
yq eval --prop data.yml'
```

it could output

```
a.array.0.name=element1
a.array.0.value=value1
a.array.1.name=element2
a.array.1.value=value2
a.array.1.sub-array.0.sub1=x
a.array.1.sub-array.1.sub2=y
a.array.1.sub-array.2.sub3=z

```

**Describe alternatives you've considered**
I wrote a [bash script](https://github.com/eldada/yaml-to-properties) to do this with `yq`, but I think this can. (and should) be a built in feature of `yq`.
