### ISSUE TITLE
Fetching and updating block literal

### ISSUE THREAD

**Issue by inianv** [mikefarah/yq#701]
I'm trying to read and update properties under a block literal object in a YAML string

Version of yq: 4.4.2
Operating system: linux
Installed via: binary release

**Input Yaml**

data1.yml:
```yaml
annotations:
  artifacthub.io/changes: |
    - Fixed linting issues.
  artifacthub.io/images: |
    - name: transmission
      image: ghcr.io/linuxserver/transmission:3.00-r0-ls75
```

Reading the block under `artifactory.io/images` seems easy

```bash
yq e '.annotations."artifacthub.io/images"'
```
But I'm not able to update the `name` or `image` tag subsequently, i.e. the following don't work

```bash
yq e '.annotations."artifacthub.io/images"="foo"' data1.yaml
yq e '.annotations."artifacthub.io/images"= { name : "foo"}' data1.yaml   # no longer remains a block literal
yq e '.annotations."artifacthub.io/images" | select(.name == "transmission")' data1.yaml # select also doesn't work
```

If this were JSON like

```json
{
  "annotations": [
    {
      "artifacthub.io/changes": "Fixed linting issues"
    },
    {
      "artifacthub.io/images": {
        "name": "transmission",
        "image: ghcr.io/linuxserver/transmission": "3.00-r0-ls75"
      }
    }
  ]
}
```
I could use `jq` to get the `name` field as below

```bash
jq '.annotations[]."artifacthub.io/images".name'
```

Is there a missing syntax here?
