### ISSUE TITLE
when operator keys is used, unexpected comments are returned

### ISSUE THREAD

**Issue by fredericrous** [mikefarah/yq#718]
**Describe the bug**
when I use `keys`, I get the keys plus some comments in between, not all, not none

Version of yq: 4.5.0
Operating system: mac 11.2
Installed via: homebrew

**Input Yaml**

```yaml
services:
  # some comment
  filebeat:
    image: docker.elastic.co/beats/filebeat:5.6.16
    volumes:
      - ${SHARED_FOLDER}/traefik/filebeat.yml:/usr/share/filebeat/filebeat.yml
#      - /opt/containerlogs:/containerlogs:ro #location to mount logs of containers that don't support stdout
    user: root

  # some other comment
  curator:
    image: stefanprodan/es-curator-cron
```

**Command**
The command you ran:
```
yq e '.services | keys' monitoring.yml
```

**Actual behavior**
return map keys or array indices + comments in between
```yaml
# some comment
- filebeat
# some other comment
- curator
```

**Expected behavior**
return map keys or array indices as described at https://mikefarah.gitbook.io/yq/operators/keys
```yaml
- filebeat
- curator
```
