### ISSUE TITLE
headComment not updating

### ISSUE THREAD

**Issue by sjhx** [mikefarah/yq#723]
**Describe the bug**
Attempting to set a headComment on each object in an array from a value in the object, comment does not change

Version of yq: 4.5.1
Operating system: mac
Installed via: homebrew

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
input.yml:
```yaml
- name: a
  desc: first
- name: b
  desc: second
- name: c
  desc: third
```

**Command**
The command you ran:
```
yq eval '.[] | . headComment=.desc | [.]' input.yaml
```

**Actual behavior**

```yaml
# first
- name: a
  desc: first
# first
- name: b
  desc: second
# first
- name: c
  desc: third
```

**Expected behavior**

```yaml
# first
- name: a
  desc: first
# second
- name: b
  desc: second
# third
- name: c
  desc: third
```
