### ISSUE TITLE
Add ability to specify a style while setting a value

### ISSUE THREAD

**Issue by dlampa** [mikefarah/yq#728]
It would be great to allow setting a value and style in a single operation, e.g:

```bash
yq e '.some.test.value="abc" style="double"' file.yaml
```

instead of:
```bash
yq e '.some.test.value="abc" | .some.test.value style="double"' file.yaml
```

It would also be great if one could apply a style to only the modified values, leaving the rest of the file as is. e.g given a sample yaml:

```yaml
country: "Australia"
value: testvalue
```

doing something like along the line of:
```bash
yq e '.test="quotedvalue" | .key="anotherquotedvalue" | style="double"' sample.yaml
```
would yield:
```yaml
country: "Australia"
value: testvalue
test: "quotedvalue"
key: "anotherquotedvalue"
```

Thanks!
