### ISSUE TITLE
help adding and deleting nested array elements in v4

### ISSUE THREAD

**Issue by olets** [mikefarah/yq#738]
I'm moving my project [git-replay](https://github.com/olets/git-replay) from yq v3 to v4, and am having trouble finding the correct new syntax for two things.

Working with a file like

```yaml
# myfile.yaml
array_1:
  array_2:
    - array_element_1
    - array_element_2
```

in v3 I would use

```shell
yq d myfile.yaml array_1.array_2.array_element_1
```

to delete `array_element_1` and 

```shell
yq w myfile.yaml "array_1.array_2[+]" array_element_3
```

to add `array_element_3`. 

What's the best v4 approach? Thanks!
