### ISSUE TITLE
when interpreting yaml, also comments are recognised

### ISSUE THREAD

**Issue by kreuzwerker-patrick** [mikefarah/yq#748]
When I parse a yaml file with comments and search with yq for keys, also the comments are parsed as keys.
IMHO, comments should not be interpreted as keys.

Version of yq: 4.6.1
Operating system: mac 
Installed via: homebrew

**Input Yaml**
values.yaml:
```yaml
harbor:
  service:
    type: NodePort
    ports:
      http: 80
      https: 443
      notary: 4443
      # test: 9999
      test: 8888
```

**Command**
command 1 - get keys:
```
yq eval ".harbor.service.ports | keys" values.yaml
```

**Actual behavior**

```yaml
- http
- https
- notary
# test: 9999
- test
```

**Expected behavior**

```yaml
- http
- https
- notary
- test
```
The following line should not be part of the output IMHO (as it is commented out):
```yaml
# test: 9999
```

**Additional context**
It is a very similar behaviour for the values as well:
**Command**
command 1 - get keys:
```
yq eval ".harbor.service.ports" values.yaml
```

**Actual behavior**

```yaml
http: 80
https: 443
notary: 4443
# test: 9999
test: 8888
```

**Expected behavior**

```yaml
http: 80
https: 443
notary: 4443
test: 8888
```
The following line should not be part of the output IMHO  (as it is commented out):
```yaml
# test: 9999
```

If it is the idea to also export the comments, 
https://github.com/mikefarah/yq/issues/19

there should at least be a flag to "disable" the output of comments.
(or even the other way around - no comments, but flag to preserve comments in output)
