### ISSUE TITLE
Filtering array only works if matching value comes first

### ISSUE THREAD

**Issue by konstruktiv** [mikefarah/yq#749]
**Describe the bug**

Filtering by array values only works if the matching value comes first. 

**Input Yaml**

data.yml:
```
Items:
  - Item: myitem1
    Tags: 
      - tag1
      - tag2
  - Item: myitem2
    Tags: 
      - tag2
      - tag3
```

**Command**
`yq e '.Items[] | select(.Tags[] == "tag2") | .Item'  data.yml`

**Actual behavior**
Querying for "tag2" from the above YAML example only returns "myitem2".

**Expected behavior**
Querying for "tag2" from the above YAML example should return "myitem1" and "myitem2". This works if "tag2" comes before "tag1" in the first item.

**Additional context**
Is the "==" operator the right one to use here? In jq, I would use `contains` for this purpose. Issue https://github.com/mikefarah/yq/issues/80 asked for supporting the [`contains` function similar to jq](https://stedolan.github.io/jq/manual/#example49) but it was closed without explanation.
