### ISSUE TITLE
Can't eval duplicates

### ISSUE THREAD

**Issue by lstday** [mikefarah/yq#752]
Version of yq: 4.6.1
Operating system: linux
Installed via: binary release

**test.yml**

```yaml
---
data:
  DB_USERNAME: placeholder
  DB_PASSWORD: placeholder
  DB_USERNAME: placeholder
  DB_PASSWORD: placeholder
---
data:
  DB_USERNAME: placeholder
  DB_PASSWORD: placeholder
  APP_SECRET: placeholder
  LOGIN: placeholder
  ANOTHER_PASSWORD: placeholder
  PASSWORD: placeholder
  TOKEN: placeholder
  DB_PASSWORD: placeholder
  DB_USERNAME: placeholder
```

**Command**
```
yq ea '.data."*" = "value"' file.yml```
```
**Actual behavior**

```yaml
data:
  DB_USERNAME: placeholder
  DB_PASSWORD: placeholder
  DB_USERNAME: value
  DB_PASSWORD: value
---
data:
  DB_USERNAME: placeholder
  DB_PASSWORD: placeholder
  APP_SECRET: value
  LOGIN: value
  ANOTHER_PASSWORD: value
  PASSWORD: value
  TOKEN: value
  DB_PASSWORD: value
  DB_USERNAME: value
```

**Expected behavior**

```yaml
data:
  DB_USERNAME: value
  DB_PASSWORD: value
  DB_USERNAME: value
  DB_PASSWORD: value
---
data:
  DB_USERNAME: value
  DB_PASSWORD: value
  APP_SECRET: value
  LOGIN: value
  ANOTHER_PASSWORD: value
  PASSWORD: value
  TOKEN: value
  DB_PASSWORD: value
  DB_USERNAME: value

```
