### ISSUE TITLE
yq can not work on Win10 console.

### ISSUE THREAD

**Issue by gauss02** [mikefarah/yq#758]
**yq can not work on Win10 console**
yq can not work on Win10 console.

Version of yq: 4.6.2
Operating system: windows

**Input Yaml**
sample.yml:
```yaml
# Some doc
a: true
b:
  c: 2
  d: [3, 4, 5]
  e:
    - name: fred
      value: 3
    - name: sam
      value: 4
```

**Command**
```
yq_windows_amd64.exe e ".b.d" sample.yaml
```

**Actual behavior**

```yaml
$yq_windows_amd64.exe e ".b.d" sample.yaml
[
```

![image](https://user-images.githubusercontent.com/1323920/112122920-b682a700-8bfb-11eb-8494-f361e9265b6a.png)

**Expected behavior**

```yaml
$./yq_linux_amd64 e ".b.d" sample.yaml 
[3, 4, 5]                              
```
![image](https://user-images.githubusercontent.com/1323920/112122975-ca2e0d80-8bfb-11eb-96d0-c606471c0677.png)
