### ISSUE TITLE
macOS not showing yml file separators

### ISSUE THREAD

**Issue by ZebraFlesh** [mikefarah/yq#768]
**Describe the bug**
Using 4.6.3 on macOS, yml file separators are not displayed.

Version of yq: 4.6.3
Operating system: macOS 11.2.3
Installed via: brew

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
data1.yml:
```yaml
- key: settings
  value:
    urls:
      url: https://foo.com/
```

data2.yml:
```yaml
- key: settings
  value:
    urls:
      url: https://bar.com/
```

**Command**
The command you ran:
```
yq e '.' -j data1.yml data2.yml
```

**Actual behavior**

```bash
[
  {
    "key": "settings",
    "value": {
      "urls": {
        "url": "https://foo.com/"
      }
    }
  }
]
[
  {
    "key": "settings",
    "value": {
      "urls": {
        "url": "https://bar.com/"
      }
    }
  }
]
```

**Expected behavior**
yml file separator is displayed:

```bash
[
  {
    "key": "settings",
    "value": {
      "urls": {
        "url": "https://foo.com/"
      }
    }
  }
]
---
[
  {
    "key": "settings",
    "value": {
      "urls": {
        "url": "https://bar.com/"
      }
    }
  }
]
```
