### ISSUE TITLE
Merge question

### ISSUE THREAD

**Issue by lyandr** [mikefarah/yq#774]
Hello,

i try to do merge multiples files like this:

file1.yml
```yaml
a:
  b:
    c:
      foo: bar
````

file2.yml
```yaml
a:
  b:
    d:
      bar: foo
````

The result i want is the following:
```yaml
a:
  b:
    c:
      foo: bar
    d:
      bar: foo
````

If i use v3 with merge option it is ok.

If i use v4 with the command `yq ea '. as $item ireduce({}; . *+ $item)'  *.yml` i have the following result:
```yaml
a:
  b:
    c:
      foo: bar
  b:
    d:
      bar: foo
````

I am certainly using wrong the multiple operator... is some one can help me please? The merge in v3 was much more simple :P

Regards

**Comment by mikefarah** [comment]
How strange, that's the right command, I tried locally and it works for me:

```
a:
  b:
    c:
      foo: bar
    d:
      bar: foo

```

The syntax definitely was simpler in v3 ;) - v4 is more powerful but it comes with more complex syntax. Sorry bout that. 

Which version of `yq` are you using?

**Comment by lyandr** [comment]
@mikefarah thank you for your help. my bad but in fact the format of files are the following (it is the nav section of mkdocs.yml file that i want to merge):

```yml
a:
  - b:
    - c:
      - foo: bar
```
```yml
a:
  - b:
    - d:
      - bar: foo
```

with v3.3.4 `yq m file*.yml` the result is:
```yml
a:
  - b:
      - c:
          - foo: bar
        d:
          - bar: foo
```
with 4.6.3 `yq ea '. as $item ireduce({}; . *+ $item)'  file*.yml`the result is:
```yml
a:
  - b:
      - c:
          - foo: bar
  - b:
      - d:
          - bar: foo
```

regards
