### ISSUE TITLE
Merge array doens' work well. Replace always first position

### ISSUE THREAD

**Issue by richard24se** [mikefarah/yq#796]
**Describe the bug**

Note that any how to questions should be posted in the discussion board and not raised as an issue.

Version of yq: 4.7.1
Operating system: linux
Installed via: binary

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
s1.yml:
```yaml
rules:
  - host: hooks.pe
    http:
      paths:
      - backend:
          serviceName: tes1
          servicePort: 5005
        pathType: ImplementationSpecific
  - host: hooks.pe2
    http:
      paths:
      - backend:
          serviceName: test2
          servicePort: 50052
        pathType: ImplementationSpecific
rules2:
  - host: hooks.pe2
    http:
      paths:
      - backend:
          serviceName: tes1
          servicePort: 5010
        pathType: ImplementationSpecific
```

**Command**
The command you ran:
```
yq eval '.rules *d .rules2' s1.yml
```

**Actual behavior**

```yaml
- host: hooks.pe2
  http:
    paths:
      - backend:
          serviceName: tes1
          servicePort: 5010
        pathType: ImplementationSpecific
- host: hooks.pe2
  http:
    paths:
      - backend:
          serviceName: test2
          servicePort: 50052
        pathType: ImplementationSpecific
```

**Expected behavior**

```yaml
- host: hooks.pe
  http:
    paths:
      - backend:
          serviceName: test1
          servicePort: 5005
        pathType: ImplementationSpecific
- host: hooks.pe2
  http:
    paths:
      - backend:
          serviceName: test1
          servicePort: 5010
        pathType: ImplementationSpecific
```

**Additional context**
