### ISSUE TITLE
yq doesn't respect yaml 1.1 merge spec

### ISSUE THREAD

**Issue by philippeboyd** [mikefarah/yq#800]
**Describe the bug**
When calling `yq eval file.yaml -j`, overrides are not being respected according to the [yaml spec](https://yaml.org/type/merge.html)

> Keys in mapping nodes earlier in the sequence override keys specified in later mapping nodes.

Version of yq: **4.7.1 and 3.4.1**
Operating system: **mac**
Installed via: **homebrew**

**Input Yaml**
file.yml:
```yaml
---
- &LEFT { x: 0, y: 2 }
- &BIG { r: 10 }
- &SMALL { r: 1 }

- # Override
  << : [ *BIG, *LEFT, *SMALL]
  x: 1
  label: center/big
```

**Command**
The command you ran:
```
yq eval file.yaml -j
```

**Actual behavior**

```json
[
  {
    "x": 0,
    "y": 2
  },
  {
    "r": 10
  },
  {
    "r": 1
  },
  {
    "r": 1, <-------
    "x": 1,
    "y": 2,
    "label": "center/big"
  }
]
```

**Expected behavior**

```json
[
  {
    "x": 0,
    "y": 2
  },
  {
    "r": 10
  },
  {
    "r": 1
  },
  {
    "label": "center/big",
    "r": 10,  <-------
    "x": 1,
    "y": 2
  }
]
```

**Additional context**
Example and spec located here [https://yaml.org/type/merge.html](https://yaml.org/type/merge.html)

Bug is also present without json conversion

```bash
> yq eval '.[3].r' file.yaml
1 # should output 10
```
