### ISSUE TITLE
Trouble creating new field with existing fields of mixed types

### ISSUE THREAD

**Issue by neothor** [mikefarah/yq#808]
I am trying to set a field which is a combination of both int and str fields.

Let's I have the following yaml
```yaml
a:
  b: 1
  c: "x"
```

My goal is to have an result like
```yaml
a:
  b: 1
  c: "x"
  d: "1x"
```

But using a command like `'.a.d = .a.b + .a.c'` results in '!!int cannot be added to !!str'.
I took a look at the tag and style documentation but can't seem to get that to work.

I expect that this should be possible and that my search skills fall short and a push into the right direction would be very appreciated.
