### ISSUE TITLE
Indentation with `--indent/-I` does not work as expected

### ISSUE THREAD

**Issue by tchupp** [mikefarah/yq#825]
**Describe the bug**

There is an inconsistency between the actually behavior of `--indent/-I` and the described behavior in this doc: https://mikefarah.gitbook.io/yq/usage/output-format#indent

I will provide a number of example commands, but the expected behavior is also in the docs I linked.

Version of yq: tried with v4.6.1 and v4.9.1
Operating system: mac
Installed via: homebrew

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
sample.yml:
```yaml
apples:
  collection:
  - name: Green
  - name: Blue
  favourite: Pink Lady
```

### `-I0`
**Command**
```bash
yq e -I0 '.' sample.yaml
```

**Actual behavior**

```yaml
apples:
    collection:
        - name: Green
        - name: Blue
    favourite: Pink Lady
```

**Expected behavior**
Expected to default to 2.
```yaml
apples:
  collection:
  - name: Green
  - name: Blue
  favourite: Pink Lady
```

### `-I1`
**Command**
```bash
yq e -I1 '.' sample.yaml
```

**Actual behavior**

```yaml
apples:
  collection:
    - name: Green
    - name: Blue
  favourite: Pink Lady
```

**Expected behavior**
Expected to output with 1 indent, lists at the same level as the key.
```yaml
apples:
 collection:
 - name: Green
 - name: Blue
 favourite: Pink Lady
```

### `-I2`
**Command**
```bash
yq e -I2 '.' sample.yaml
```

**Actual behavior**

```yaml
apples:
  collection:
    - name: Green
    - name: Blue
  favourite: Pink Lady
```

**Expected behavior**
Expected to output with 2 indent, lists at the same level as the key.
```yaml
apples:
  collection:
  - name: Green
  - name: Blue
  favourite: Pink Lady
```

### `-I3`
**Command**
```bash
yq e -I3 '.' sample.yaml
```

**Actual behavior**

```yaml
apples:
   collection:
      - name: Green
      - name: Blue
   favourite: Pink Lady
```

**Expected behavior**
Expected to output with 3 indent, lists at the same level as the key.
```yaml
apples:
   collection:
   - name: Green
   - name: Blue
   favourite: Pink Lady
```

### `-I4`
**Command**
```bash
yq e -I3 '.' sample.yaml
```

**Actual behavior**

```yaml
apples:
    collection:
        - name: Green
        - name: Blue
    favourite: Pink Lady
```

**Expected behavior**
Expected to output with 4 indent, list indented 4 from the key.
```yaml
apples:
    collection:
        - name: Green
        - name: Blue
    favourite: Pink Lady
```

Please let me know if more detail is required!
Thank you.
