### ISSUE TITLE
Yq delete not working in v4

### ISSUE THREAD

**Issue by thatsk** [mikefarah/yq#826]
**Describe the bug**
Delete operation not working in yaml file.
yq version 4.9.1
Operating system: linux
Installed via: binary release

**Input Yaml**
```yaml
data1.yml:
profile::generic_mdir::dirs::files:
  "/var/log/example1":
    ensure: directory
    owner: 10001
    group: 10001
    mode: "0755"
  "/etc/logrotate.d/example2":
    ensure: file
    mode: "0644"
    content: |2
      /var/log/this-is-testo-example/jvmgc.log
      /var/log/this-is-testo-example/this-is-testo-validation-service-console.log
      /var/log/this-is-testo-example/access_log*-validation-service*.log  {
         copytruncate
         daily
         rotate 35
         compress
         missingok
         dateext
      }
  "/var/log/example3":
    ensure: directory
    owner: 10001
    group: 10001
    mode: "0755"
  "/etc/logrotate.d/example3":
    ensure: file
    mode: "0644"
    content: |2
      /var/log/this-is-testo-example/jvmgc.log
      /var/log/this-is-testo-example/this-is-testo-validation-service-console.log
      /var/log/this-is-testo-example/access_log*-validation-service*.log  {
         copytruncate
         daily
         rotate 35
         compress
         missingok
         dateext
      }
docker::run_instance::instance:
  example2:
    image: 'servicedefination'
    depend_services:
      - consul
    volumes:
      - '/var/log/example2:/var/log/example2'
      - '/var/tmp:/var/tmp'
    net: host
    env:
      - CONSUL_TOKEN=%{hiera('consul.service_token')}
    stop_wait_time: 30
    remove_container_on_stop: false
  example1:
    image: 'servicedefination2'
    ensure: present
    depend_services:
      - consul
    volumes:
      - '/var/log/example1:/var/log/example1'
      - '/var/tmp:/var/tmp'
    net: host
    env:
      - CONSUL_TOKEN=%{hiera('service_token')}
    stop_wait_time: 30
    remove_container_on_stop: false
```

**Command**
The command you ran:
```
./yq4 eval 'del(.docker::run_instance::instance.example2)' data.yaml
```

**Actual behaviour**

```yaml
Error: Parsing expression: Lexer error: could not match text starting at 1:14 failing at 1:15.
unmatched text: "r"
```

**Expected behaviour**

```yaml
profile::generic_mdir::dirs::files:
  "/var/log/example1":
    ensure: directory
    owner: 10001
    group: 10001
    mode: "0755"
  "/etc/logrotate.d/example2":
    ensure: file
    mode: "0644"
    content: |2
      /var/log/this-is-testo-example/jvmgc.log
      /var/log/this-is-testo-example/this-is-testo-validation-service-console.log
      /var/log/this-is-testo-example/access_log*-validation-service*.log  {
         copytruncate
         daily
         rotate 35
         compress
         missingok
         dateext
      }
  "/var/log/example3":
    ensure: directory
    owner: 10001
    group: 10001
    mode: "0755"
  "/etc/logrotate.d/example3":
    ensure: file
    mode: "0644"
    content: |2
      /var/log/this-is-testo-example/jvmgc.log
      /var/log/this-is-testo-example/this-is-testo-validation-service-console.log
      /var/log/this-is-testo-example/access_log*-validation-service*.log  {
         copytruncate
         daily
         rotate 35
         compress
         missingok
         dateext
      }
docker::run_instance::instance:
  example1:
    image: 'servicedefination2'
    ensure: present
    depend_services:
      - consul
    volumes:
      - '/var/log/example1:/var/log/example1'
      - '/var/tmp:/var/tmp'
    net: host
    env:
      - CONSUL_TOKEN=%{hiera('service_token')}
    stop_wait_time: 30
    remove_container_on_stop: false
```
