### ISSUE TITLE
Any "\n" gets turned into a newline

### ISSUE THREAD

**Issue by brikis98** [mikefarah/yq#828]
**Describe the bug**

If a YAML file contains `"\n"`, it gets replaced with an actual newline. 

Version of yq:  4.9.2
Operating system: mac
Installed via: homebrew

**Input Yaml**

Extracted from a CircleCi `config.yml` (and simplified):

```yaml
jobs:
  test:
    steps:
      - checkout
      - run: 
        command: |
          echo "\nHello, World\n"
```

**Command**
The command you ran:
```
yq eval 'some stuff to change' config.yml
```

The exact change we're applying doesn't matter. 

**Actual behavior**

```yaml
jobs:
  test:
    steps:
      - checkout
      - run: 
        command: |
          echo "
Hello, World
"
```

**Expected behavior**

The YAML file, and especially the `\n`, should be unchanged.

**Comment by mikefarah** [comment]
Can you give a specific example when that happens?

```
yq e '.jobs.test.cat = 3' data.yml
```

Gave:

```
jobs:
  test:
    steps:
      - checkout
      - run:
        command: |-
          echo "\nHello, World\n"
    cat: 3
```
