### ISSUE TITLE
Support other configuration file formats: specifically `properties`

### ISSUE THREAD

**Issue by phreed** [mikefarah/yq#840]
I wish I could use yq to manipulate `properties` files. 
There is a library for reading and writing `properties` https://github.com/magiconair/properties
I can already use yq to work with JSON files. 

## Input File
If we have `data1.properties` file like:
```properties
country = Australia
state = Tasmania
town = Burnie
```
It would be read as if it had been `data1.yaml`.
```yaml
country: Australia
state: Tasmania
town: Burnie
```

If we have `data2.properties` file like:
```properties
country.state.town =  Burnie
```
It would be read as if it had been `data2.yaml`.
```yaml
country: 
  state: 
     town: Burnie
```
Flattening a `yaml` file to properties generally is (almost) certainly lossy. 

## Describe alternatives you've considered
Making use of `sed` to translate specific properties files to yaml.
This involves ...
* replacing the first '=' in each line with ':' for properties -> yaml
* comments are similar enough that they can remain unchanged

Write my own standalone go program for translating between configuration files.
The main issue is related to the several configuration file formats.
* yaml
* json
* xml
* properties
* ini
Where would it all end?
The thought is to introduce a graph abstraction for each format.
https://github.com/gonum/gonum
`yq` is effectively a graph rewriting tool.

**Comment by phreed** [comment]
The on-line tool http://www.allencoders.online/converters/props2yaml gives some insight into how the properties files would be read.
```properties
gremlin.remote.remoteConnectionClass=org.apache.tinkerpop.gremlin.driver.remote.DriverRemoteConnection
gremlin.remote.driver.clusterFile=conf/remote-objects.yaml
gremlin.remote.driver.sourceName=g
```
```yaml
gremlin:
    remote:
        driver:
            clusterFile: conf/remote-objects.yaml
            sourceName: g
        remoteConnectionClass: org.apache.tinkerpop.gremlin.driver.remote.DriverRemoteConnection
```
