### ISSUE TITLE
Add output ability to yq GitHub action

### ISSUE THREAD

**Issue by devorbitus** [mikefarah/yq#844]
**Please describe your feature request.**
What would you think of adding the ability to have output from read operations be available for downstream stages?

I created [this action](https://github.com/devorbitus/yq-action-output) as a test and I think it could be really useful for some folks. If you are interested I could submit a PR for these features to be added to your GH Action.

**Comment by mikefarah** [comment]
I'm still learning github actions - I'd be open to a PR, but I need to understand what it does to accept it. Can you walk me through your entrypoint.sh?

**Comment by devorbitus** [comment]
No problem, the output action is almost identical to your existing action. The main difference is the addition of capturing the output into a shell variable then "setting" the output variable to the value of the shell variable so that the contents of the shell variable can be used in downstream GitHub Action steps. There have also been some debug statements added to help diagnose issues as simply adding a GitHub secret of `ACTIONS_STEP_DEBUG` with a value of `true` will illuminate these values.

```sh
#!/bin/sh -l

echo "::debug::\$cmd: $1"
RESULT=$(eval "$1")
echo "::debug::\$RESULT: $RESULT"
echo ::set-output name=result::"$RESULT"
```

The only real difference from the action.yml perspective is the addition of the output property called `result`

```yml
name: 'yq with output - portable yaml processor'
description: 'create, read, update, delete, merge, validate and do more with yaml'
branding:
  icon: command
  color: gray-dark
inputs:
  cmd:
    description: 'The Command which should be run'
    required: true
outputs:
  result:
    description: "The complete result from the yq command being run"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.cmd }}
```
GitHub Actions allows for outputs to be used in later steps like this...

```yml
      - uses: actions/checkout@v2
      - name: Get SDK Version from config
        id: lookupSdkVersion
        uses: devorbitus/yq-action-output@v1.1
        with:
          cmd: yq eval '.renutil.version' 'config.yml'
      - name: Restore Cache
        id: restore-cache
        uses: actions/cache@v2
        with:
          path: ../renpy
          key:  ${{ runner.os }}-sdk-${{ steps.lookupSdkVersion.outputs.result }}
          restore-keys: |
            ${{ runner.os }}-sdk
      # ... more

```
And since you can look up any YAML information INCLUDING the action's own configuration you can do something like this to lookup the name of the configuration YAML file then lookup a useful piece of information out of the config...

Contents of an example release workflow found at `.github/workflows/release-action.yml` :

```yml
name: Release Workflow

on:
  release:
    types: [created]

jobs:
  build:
    name: Build Automation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get SDK Version from config
        id: lookupSdkVersion
        uses: devorbitus/yq-action-output@v1.0
        with:
          cmd: yq eval '.renutil.version' $(yq eval '.jobs.build.steps[] | select(.id == "buildStep") | .with.config-file' .github/workflows/release-action.yml)
      - name: show yq result
        run: echo Result is ${{ steps.lookupSdkVersion.outputs.result }}
      - name: Restore Cache
        id: restore-cache
        uses: actions/cache@v2
        with:
          path: ../build
          key:  ${{ runner.os }}-sdk-${{ steps.lookupSdkVersion.outputs.result }}
      - name: Build VN Project New
        uses: devorbitus/renconstruct-build-action@v1.0.3
        id: buildStep
        with:
          config-file: 'config.yml'
          android-config-file: '.android.json'
        env:
          RC_KEYSTORE: ${{ secrets.BASE64_ANDROID_KEYSTORE }}
      - name: Cache SDK
        id: save-cache
        if: steps.restore-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v2
        with:
          path: ../build
          key:  ${{ runner.os }}-sdk-${{ steps.lookupSdkVersion.outputs.result }}
```
