### ISSUE TITLE
Unable to convert `str` to `null`

### ISSUE THREAD

**Issue by sezu** [mikefarah/yq#863]
**Describe the bug**
There doesn't seem to be a way to convert a `string` to a `null` value

Version of yq: 4.9.6
Operating system: mac
Installed via: homebrew

**Input Yaml**
test.yml:
```yaml
a: null
b: NULL
c: ""
d: "null"
e: "NULL"
```

**Command**
The command you ran:
```shell
$ yq e '.. tag="!!str"' test.yml
$ yq e '.. tag="!!null"' test.yml
```

**Actual behavior**

```yaml
!!str
a: "null"
b: "NULL"
c: ""
d: "null"
e: "NULL"
```

```yaml
!!null
a: null
b: NULL
c: ""
d: "null"
e: "NULL"
```

**Expected behavior**

```yaml
!!str
a: "null"
b: "NULL"
c: ""
d: "null"
e: "NULL"
```

maybe?
```yaml
!!null
a: null
b: null
c: null
d: null
e: null
```
