### ISSUE TITLE
updating variable based on field results in wrong value

### ISSUE THREAD

**Issue by bobbwest** [mikefarah/yq#870]
**Describe the bug**
Given an array of objects, updating (or adding) an element in the objects from the value of another element results in the wrong value.  It always uses the value of the element from the last object in the array.

Version of yq: 4.9.6
Operating system: linux
Installed via: binary release

**Input Yaml**

data1.yml:
```yaml
- foo: 1 
- foo: 2 
```

**Command**

```
yq eval '.[] | .bar = .foo' data1.yaml
```

**Actual behavior**

```yaml
foo: 1 
bar: 1 
foo: 2 
bar: 1 
```

**Expected behavior**

```yaml
foo: 1 
bar: 1 
foo: 2 
bar: 2 
```
