### ISSUE TITLE
Update value defined in an anchor after explode command seems to update every references

### ISSUE THREAD

**Issue by ThibaultDelaune-pro** [mikefarah/yq#877]
**Describe the bug**
I try to update an object field originally defined in an anchor so I exploded the object but after the update of the field, the anchor is updated too.
If I explode the entire yaml file, after the update of the only field I want to be updated, every passed references of the alias are updated too!
It's like if the explode command was maintaining the link of the alias in some way...

Version of yq: 4.6.3
Operating system: windows executed in a Git Bash terminal
Installed via: binary

**Input Yaml**

test.yaml:
```yaml
item_value: &item_value
  value: true
array:
  - name: item_1
    <<: *item_value
  - name: item_2
    <<: *item_value
```

**Command**
command 1:
```sh
yq e '( .array.[] | select(.name == "item_1") | explode(.) | .value = false ) as $test | .array.[] |= (. as $cur | $cur * ($test | select(.name == $cur.name)))' test.yaml
```
command 2:
```sh
yq e '( explode(.) | .array.[] | select(.name == "item_1") | .value = false ) as $test | explode(.) | .array.[] |= (. as $cur | $cur * ($test | select(.name == $cur.name)))' test.yaml
```

**Actual behavior**

with command 1:
```yaml
item_value: &item_value
  value: false
array:
  - name: item_1
    value: false
  - name: item_2
    !!merge <<: *item_value
```

with command 2:
```yaml
item_value:
  value: false
array:
  - name: item_1
    value: false
  - name: item_2
    value: false
```

**Expected behavior**

The anchor value shouldn't be changed by the update of the field and the item_2 value shouldn't be change neither.
```yaml
item_value:
  value: true
array:
  - name: item_1
    value: false
  - name: item_2
    value: true
```

**Additional context**
I noticed that with the following shorter expression I have the same (bad) result. I would expect the output yaml would only be exploded and not that the values changed:
```sh
yq e '( explode(.) | .array.[] | select(.name == "item_1") | .value = false ) as $test' test.yaml
```

**Comment by ThibaultDelaune-pro** [comment]
I just checked, I have the same behavior with the last version (4.9.6).

**Comment by inianv** [comment]
@mikefarah I was hoping this would work, which didn't

```bash
yq e '(explode(.)) as $d | (.array[] | select(.name=="item_1").value) |= false'
```

**Comment by mikefarah** [comment]
Ooh I see - yes `yq` secretly still has links to the alias (for performance reasons). The best way to break that link is to use merge, as merge always creates a new object:


```
yq e '(.array[] | select(.name=="item_1")) |= explode(.) * {"value": false}' examples/data1.yaml
```

yields:

```
item_value: &item_value
  value: true
array:
  - name: item_1
    value: false
  - name: item_2
    !!merge <<: *item_value

```
