### ISSUE TITLE
Regression on merge operator

### ISSUE THREAD

**Issue by pierrecregut** [mikefarah/yq#880]
Merge empty object with other seems to always give an empty object

Version of yq: >= 4.9.2 (4.9.1 is fine)
Operating system: linux (not tested on other)
Installed via: binary release

**Input Yaml**

data.yml:
```yaml
source:
  a: 1
  b: 2
```

**Command**
The command you ran:
```
yq e '.sink = {} * .source' data.yaml
```

**Actual behavior**

```yaml
source:
  a: 1
  b: 2
sink: {}
```

**Expected behavior**

```yaml
source:
  a: 1
  b: 2
sink:
  a: 1
  b: 2
```

**Additional context**
None
