### ISSUE TITLE
loss a "-" when add an item to envFrom array

### ISSUE THREAD

**Issue by urguide** [mikefarah/yq#881]
**Describe the bug**

Note that any how to questions should be posted in the discussion board and not raised as an issue.

Version of yq: 4.9.6
Operating system: linux
Installed via: binary release

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
data1.yml:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafdrop
spec:
  selector:
    matchLabels:
      app: kafdrop
  replicas: 1
  template:
    metadata:
      labels:
        app: kafdrop
    spec:
      containers:
        - name: kafdrop
          image: obsidiandynamics/kafdrop:latest
          envFrom:
            - configMapRef:
                name: routing-table
            - secretRef:
                name: common
```

**Command**
The command you ran:
```
yq e '.spec.template.spec.containers.[0].envFrom[0].secretRef.name = "gameevent"' data1.yaml
```

**Actual behavior**

```yaml
          envFrom:
            - configMapRef:
                name: routing-table
              secretRef:
                name: gameevent
            - secretRef:
                name: common
```

**Expected behavior**

```yaml
          envFrom:
            - configMapRef:
                name: routing-table
            - secretRef:
                name: gameevent
            - secretRef:
                name: common
```

**Additional context**
