### ISSUE TITLE
Merge two YAMLs when common anchor is defined in 1st one

### ISSUE THREAD

**Issue by kuvaldini** [mikefarah/yq#889]
**Describe the bug**
Got and error when merging two YAMLs when common anchor is defined in 1st one.

Version of yq: 4.9.8
Operating system: mac
Installed via: homebrew

**Input Yaml**
1.yml:
```yaml
x-iroha-base: &service_iroha_base
  image: ${IROHA_IMAGE:-hyperledger/iroha}

services:
  iroha1:
    <<: *service_iroha_base
    env:
      KEY: qwertyasdfgh
```

2.yml:
```yaml
services:
  iroha2:
    <<: *service_iroha_base
    env:
      KEY: zxcvbnqwerty
```

**Command**
The command you ran:
```
yq eval-all 'select(fileIndex==0)  * select(fileIndex == 1)' 1.yml 2.yml
```

**Actual behavior**

```yaml
Error: yaml: unknown anchor 'service_iroha_base' referenced
```

**Expected behavior**

```yaml
x-iroha-base: &service_iroha_base
  image: ${IROHA_IMAGE:-hyperledger/iroha}
services:
  iroha1:
    <<: *service_iroha_base
    env:
      KEY: qwertyasdfgh
  iroha2:
    <<: *service_iroha_base
    env:
      KEY: zxcvbnqwerty
```

**Additional context**

**Comment by mikefarah** [comment]
Yep - the yaml files have to be able to be read independently before attempting any processing, and the second file is missing that anchor.

You can work around this by updating the second doc to:

```
fake: &service_iroha_base

services:
  iroha2:
    <<: *service_iroha_base
    env:
      KEY: zxcvbnqwerty
```

and then running:
yq eval-all 'select(fileIndex==0)  * select(fileIndex == 1) | del(.fake)' 1.yml 2.yml
