### ISSUE TITLE
safelyRenameFile [ERRO] when updating yaml using 4.9.8 yq docker image 

### ISSUE THREAD

**Issue by vldpro** [mikefarah/yq#890]
**Describe the bug**
Seems like the same as https://github.com/mikefarah/yq/issues/884

Version of yq: 4.9.8
Operating system: linux
Installed via: docker

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
data1.yml:
```yaml
images:
  - name: img1
    newName: img1-1
    newTag: 2
  - name: img2
    newName: img2-1
    newTag: 2
  - name: img3
    newName: img3-1
    newTag: 2
```

**Command**
The command you ran:
```
docker run --rm -v "${PWD}":/workdir mikefarah/yq:4.9.8 e ".images.[].newTag = \"abc\"" -i data1.yml
```

**Actual behavior**

Bash error

```sh
14:59:32 safelyRenameFile [ERRO] Failed copying from /tmp/temp054283769 to data1.yml
14:59:32 safelyRenameFile [ERRO] open data1.yml: permission denied
```

**Expected behavior**

```yaml
images:
  - name: img1
    newName: img1-1
    newTag: abc
  - name: img2
    newName: img2-1
    newTag: abc
  - name: img3
    newName: img3-1
    newTag: abc
```

**Additional context**

There is strange behavior. If I run it on localhost, there no error (tested with 4.9.6, 4.9.7, and 4.9.8) but if I run it on GitHub actions, the problem occurs with 4.9.7 and 4.9.8 docker images.
