### ISSUE TITLE
operator ireduce duplicates merge '<<:' operation when used with multiplication 'ireduce({}; . * $item)'

### ISSUE THREAD

**Issue by kuvaldini** [mikefarah/yq#899]
**Describe the bug**
$subj

Version of yq: 4.11.1
Operating system: mac
Installed via: homebrew

**Input Yaml**
data1.yml:
```yaml
jobs:
  build-iroha-ubuntu-debug:
    steps:
      - &step_export_cxx
        env: &step_export_cxx_env
          CC: ${{matrix.CC}}
          CCACHE_PATH: /usr/lib/ccache

  build-iroha-macos:
    steps:
      - <<: *step_export_cxx
        env:
          <<: *step_export_cxx_env
          CCACHE_PATH: /usr/local/opt/ccache/libexec
```

**Command**
The command you ran:
```
yq eval '. as $item ireduce ({}; . * $item)' data1.yml
```

**Actual behavior**

```yaml
jobs:
  build-iroha-ubuntu-debug:
    steps:
      - &step_export_cxx
        env: &step_export_cxx_env
          CC: ${{matrix.CC}}
          CCACHE_PATH: /usr/lib/ccache
  build-iroha-macos:
    steps:
      - !!merge <<: *step_export_cxx
        env:
          !!merge <<: *step_export_cxx_env
          CCACHE_PATH: /usr/local/opt/ccache/libexec
          <<: *step_export_cxx_env
        <<: *step_export_cxx
```

**Expected behavior**

```yaml
jobs:
  build-iroha-ubuntu-debug:
    steps:
      - &step_export_cxx
        env: &step_export_cxx_env
          CC: ${{matrix.CC}}
          CCACHE_PATH: /usr/lib/ccache
  build-iroha-macos:
    steps:
      - <<: *step_export_cxx
        env:
          <<: *step_export_cxx_env
          CCACHE_PATH: /usr/local/opt/ccache/libexec
```
