### ISSUE TITLE
Can't handle multiple yaml documents within one file

### ISSUE THREAD

**Issue by IdanAdar** [mikefarah/yq#9]
Given the following Kubernetes YAML configuration file: 

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: somename
spec:
   revisionHistoryLimit: 5
   minReadySeconds: 10
   strategy:
      type: RollingUpdate
      rollingUpdate:
         maxUnavailable: 0
         maxSurge: 1
   replicas: 1
   template:
      metadata:
         labels:
            microservice: somename
      spec: 
         containers:
         - name: serviceapi
           image: myimage:0.0.6
           ports:
           - containerPort: 8080
           env:
##### ENVIRONMENT VARIABLES
            - name: somename
              valueFrom:
                configMapKeyRef:
                   name: serviceapi-environment-configuration
                   key: somekey
---
apiVersion: v1
kind: Service
metadata:
  name: somename
  labels: 
     microservice: somename
spec:
   type: NodePort
   ports:
   - port: 8080
   selector:
      microservice: somename
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: some-name
  namespace: default
data:
  someData: data
```

This command will work: 

```
./yaml w -i myfile.yaml spec.template.spec.containers[0].image myimage:0.0.19
```

The `image` value will be replaced, however, the file will then change to this:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: somename
spec:
   revisionHistoryLimit: 5
   minReadySeconds: 10
   strategy:
      type: RollingUpdate
      rollingUpdate:
         maxUnavailable: 0
         maxSurge: 1
   replicas: 1
   template:
      metadata:
         labels:
            microservice: somename
      spec: 
         containers:
         - name: serviceapi
           image: myimage:0.0.19
           ports:
           - containerPort: 8080
           env:
##### ENVIRONMENT VARIABLES
            - name: somename
              valueFrom:
                configMapKeyRef:
                   name: serviceapi-environment-configuration
                   key: somekey
```

As you can see, the Services and ConfigMap sections (denoted with `---`) have disappeared.

**Comment by mikefarah** [comment]
Currently this uses go-yaml to parse yaml files and that does not yet support multiple yaml documents embedded into a separate file (https://github.com/go-yaml/yaml/issues/232) :(

**Comment by IdanAdar** [comment]
Too bad... hopefully this will be added - soon!

**Comment by IdanAdar** [comment]
What are the chances of a workaround?

**Comment by mikefarah** [comment]
Only thing I can think of is:
- preprocessing the document before hand to split it out into seperate docs
- running the update as per usual on the selected doc number (provided via the cli)
- post processing to stitch the documents back together

If I had more time I'd look into it, happy to review and merge a pull request though....

**Comment by therealplato** [comment]
go-yaml recently merged a fix to their development branch. Really looking forward to this feature for scripting with kube manifests!

**Comment by mikefarah** [comment]
oh neat :)

**Comment by JeanMertz** [comment]
was looking for this as well, looks like this is the fix that makes this now possible:

https://github.com/go-yaml/yaml/pull/301

**Comment by IdanAdar** [comment]
Does this require updating the go version in yq?
@mikefarah

**Comment by therealplato** [comment]
@mikefarah what needs to be done to resolve this issue? i need it so badly! i'm happy to try and implement it, but not being familiar with either codebase, i could use a hint.

API ideas:
Given `a.yml` is:
```
---
foo: 1
---
bar: 2
```
When I type `yq read a.yml foo`
Then I expect output `foo: 1`
When I type `yq read a.yml bar`
Then I expect output `bar: 2`

Given `b.yml` is:
```
---
foo: 1
---
foo: 2
```
When I type `yq read b.yml foo`
Then I expect output 
```
---
foo: 1
---
foo: 2
```

I haven't used `yq write` so I don't have an expectation for the behavior when invoke `yq write` on a multi-document file.

A totally separate idea: For multi-document use, treat the document number as a top level key that vanishes: 
```
yq read b.yml ---0.foo
foo: 1
```

**Comment by therealplato** [comment]
Updated ideas:
```
// read second document
yq read document.yaml @1.a.b.c
yq read document.yml @1 a.b.c
```
I haven't used `new, merge, write` commands. Any ideas based on your workflows @IdanAdar @JeanMertz ?

**Comment by svnpenn** [comment]
https://github.com/mikefarah/yq/issues/147

**Comment by svnpenn** [comment]
https://github.com/mikefarah/yq/issues/144

**Comment by svnpenn** [comment]
https://github.com/mikefarah/yq/issues/16

**Comment by svnpenn** [comment]
https://github.com/mikefarah/yq/pull/137

**Comment by ctaggart** [comment]
You can also use the [log file example](http://yaml.org/spec/1.2/spec.html#id2761803) in the yaml 1.2 spec for testing. I need this bad for all kubernetes tools like kubectl and helm.

**Comment by mikefarah** [comment]
Just started working on this - multi read is working in master, though I haven't built a release yet :)

I will create a release once write is working too.

**Comment by ctaggart** [comment]
Awesome! I haven't checked it out yet. Was thinking on the design that given the spec example, it currently reads the first document, so it acts like `cat log.yaml | yq -d 0 r -`. It would be nice to have a `--documentcount` too. I'd stick with zero-based index like bash/go and most languages. What design did you go with?

``` yaml
---
Time: 2001-11-23 15:01:42 -5
User: ed
Warning:
  This is an error message
  for the log file
---
Time: 2001-11-23 15:02:31 -5
User: ed
Warning:
  A slightly different error
  message.
---
Date: 2001-11-23 15:03:17 -5
User: ed
Fatal:
  Unknown variable "bar"
Stack:
  - file: TopClass.py
    line: 23
    code: |
      x = MoreObject("345\n")
  - file: MoreClass.py
    line: 58
    code: |-
      foo = bar
```

```
$ cat log.yaml | yq r -
Time: 2001-11-23 15:01:42 -5
User: ed
Warning: This is an error message for the log file
```
