### ISSUE TITLE
Cannot get double quotes to work V4

### ISSUE THREAD

**Issue by mailsanchu** [mikefarah/yq#902]
my input file is like the following 

```
spec:
  template:
    spec:
      containers:
        - name: edge-2-3-0
          resources:
            limits:
              cpu: '8'
              memory: 12.5Gi
            requests:
              cpu: '8'
              memory: 12.5Gi
          livenessProbe:
            initialDelaySeconds: 200
```

I am running this command to get the double quotes 
MEM=12.5
yq -i eval '.spec.template.spec.containers[0].resources.limits.memory=strenv(MEM) +"Gi"' /home/svarkey/tmp/test.yml
yq -i eval '.spec.template.spec.containers[0].resources.requests.memory=strenv(MEM) +"Gi"' /home/svarkey/tmp/test.yml

output is given below 

```
spec:
  template:
    spec:
      containers:
        - name: edge-2-3-0
          resources:
            limits:
              cpu: '8'
              memory: '12.5Gi'
            requests:
              cpu: '8'
              memory: '12.5Gi'
          livenessProbe:
            initialDelaySeconds: 200
```

As you can see it is single quotes but I want **double quotes** around memory. Is it possible?
