### ISSUE TITLE
yq modifies the whitespace during inline update 

### ISSUE THREAD

**Issue by varshachandanb** [mikefarah/yq#904]
Yaml File: test.yaml
```
deployment:  
  container:  
     name:  test-container   
     image:  test-image 

```

Command:
```
ya eval -i '.deployment.container.name = new-container' test.yaml 
```

Expected:
```
deployment:  
  container:  
     name:  new-container   
     image:  test-image 

```

Got: (Does not preserve whitespace or newlines)
```
deployment:
  container:
     name:  new-container  
     image:  test-image
```

Is there a flag that can be used to prevent yq from formatting the yaml file ? If not, could you please provide one.
