### ISSUE TITLE
Permission denied when trying to parse a file as the root user

### ISSUE THREAD

**Issue by senyahnoj** [mikefarah/yq#917]
**Describe the bug**

I have a yaml document which is owned by user "baa" and has chmod 644 permissions

```
-rw-r--r-- 1 baa baa 123 Aug 13 06:29 Chart.yaml
```
As the "baa" user, can run

```bash
yq e '.version' Chart.yaml
```
.. and it correctly extracts the 'version' value:

```bash
# Running as user 'baa'
yq e '.version' Chart.yaml 
2.0.0
```
However, when I become the root user it tells me 'permission denied'

```bash
# Running as 'root' 
yq e '.version' Chart.yaml 
Error: open Chart.yaml: permission denied
```

The permissions allow root user can read the file under normal circumstances (after all I can 'cat' the file as root) so I would expect yq to be able to parse it.

I have tried various ways of becoming root/running under root and get the same error.

```bash
sudo -i
yq e '.version' Chart.yaml
sudo su -
yq e '.version' Chart.yaml
sudo bash
/snap/bin/yq e '.version' Chart.yaml
```

Version of yq: 4.11.2
Operating system: linux (tested on both Ubuntu 18.02 and Debian 10)
Installed via: snap

**Input Yaml**

Chart.yaml

```yaml
apiVersion: v2
appVersion: 1.0.0
description: Example HELM chart
name: Charty McChartFace
type: application
version: 2.0.0
```
