### ISSUE TITLE
preseve the old data and overwrite the new data

### ISSUE THREAD

**Issue by thatsk** [mikefarah/yq#918]
**Please describe your feature request.**
A clear and concise description of what the request is and what it would solve. 
For example, I wish I could use yq to [...] extract the data and append or overwrite the data in the new yaml file or existing yaml file.

**Describe the solution you'd like**
If we have data1.yml like:

```yaml
service1:
    name: service1
    count: 1
    nodetype: ath
    port: 8105
    portname: '_service1'
    healthcheck: '/loadbalancer/health'
    fluentd: "false"
    externallogback: "false"
    locallogback: "true"
    urlprefix: 'service1/monitoring/health'
    resource: medium
    env_vars:
      - key: service_token
service2:
  name: service2
  count: 1
  nodetype: ath
  port: 8105
  portname: 'service2'
  healthcheck: '/loadbalancer/health'
  fluentd: "false"
  externallogback: "false"
  locallogback: "true"
  urlprefix: 'service/monitoring/health'
  resource: medium
  env_vars:
    - key: service_token
service3:
  name: service3
  count: 1
  nodetype: liv
  port: 8105
  portname: '_service3'
  healthcheck: '/loadbalancer/health'
  fluentd: "false"
  externallogback: "false"
  locallogback: "true"
  urlprefix: 'service3/monitoring/health'
  resource: medium
  env_vars:
    - key: service_token
```

And we run a command:

```bash
cat data.yaml | yq4 e '.service1' - | sponge data2.yaml
```

it could output

```yaml
service1:
    name: service1
    count: 1
    nodetype: ath
    port: 8105
    portname: '_service1'
    healthcheck: '/loadbalancer/health'
    fluentd: "false"
    externallogback: "false"
    locallogback: "true"
    urlprefix: 'service1/monitoring/health'
    resource: medium
    env_vars:
      - key: service_token
```

Real Output we want.
```yaml
key1: value1
key2: value2
service1:
    name: service1
    count: 1
    nodetype: ath
    port: 8105
    portname: '_service1'
    healthcheck: '/loadbalancer/health'
    fluentd: "false"
    externallogback: "false"
    locallogback: "true"
    urlprefix: 'service1/monitoring/health'
    resource: medium
    env_vars:
      - key: service_token
```

**Describe alternatives you've considered**
I was trying to place In variable but didn't work.

**Additional context**
