### ISSUE TITLE
Merging documents strips some comments

### ISSUE THREAD

**Issue by tomlankhorst** [mikefarah/yq#919]
**Describe the bug**
Merging documents strips comments

Version of yq: 4.9.6 (correct), 4.11.2 (incorrect)
Operating system: Ubuntu 20.04
Installed via: binary release

**Input Yaml**
a.yml:
```yaml
# a1
a: 1
# a2
```
b.yml:
```yml
#b1 
b: 2
#b2
```

**Command**
The command you ran:
```
yq eval-all 'select(fileIndex == 0) * select(fileIndex == 1)' a.yml b.yml
```

**Actual behavior (4.11.2)**

```yaml
a: 1
# a2

b: 1
# b2
```

**Expected behavior (4.9.6)**

```yaml
# a1
a: 1
# a2

# b1
b: 1
# b2
```

**Comment by mikefarah** [comment]
Just released 4.12.0 it now does this: 

```yaml
# a1
a: 1
# a2

b: 2
#b2
```

But still missing `#b1`. The issue with b1 is that the underlying yaml parser puts that at the document node level, not at the `.b` level. On merging, the default merging logic does not set the comment at a node if a comment is already there, which it is, `# a1`. Even if it merged it in, it would be at the top of the merged document...
