### ISSUE TITLE
quotes removed for particular string

### ISSUE THREAD

**Issue by thatsk** [mikefarah/yq#923]
**Describe the bug**
i want to keep quotes for on off string in yaml files while formatting.

**Input Yaml**
data1.yml:
```yaml
test1: "ON"
key2: "OFF"
meos: '"kunal"'
assd: '"abs"'
```

**Command**
The command you ran:
```
yq4 eval --unwrapScalar=false --prettyPrint test.yaml
```

**Actual behavior**

```yaml
test1: ON
key2: OFF
meos: '"kunal"'
assd: '"abs"'

```

**Expected behavior**

```yaml
test1: "ON"
key2: "OFF"
meos: '"kunal"'
assd: '"abs"'
```
