### ISSUE TITLE
Splat doesn't work for array

### ISSUE THREAD

**Issue by ggolub** [mikefarah/yq#924]
**Describe the bug**
The splat operator doesn't work with arrays.

Version of yq: 4.12.0
Operating system: windows
Installed via: binary release

**Input Yaml**
example.yml:
```yaml
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-frontend
        image: myrepo.azurecr.io/myapp-frontend:latest
      - name: myapp-backend
        image: myrepo.azurecr.io/myapp-backend:latest
```

**Command**
# works correctly using integer:
```
yq eval '.spec.template.spec.containers[0].image' ./example.yaml
myrepo.azurecr.io/myapp-frontend:latest
yq eval '.spec.template.spec.containers[1].image' ./example.yaml
myrepo.azurecr.io/myapp-backend:latest
```

# fails with error using splat:
```
yq eval '.spec.template.spec.containers[*].image' ./example.yaml
Error: '' expects 2 args but there is 1
```
