### ISSUE TITLE
GitHub Actions edit inplace file permission denied

### ISSUE THREAD

**Issue by cabrinha** [mikefarah/yq#926]
**Describe the bug**
Trying to replace a string inside of a file, using a GitHub Action run.

Getting permission denied and having a hard time figuring out how to feed the replacement value in as an environment variable.

Version of yq: 4.12.0
Operating system: linux / docker / github action runner
Installed via: docker

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
data1.yml:
```yaml
grafana:
  podAnnotations:
    dashboards_checksum: 587679412b6e54d6cbbb5b36f5069213604a3c82
```

**Command**
The command you ran:
```
checksum=$(cat charts/grafana-dashboards/files/dashboards/*/* | sha1sum | cut -d' ' -f1) \
  yq e '.grafana.podAnnotations.dashboards-checksum = env(checksum)' -i ./charts/grafana-dashboards/values.yaml
```

**Actual behavior**
00:05:34 safelyRenameFile [ERRO] Failed copying from /tmp/temp530988650 to ./charts/grafana-dashboards/values.yaml
00:05:34 safelyRenameFile [ERRO] open ./charts/grafana-dashboards/values.yaml: permission denied

**Expected behavior**

```yaml
grafana:
  podAnnotations:
    dashboards_checksum: c63694e5bd8995c6eb03d808476fd68fa3dd322a
```

**Additional context**
Seems like it's kinda hard to pass in environment variables as values inside of GitHub Actions. Also kinda weird that I'm getting permission denied on files that `yq` should have access to.
