### ISSUE TITLE
yq eval edits formatting of not touched lines

### ISSUE THREAD

**Issue by pavel1yakimovich** [mikefarah/yq#927]
**Describe the bug**
yq eval edits formatting of not touched lines even when specify -I2 flag
I need to save original formatting

Version of yq: 4.12.1
Operating system: mac
Installed via: homebrew

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
data1.yml (untouched lines):
```yaml
a:
- arr: 42
  b: node
  c: node
```

actual:
data2yml:
```yaml
a:
  - arr: 42
    b: node
    c: node
```

expected:
to be exactly as in data1

**Command**
The command you ran:
```
yq eval '*some command*' -i -I2 data1.yaml
```

**Additional context**
