### ISSUE TITLE
Allow string operations on nodes with custom tags

### ISSUE THREAD

**Issue by Slooz** [mikefarah/yq#933]
**Please describe your feature request.**
I have to modify a [CloudFormation template](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-guide.html) that uses [intrinsic functions](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference.html). Intrinsic functions are prepended with an exclamation point. yq treats the intrinsic functions as custom tags and prevents me from performing string operations.

**Describe the solution you'd like**
For example:
```yaml
Resources:
  S3Bucket:
    Type: AWS::CloudFormation::Stack
    Properties:
      BucketName: !Ref MyBucketName
```

And we run a command:

```zsh
yq eval '.Resources.S3Bucket.Properties.BucketName += "A"'
```

it would output

```yaml
Resources:
  S3Bucket:
    Type: AWS::CloudFormation::Stack
    Properties:
      BucketName: !Ref MyBucketNameA
```

**Describe alternatives you've considered**
Convert to a `!!str` and then back to a `!Ref`

**Additional context**
yq shows an error:

> Error: !Ref cannot be added to !!str

I think yq should act as if custom tags were strings. From my point of view, `!Ref MyBucketName` may as well just be a string, but yq treats `!Ref` as a tag and `MyBucketName` as a value of type `!Ref`, which prevents me from performing any string operations, even though `!Ref MyBucketName` is really just a string.
