### ISSUE TITLE
Swapping values inside an array of objects not working

### ISSUE THREAD

**Issue by inianv** [mikefarah/yq#934]
I'm trying to swap values between two objects in an array, but the resulting swap is not working as expected.

Version of yq: 4.12.2
Operating system: mac
Installed via: homebrew.

**Input Yaml**

```yaml
array:
  - foo: "foo1"
    bar: 1.0
    zoo: "zoo1"
  - foo: "foo2"
    bar: 2.0
    zoo: "zoo2"
```
Attempts

```bash
yq e '.array[0].bar as $x | .array[1].bar as $y | .array[1].bar = $x | .array[0].bar = $y' yaml
```

or

```bash
yq e '.array[0].bar as $t | .array[0].bar = .array[1].bar | .array[1].bar = $t' yaml
```

should work, but it doesn't.

**Actual behavior**

```yaml
array:
  - foo: "foo1"
    bar: 2.0
    zoo: "zoo1"
  - foo: "foo2"
    bar: 2.0
    zoo: "zoo2"
```

**Expected behavior**

```yaml
array:
  - foo: "foo1"
    bar: 2.0
    zoo: "zoo1"
  - foo: "foo2"
    bar: 1.0
    zoo: "zoo2"
```

**Additional context**

The same works fine with `jq` though when dealing with JSON

```bash
yq e . yaml2 -j | jq '.array[0].bar as $t | .array[0].bar = .array[1].bar | .array[1].bar = $t'
```

But `jq` truncates the floats, but thats a different issue though.
