### ISSUE TITLE
[question] howto assign key in array of maps with another key?

### ISSUE THREAD

**Issue by Slach** [mikefarah/yq#939]
```
yq (https://github.com/mikefarah/yq/) version 4.12.2
```

Input yaml
```yaml
spec:
  additionalPrinterColumns:
  - name: version
    type: string
    description: Operator version
    priority: 1 # show in wide view
    jsonPath: .status.version
  - name: clusters
    type: integer
    description: Clusters count
    priority: 0 # show in standard view
    jsonPath: .status.clusters
```

need to setup `JSONPath` with value from `jsonPath` the same array map
and would get
```yaml
spec:
  additionalPrinterColumns:
  - name: version
    type: string
    description: Operator version
    priority: 1 # show in wide view
    jsonPath: .status.version
    JSONPath: .status.version
    
  - name: clusters
    type: integer
    description: Clusters count
    priority: 0 # show in standard view
    jsonPath: .status.clusters
    JSONPath: .status.clusters
```

I tried
```
yq eval -e --inplace '.spec.additionalPrinterColumns[].JSONPath = .spec.additionalPrinterColumns[].jsonPath' 
```
but it setup all array items map key `JSONPath` with value of `jsonPath` from latest array element `.status.clusters`
