### ISSUE TITLE
merge files as v3 with yq v4

### ISSUE THREAD

**Issue by jerome-laforge** [mikefarah/yq#941]
With yq v3, I am able to merge with append yaml files with `yq m -a $(ls *.yaml)`, how can do the same with yq v4?

Thx in adv

**Comment by mikefarah** [comment]
This should do it https://mikefarah.gitbook.io/yq/operators/multiply-merge#merge-appending-arrays

**Comment by jerome-laforge** [comment]
Thank @mikefarah but when I try this: 
```bash
$ yq e '.a *+ .b' $(ls *.yaml)
Error: Cannot multiply !!null with !!null
```

Any clue?

**Comment by mikefarah** [comment]
Not without sample docs...

**Comment by jerome-laforge** [comment]
Sorry for the delay, and thank @mikefarah again for your support

Please find an example with only two files to merge (but in reality, I have more than 2 files):

file1.yaml contains:
```yaml
map:
  "key":
    array:
      - item: 1
```

file2.yaml contains:
```yaml
map:
  "key":
    array:
      - item: 2
```

With yq v3 and `yq m -a *.yaml` give (this is the expected merged result):
```yaml
map:
  "key":
    array:
      - item: 1
      - item: 2
```

Unfortunately, yq v4 (as it doesn't support merge with append) and `yq ea '. as $item ireduce ({}; . * $item )' *.yaml` give:
```yaml
map:
  "key":
    array:
      - item: 2
```

Unfortunately, yq v4, if I use `yq e '.a *+ .b' *.yaml` gives:
```
Error: Cannot multiply !!null with !!null
```
