### ISSUE TITLE
Add sort_by operator

### ISSUE THREAD

**Issue by 030** [mikefarah/yq#947]
```
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        a: "true"
    - matchLabels:
        c: "true"
    - matchLabels:
        b: "true"
```

**Attempts**

* `yq eval 'sortKeys(.)' some-file.yaml`
* `yq eval 'sortKeys(..)' some-file.yaml`

**Comment by mikefarah** [comment]
Ah I don't think you can do that in `yq` yet - looking at `jq` it has a `sort_by` operator that `yq` needs.

**Comment by 030** [comment]
@mikefarah Could you give some pointers regarding the implementation? What file should I change or should I create a new go file to implement this feature? I would like to try to implement this feature.

**Comment by mikefarah** [comment]
Awesome! You'll need to create new files

- operator_sort_by.go
- operator_sort_by_test.go

The code should be something like:

```
// context represents the current matching nodes in the expression pipeline
//expressionNode is your current expression (sort_by)
func sortByOperator(d *dataTreeNavigator, context Context, expressionNode *ExpressionNode) (Context, error) {
      // crossFunction will basically do a set multiplication...don't worry too much about it
	return crossFunction(d, context, expressionNode, sortByFunc, false)
}

// here is where the guts need to go
func sortByFunc(d *dataTreeNavigator, context Context, lhs *CandidateNode, rhs *CandidateNode) (*CandidateNode, error) {
	// now we need to sort LHS by RHS
}
```

Have a look at other operator code like `alternative`, `contains` etc for examples. Note that the tests generate the documentation which I then publish at https://mikefarah.gitbook.io/yq/.

The `jq` docs are usually a good spot to get the first couple of tests to try to replicate https://stedolan.github.io/jq/manual/#sort,sort_by(path_expression).

Note that `sort` is basically just `sort_by(.)`

**Comment by mikefarah** [comment]
How are you going with this @030 ?

**Comment by mikefarah** [comment]
How are you going with this? I'd like to put it in - if you don't have time for it perhaps I can finish what you've started?

**Comment by 030** [comment]
I started to write some code in a separate repository with a random name generated by github https://github.com/030/legendary-pancake/tree/1-sort-by I hope to continue with this weekend. Perhaps you could have a look? I am struggling how to make it more generic so it is able to sort all kind of yaml structures.

**Comment by mikefarah** [comment]
Happy to look - that link didn't work for me though. If you like, why don't you raise a PR and I can review what you've done so far

**Comment by janeklb** [comment]
+1 on this feature - there's an older request for it here too: https://github.com/mikefarah/yq/issues/75

**Comment by mikefarah** [comment]
@030 I don't have access to that link -

**Comment by 030** [comment]
@mikefarah  I changed the repo to public.

**Comment by mikefarah** [comment]
Sorry @030 I don't understand how that would work with `yq` - I've gone ahead and implemented `sort_by` as I've had several requests for it. Feel free to look at the codes.

Release in 4.16.1

**Comment by 030** [comment]
Perhaps you could refer to the tickets in the commits.

**Comment by 030** [comment]
```
yq --version
yq (https://github.com/mikefarah/yq/) version 4.14.2
sudo snap refresh yq
snap "yq" has no updates available
```

**Comment by 030** [comment]
Given some-file.yaml:
```
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        olm.opgroup.permissions/aggregate-to-abc-admin: "true"
    - matchLabels:
        olm.opgroup.permissions/aggregate-to-zef-admin: "true"
    - matchLabels:
        olm.opgroup.permissions/aggregate-to-hgjadmin: "true"
    - matchLabels:
        olm.opgroup.permissions/aggregate-to-aaa-admin: "true"
```

and

./yq4  eval 'sortKeys(...)' some-file.yaml

returns:

Error: 0 - [] is not an array
