### ISSUE TITLE
Inplace array merge causing duplicates instead of replace

### ISSUE THREAD

**Issue by mssanjay** [mikefarah/yq#948]
**Describe the bug**
I am trying to merge(replace) array elements by key or name. This is causing duplicates instead of replace.
As explained below, my expection is that the YQ inplace merge should overwrite array elements by matching "service.[].name"

Version of yq: 4.13.2
Operating system: windows
Installed via: binary release

**Input Yaml**
service1.yml:
```yaml
_format_version: "1.1"
services:
  - name: service1
    url: https://service11.microservice.net
plugins:
  - name: prometheus
```

service2.yml:
```yaml
_format_version: "1.1"
services:
  - name: service2
    url: https://service22.microservice.net
plugins:
  - name: prometheus
```
master.yml:
```yaml
_format_version: "1.1"
services:
  - name: service1
    url: https://service1.microservice.net
  - name: service2
    url: https://service2.microservice.net
  - name: service3
    url: https://service3.microservice.net
  - name: service4
    url: https://service4.microservice.net    
plugins:
  - name: prometheus
```

**Command**
The command you ran:
```
yq eval-all '. as $item ireduce ({}; . *+ $item)' --inplace master.yml .\service1.yml .\service2.yml
```

**Actual behavior**

```yaml
_format_version: "1.1"
services:
  - name: service1
    url: https://service1.microservice.net
  - name: service2
    url: https://service2.microservice.net
  - name: service3
    url: https://service3.microservice.net
  - name: service4
    url: https://service4.microservice.net
  - name: service1
    url: https://service11.microservice.net
  - name: service2
    url: https://service22.microservice.net
plugins:
  - name: prometheus
  - name: prometheus
  - name: prometheus
```

**Expected behavior**

```yaml
_format_version: "1.1"
services:
  - name: service1
    url: https://service11.microservice.net
  - name: service2
    url: https://service22.microservice.net
  - name: service3
    url: https://service3.microservice.net
  - name: service4
    url: https://service4.microservice.net    
plugins:
  - name: prometheus
```

**Additional context**
I like to overwrite array elements with service1.yml and service2.yml "services".

Thanks
Sanjay

**Comment by mikefarah** [comment]
Just use `*` instead of `*+` 

`*+` is specifically meant to append arrays :)

**Comment by mssanjay** [comment]
If I use just *, only the array element from service2.yaml is added. Other elements are lost.

yq eval-all '. as $item ireduce ({}; . * $item)' master.yaml .\service1.yaml .\service2.yaml

Here is the output.
```
_format_version: "1.1"
services:
  - name: service2
    url: https://service22.microservice.net
plugins:
  - name: prometheus
```
Expected:
```
_format_version: "1.1"
services:
  - name: service1
    url: https://service11.microservice.net
  - name: service2
    url: https://service22.microservice.net
  - name: service3
    url: https://service3.microservice.net
  - name: service4
    url: https://service4.microservice.net    
plugins:
  - name: prometheus
 ```
