### ISSUE TITLE
Select not returning results if the first match is false

### ISSUE THREAD

**Issue by mikefarah** [mikefarah/yq#958]
**Describe the bug**

Note that any how to questions should be posted in the discussion board and not raised as an issue.

Version of yq: 4.13.3

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
data1.yml:
```yaml
servers:
  - name: server-1
    tags:
      - foo
  - name: server-2
    tags:
      - bar
  - name: server-3
    tags:
      - foo
      - bar
```

**Command**
The command you ran:
```
yq e '.servers[] | select(.tags[] | contains("bar")) | .name' test.yaml
```

**Actual behavior**

```yaml
server-2
```

**Expected behavior**
server-2
server-3
```yaml
this: should really work
but: it strangely didn't
```

**Additional context**
