### ISSUE TITLE
Split file operator

### ISSUE THREAD

**Issue by stevehipwell** [mikefarah/yq#966]
**Please describe your feature request.**
Given a file containing multiple documents separated by `---` I would like to be able to create a new file from each document with a templated name.

**Describe the solution you'd like**
If we have data1.yml like:
(please keep to around 10 lines )

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: alertmanagerconfigs.monitoring.coreos.com
spec:
  group: monitoring.coreos.com
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: alertmanagers.monitoring.coreos.com
spec:
  group: monitoring.coreos.com
```

And we run a command:

```bash
yq eval-split 'crd-${.metadata.name}.yaml' sample.yaml
```

it could save 2 files

crd-alertmanagers.monitoring.coreos.com.yaml
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: alertmanagerconfigs.monitoring.coreos.com
spec:
  group: monitoring.coreos.com
```

crd-alertmanagerconfigs.monitoring.coreos.com.yaml
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: alertmanagers.monitoring.coreos.com
spec:
  group: monitoring.coreos.com
```

**Describe alternatives you've considered**
We could use awk.

**Additional context**
n/a
