### ISSUE TITLE
YAML to JSON removes null in list

### ISSUE THREAD

**Issue by braderhart** [mikefarah/yq#985]
**Describe the bug**
Trying to convert YAML file to JSON for a JSON Schema file. I am trying to convert a `null` value in a list to a literal `null` in JSON, but it simply removes it. It appears this works in a map just fine.

Version of yq: 4.13.5
Operating system: Linux
Installed via: Arch Repo

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
values.schema.yaml:
```yaml
metricsExporter:
  description: The metrics exporter to use.
  enum:
  - ""
  - gcp
  - null
  - prometheus
  default: ""
```

**Command**
The command you ran:
```
yq eval --output-format json values.schema.yaml > values.schema.json
```

**Actual behavior**

values.schema.json:
```json
    "metricsExporter": {
      "description": "The metrics exporter to use.",
      "enum": [
        "",
        "gcp",
        "prometheus"
      ],
      "default": ""
    },
```
**Expected behavior**

values.schema.json:
```json
    "metricsExporter": {
      "description": "The metrics exporter to use.",
      "enum": [
        "",
        "gcp",
        null,
        "prometheus"
      ],
      "default": ""
    },
```
