### ISSUE TITLE
How do I add variables to expression

### ISSUE THREAD

**Issue by moluzhui** [mikefarah/yq#988]
**Describe the bug**

Note that any how to questions should be posted in the discussion board and not raised as an issue.

Version of yq: 4.14.1
Operating system: mac/linux/windows/....
Installed via: docker/binary release/homebrew/snap/...

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
data1.yml:
```yaml
test1: test1
test2:
  subtest2: test2
```

**Command**
The command you ran:
```
test3="test3"
yq e -i '.test2.subtest2= \"${test3}\"' data1.yml
```

**Actual behavior**

```bash
Error: Parsing expression: Lexer error: could not match text starting at 1:18 failing at 1:19.
        unmatched text: "\\"
```

**Expected behavior**

```yaml
test1: test1
test2:
  subtest2: test3
```

**Additional context**
Centos 7
