### ISSUE TITLE
Declared field ordering messed up upon merging

### ISSUE THREAD

**Issue by john-wd** [mikefarah/yq#991]
**Describe the bug**
When I am merging fields on fields and arrays, the ordering of attributes is not been kept. So attributes declared before an array to be merged gets declared last. This means that I cannot forward declare a 

Version of yq: 4.13.3
Operating system: mac
Installed via: homebrew

**Input Yaml**
one.yml:
```yaml
service:
  - name: aservice
    config:
      some_config: hey
      another_config: test
```

two.yml:
```yaml
some_config: &some_config

field:
  test: true

service:
  - name: another-service
    config:
      some_config: *some_config
      another_config: another_config
```

variables.yaml
```yaml
some_config: &some_config
  - one
  - two
  - three
```

**Command**
The command you ran:
```
yq eval-all '. as $item ireduce ({}; . *+ $item)' one.yaml two.yaml variables.yaml
```

**Actual behavior**

```yaml
service:
  - name: aservice
    config:
      some_config: hey
      another_config: test
  - name: another-service
    config:
      some_config: *some_config
      another_config: another_config
some_config: &some_config
  - one
  - two
  - three
field:
  test: true
```

**Expected behavior**

```yaml
some_config: &some_config
  - one
  - two
  - three
field:
  test: true
service:
  - name: aservice
    config:
      some_config: hey
      another_config: test
  - name: another-service
    config:
      some_config: *some_config
      another_config: another_config
```

**Additional context**
Later on, when I try to explode the anchors, the resulting file errors because the anchor is defined after being referenced. One workaround is to have yet another "header" file that just declares the variable before anything, then replace it afterwards, but it wouldn't be good to have to keep up anchors declared in two places.

Moreover, if I declare the variables before, the `two.yaml` empty declaration will override the actual variables.
